Add Bazel rules for generating rust-project.json
TraceMachina/nativelink pull request #1019
Opened 2024-06-18 11:06 UTC by caass

# Description

rust-analyzer can parse Cargo.toml files or rust-project.json files to
generate context about the projects it's run on. rust-project.json files
are a format intended to be generated by build tools other than Cargo,
such as Bazel. With this setup we can tell rust-analyzer to build the
project with Bazel instead of Cargo.

## Type of change

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

N/A

## Checklist

- [x] Updated documentation if needed
- [ ] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-06-18 11:08 UTC, caass reviewed
+@aaronmondal 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1019#-:-O-f0pyA83iGhCN6S9XB:b-p12xwa)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, and 1 discussions need to be resolved (waiting on @aaronmondal)

___
*[`BUILD.bazel` line 77 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1019#-O-f0veMCXvSXf3hUwJy:-O-f0veMCXvSXf3hUwJz:baunss5) ([raw file](https://github.com/TraceMachina/nativelink/blob/e568ad9be6d1dfcdd30a15cc1b2caa4c77001488/BUILD.bazel#L77)):*
> ```Starlark
>     name = "gen_rust_project",
>     actual = "@rules_rust//tools/rust_analyzer:gen_rust_project",
> )
> ```

This was easier than making a genrule (or, whatever it is I would need to do) to wrap `gen_rust_project`, but I'm happy to change it if necessary.



_Code quote:_
```Starlark
alias(
    name = "gen_rust_project",
    actual = "@rules_rust//tools/rust_analyzer:gen_rust_project",
)
```


<!-- Sent from Reviewable.io -->

2024-06-18 16:18 UTC, aaronmondal submitted a review, later dismissed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1019)* status: 0 of 1 LGTMs obtained, and 2 discussions need to be resolved

___
*[`BUILD.bazel` line 77 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1019#-O-f0veMCXvSXf3hUwJy:-O-g6E5Y3-4D-GkNTRKt:bcukxhv) ([raw file](https://github.com/TraceMachina/nativelink/blob/e568ad9be6d1dfcdd30a15cc1b2caa4c77001488/BUILD.bazel#L77)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

This was easier than making a genrule (or, whatever it is I would need to do) to wrap `gen_rust_project`, but I'm happy to change it if necessary.
</blockquote></details>

Instead of a target we could just drop a line like this into CONTRIBUTING.md. This way we save one build-level target and have documentation at the same time:

```bash
bazel run @rules_rust//tools/rust_analyzer:gen_rust_project
```

Or am I misunderstanding and this is supposed to run on every build?

FYI generally I'd say the `alias` approach is fine and actually more desirable than genrules. A genrule introduces an additional target that could potentially cause issues when run in remote execution. With an alias you save one level of indirection.
___
*[`MODULE.bazel` line 80 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1019#-O-g66XLAPNS3aR1bSwj:-O-g66XLAPNS3aR1bSwk:undefined) ([raw file](https://github.com/TraceMachina/nativelink/blob/e568ad9be6d1dfcdd30a15cc1b2caa4c77001488/MODULE.bazel#L80)):*
> ```Starlark
> use_repo(crate, "crates")
> 
> rust_analyzer = use_extension("@rules_rust//tools/rust_analyzer:extension.bzl", "rust_analyzer_dependencies")
> ```





_Suggestion:_
```Starlark
rust_analyzer = use_extension(
    "@rules_rust//tools/rust_analyzer:extension.bzl",
    "rust_analyzer_dependencies",
)
```


<!-- Sent from Reviewable.io -->

2024-06-18 18:36 UTC, adam-singer reviewed
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1019)* status: 0 of 1 LGTMs obtained, and 2 discussions need to be resolved (waiting on @aaronmondal)



<!-- Sent from Reviewable.io -->

2024-06-18 19:46 UTC, caass reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1019)* status: 0 of 1 LGTMs obtained, and 2 discussions need to be resolved (waiting on @aaronmondal)

___
*[`BUILD.bazel` line 77 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1019#-O-f0veMCXvSXf3hUwJy:-O-gsONrE5sga8x7lLZ3:byjmlkm) ([raw file](https://github.com/TraceMachina/nativelink/blob/e568ad9be6d1dfcdd30a15cc1b2caa4c77001488/BUILD.bazel#L77)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Instead of a target we could just drop a line like this into CONTRIBUTING.md. This way we save one build-level target and have documentation at the same time:

```bash
bazel run @rules_rust//tools/rust_analyzer:gen_rust_project
```

Or am I misunderstanding and this is supposed to run on every build?

FYI generally I'd say the `alias` approach is fine and actually more desirable than genrules. A genrule introduces an additional target that could potentially cause issues when run in remote execution. With an alias you save one level of indirection.
</blockquote></details>

We don't need to have it built in here, but it is nice to be able to rebuild -- basically, every time you add something for bazel to build (i.e. a new rust file, new dependency, etc.) you need to rebuild the `rust-project.json`
___
*[`MODULE.bazel` line 80 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1019#-O-g66XLAPNS3aR1bSwj:-O-gslwC7qnm5Q0ewsKh:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e568ad9be6d1dfcdd30a15cc1b2caa4c77001488/MODULE.bazel#L80)):*
> ```Starlark
> use_repo(crate, "crates")
> 
> rust_analyzer = use_extension("@rules_rust//tools/rust_analyzer:extension.bzl", "rust_analyzer_dependencies")
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-06-18 20:05 UTC, adam-singer requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1019)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 3 discussions need to be resolved (waiting on @aaronmondal)

___
*[`BUILD.bazel` line 77 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1019#-O-f0veMCXvSXf3hUwJy:-O-gwHeJ6qltv4lNB5Xt:bcyn6tc) ([raw file](https://github.com/TraceMachina/nativelink/blob/e568ad9be6d1dfcdd30a15cc1b2caa4c77001488/BUILD.bazel#L77)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

We don't need to have it built in here, but it is nice to be able to rebuild -- basically, every time you add something for bazel to build (i.e. a new rust file, new dependency, etc.) you need to rebuild the `rust-project.json`
</blockquote></details>

lets avoid alias for now, in a prior life alias looks innocent and friendly but has caused a world of complexity due to abuse. We don't need pointer redirection atm for this
___
*[`CONTRIBUTING.md` line 305 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1019#-O-gvLZg4tlx2YCqIpTY:-O-gvLZg4tlx2YCqIpTZ:beewqwt) ([raw file](https://github.com/TraceMachina/nativelink/blob/4e51cbef0f246a3ef9341f62e78ac7b42c0cc3e3/CONTRIBUTING.md#L305)):*
> ```Markdown
> ### Setting up rust-analyzer
> 
> [rust-analyzer](https://rust-analyzer.github.io/) works reasonably well out of the box due to picking up the manifest for the `nativelink` crate, but it isn't integrated with Bazel by default. In order to generate a project configuration for rust-analyzer,
> ```

Will we have problems with vscode rust analyzer competing with bazel rust analyzer in vscode?


<!-- Sent from Reviewable.io -->

2024-06-18 20:24 UTC, caass reviewed
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1019)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Bazel Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, ubuntu-20.04 / stable, vale, and 2 discussions need to be resolved (waiting on @aaronmondal)

___
*[`CONTRIBUTING.md` line 305 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1019#-O-gvLZg4tlx2YCqIpTY:-O-h-jeT6vgA4GciFN0t:b7lnecy) ([raw file](https://github.com/TraceMachina/nativelink/blob/4e51cbef0f246a3ef9341f62e78ac7b42c0cc3e3/CONTRIBUTING.md#L305)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Will we have problems with vscode rust analyzer competing with bazel rust analyzer in vscode?
</blockquote></details>

No, because you'll configure VS Code rust analyzer to talk to bazel by setting `.vscode/settings.json#rust-analyzer.linkedProjects` to `[rust-project.json`
___
*[`BUILD.bazel` line 77 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1019#-O-f0veMCXvSXf3hUwJy:-O-h0Ixs1Y_O17Yjo7S5:b-qqwet0) ([raw file](https://github.com/TraceMachina/nativelink/blob/e568ad9be6d1dfcdd30a15cc1b2caa4c77001488/BUILD.bazel#L77)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

lets avoid alias for now, in a prior life alias looks innocent and friendly but has caused a world of complexity due to abuse. We don't need pointer redirection atm for this
</blockquote></details>

Totally


<!-- Sent from Reviewable.io -->

2024-06-18 20:28 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1019#-:-O-h1For3RwChVoMfBMD:bnfp4nl)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 1 discussions need to be resolved (waiting on @aaronmondal)



<!-- Sent from Reviewable.io -->

2024-06-18 21:50 UTC, caass reviewed
-@aaronmondal 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1019#-:-O-hK-qE4bEok9ZDNyVT:bta1d0k)* status: 1 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, and 1 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-06-19 01:51 UTC, caass reviewed
> Dismissed @aaronmondal from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1019)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-06-19 01:51 UTC, merged

2024-06-19 02:34 UTC, aaronmondal reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1019#-:-O-iKy1eCuMx3B5FJQEL:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->