redis matching engine state
TraceMachina/nativelink pull request #1023
Opened 2024-06-18 19:58 UTC by zbirenbaum

# Description
Implements MachingEngineStateManager trait for RedisStateManager.
Provides API hooks to support the Worker-Operation matching engine
including filtering and removal of operations.
Please include a summary of the changes and the related issue. Please also
include relevant motivation and context.

Requires: #1022 #1021 #1020

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-06-19 06:25 UTC, adam-singer reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1023)* status: 0 of 1 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04)



<!-- Sent from Reviewable.io -->

2024-06-19 20:47 UTC, adam-singer approved these changes
> Reviewed 4 of 7 files at r1, 3 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1023)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-06-25 17:09 UTC, allada requested changes
> Reviewed 3 of 7 files at r1, 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1023)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, and 11 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 35 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FIZps8ldRQznen2Zt:-O0FIZps8ldRQznen2Zu:b9o3eoi) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L35)):*
> ```XML
> 
> #[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
> enum OperationStage {
> ```

Why can't we use `ActionStage`?
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 43 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0AZ_EdCOQOSnq9f1y4:-O0AZ_EdCOQOSnq9f1y5:b7zb1v2) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L43)):*
> ```XML
> }
> 
> fn _parse_stage_flags(flags: &OperationStageFlags) -> Vec<OperationStage> {
> ```

unused. Because this is not a trivial function and returns allocations, I want to see it's uses before putting the code in.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 78 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0AZxSnCrHRkHz7X3gy:-O0AZxSnCrHRkHz7X3gz:b-azyysh) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L78)):*
> ```XML
>         let (tx, rx) = watch::channel(inner.as_state().unwrap());
> 
>         let _join_handle = background_spawn!("redis_subscription_watcher", async move {
> ```

nit: `join_handle` should be part of the `Self` struct.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 81 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0A_2aWAWJWxQbhF-9t:-O0A_2aWAWJWxQbhF-9u:bvb0blj) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L81)):*
> ```XML
>             loop {
>                 let Ok(item) = subscription.changed().await else {
>                     return;
> ```

nit: Put a comment here explaining when this might happen.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 84 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0A_Q5S1oQEPp9RTF_U:-O0A_Q5S1oQEPp9RTF_V:b-7honxv) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L84)):*
> ```XML
>                 };
>                 let (mut data_tx, mut data_rx) = make_buf_channel_pair();
>                 // If get fails then we drop the tx.
> ```

nit: Move this comment to the line below and make it more clear why we use `async move`.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 90 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0A_Xfp1SWtRcU6kUmq:-O0A_Xfp1SWtRcU6kUmr:b-23pyxf) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L90)):*
> ```XML
>                 );
>                 if let Err(_e) = res {
>                     todo!()
> ```

nit: Handle this properly.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 92 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0A__Xt7ou7EY7xvupP:-O0A__Xt7ou7EY7xvupQ:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L92)):*
> ```XML
>                     todo!()
>                 }
>                 let Ok(data) = data_res else { todo!() };
> ```

ditto.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 93 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0A_b_FClDwkoRe4W3N:-O0A_b_FClDwkoRe4W3O:bv4xdlv) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L93)):*
> ```XML
>                 }
>                 let Ok(data) = data_res else { todo!() };
>                 let slice = &data[..];
> ```

nit: inline this.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 94 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0A_ckB66um6XF0cEoG:-O0A_ckB66um6XF0cEoH:b-lcgu9) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L94)):*
> ```XML
>                 let Ok(data) = data_res else { todo!() };
>                 let slice = &data[..];
>                 let state: Arc<ActionState> = RedisOperation::from_slice(slice).as_state().unwrap();
> ```

nit: Don't use `unwrap()`
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 95 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0A_efi8WUHwJ5vhN6P:-O0A_efi8WUHwJ5vhN6Q:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L95)):*
> ```XML
>                 let slice = &data[..];
>                 let state: Arc<ActionState> = RedisOperation::from_slice(slice).as_state().unwrap();
>                 let _ = tx.send(state).map_err(|_| todo!());
> ```

ditto.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 105 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0Aa1VrERCu9XKpsu1T:-O0Aa1VrERCu9XKpsu1U:b-k0lwqv) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L105)):*
> ```XML
> impl ActionStateResult for RedisOperationState {
>     async fn as_state(&self) -> Result<Arc<ActionState>, Error> {
>         Ok(Arc::new(self.inner.clone().try_into()?))
> ```

nit: Lets make `inner` an `Arc` and clone it instead. This will be much more efficient.

When you are modifying `inner`, I suggest using `Arc::make_mut`. Yes it sounds dangerous, and if you are concerned, put this function behind another function and document why it's safe.

In this case it's safe because we are only using `inner` to denote the "current" item. We are not using it to change shared data. Only using it to attempt to recycle memory if possible.


<!-- Sent from Reviewable.io -->

2024-06-25 18:00 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1023)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 16 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 78 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0AZxSnCrHRkHz7X3gy:-O0FUDJqDP2JDMjZvGo_:bsladkh) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L78)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: `join_handle` should be part of the `Self` struct.
</blockquote></details>

make this a `spawn`
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 41 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FSsfj7dEJBgNc6zUI:-O0FSsfj7dEJBgNc6zUJ:blogw8g) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L41)):*
> ```XML
> 
> #[inline]
> fn build_action_key(action_name: &str) -> String {
> ```

Lets have this take `unique_qualifier`
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 46 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FSqsc4Ha5itohygdA:-O0FSqsc4Ha5itohygdB:b75100i) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L46)):*
> ```XML
> 
> #[inline]
> fn build_operations_key(operation_id_str: &str) -> String {
> ```

Lets have this take `OperationId`
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 56 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FTqru4tflCqSfRg6G:-O0FTqru4tflCqSfRg6H:bkagfqv) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L56)):*
> ```XML
>     Executing,
>     Completed,
>     Unknown,
> ```

lets remove this.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 91 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FUx2E6hXWAIchOVP_:-O0FUx2E6hXWAIchOVPa:b-n960jx) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L91)):*
> ```XML
> 
> impl RedisOperationState {
>     fn new(inner: RedisOperation, mut subscription: Box<dyn StoreSubscription>) -> Self {
> ```

lets name this `operation_subscription`.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 140 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FY0pS3e9YPFjIG15u:-O0FY0pS3e9YPFjIG15v:b-hbymqr) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L140)):*
> ```XML
>     info: ActionInfo,
>     worker_id: Option<WorkerId>,
>     result: Option<ActionResult>,
> ```

lets make a `RedisOperationStage` and hide away the to/from action logic inside it.


<!-- Sent from Reviewable.io -->

2024-06-25 19:23 UTC, allada requested changes
> Reviewed 1 of 7 files at r1, 1 of 3 files at r12, 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1023)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 35 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 186 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FkAUG8kxLgHPXtBg9:-O0FkAUG8kxLgHPXtBgA:b-qg2wyq) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L186)):*
> ```XML
>     pub fn as_state(&self) -> Result<Arc<ActionState>, Error> {
>         let action_state = ActionState {
>             stage: self.action_stage()?,
> ```

nit: We need an `err_tip`
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 231 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FkZc-9tpgrBkMkLmy:-O0FkZc-9tpgrBkMkLmz:bbau6si) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L231)):*
> ```XML
>         Ok(ActionState {
>             id: value.operation_id.clone(),
>             stage: value.action_stage()?,
> ```

nit: Needs `err_tip`
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 239 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FlN7U4o_9Ko6_U0EC:-O0FlN7U4o_9Ko6_U0ED:blydhvc) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L239)):*
> ```XML
> // If the filter value is Some and the value opt is None, it can't be a match so we return false.
> // If both values are Some, we run the predicate fn provided to determine if there is a match.
> fn match_optional_filter<T: PartialEq>(
> ```

nit: move this inside the `matches_filter` function.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 255 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0Fl-bcBtp2UZ9ayyhP:-O0Fl-bcBtp2UZ9ayyhQ:b-qemhn1) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L255)):*
> ```XML
> pub fn matches_filter(operation: &RedisOperation, filter: &OperationFilter) -> bool {
>     // It would be nice if we could just check to see if the operation stage is contained in the bits, but there are a few issues:
>     // 1. Can we add a flag for Unknown?
> ```

nit: no.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 266 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FlZwj5I8BseRGCpRd:-O0FlZwj5I8BseRGCpRe:b-ccj7v5) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L266)):*
> ```XML
>         return false;
>     }
>     match_optional_filter(
> ```

to be honest, I feel this would be easier to read if we inlined all of this.

Can we just do a lot of variable definitions then a bunch of if-statements instead?
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 288 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0Flkfr59cfSz8Vazx-:-O0Flkfr59cfSz8Vazx0:b1j9e9t) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L288)):*
> ```XML
>     T: ConnectionLike + Unpin + Clone + Send + Sync + 'static = ConnectionManager,
> > {
>     pub store: Arc<RedisStore<T>>,
> ```

nit: Don't make this public, make it a getter if it needs to be public (which I don't think it does).
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 308 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0Fm3ifCxyMKYuZnH6M:-O0Fm3ifCxyMKYuZnH6N:bplvf1f) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L308)):*
> ```XML
>         V: Send + Sync,
>     {
>         let mut con = self.get_conn().await?;
> ```

nit: All these need `err_tip`.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 311 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0Fm6vSDY8Dt1g2nMmr:-O0Fm6vSDY8Dt1g2nMms:bx5h4sl) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L311)):*
> ```XML
>         let ids_iter = con.scan_match::<&str, String>(prefix).await?;
>         let keys = ids_iter.collect::<Vec<String>>().await;
>         let raw_values: Vec<String> = con.get(&keys).await?;
> ```

nit: Don't collect this, instead keep it as an iterator then collect it below in the `.zip`.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 323 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FmyMm0nz9gO92CpIh:-O0FmyMm0nz9gO92CpIi:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L323)):*
> ```XML
>     ) -> Result<Arc<dyn ActionStateResult>, Error> {
>         let operation_id = OperationId::new(action_info.unique_qualifier.clone());
>         let mut con = self.get_conn().await?;
> ```

ditto.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 326 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0Fn2brAT2UzWYS648n:-O0Fn2brAT2UzWYS648o:b-ckcrh7) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L326)):*
> ```XML
>         let action_key = build_action_key(&operation_id.unique_qualifier.action_name());
>         // TODO: List API call to find existing actions.
>         let mut existing_operations: Vec<String> = Vec::new();
> ```

nit: Lets implement this.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 330 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0Fn5pYCOJIQdJ62All:-O0Fn5pYCOJIQdJ62Alm:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L330)):*
> ```XML
>             Some(existing_operation) => {
>                 let operations_key = build_operations_key(&existing_operation);
>                 let operation: RedisOperation = con.get(operations_key).await?;
> ```

ditto.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 342 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FnJim9_cXTHvosBkv:-O0FnJim9_cXTHvosBkw:bcdsvcw) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L342)):*
> ```XML
>         let store = self.store.as_store_driver_pin();
>         store
>             .update_oneshot(operation_key.clone().into(), operation.as_json().into())
> ```

nit: Probably worth making a comment here saying that we don't want to parallelize these two uploads because we should always upload an operation first followed by the action.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 343 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FnU7u4jQG3ZoKEIGp:-O0FnU7u4jQG3ZoKEIGq:b-ktew7t) ([raw file](https://githu [...]

2024-06-26 04:24 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1023)* status: 0 of 1 LGTMs obtained, and pending CI: Vercel, pre-commit-checks, and 29 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 35 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FIZps8ldRQznen2Zt:-O0HOhXU-dFioD8KWQ5o:b-tmrllq) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L35)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Why can't we use `ActionStage`?
</blockquote></details>

Done. Discussed offline. Added `RedisOperationStage` to address this
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 43 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0AZ_EdCOQOSnq9f1y4:-O0HmBJn3ku5KpSyF2ua:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L43)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

unused. Because this is not a trivial function and returns allocations, I want to see it's uses before putting the code in.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 90 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0A_Xfp1SWtRcU6kUmq:-O0HmCww0oiDdwCa16Wd:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L90)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Handle this properly.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 92 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0A__Xt7ou7EY7xvupP:-O0HmDkBCwyZP1vvVJaq:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L92)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 93 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0A_b_FClDwkoRe4W3N:-O0HmESm7LnmS32brTsG:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L93)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: inline this.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 94 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0A_ckB66um6XF0cEoG:-O0HmFI0-PxJfG9dyjTC:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L94)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Don't use `unwrap()`
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 95 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0A_efi8WUHwJ5vhN6P:-O0HmFvp36FZH0vQ6VBA:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L95)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 41 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FSsfj7dEJBgNc6zUI:-O0GpnM_Bh-aC_X3QgkA:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L41)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Lets have this take `unique_qualifier`
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 46 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FSqsc4Ha5itohygdA:-O0Gpnc4DMqo6LFDHR_8:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L46)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Lets have this take `OperationId`
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 56 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FTqru4tflCqSfRg6G:-O0HmA5yAOC3FFJu18do:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L56)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

lets remove this.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 91 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FUx2E6hXWAIchOVP_:-O0GqQHf0dLNSnQFAEUw:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L91)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

lets name this `operation_subscription`.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 140 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FY0pS3e9YPFjIG15u:-O0HmK-95DAG9vOuCiYk:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L140)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

lets make a `RedisOperationStage` and hide away the to/from action logic inside it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-26 15:13 UTC, allada reviewed
> Reviewed 2 of 3 files at r16, 1 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1023)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 19 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-06-26 15:25 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1023)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 25 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_action_stage.rs` line 1 at r17](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0K7_pL3cLUecE7OLQE:-O0K7_pL3cLUecE7OLQF:bxqvv2y) ([raw file](https://github.com/TraceMachina/nativelink/blob/3d7035ff0379c88573f6a78039e2834ec825c377/nativelink-scheduler/src/redis_action_stage.rs#L1)):*
> ```XML
> // Copyright 2023 The NativeLink Authors. All rights reserved.
> ```

nit: 2024
___
*[`nativelink-scheduler/src/redis_action_stage.rs` line 21 at r17](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0K7YIaDSBwEZesnh1T:-O0K7YIaDSBwEZesnh1U:bz367u2) ([raw file](https://github.com/TraceMachina/nativelink/blob/3d7035ff0379c88573f6a78039e2834ec825c377/nativelink-scheduler/src/redis_action_stage.rs#L21)):*
> ```XML
> use crate::operation_state_manager::OperationStageFlags;
> 
> // TODO(allada) Remove the need for clippy argument by making the ActionResult and ProtoActionResult
> ```

nit: These comments seem to not be for this struct.
___
*[`nativelink-scheduler/src/redis_action_stage.rs` line 53 at r17](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0K7okg3SM4SKuBBDdu:-O0K7okg3SM4SKuBBDdv:bvz0lc) ([raw file](https://github.com/TraceMachina/nativelink/blob/3d7035ff0379c88573f6a78039e2834ec825c377/nativelink-scheduler/src/redis_action_stage.rs#L53)):*
> ```XML
>             ActionStage::Queued => Ok(RedisOperationStage::Queued),
>             ActionStage::Executing => Ok(RedisOperationStage::Executing),
>             ActionStage::Unknown => Err(make_input_err!("ActionStage conversion to RedisOperationStage failed with Error - Unknown is not a valid OperationStage")),
> ```

nit: This should be last.
___
*[`nativelink-scheduler/src/redis_action_stage.rs` line 56 at r17](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0K7uFz9cVxV2RJjz7b:-O0K7uFz9cVxV2RJjz7c:b-tz0ila) ([raw file](https://github.com/TraceMachina/nativelink/blob/3d7035ff0379c88573f6a78039e2834ec825c377/nativelink-scheduler/src/redis_action_stage.rs#L56)):*
> ```XML
>             ActionStage::Completed(result) => Ok(RedisOperationStage::Completed(result)),
>             ActionStage::CompletedFromCache(proto_result) => {
>                 let decoded = ActionResult::try_from(proto_result);
> ```

nit: use `.map_err` or `.err_tip` and use questionmark.
___
*[`nativelink-scheduler/src/redis_action_stage.rs` line 82 at r17](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0K8G_g8uf4f3bWZ2P0:-O0K8G_g8uf4f3bWZ2P1:btsdda5) ([raw file](https://github.com/TraceMachina/nativelink/blob/3d7035ff0379c88573f6a78039e2834ec825c377/nativelink-scheduler/src/redis_action_stage.rs#L82)):*
> ```XML
> impl From<&RedisOperationStage> for ActionStage {
>     fn from(stage: &RedisOperationStage) -> Self {
>         match stage {
> ```

nit: use:
```rs
stage.clone().into()
```
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 88 at r17](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0K7DXIDpAS0rTgkzvM:-O0K7DXIDpAS0rTgkzvN:b-my7jyi) ([raw file](https://github.com/TraceMachina/nativelink/blob/3d7035ff0379c88573f6a78039e2834ec825c377/nativelink-scheduler/src/redis_operation_state.rs#L88)):*
> ```XML
>                     });
>                 if let Err(e) = res {
>                     event!(
> ```

nit: Lets add a `todo` to refactor the API to allow this error to be propagated to the client.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 176 at r17](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0K8Ul24J3jUF1wQvH3:-O0K8Ul24J3jUF1wQvH4:b-lzv4ov) ([raw file](https://github.com/TraceMachina/nativelink/blob/3d7035ff0379c88573f6a78039e2834ec825c377/nativelink-scheduler/src/redis_operation_state.rs#L176)):*
> ```XML
>     }
> 
>     pub fn action_stage(&self) -> ActionStage {
> ```

nit: Lets remove this and have the caller use `.into()`.


<!-- Sent from Reviewable.io -->

2024-06-26 17:33 UTC, adam-singer reviewed
> Reviewed 1 of 3 files at r12, 2 of 3 files at r16, 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1023)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 25 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-06-26 18:09 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1023)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 9 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_action_stage.rs` line 1 at r17](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0K7_pL3cLUecE7OLQE:-O0KSKiOAE8n3XIsEWjt:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/3d7035ff0379c88573f6a78039e2834ec825c377/nativelink-scheduler/src/redis_action_stage.rs#L1)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: 2024
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_action_stage.rs` line 21 at r17](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0K7YIaDSBwEZesnh1T:-O0KSaMMCoF_v8mCMiKN:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/3d7035ff0379c88573f6a78039e2834ec825c377/nativelink-scheduler/src/redis_action_stage.rs#L21)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: These comments seem to not be for this struct.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_action_stage.rs` line 53 at r17](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0K7okg3SM4SKuBBDdu:-O0KSzYT01wHWLIpkr17:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/3d7035ff0379c88573f6a78039e2834ec825c377/nativelink-scheduler/src/redis_action_stage.rs#L53)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: This should be last.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_action_stage.rs` line 56 at r17](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0K7uFz9cVxV2RJjz7b:-O0KTpI7CZcywAGqBjvx:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/3d7035ff0379c88573f6a78039e2834ec825c377/nativelink-scheduler/src/redis_action_stage.rs#L56)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: use `.map_err` or `.err_tip` and use questionmark.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_action_stage.rs` line 82 at r17](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0K8G_g8uf4f3bWZ2P0:-O0KTyr_AepTJMOAKuUG:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/3d7035ff0379c88573f6a78039e2834ec825c377/nativelink-scheduler/src/redis_action_stage.rs#L82)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: use:
```rs
stage.clone().into()
```
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 105 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0Aa1VrERCu9XKpsu1T:-O0KXEs9BGfCBa8DBzgZ:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L105)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Lets make `inner` an `Arc` and clone it instead. This will be much more efficient.

When you are modifying `inner`, I suggest using `Arc::make_mut`. Yes it sounds dangerous, and if you are concerned, put this function behind another function and document why it's safe.

In this case it's safe because we are only using `inner` to denote the "current" item. We are not using it to change shared data. Only using it to attempt to recycle memory if possible.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 186 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FkAUG8kxLgHPXtBg9:-O0KXQuaBvsS2kg_Jh-N:bfiv8dp) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L186)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: We need an `err_tip`
</blockquote></details>

Done. This is no longer a result.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 231 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FkZc-9tpgrBkMkLmy:-O0KYtvs8DLPe9SWbUlf:b-e7j0uh) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L231)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Needs `err_tip`
</blockquote></details>

Done. This is not a result anymore
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 255 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0Fl-bcBtp2UZ9ayyhP:-O0KgDvIDJDkdJH_eX3p:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L255)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: no.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 266 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FlZwj5I8BseRGCpRd:-O0KgCrhC5K_EV2G_wrl:b-4h2vdq) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L266)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

to be honest, I feel this would be easier to read if we inlined all of this.

Can we just do a lot of variable definitions then a bunch of if-statements instead?
</blockquote></details>

Done.  I cleaned this up and made it a member of `RedisOperation`
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 288 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0Flkfr59cfSz8Vazx-:-O0KgVNwDRr7vr5s2uQD:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L288)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Don't make this public, make it a getter if it needs to be public (which I don't think it does).
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 308 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0Fm3ifCxyMKYuZnH6M:-O0KgpnM7xfZQ_ReovCR:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L308)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: All these need `err_tip`.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 323 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0FmyMm0nz9gO92CpIh:-O0KjDKe8Ozj6O8UsGUb:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/9bc29d3d974c31f0f0da198eaba8b2cc38bf0954/nativelink-scheduler/src/redis_operation_state.rs#L323)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 330 at r15](https://reviewable. [...]

2024-06-26 22:40 UTC, allada requested changes
> Reviewed 2 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1023)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-22.04, and 3 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 189 at r18](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0LfXR_CGSsf65IBRz_:-O0LfXRaDs6YiYmbyh9T:bg287b6) ([raw file](https://github.com/TraceMachina/nativelink/blob/05bd29eac3a31f8638628057c5b60da3bda6d2de/nativelink-scheduler/src/redis_operation_state.rs#L189)):*
> ```XML
>         // If the filter value is Some and the value is None, it can't be a match so we return false.
>         // If both values are Some, we compare to determine if there is a match.
>         let matches_stage_filter = !filter.stages.contains(self.stage.as_state_flag())
> ```

this is a bitwise, so it should be:
```rs
(self.stage & filters.stages) != filters.stages
```
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 387 at r18](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0LgpUW-H6jBb3hHnRU:-O0LgpUX1273lsd5n6LT:b-vdp3rq) ([raw file](https://github.com/TraceMachina/nativelink/blob/05bd29eac3a31f8638628057c5b60da3bda6d2de/nativelink-scheduler/src/redis_operation_state.rs#L387)):*
> ```XML
>             Ok(stage) => {
>                 // If this fails we return early ActionStage is invalid and we do not update
>                 match RedisOperationStage::try_from(stage) {
> ```

nit:
```rs
operation.stage = stage
    .try_into()
    .err_tip(|| "In RedisStateManager::inner_update_operation")?;
```
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 389 at r18](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0LhFOT2JMRtR87uF6j:-O0LhFOT2JMRtR87uF6k:b-hpky4s) ([raw file](https://github.com/TraceMachina/nativelink/blob/05bd29eac3a31f8638628057c5b60da3bda6d2de/nativelink-scheduler/src/redis_operation_state.rs#L389)):*
> ```XML
>                 match RedisOperationStage::try_from(stage) {
>                     Ok(stage) => operation.stage = stage,
>                     Err(e) => return Err(e),
> ```

should we send this to `operation.last_error`?


<!-- Sent from Reviewable.io -->

2024-06-26 22:40 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-:-O0LhM4IAxnlHto7uQpn:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-22.04, and 3 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-06-27 17:53 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1023)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-22.04, and 2 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 189 at r18](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0LfXR_CGSsf65IBRz_:-O0PkAY3BDGW6ygZnsGp:bvuo9dr) ([raw file](https://github.com/TraceMachina/nativelink/blob/05bd29eac3a31f8638628057c5b60da3bda6d2de/nativelink-scheduler/src/redis_operation_state.rs#L189)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

this is a bitwise, so it should be:
```rs
(self.stage & filters.stages) != filters.stages
```
</blockquote></details>

Using a bitwise op gets a little verbose since `self.stage` is a `RedisOperationStage` and `filters.stages` is `OperationStateFlags`

```
(self.stage.as_state_flag().bits() & filter.stages.bits()) == self.stage.as_state_flag().bits();
```

It actually should be `filter.stages.contains(self.stage.as_state_flag())` instead of using `!` but these two code blocks are functionally equivalent and I think the contains one is a bit clearer.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 387 at r18](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0LgpUW-H6jBb3hHnRU:-O0PmhkvA44gpAnXRwfV:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/05bd29eac3a31f8638628057c5b60da3bda6d2de/nativelink-scheduler/src/redis_operation_state.rs#L387)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit:
```rs
operation.stage = stage
    .try_into()
    .err_tip(|| "In RedisStateManager::inner_update_operation")?;
```
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 389 at r18](https://reviewable.io/reviews/TraceMachina/nativelink/1023#-O0LhFOT2JMRtR87uF6j:-O0Pmoq0EVsZBrYwt8Ia:bxy4n4s) ([raw file](https://github.com/TraceMachina/nativelink/blob/05bd29eac3a31f8638628057c5b60da3bda6d2de/nativelink-scheduler/src/redis_operation_state.rs#L389)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

should we send this to `operation.last_error`?
</blockquote></details>

I thought about this but ultimately wasn't sure we should. This error occurs while attempting to update the operation, and if it happens then no update actually occurs. It also really shouldn't ever trigger.


<!-- Sent from Reviewable.io -->

2024-06-27 20:41 UTC, allada approved these changes
> Reviewed 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1023)* status: 1 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04



<!-- Sent from Reviewable.io -->

2024-06-27 21:26 UTC, merged