[WIP] Implement MatchingEngineStateManager
TraceMachina/nativelink pull request #1041
Opened 2024-06-20 21:43 UTC by adam-singer

# Description

Please include a summary of the changes and the related issue. Please also
include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-06-22 00:00 UTC, zbirenbaum requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, macos-13, windows-2022 / stable, and 4 discussions need to be resolved

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 257 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-x9by80xkMFRpaAqOI:-O-x9by80xkMFRpaAqOJ:b-6ufasv) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/simple_scheduler.rs#L257)):*
> ```XML
>             &self.state_manager,
>             OperationFilter {
>                 stages: OperationStageFlags::Queued,
> ```

Why only return Queued actions? Shouldn't this be any stage or passed as a parameter to the function?
___
*[`nativelink-scheduler/src/scheduler_state/matching_engine_action_state_result.rs` line 43 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xA0b1D5W_qiK_iiIe:-O-xA0b1D5W_qiK_iiIf:b-ahou9e) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/matching_engine_action_state_result.rs#L43)):*
> ```XML
>     }
> 
>     async fn as_action_info(&self) -> Result<Arc<ActionInfo>, Error> {
> ```

Do we still need this
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 328 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xEPxA2Q7EOgSHbKMx:-O-xEPxA2Q7EOgSHbKMy:bkhjr3y) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/state_manager.rs#L328)):*
> ```XML
>     }
> 
>     async fn update_operation(
> ```

Lets see if we can break this up into some helper functions so it's a bit easier to document and break down what's happening here
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 340 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xEJcOArWiGZX-Wugk:-O-xEJcOArWiGZX-Wugl:bllk2n) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/state_manager.rs#L340)):*
> ```XML
>         {
>             // worker_id related updates
>             // We do not have the infra to handle this code path currently
> ```

probably don't need this comment


<!-- Sent from Reviewable.io -->

2024-06-22 00:16 UTC, allada requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041)* status: 0 of 1 LGTMs obtained, and 12 discussions need to be resolved

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 288 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xGUTk7TtK3wIolg-f:-O-xGUTk7TtK3wIolg-g:br6tn0d) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/simple_scheduler.rs#L288)):*
> ```XML
>                     // TODO(adams): error handling here.
>                     let action_info: Arc<ActionInfo> =
>                         action_state_result.as_action_info().await.unwrap();
> ```

don't use unwrap.
___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 290 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xGZXB2Ra0j3g_ytt-:-O-xGZXB2Ra0j3g_ytt0:bdmom8c) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/simple_scheduler.rs#L290)):*
> ```XML
>                         action_state_result.as_action_info().await.unwrap();
> 
>                     // TODO(adams): AwaitedAction has action_info: Arc<ActionInfo> and current_state: Arc<ActionState>
> ```

note: comment.
___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 307 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xGlpv4XlE6UD1pQC0:-O-xGlpv4XlE6UD1pQC1:bw66ll5) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/simple_scheduler.rs#L307)):*
> ```XML
>                     };
> 
>                     // TODO(adams): What happens when we have two concurrent OperationsId
> ```

nit: comment.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 96 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xHPNp67k2kW_SXZND:-O-xHPNp67k2kW_SXZNE:bqjyzzs) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/state_manager.rs#L96)):*
> ```XML
>                 let send_result = if awaited_action.attempts >= self.inner.max_job_retries {
>                     self.inner.metrics.retry_action_max_attempts_reached.inc();
>                     Arc::make_mut(&mut awaited_action.current_state).stage = ActionStage::Completed(ActionResult {
> ```

nit: Use new function introduced in other PR?
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 114 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xHT8M5F1OXmrPKneu:-O-xHT8M5F1OXmrPKnev:b-5v3gaq) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/state_manager.rs#L114)):*
> ```XML
>                 } else {
>                     self.inner.metrics.retry_action.inc();
>                     Arc::make_mut(&mut awaited_action.current_state).stage = ActionStage::Queued;
> ```

nit: ditto.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 343 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xHdjO1RcnUgYvCWhN:-O-xHdjO1RcnUgYvCWhO:bw66ll5) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/state_manager.rs#L343)):*
> ```XML
> 
>             if let Some(worker_id) = worker_id {
>                 // Here we would remove the worker and assign it to a new one
> ```

nit: comment.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 388 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xHvck-2lSNUR7EUnj:-O-xHvck-2lSNUR7EUnk:b-5v3gaq) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/state_manager.rs#L388)):*
> ```XML
>                 match action_stage {
>                     Ok(action_stage) => {
>                         Arc::make_mut(&mut awaited_action.current_state).stage = action_stage;
> ```

nit: ditto.
___
*[`nativelink-scheduler/src/scheduler_state/workers.rs` line 117 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xIAP04xm98bnpBP3Z:-O-xIAP04xm98bnpBP3_:b23m239) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/workers.rs#L117)):*
> ```XML
>             }),
>         };
>         workers_iter.map(|(_, w)| &w.id).copied()
> ```

I don't think this counts as "touch"ing the item. To touch it we need to call `get_mut` I believe.


<!-- Sent from Reviewable.io -->

2024-06-22 03:05 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041)* status: 0 of 1 LGTMs obtained, and 12 discussions need to be resolved

___
*[`nativelink-scheduler/src/scheduler_state/workers.rs` line 117 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xIAP04xm98bnpBP3Z:-O-xtmhCB8rBibg_d3fO:b-xwrbu) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/workers.rs#L117)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I don't think this counts as "touch"ing the item. To touch it we need to call `get_mut` I believe.
</blockquote></details>

It's enough to just call `get` it delegates to `get_mut` under the hood.

```

    /// Returns a reference to the value of the key in the cache or `None` if it is not
    /// present in the cache. Moves the key to the head of the LRU list if it exists.
    ///
    /// # Example
    ///
    /// ```
    /// use lru::LruCache;
    /// use std::num::NonZeroUsize;
    /// let mut cache = LruCache::new(NonZeroUsize::new(2).unwrap());
    ///
    /// cache.put(1, "a");
    /// cache.put(2, "b");
    /// cache.put(2, "c");
    /// cache.put(3, "d");
    ///
    /// assert_eq!(cache.get(&1), None);
    /// assert_eq!(cache.get(&2), Some(&"c"));
    /// assert_eq!(cache.get(&3), Some(&"d"));
    /// ```
    pub fn get<'a, Q>(&'a mut self, k: &Q) -> Option<&'a V>
    where
        K: Borrow<Q>,
        Q: Hash + Eq + ?Sized,
    {
        if let Some(node) = self.map.get_mut(KeyWrapper::from_ref(k)) {
            let node_ptr: *mut LruEntry<K, V> = node.as_ptr();

            self.detach(node_ptr);
            self.attach(node_ptr);

            Some(unsafe { &*(*node_ptr).val.as_ptr() })
        } else {
            None
        }
    }
```


<!-- Sent from Reviewable.io -->

2024-06-24 05:19 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041)* status: 0 of 1 LGTMs obtained, and 12 discussions need to be resolved

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 257 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-x9by80xkMFRpaAqOI:-O07fRRh-y8zP6cs12Vm:b2wju3n) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/simple_scheduler.rs#L257)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Why only return Queued actions? Shouldn't this be any stage or passed as a parameter to the function?
</blockquote></details>

I assume we are only running matching engine on actions that are queued, tbh, I don't think the implementation honors this atm and directly checks queued actions
___
*[`nativelink-scheduler/src/scheduler_state/matching_engine_action_state_result.rs` line 43 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xA0b1D5W_qiK_iiIe:-O07diF8E5ZKYXPFPlN-:bzcqwck) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/matching_engine_action_state_result.rs#L43)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Do we still need this
</blockquote></details>

@zbirenbaum can you suggest what should be done otherwise? I'll revisit some of the call sites, iirc we didn't or don't have a way to go from `ActionState -> ActionInfo`. ah.. `ActionState.id: OperationId` means we can look up the action info in one of the `queued_actions_set: HashSet<Arc<ActionInfo>>`, `queued_actions: BTreeMap<Arc<ActionInfo>, AwaitedAction>`, `active_actions: HashMap<Arc<ActionInfo>, AwaitedAction>` ?
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 96 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xHPNp67k2kW_SXZND:-O07eouW9Aaw2u0Ird8C:b-k2ag76) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/state_manager.rs#L96)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Use new function introduced in other PR?
</blockquote></details>

I'll move this over once the other is landed


<!-- Sent from Reviewable.io -->

2024-06-24 18:21 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041)* status: 0 of 1 LGTMs obtained, and 12 discussions need to be resolved

___
*[`nativelink-scheduler/src/scheduler_state/matching_engine_action_state_result.rs` line 43 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xA0b1D5W_qiK_iiIe:-O0ATM3a1sP651AFgopn:b-hj4lcl) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/matching_engine_action_state_result.rs#L43)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

@zbirenbaum can you suggest what should be done otherwise? I'll revisit some of the call sites, iirc we didn't or don't have a way to go from `ActionState -> ActionInfo`. ah.. `ActionState.id: OperationId` means we can look up the action info in one of the `queued_actions_set: HashSet<Arc<ActionInfo>>`, `queued_actions: BTreeMap<Arc<ActionInfo>, AwaitedAction>`, `active_actions: HashMap<Arc<ActionInfo>, AwaitedAction>` ?
</blockquote></details>

Exactly, given the OperationId you have the unique_qualifier so you can look up in any of those. Ideally you would do the lookup in `queued_actions_set` and `active_actions` since those are optimized for it, and then update the BTreeMap if need to mutate `queued_actions_set`


<!-- Sent from Reviewable.io -->

2024-06-24 18:41 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041)* status: 0 of 1 LGTMs obtained, and 12 discussions need to be resolved

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 257 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-x9by80xkMFRpaAqOI:-O0AXxIGDH1H1sJQjtQS:b-80ze5g) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/simple_scheduler.rs#L257)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

I assume we are only running matching engine on actions that are queued, tbh, I don't think the implementation honors this atm and directly checks queued actions
</blockquote></details>

nit: Can we rename this `get_queued_operations()`? The current name is not clear what it is going to return.


<!-- Sent from Reviewable.io -->

2024-06-24 19:08 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041)* status: 0 of 1 LGTMs obtained, and 11 discussions need to be resolved

___
*[`nativelink-scheduler/src/scheduler_state/matching_engine_action_state_result.rs` line 43 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xA0b1D5W_qiK_iiIe:-O0AZd-z5RfKWoBWkp4H:b-kbdocs) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/matching_engine_action_state_result.rs#L43)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Exactly, given the OperationId you have the unique_qualifier so you can look up in any of those. Ideally you would do the lookup in `queued_actions_set` and `active_actions` since those are optimized for it, and then update the BTreeMap if need to mutate `queued_actions_set`
</blockquote></details>

Discussed offline with @zbirenbaum , no change for now


<!-- Sent from Reviewable.io -->

2024-06-24 19:10 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041)* status: 0 of 1 LGTMs obtained, and 11 discussions need to be resolved

___
*[`nativelink-scheduler/src/scheduler_state/workers.rs` line 117 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xIAP04xm98bnpBP3Z:-O0Acg1O1a-ddalSLqp6:bkeovol) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/workers.rs#L117)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

It's enough to just call `get` it delegates to `get_mut` under the hood.

```

    /// Returns a reference to the value of the key in the cache or `None` if it is not
    /// present in the cache. Moves the key to the head of the LRU list if it exists.
    ///
    /// # Example
    ///
    /// ```
    /// use lru::LruCache;
    /// use std::num::NonZeroUsize;
    /// let mut cache = LruCache::new(NonZeroUsize::new(2).unwrap());
    ///
    /// cache.put(1, "a");
    /// cache.put(2, "b");
    /// cache.put(2, "c");
    /// cache.put(3, "d");
    ///
    /// assert_eq!(cache.get(&1), None);
    /// assert_eq!(cache.get(&2), Some(&"c"));
    /// assert_eq!(cache.get(&3), Some(&"d"));
    /// ```
    pub fn get<'a, Q>(&'a mut self, k: &Q) -> Option<&'a V>
    where
        K: Borrow<Q>,
        Q: Hash + Eq + ?Sized,
    {
        if let Some(node) = self.map.get_mut(KeyWrapper::from_ref(k)) {
            let node_ptr: *mut LruEntry<K, V> = node.as_ptr();

            self.detach(node_ptr);
            self.attach(node_ptr);

            Some(unsafe { &*(*node_ptr).val.as_ptr() })
        } else {
            None
        }
    }
```
</blockquote></details>

@allada I think this is a better way of handling `find_worker_for_action` returning an ID being a essentially peek operation and then updating the LRU when the worker is actually used/sent an update makes the most sense and causes the least borrow checker issues. The LRU cache is still updated inside of `update_action` when the update is sent here
```
async fn update_operation(
    &mut self,
    operation_id: OperationId,
    worker_id: Option<WorkerId>,
    action_stage: Result<ActionStage, Error>,
) -> Result<(), Error> {
if let Some(action_info) = self
    .inner
    .queued_actions_set
    .get(&operation_id.unique_qualifier)
{
    // worker_id related updates
    // We do not have the infra to handle this code path currently
    if let Some(worker_id) = worker_id {
        // Here we would remove the worker and assign it to a new one

        let worker = self.inner.workers.workers.get_mut(&worker_id);

        let action_info = action_info.clone();

        if let Some(worker) = worker {
            let notify_worker_result =
                worker.notify_update(WorkerUpdate::RunAction(action_info.clone()));
```


<!-- Sent from Reviewable.io -->

2024-06-24 21:31 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041)* status: 0 of 1 LGTMs obtained, and 6 discussions need to be resolved

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 257 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-x9by80xkMFRpaAqOI:-O0Ayjha0OmNM7wUWJIs:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/simple_scheduler.rs#L257)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Can we rename this `get_queued_operations()`? The current name is not clear what it is going to return.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 288 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xGUTk7TtK3wIolg-f:-O0B4W1u5CATlwAq_4ED:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/simple_scheduler.rs#L288)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

don't use unwrap.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 290 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xGZXB2Ra0j3g_ytt-:-O0B4hyfDRXVMSuIuRxp:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/simple_scheduler.rs#L290)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

note: comment.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 307 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xGlpv4XlE6UD1pQC0:-O0B4oFqADcSfX7Xj5XO:bugzwse) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/simple_scheduler.rs#L307)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: comment.
</blockquote></details>

@allada is there a way we can handle this currently? My understanding is we planned to defer this or not able to handle it for some reasons, tbh I forgot the reasons for that. 
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 96 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xHPNp67k2kW_SXZND:-O0B6LzB4JSJCi96gk2A:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/state_manager.rs#L96)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

I'll move this over once the other is landed
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 114 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xHT8M5F1OXmrPKneu:-O0B6L8NEJFzOKpawE9u:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/state_manager.rs#L114)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: ditto.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 340 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xEJcOArWiGZX-Wugk:-O0B8i-o76xcBiihXJLC:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/state_manager.rs#L340)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

probably don't need this comment
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 343 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xHdjO1RcnUgYvCWhN:-O0B8wjzE4IerJPe5KgY:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/state_manager.rs#L343)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: comment.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 388 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xHvck-2lSNUR7EUnj:-O0B8PP82KtDkK9tPdMN:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/state_manager.rs#L388)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: ditto.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/workers.rs` line 117 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xIAP04xm98bnpBP3Z:-O0B8Snm4jr0x7CQUTW0:bqci4o9) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/workers.rs#L117)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

@allada I think this is a better way of handling `find_worker_for_action` returning an ID being a essentially peek operation and then updating the LRU when the worker is actually used/sent an update makes the most sense and causes the least borrow checker issues. The LRU cache is still updated inside of `update_action` when the update is sent here
```
async fn update_operation(
    &mut self,
    operation_id: OperationId,
    worker_id: Option<WorkerId>,
    action_stage: Result<ActionStage, Error>,
) -> Result<(), Error> {
if let Some(action_info) = self
    .inner
    .queued_actions_set
    .get(&operation_id.unique_qualifier)
{
    // worker_id related updates
    // We do not have the infra to handle this code path currently
    if let Some(worker_id) = worker_id {
        // Here we would remove the worker and assign it to a new one

        let worker = self.inner.workers.workers.get_mut(&worker_id);

        let action_info = action_info.clone();

        if let Some(worker) = worker {
            let notify_worker_result =
                worker.notify_update(WorkerUpdate::RunAction(action_info.clone()));
```
</blockquote></details>

@allada any other concerns related to that?


<!-- Sent from Reviewable.io -->

2024-06-24 23:29 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), integration-tests (20.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, and 5 discussions need to be resolved

___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 328 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xEPxA2Q7EOgSHbKMx:-O0B_EIBEv9eTTv4KiiX:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/state_manager.rs#L328)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Lets see if we can break this up into some helper functions so it's a bit easier to document and break down what's happening here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-25 05:30 UTC, zbirenbaum approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> Awesome work! Looks great

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-:-O0CrsXY-1REePkV2SrA:b-1a134v)* status: 1 of 1 LGTMs obtained, and 4 discussions need to be resolved

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 307 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xGlpv4XlE6UD1pQC0:-O0CqVLCC6Veu5OeaTqT:b-z1tdqy) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/simple_scheduler.rs#L307)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

@allada is there a way we can handle this currently? My understanding is we planned to defer this or not able to handle it for some reasons, tbh I forgot the reasons for that.
</blockquote></details>

There can't be two OperationIds with the same unique qualifier for the in memory version of the state manager so it doesn't need to be handled here. For the distributed version we can just return the first detected OperationId containing the corresponding unique qualifier.

You shouldn't have to handle this edge case here, the state manager can abstract it away for now when it's relevant.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 340 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xEJcOArWiGZX-Wugk:-O0CrXmt1zcrchyCqHfL:bh50i5a) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/state_manager.rs#L340)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

So much cleaner, awesome change!


<!-- Sent from Reviewable.io -->

2024-06-25 19:40 UTC, allada approved these changes
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041)* status: 1 of 1 LGTMs obtained, and 3 discussions need to be resolved

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 282 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O0FruPO7xYaxIPmPKuN:-O0FruPO7xYaxIPmPKuO:b-ge0t0y) ([raw file](https://github.com/TraceMachina/nativelink/blob/007177a6f0d90dec25a29f639a976b22f8bb115c/nativelink-scheduler/src/simple_scheduler.rs#L282)):*
> ```XML
>                 while let Some(action_state_result) = stream.next().await {
>                     let action_info_result = action_state_result.as_action_info().await;
>                     let action_info = match action_info_result {
> ```

nit, rust  has new better syntax:
```rs
let Ok(action_info) = action_state_result.as_action_info().await else {
    event!(
        Level::ERROR,
        ?err,
        "Failed to get action_info from action_state_results stream"
    );
    continue;
};
```
___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 445 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O0FtbH48taVybd8nwm7:-O0FtbH48taVybd8nwm8:b-me98gl) ([raw file](https://github.com/TraceMachina/nativelink/blob/007177a6f0d90dec25a29f639a976b22f8bb115c/nativelink-scheduler/src/simple_scheduler.rs#L445)):*
> ```XML
>                 self.state_manager
>                     .inner
>                     .tasks_or_workers_change_notify
> ```

nit: Lets put this in `update_operation` bindly.
___
*[`nativelink-scheduler/src/scheduler_state/workers.rs` line 117 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xIAP04xm98bnpBP3Z:-O0Fu8dl-RI-MNUv9wcy:b-cujjjn) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/workers.rs#L117)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

@allada any other concerns related to that?
</blockquote></details>

All good.


<!-- Sent from Reviewable.io -->

2024-06-25 19:41 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-:-O0Fuc4PEiCJ8XIXjhkl:bnfp4nl)* status: 2 of 1 LGTMs obtained, and 3 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-06-25 20:32 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041)* status: 2 of 1 LGTMs obtained, and pending CI: Local / ubuntu-22.04, Vercel, docker-compose-compiles-nativelink (20.04), pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, vale, and 2 discussions need to be resolved

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 445 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O0FtbH48taVybd8nwm7:-O0G5LxG2UKINXiUWIAH:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/007177a6f0d90dec25a29f639a976b22f8bb115c/nativelink-scheduler/src/simple_scheduler.rs#L445)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Lets put this in `update_operation` bindly.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/workers.rs` line 117 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xIAP04xm98bnpBP3Z:-O0G5Nkn1UIeBEOfO1Qs:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/scheduler_state/workers.rs#L117)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

All good.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-25 20:49 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041)* status: 2 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 2 discussions need to be resolved

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 282 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O0FruPO7xYaxIPmPKuN:-O0G5k9g61dVm5Kzi308:bepwe0j) ([raw file](https://github.com/TraceMachina/nativelink/blob/007177a6f0d90dec25a29f639a976b22f8bb115c/nativelink-scheduler/src/simple_scheduler.rs#L282)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit, rust  has new better syntax:
```rs
let Ok(action_info) = action_state_result.as_action_info().await else {
    event!(
        Level::ERROR,
        ?err,
        "Failed to get action_info from action_state_results stream"
    );
    continue;
};
```
</blockquote></details>

In the else case how do you extract the `err` for error message? One alternative that does provide a handle to the `err` within the Result and using the `let` type matching for `Ok` without directly unpacking `err` was 

```
                    let action_state_result = action_state_result.as_action_info().await;
                    let Ok(action_info) = action_state_result else {
                        let _ = action_state_result.inspect_err(|err| {
                            event!(
                                Level::ERROR,
                                ?err,
                                "Failed to get action_info from action_state_results stream"
                            );
                        });
                        continue;
                    };
```

I think the purpose of the code is "on error run this side effecting function of logging", slight indication we are moving forward without halting of an error in this case, which is maybe more of a warning this this case?  


<!-- Sent from Reviewable.io -->

2024-06-25 20:51 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041)* status: 2 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Bazel Dev / ubuntu-22.04, Local / ubuntu-22.04, Vercel, asan / ubuntu-22.04, pre-commit-checks, ubuntu-22.04, vale, and 1 discussions need to be resolved

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 282 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O0FruPO7xYaxIPmPKuN:-O0G9dRWE_dOgb2OIO19:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/007177a6f0d90dec25a29f639a976b22f8bb115c/nativelink-scheduler/src/simple_scheduler.rs#L282)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

In the else case how do you extract the `err` for error message? One alternative that does provide a handle to the `err` within the Result and using the `let` type matching for `Ok` without directly unpacking `err` was 

```
                    let action_state_result = action_state_result.as_action_info().await;
                    let Ok(action_info) = action_state_result else {
                        let _ = action_state_result.inspect_err(|err| {
                            event!(
                                Level::ERROR,
                                ?err,
                                "Failed to get action_info from action_state_results stream"
                            );
                        });
                        continue;
                    };
```

I think the purpose of the code is "on error run this side effecting function of logging", slight indication we are moving forward without halting of an error in this case, which is maybe more of a warning this this case?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-25 20:52 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041)* status: 2 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Bazel Dev / ubuntu-22.04, Local / ubuntu-22.04, Vercel, asan / ubuntu-22.04, pre-commit-checks, ubuntu-22.04, vale, and 1 discussions need to be resolved

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 307 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xGlpv4XlE6UD1pQC0:-O0G9h0G9m0Ssp_r6SAy:b-zd2qd5) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/simple_scheduler.rs#L307)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

There can't be two OperationIds with the same unique qualifier for the in memory version of the state manager so it doesn't need to be handled here. For the distributed version we can just return the first detected OperationId containing the corresponding unique qualifier.

You shouldn't have to handle this edge case here, the state manager can abstract it away for now when it's relevant.
</blockquote></details>

Closing out (after comment update) assuming @zbirenbaum has answered/resolved concerns here? 


<!-- Sent from Reviewable.io -->

2024-06-25 20:53 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1041)* status: 2 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 307 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1041#-O-xGlpv4XlE6UD1pQC0:-O0GAGfb8PueK-PQohdX:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7f3e9d75c881c18d40f57341b569b08643faa58/nativelink-scheduler/src/simple_scheduler.rs#L307)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Closing out (after comment update) assuming @zbirenbaum has answered/resolved concerns here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-25 21:56 UTC, merged