Use `StoreKey` internally for `FilesystemStore`
TraceMachina/nativelink pull request #1120
Opened 2024-07-09 05:56 UTC by jhpratt

Closes #1108

# Description

From #1108:

> Inside `FilesystemStore` we always turn the `StoreKey` into a digest, but in reality it should be using `.as_str()` for it's final destination storage name. This will make it much more usable for other future things (like BEP).

## Type of change

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

All existing tests pass without modification.

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-07-09 05:59 UTC, MarcusSorealheis reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1120)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 1 discussions need to be resolved

___
*[`nativelink-store/src/filesystem_store.rs` line 671 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1120#-O1L3bqu6ZU6vRO87DaT:-O1L3bqu6ZU6vRO87DaU:b-31pkhp) ([raw file](https://github.com/TraceMachina/nativelink/blob/dec3fa4856707d474f31802ccc3228a84c1e6333/nativelink-store/src/filesystem_store.rs#L671)):*
> ```XML
> 
>         // Take ownership to avoid lifetime issues.
>         // FIXME(jhpratt) Get rid of this eventually.
> ```

nit: can you change this not into a `TODO` rather than a `FIXME` so that is in line with the other similar notes and get picked up by the relevant tools. 


<!-- Sent from Reviewable.io -->

2024-07-09 15:18 UTC, allada requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1120)* status: 0 of 1 LGTMs obtained, and 5 discussions need to be resolved

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/1120#-O1N22562dHGoN0I_lmx:-O1N22562dHGoN0I_lmy:b-1tfmyy) (no related file):*
The point of this PR is to enable filtering by list/range, by going into a `DigestInfo` we are loosing the key's range information making the call pointless.

We are also going to need to add some encoding to the name/format of the files. We probably want to prefix all files with `h` for digests and `s` for strings, then when we load them, we can turn them back to the `StoreKey` enum.

Note: When doing this make sure if it doesn't start with `h` or `s` to load them in as `DigestInfo` for reverse compatibility.

___
___
*[`nativelink-store/src/filesystem_store.rs` line 78 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1120#-O1N1c6_09ar6P9RSfi8:-O1N1c6_09ar6P9RSfi9:b-5aypju) ([raw file](https://github.com/TraceMachina/nativelink/blob/f6f77beb32c022cebbcc85320988003e3c176258/nativelink-store/src/filesystem_store.rs#L78)):*
> ```XML
>     shared_context: Arc<SharedContext>,
>     path_type: PathType,
>     digest: FileNameDigest,
> ```

This should be a `StoreKey<'a>`
___
*[`nativelink-store/src/filesystem_store.rs` line 671 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1120#-O1N0elcDoK2foFHmxli:-O1N0elcDoK2foFHmxlj:bylgrwf) ([raw file](https://github.com/TraceMachina/nativelink/blob/f6f77beb32c022cebbcc85320988003e3c176258/nativelink-store/src/filesystem_store.rs#L671)):*
> ```XML
> 
>         // Take ownership to avoid lifetime issues.
>         // TODO(jhpratt) Get rid of this eventually.
> ```

nit: Lets remove this comment unless there's a ticket, this will be just noise.
___
*[`nativelink-store/src/filesystem_store.rs` line 672 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1120#-O1N0jz12K6fo1H6uxuE:-O1N0jz12K6fo1H6uxuF:b-da9nvi) ([raw file](https://github.com/TraceMachina/nativelink/blob/f6f77beb32c022cebbcc85320988003e3c176258/nativelink-store/src/filesystem_store.rs#L672)):*
> ```XML
>         // Take ownership to avoid lifetime issues.
>         // TODO(jhpratt) Get rid of this eventually.
>         let final_key = final_key.borrow().into_owned();
> ```

FYI, I fought a lot trying to fix these lifetime issues and eventually gaveup. From what I could tell rust looses proof that lookups don't need to outlive `'static`.
___
*[`nativelink-store/src/filesystem_store.rs` line 681 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1120#-O1N1AGs01QSE5oSrkXW:-O1N1AGs01QSE5oSrkXX:b-ad8l00) ([raw file](https://github.com/TraceMachina/nativelink/blob/f6f77beb32c022cebbcc85320988003e3c176258/nativelink-store/src/filesystem_store.rs#L681)):*
> ```XML
>                 &PathType::Content,
>                 encoded_file_path.shared_context.as_ref(),
>                 &final_key.borrow().into_digest(),
> ```

This should take a `StoreKey` not a `DigestInfo`
___
*[`nativelink-store/src/filesystem_store.rs` line 769 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1120#-O1N1wXR01Uz_s20YuCd:-O1N1wXR01Uz_s20YuCe:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/f6f77beb32c022cebbcc85320988003e3c176258/nativelink-store/src/filesystem_store.rs#L769)):*
> ```XML
>         _upload_size: UploadSizeInfo,
>     ) -> Result<(), Error> {
>         let digest = key.borrow().into_digest();
> ```

ditto.


<!-- Sent from Reviewable.io -->

2024-07-10 06:29 UTC, jhpratt reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1120)* status: 0 of 1 LGTMs obtained, and 5 discussions need to be resolved

___
*[`nativelink-store/src/filesystem_store.rs` line 78 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1120#-O1N1c6_09ar6P9RSfi8:-O1QHrXs6t2IC4eFoVyP:bonoi9f) ([raw file](https://github.com/TraceMachina/nativelink/blob/f6f77beb32c022cebbcc85320988003e3c176258/nativelink-store/src/filesystem_store.rs#L78)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This should be a `StoreKey<'a>`
</blockquote></details>

What lifetime are you envisioning? If it's `'static`, then it seems possible but doesn't gain much (as anything non-trivial has to effectively be cloned). If you want to attach a lifetime to `EncodedFilePath` then things will get very messy very quickly.


<!-- Sent from Reviewable.io -->

2024-07-10 09:01 UTC, jhpratt reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1120)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks, and 4 discussions need to be resolved

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/1120#-O1N22562dHGoN0I_lmx:-O1QjZva8XwdAtmC-O5n:b-hqlga4) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

The point of this PR is to enable filtering by list/range, by going into a `DigestInfo` we are loosing the key's range information making the call pointless.

We are also going to need to add some encoding to the name/format of the files. We probably want to prefix all files with `h` for digests and `s` for strings, then when we load them, we can turn them back to the `StoreKey` enum.

Note: When doing this make sure if it doesn't start with `h` or `s` to load them in as `DigestInfo` for reverse compatibility.
</blockquote></details>

Gotcha. I changed the naming to be prefixed as suggested. Tests are currently failing, which seems to be due to the renaming. I'll be looking into this more later.

___
___
*[`nativelink-store/src/filesystem_store.rs` line 671 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1120#-O1N0elcDoK2foFHmxli:-O1QjJPc3j95aTp6V2FD:bb7f2mf) ([raw file](https://github.com/TraceMachina/nativelink/blob/f6f77beb32c022cebbcc85320988003e3c176258/nativelink-store/src/filesystem_store.rs#L671)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Lets remove this comment unless there's a ticket, this will be just noise.
</blockquote></details>

done
___
*[`nativelink-store/src/filesystem_store.rs` line 681 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1120#-O1N1AGs01QSE5oSrkXW:-O1QjRgt2XZsyS_3ivmH:bb7f2mf) ([raw file](https://github.com/TraceMachina/nativelink/blob/f6f77beb32c022cebbcc85320988003e3c176258/nativelink-store/src/filesystem_store.rs#L681)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This should take a `StoreKey` not a `DigestInfo`
</blockquote></details>

done
___
*[`nativelink-store/src/filesystem_store.rs` line 769 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1120#-O1N1wXR01Uz_s20YuCd:-O1QjT7Z8u3UVlRxUy16:bb7f2mf) ([raw file](https://github.com/TraceMachina/nativelink/blob/f6f77beb32c022cebbcc85320988003e3c176258/nativelink-store/src/filesystem_store.rs#L769)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-07-10 09:06 UTC, jhpratt reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1120)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), pre-commit-checks, vale, and 5 discussions need to be resolved

___
*[`nativelink-store/tests/filesystem_store_test.rs` line 821 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1120#-O1QtCX768C6v-5IFwhg:-O1QtCX768C6v-5IFwhh:bb9q1cd) ([raw file](https://github.com/TraceMachina/nativelink/blob/b07c665a1674997642c5a9a952cf0edcfcf453c3/nativelink-store/tests/filesystem_store_test.rs#L821)):*
> ```XML
>     let big_digest = DigestInfo::try_new(HASH1, BIG_VALUE.len())?;
> 
>     static UNREFED_KEYS: Mutex<Vec<StoreKey<'static>>> = Mutex::new(Vec::new());
> ```

Drive-by change: `Mutex::new` has been const for quite a while, so there's no need to use `Lazy` here.


<!-- Sent from Reviewable.io -->

2024-07-10 09:17 UTC, aaronmondal reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1120)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 5 discussions need to be resolved

___
*[`nativelink-store/tests/filesystem_store_test.rs` line 821 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1120#-O1QtCX768C6v-5IFwhg:-O1Qujcl1981Mp-PS9gS:bfzgkod) ([raw file](https://github.com/TraceMachina/nativelink/blob/b07c665a1674997642c5a9a952cf0edcfcf453c3/nativelink-store/tests/filesystem_store_test.rs#L821)):*
<details><summary><i>Previously, jhpratt (Jacob Pratt) wrote…</i></summary><blockquote>

Drive-by change: `Mutex::new` has been const for quite a while, so there's no need to use `Lazy` here.
</blockquote></details>

fyi: A `grep once_cell` shows that the only other use of the crate is another `once_cell::sync::Lazy` in `nativelink-worker/tests/running_actions_manager_test.rs`.

If that can be removed as well we can remove the explicit `once_cell` dependency altogether.Might be better to defer this to another PR though.


<!-- Sent from Reviewable.io -->

2024-08-23 20:04 UTC, closed without merging