Hyper hyper
TraceMachina/nativelink pull request #1155
Opened 2024-07-13 20:59 UTC by aaronmondal

https://www.youtube.com/watch?v=7Twnmhe948A&ab_channel=Kontor.TV

2024-07-15 11:00 UTC, aaronmondal reviewed
+@adam-singer +@allada +@caass +@jhpratt +@zbirenbaum

Only the second commit here is relevant. The other one is #1159 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-:-O1p0Vzs0DwBv3mSVShK:b-bdaw6d)* status: 0 of 5 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @adam-singer, @allada, @caass, @jhpratt, and @zbirenbaum)



<!-- Sent from Reviewable.io -->

2024-07-15 17:42 UTC, allada requested changes
> Reviewed 12 of 34 files at r2.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1155)* status: 0 of 5 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), and 18 discussions need to be resolved (waiting on @adam-singer, @caass, @jhpratt, and @zbirenbaum)

___
*[`nativelink-service/tests/bytestream_server_test.rs` line 93 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rJPXN-aDz5ZRmx9di:-O1rJPXO9av4-fORiU5Z:b4afmck) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-service/tests/bytestream_server_test.rs#L93)):*
> ```XML
>     encoding: Option<CompressionEncoding>,
> ) -> (
>     tokio::sync::mpsc::Sender<Frame<Bytes>>,
> ```

nit: shorten this to `mpsc::Sender`... This is how most other places in the code do it.
___
*[`nativelink-service/tests/bytestream_server_test.rs` line 107 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rJXggByFlEODm53PE:-O1rJXggByFlEODm53PF:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-service/tests/bytestream_server_test.rs#L107)):*
> ```XML
>     bs_server: Arc<ByteStreamServer>,
>     encoding: Option<CompressionEncoding>,
> ) -> (tokio::sync::mpsc::Sender<Frame<Bytes>>, JoinHandle) {
> ```

ditto.
___
*[`nativelink-service/tests/bytestream_server_test.rs` line 152 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rK6sVDJmH7LRsTMOx:-O1rK6sVDJmH7LRsTMOy:b-xgx4nh) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-service/tests/bytestream_server_test.rs#L152)):*
> ```XML
>                 let body = body
>                     .map_err(|e| tonic::Status::internal(e.to_string()))
>                     .boxed_unsync();
> ```

I wounder if we can do this without a box?
___
*[`nativelink-util/Cargo.toml` line 17 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rKl9i97cLTj42_MsB:-O1rKl9i97cLTj42_MsC:b-nn9oeb) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/Cargo.toml#L17)):*
> ```TOML
> # TODO(aaronmondal): This is the commit that migrates tonic 0.11 to 0.12. Use a
> #                    regular version once console-subscriber 0.4.0 is released.
> console-subscriber = { git = "https://github.com/tokio-rs/console", rev = "5f6faa2" }
> ```

nit: Shouldn't this be under a feature?
___
*[`nativelink-util/src/channel_body.rs` line 1 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rQJlT3SsU-sZ-NIZU:-O1rQJlT3SsU-sZ-NIZV:b6oe9ld) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/src/channel_body.rs#L1)):*
> ```XML
> // Copyright 2023 The NativeLink Authors. All rights reserved.
> ```

nit: Should we rename this `channel_body_for_test` (and rename the struct)? This should reduce the chances of it being used in production code.
___
*[`nativelink-util/src/channel_body.rs` line 26 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rLE6B2XiORuZ7XKRq:-O1rLE6D8_pjfIvLwbrG:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/src/channel_body.rs#L26)):*
> ```XML
>     pub struct ChannelBody {
>         #[pin]
>         rx: tokio::sync::mpsc::Receiver<Frame<Bytes>>,
> ```

ditto.
___
*[`nativelink-util/src/channel_body.rs` line 35 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rPV5lA5j86TRarzVk:-O1rPV5lA5j86TRarzVl:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/src/channel_body.rs#L35)):*
> ```XML
> impl ChannelBody {
>     #[must_use]
>     pub fn new() -> (tokio::sync::mpsc::Sender<Frame<Bytes>>, Self) {
> ```

ditto.
___
*[`nativelink-util/src/channel_body.rs` line 36 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rPW391mVaFRpbaSby:-O1rPW391mVaFRpbaSbz:b-nwpov1) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/src/channel_body.rs#L36)):*
> ```XML
>     #[must_use]
>     pub fn new() -> (tokio::sync::mpsc::Sender<Frame<Bytes>>, Self) {
>         Self::with_buffer_size(32)
> ```

nit: Magic numbers should be a `const` and at top of file.
___
*[`nativelink-util/src/channel_body.rs` line 40 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rPb953cOV3Z4pxq-w:-O1rPb953cOV3Z4pxq-x:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/src/channel_body.rs#L40)):*
> ```XML
> 
>     #[must_use]
>     pub fn with_buffer_size(buffer_size: usize) -> (tokio::sync::mpsc::Sender<Frame<Bytes>>, Self) {
> ```

ditto.
___
*[`nativelink-util/src/channel_body.rs` line 41 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rPa1V9XG_5qlci7U8:-O1rPa1V9XG_5qlci7U9:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/src/channel_body.rs#L41)):*
> ```XML
>     #[must_use]
>     pub fn with_buffer_size(buffer_size: usize) -> (tokio::sync::mpsc::Sender<Frame<Bytes>>, Self) {
>         let (tx, rx) = tokio::sync::mpsc::channel(buffer_size);
> ```

ditto.
___
*[`nativelink-util/src/connection_manager.rs` line 432 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rQZs45Psb7bHJHG5T:-O1rQZs45Psb7bHJHG5U:b-rknirc) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/src/connection_manager.rs#L432)):*
> ```XML
> /// to allow messaging about connection success and failure.
> impl tonic::codegen::Service<tonic::codegen::http::Request<tonic::body::BoxBody>> for Connection {
>     type Response = tonic::codegen::http::Response<tonic::body::BoxBody>;
> ```

I'm interested to know if we can do this without a box?
___
*[`nativelink-util/tests/channel_body_test.rs` line 1 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rTYNm1MlBdh5t-DY5:-O1rTYNm1MlBdh5t-DY6:bxfvba4) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/tests/channel_body_test.rs#L1)):*
> ```XML
> // Copyright 2023 The NativeLink Authors. All rights reserved.
> ```

to be honest this has way too many tests, It looks like this was taken from the tokio code? Can we just put a comment in here pointing at the file/commit this was taken from?

Second, I'd suggest just putting a couple happy path tests in. This feels like we are going to lug around these tests for something that isn't even our code.
___
*[`nativelink-util/tests/channel_body_test.rs` line 29 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rQizE-gPynlBBOitd:-O1rQizE-gPynlBBOite:b-7kw49n) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/tests/channel_body_test.rs#L29)):*
> ```XML
> async fn setup_channel_body(
>     frames: Vec<String>,
> ) -> (tokio::sync::mpsc::Sender<Frame<Bytes>>, ChannelBody) {
> ```

(ditto with all these in this file).
___
*[`nativelink-util/tests/channel_body_test.rs` line 59 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rQrKn98FAtNTtbGQ6:-O1rQrKn98FAtNTtbGQ7:b-qjh54a) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/tests/channel_body_test.rs#L59)):*
> ```XML
> 
> generate_channel_body_tests! {
>     test_channel_body_empty: [String::new()],
> ```

yuck, can we just spell these out? It makes debugging impossible when people use generated tests.
___
*[`nativelink-util/test [...]

2024-07-16 10:00 UTC, aaronmondal reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1155)* status: 0 of 5 LGTMs obtained, and pending CI: pre-commit-checks, and 14 discussions need to be resolved (waiting on @adam-singer, @allada, @caass, @jhpratt, and @zbirenbaum)

___
*[`nativelink-service/tests/bytestream_server_test.rs` line 107 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rJXggByFlEODm53PE:-O1uUGsR8C81PSEz7z4a:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-service/tests/bytestream_server_test.rs#L107)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`nativelink-service/tests/bytestream_server_test.rs` line 152 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rK6sVDJmH7LRsTMOx:-O1uUHNc3GnHGZc6r6M2:bau0iz) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-service/tests/bytestream_server_test.rs#L152)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I wounder if we can do this without a box?
</blockquote></details>

I'm not sure in this case, as it's the `tonic::service::Routes` that dictates it in this case. Tonic's new request body type is called `BoxBody` and looks like this:

```rust
type BoxBody = UnsyncBoxBody<Bytes, Status>;
```

https://docs.rs/tonic/latest/tonic/body/type.BoxBody.html
___
*[`nativelink-util/Cargo.toml` line 17 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rKl9i97cLTj42_MsB:-O1uxNT58eGVWVQN1uS0:b-6i0b05) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/Cargo.toml#L17)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Shouldn't this be under a feature?
</blockquote></details>

I'll leave that up to @adam-singer to address in a separate PR.
___
*[`nativelink-util/src/connection_manager.rs` line 432 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rQZs45Psb7bHJHG5T:-O1ujLAW0Qnlqxpk_M_y:blt9abu) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/src/connection_manager.rs#L432)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I'm interested to know if we can do this without a box?
</blockquote></details>

AFAIU this isn't possible at the moment due to this being a direct requirement of tonics `Router`:

https://github.com/hyperium/tonic/blob/aa57ffebc75c8ef5caa0534d7976f43c01f86051/tonic/src/service/router.rs#L55

However, this doesn't seem to be a pessimization since apparently the previous implementation used a `BoxBody` internally already:

https://github.com/hyperium/tonic/pull/1670/commits/aaede1e47bc2396001106a82fc97fff1979407f1#diff-bf2e5f587650907b7a56b51043b1f36494faf3fb4a33e78f44cd3b99356fe207
___
*[`nativelink-util/tests/channel_body_test.rs` line 1 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rTYNm1MlBdh5t-DY5:-O1umrG27-cX6DNk1tK0:bja11zs) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/tests/channel_body_test.rs#L1)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

to be honest this has way too many tests, It looks like this was taken from the tokio code? Can we just put a comment in here pointing at the file/commit this was taken from?

Second, I'd suggest just putting a couple happy path tests in. This feels like we are going to lug around these tests for something that isn't even our code.
</blockquote></details>

Done. fyi the ChannelBody is adapted from https://github.com/hyperium/tonic/pull/1670/files#diff-471242ec6300ff9b1d2be22fd95e1bd348f69eced60ec53f63e7cc5c86d2a985. I made it a bit less generic and a bit more explicit to be a `hyper::body::Body`.

Regarding the tests I agree. They were initially intended to showcase some examples and then I got sidetracked into making way too many.

I'll remove most of them and only keep some basic functionality for exemplary purposes. Also agreed to make this a `channel_body_for_tests`.
___
*[`nativelink-util/tests/channel_body_test.rs` line 29 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rQizE-gPynlBBOitd:-O1utNFzEsbyuvaVtSK4:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/tests/channel_body_test.rs#L29)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

(ditto with all these in this file).
</blockquote></details>

Done.
___
*[`nativelink-util/tests/channel_body_test.rs` line 59 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rQrKn98FAtNTtbGQ6:-O1unSeL27VvBE_bpDxf:b-g1ln0j) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/tests/channel_body_test.rs#L59)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

yuck, can we just spell these out? It makes debugging impossible when people use generated tests.
</blockquote></details>

Done. My fantastic python fixtrue approach though :laughing:

Actually removing them altogether as we have enough fidelity from just a `test_channel_body_hello` test and the usage in the other tests.
___
*[`nativelink-util/tests/channel_body_test.rs` line 171 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rSG257jGzcD5m8GS1:-O1uo5gy5WYU5fMii9TX:bfs2rwy) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/tests/channel_body_test.rs#L171)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This does not appear to be testing anything abnormal.

Yes it is sending 40 frames, but nowhere do we ensure it is receiving backpressure.

If we want this test, you can't use `spawn`s, instead you need to poll the futures manually in step-sequence to ensure it has the intended behavior.
</blockquote></details>

Done. (removed). Not necessary for a test utility.
___
*[`nativelink-util/tests/channel_body_test.rs` line 281 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rT6qu8YP5_UjXqpGR:-O1uoJZ804XZS7cbj8bW:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/tests/channel_body_test.rs#L281)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

we appear to have this test above.
</blockquote></details>

Done.
___
*[`nativelink-util/tests/channel_body_test.rs` line 348 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rTNxMB-ARXv3kv5hV:-O1uoJz_AzSjK9D8CA7J:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/tests/channel_body_test.rs#L348)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

remove this test, we don't allow our tests to depend on wall time.
</blockquote></details>

Done.
___
*[`nativelink-util/src/channel_body.rs` line 1 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rQJlT3SsU-sZ-NIZU:-O1uxbIK60QRNtOAR9j9:b-x41muy) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/src/channel_body.rs#L1)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Should we rename this `channel_body_for_test` (and rename the struct)? This should reduce the chances of it being used in production code.
</blockq [...]

2024-07-16 14:55 UTC, aaronmondal commented
Blocked by:

- https://github.com/TraceMachina/nativelink/issues/1164

2024-07-17 03:53 UTC, jhpratt reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1155)* status: 1 of 5 LGTMs obtained, and pending CI: integration-tests (20.04), integration-tests (22.04), and 2 discussions need to be resolved (waiting on @adam-singer, @caass, and @zbirenbaum)

___
*[`nativelink-macro/Cargo.toml` line 10 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1ymBxH6JkvU7-CWSDp:-O1ymBxH6JkvU7-CWSDq:b-sjnibg) ([raw file](https://github.com/TraceMachina/nativelink/blob/c8b55ae68c2209784ca81f8cd071fa98c8d21133/nativelink-macro/Cargo.toml#L10)):*
> ```TOML
> 
> [dependencies]
> # TODO(allada) We currently need to pin these to specific version.
> ```

This comment can be removed as the deps are no longer pinned.
___
*[`nativelink-util/src/channel_body_for_tests.rs` line 1 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1yoL429VOIzy-VopZO:-O1yoL429VOIzy-VopZP:b-vpanqf) ([raw file](https://github.com/TraceMachina/nativelink/blob/c8b55ae68c2209784ca81f8cd071fa98c8d21133/nativelink-util/src/channel_body_for_tests.rs#L1)):*
> ```XML
> // Copyright 2023 The NativeLink Authors. All rights reserved.
> ```

Copyright 2023 should be 2024. This is the case in most of the repository, though, so it's not a big deal. Likewise for other new files.


<!-- Sent from Reviewable.io -->

2024-07-17 05:44 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1155)* status: 1 of 5 LGTMs obtained, and pending CI: integration-tests (20.04), integration-tests (22.04), and 2 discussions need to be resolved (waiting on @adam-singer, @caass, @jhpratt, and @zbirenbaum)

___
*[`nativelink-util/Cargo.toml` line 17 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rKl9i97cLTj42_MsB:-O1zCFth3Rg9Gy-9B6pS:bvmbpap) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/Cargo.toml#L17)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

I'll leave that up to @adam-singer to address in a separate PR.
</blockquote></details>

sg, can we add https://github.com/tokio-rs/console/pull/571 / https://github.com/tokio-rs/console/pull/576 in the comment and file a ticket to track it or will renovate pick up pin versions like this? 


<!-- Sent from Reviewable.io -->

2024-07-17 08:32 UTC, aaronmondal reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1155)* status: 1 of 5 LGTMs obtained, and pending CI: Installation / ubuntu-22.04, pre-commit-checks (waiting on @adam-singer, @caass, @jhpratt, and @zbirenbaum)

___
*[`nativelink-util/Cargo.toml` line 17 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1rKl9i97cLTj42_MsB:-O1zngzd3DDe8sUheV-O:b9b96dq) ([raw file](https://github.com/TraceMachina/nativelink/blob/de1ae184177dd06b9ee8cedb0f027f7bb7488df8/nativelink-util/Cargo.toml#L17)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

sg, can we add https://github.com/tokio-rs/console/pull/571 / https://github.com/tokio-rs/console/pull/576 in the comment and file a ticket to track it or will renovate pick up pin versions like this?
</blockquote></details>

I'm not sure whether renovate picks this up. I'll create a ticket just in case once we land (leaving this comment open for now).

Since we're AFAIK blocked on #1164, there is a chance that a new version will be available at the time we land this PR.
___
*[`nativelink-util/src/channel_body_for_tests.rs` line 1 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O1yoL429VOIzy-VopZO:-O1znWjk876FW6sKaEgX:b-dvu86b) ([raw file](https://github.com/TraceMachina/nativelink/blob/c8b55ae68c2209784ca81f8cd071fa98c8d21133/nativelink-util/src/channel_body_for_tests.rs#L1)):*
<details><summary><i>Previously, jhpratt (Jacob Pratt) wrote…</i></summary><blockquote>

Copyright 2023 should be 2024. This is the case in most of the repository, though, so it's not a big deal. Likewise for other new files.
</blockquote></details>

Done. I also sent https://github.com/TraceMachina/nativelink/pull/1172 to fix this in other files.


<!-- Sent from Reviewable.io -->

2024-07-18 02:03 UTC, jhpratt approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-:-O22_68W78Pp6HqEbron:bnfp4nl)* status: 2 of 5 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04) (waiting on @adam-singer, @caass, and @zbirenbaum)



<!-- Sent from Reviewable.io -->

2024-07-27 02:05 UTC, allada commented
The metrics refactor is in, so this PR should be able to land.

2024-07-27 16:06 UTC, caass approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 25 of 25 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-:-O2owNpu7aj8IV6xisMY:bg7igkv)* status: 3 of 5 LGTMs obtained, and all files reviewed, and pending CI: integration-tests (20.04), integration-tests (22.04), and 1 discussions need to be resolved (waiting on @adam-singer and @zbirenbaum)

___
*[`BUILD.bazel` line 31 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O2oupTx7xZICLx9VvCA:-O2oupTx7xZICLx9VvCB:b8j1ybi) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8f0ec06695d227a5bf94628e9e57edde66ff253/BUILD.bazel#L31)):*
> ```Starlark
>         "@crates//:clap",
>         "@crates//:futures",
>         "@crates//:hyper-1.4.1",
> ```

Wait, should we be specifying our crates like this everywhere? I didn't realize we could put version qualifiers on them. Can we put feature flags on them, too?
___
*[`Cargo.toml` line 51 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O2ov7de0hYJrnthQ1bE:-O2ov7de0hYJrnthQ1bF:b-hqv28x) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8f0ec06695d227a5bf94628e9e57edde66ff253/Cargo.toml#L51)):*
> ```TOML
> clap = { version = "4.5.9", features = ["derive"] }
> futures = "0.3.30"
> hyper = { version = "1.4.1" }
> ```

Minor, is there a reason we don't use the shorthand here?
___
*[`nativelink-store/BUILD.bazel` line 55 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O2ow0Bx85LrTaA5HWmW:-O2ow0Bx85LrTaA5HWmX:bsf1eog) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8f0ec06695d227a5bf94628e9e57edde66ff253/nativelink-store/BUILD.bazel#L55)):*
> ```Starlark
>         "@crates//:hex",
>         "@crates//:http-body",
>         "@crates//:hyper-0.14.30",
> ```

Oh, I see -- we're still using the old hyper here.


<!-- Sent from Reviewable.io -->

2024-07-27 18:27 UTC, aaronmondal reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1155)* status: 3 of 5 LGTMs obtained, and 34 of 37 files reviewed, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, windows-2022 / stable (waiting on @adam-singer and @zbirenbaum)

___
*[`BUILD.bazel` line 31 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-O2oupTx7xZICLx9VvCA:-O2pQwAG4uv2N8uoCz9a:b-7g9fv3) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8f0ec06695d227a5bf94628e9e57edde66ff253/BUILD.bazel#L31)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Wait, should we be specifying our crates like this everywhere? I didn't realize we could put version qualifiers on them. Can we put feature flags on them, too?
</blockquote></details>

AFAIK this is only useful for using two crates of the same version, but there aren't specific feature variants.

You can query available crates like so:

```bash
bazel query @crates//...
```


<!-- Sent from Reviewable.io -->

2024-07-27 18:27 UTC, aaronmondal reviewed
> Reviewed 7 of 34 files at r2, 2 of 9 files at r3, 3 of 4 files at r4, 22 of 25 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1155)* status: 3 of 5 LGTMs obtained, and all files reviewed, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, windows-2022 / stable (waiting on @adam-singer and @zbirenbaum)



<!-- Sent from Reviewable.io -->

2024-07-27 18:29 UTC, aaronmondal reviewed
-@adam-singer -@zbirenbaum 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1155#-:-O2pS2jGDOD27zcnyJpU:b7ln03i)* status: 3 of 3 LGTMs obtained, and all files reviewed, and pending CI: Installation / macos-13, Installation / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04



<!-- Sent from Reviewable.io -->

2024-07-27 18:44 UTC, merged