Add FAQ section for current bazel/buck2 users
TraceMachina/nativelink pull request #1160
Opened 2024-07-15 11:15 UTC by blakehatch

# Description
Adds a new FAQ page on the docs targeting users already on supported build systems but are unfamiliar with RBE systems such as NativeLink.

2024-07-16 16:46 UTC, aaronmondal requested changes
With these incremental improvements that add small-ish/manageable files, please make sure that they pass `warning`-level vale as outlined in https://github.com/TraceMachina/nativelink/issues/1150

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1160#-:-O1wQuL8B8Uic6vOG38K:b-dxsutg)* status: 0 of 1 LGTMs obtained, and 1 discussions need to be resolved

___
*[`docs/src/content/docs/faq/why-nativelink.mdx` line 11 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1160#-O1wMpa59DaCRBXerJPL:-O1wMpa59DaCRBXerJPM:b45h) ([raw file](https://github.com/TraceMachina/nativelink/blob/08827984405d3abd18951f6350b9f9d7478e0970/docs/src/content/docs/faq/why-nativelink.mdx#L11)):*
> ```MDX
> NativeLink's features, you stand to gain significant benefits with minimal effort.
> 
> By just integrating remote caching via our **free** hosted cloud,
> ```




<!-- Sent from Reviewable.io -->

2024-07-16 16:46 UTC, MarcusSorealheis approved these changes
this doc doesn't really answer the question fully. You need to talk about how it is a server implementation. Bazel and Buck2 by themselves are clients.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1160#-:-O1wQ_uhCIgVrLDb4uJZ:b-sw5ep2)* status: 0 of 1 LGTMs obtained, and 2 discussions need to be resolved

___
*[`docs/src/content/docs/faq/why-nativelink.mdx` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1160#-O1wQyfmC0qZbl-fzzs8:-O1wQyfmC0qZbl-fzzs9:b-7w31fw) ([raw file](https://github.com/TraceMachina/nativelink/blob/08827984405d3abd18951f6350b9f9d7478e0970/docs/src/content/docs/faq/why-nativelink.mdx#L10)):*
> ```MDX
> perhaps due to monorepo requirements, and aren't yet familiar with
> NativeLink's features, you stand to gain significant benefits with minimal effort.
> ```

this doc doesn't really answer the question fully. You need to talk about how NativeLink is a server implementation. Bazel and Buck2 by themselves are clients.


<!-- Sent from Reviewable.io -->

2024-07-17 00:01 UTC, blakehatch reviewed
Will do @aaronmondal

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1160#-:-O1xo7E15Euyzzy-HdqB:bmqj5a8)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks, and 2 discussions need to be resolved

___
*[`docs/src/content/docs/faq/why-nativelink.mdx` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1160#-O1wQyfmC0qZbl-fzzs8:-O1xvdu3CW645jPXo3lW:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/08827984405d3abd18951f6350b9f9d7478e0970/docs/src/content/docs/faq/why-nativelink.mdx#L10)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

this doc doesn't really answer the question fully. You need to talk about how NativeLink is a server implementation. Bazel and Buck2 by themselves are clients.
</blockquote></details>

Done.
___
*[`docs/src/content/docs/faq/why-nativelink.mdx` line 11 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1160#-O1wMpa59DaCRBXerJPL:-O1xukH10YDVx3pWeuKY:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/08827984405d3abd18951f6350b9f9d7478e0970/docs/src/content/docs/faq/why-nativelink.mdx#L11)):*
> ```MDX
> NativeLink's features, you stand to gain significant benefits with minimal effort.
> 
> By just integrating remote caching via our **free** hosted cloud,
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-17 00:01 UTC, blakehatch reviewed
Passed `pre-commit run -a`

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1160#-:-O1xzbMECjtSyeDjr-da:b-68d9mb)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks, and 2 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-07-17 08:09 UTC, aaronmondal reviewed
Doesn't pass with warning level. If I change this to warning:

https://github.com/TraceMachina/nativelink/blob/b7ef3b6c7af2451fafc8690158d49769b3d31dc8/.vale.ini#L5

And run `vale <thefile>` I get something like this:

```
0 errors, 10 warnings and 0 suggestions in 1 file.
```

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1160#-:-O1zieqA75hji5tyIYDF:b403avl)* status: 0 of 1 LGTMs obtained, and 1 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-07-17 23:52 UTC, blakehatch reviewed
This is the result of `pre-commit run -a` with the `.vale.ini` shown below. Let me know if there's a step I'm missing

```
mixed-line-ending........................................................Passed
rustfmt..................................................................Passed
statix...................................................................Passed
trailing-whitespace......................................................Passed
vale.....................................................................Passed


Blakes-MacBook-Pro:docs blakehatch$ cat ../.vale.ini
StylesPath = .github/styles

# TODO(aaronmondal): Set this to `warning`, then to `suggestion` once Vale
#                    stabilizes in CI.
MinAlertLevel = warning

Vocab = TraceMachina

Packages = alex, Microsoft, write-good
```

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1160#-:-O225y-E-S2HBYxaUwkE:bso268w)* status: 0 of 1 LGTMs obtained, and 1 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-07-18 00:45 UTC, aaronmondal commented
Ah yeah this is super confusing and we should document this better. Triggering a "warning" in vale doesn't return with a non-zero exit code. This causes the pre-commit hooks to ignore warnings even with the setting.

There are two ways to see the warnings:

1. Add a bogus word that triggers an actual "error". Then the pre-commit hooks will fail and you'll see the warnings in the logs as well.
2. Run vale manually with "vale path/to/file.mdx". This should also print the warnings.

I'm aware that this is horrible ux, and I'm really sorry that this is so complicated. Last time I looked into improving this ux it seemed like the only way to treat warnings as errors is via adjustments to our vale GitHub action workflows where we can use another tool to expose warnings more easily. I can add such an improvement as soon as we can "globally" enable the warning level in the codebase. Then it'll be much easier to see warnings and prevent new ones. But for this to work we have to fix all existing warnings first. There are already hundreds of them, which is why I'm trying so hard to prevent new ones.

2026-06-18 13:19 UTC, palfrey commented
Outdated now with https://github.com/TraceMachina/nativelink/pull/2448 in

2026-06-18 13:19 UTC, closed without merging