Make CAS and AC server not to use the same store
TraceMachina/nativelink pull request #1175
Opened 2024-07-19 04:16 UTC by aleksdmladenovic

# Description

When CAS and AC uses the same store, it might produce unexpected side-effects and wrong behaviors. To prevent system from such situation, it currently raises an error when CAS and AC uses the same store.

Fixes #768 

## Type of change

Please delete options that aren't relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1175)

2024-07-19 04:17 UTC, aleksdmladenovic commented
Hope you to review this. cc: @allada , @MarcusSorealheis

2024-07-19 05:15 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1175)* status: 0 of 1 LGTMs obtained, and 2 discussions need to be resolved

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-O28PecLCyANP5rbRanL:-O28PecLCyANP5rbRanM:b-vvf0g1) (no related file):*
We should also create an integration test for this.

___
___
*[`src/bin/nativelink.rs` line 230 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-O28PCvcAk5cmf4CylGY:-O28PCvcAk5cmf4CylGZ:bwanlxs) ([raw file](https://github.com/TraceMachina/nativelink/blob/c552c87df663ff884d4680b3d4b162204feaa46e/src/bin/nativelink.rs#L230)):*
> ```XML
> 
>         // Check if CAS and AC uses the same store.
>         if let Some(cas_config) = &services.cas {
> ```

This is `O(N^2)`. Can we instead create a hashmap, of one of them then index into the other to check? This will make it `O(max(N, M))` which is literally exponentially more efficient.


<!-- Sent from Reviewable.io -->

2024-07-19 18:07 UTC, MarcusSorealheis reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1175)* status: 0 of 1 LGTMs obtained, and 2 discussions need to be resolved

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-O28PecLCyANP5rbRanL:-O2BAEOlAF5dW1hD-fKv:b32v57) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

We should also create an integration test for this.
</blockquote></details>

+1

___


<!-- Sent from Reviewable.io -->

2024-07-20 02:48 UTC, aleksdmladenovic reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1175)* status: 0 of 1 LGTMs obtained, and 2 discussions need to be resolved

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-O28PecLCyANP5rbRanL:-O2D1aBjCCeoTxyW2o1z:b-c8bdi5) (no related file):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

+1
</blockquote></details>

I will add integration test in mins.

___
___
*[`src/bin/nativelink.rs` line 230 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-O28PCvcAk5cmf4CylGY:-O2D0p7-6Qs2ookpxI5N:bzeskzj) ([raw file](https://github.com/TraceMachina/nativelink/blob/c552c87df663ff884d4680b3d4b162204feaa46e/src/bin/nativelink.rs#L230)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This is `O(N^2)`. Can we instead create a hashmap, of one of them then index into the other to check? This will make it `O(max(N, M))` which is literally exponentially more efficient.
</blockquote></details>

My algorithm is already O(N * logM).
I do not agree to this.
Well, fyi, `cas_config` and `ac_config` are already hashmaps here. 
There is only one for loop here for looping through the hashmap `cas_config`.
And then `ac_config.get(instance_name)` - this part is O(logM) because `ac_config` is already `HashMap`.
Since we have hashmaps by default there's no need to create a new hashmap or something.

Hope you to check the code again. cc: @allada 


<!-- Sent from Reviewable.io -->

2024-07-20 02:49 UTC, aleksdmladenovic reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1175)* status: 0 of 1 LGTMs obtained, and 2 discussions need to be resolved

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-O28PecLCyANP5rbRanL:-O2D1gN60RuKddlPD_b1:b-5t2w02) (no related file):*
<details><summary><i>Previously, aleksdmladenovic (Aleksandar Mladenovic) wrote…</i></summary><blockquote>

I will add integration test in mins.
</blockquote></details>

cc: @allada , @MarcusSorealheis 

___


<!-- Sent from Reviewable.io -->

2024-07-21 17:27 UTC, MarcusSorealheis commented
Oh wait, @aleksdmladenovic you're already working on this issue. I'll check it now.

2024-07-21 17:29 UTC, MarcusSorealheis reviewed
We need a test, for sure. All you need to do is include a config JSON where the AC and CAS use the same type. 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-:-O2LKiwr4LV0484IaVzI:be10ydd)* status: 0 of 1 LGTMs obtained, and 2 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-07-22 18:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TraceMachina/nativelink?pullRequest=1175) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TraceMachina/nativelink?pullRequest=1175) before we can accept your contribution.<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TraceMachina/nativelink?pullRequest=1175) it.</sub>

2024-07-22 18:20 UTC, aleksdmladenovic reviewed
I added an integration test for this. cc: @allada , @MarcusSorealheis 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-:-O2Qes688XFqGVtfpY7m:b-1998cd)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 2 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-07-22 23:41 UTC, MarcusSorealheis reviewed
There is some weird failure not related to the PR, I believe, at first glance. It was caused by some permissions issue with Tekton so I re-ran the commit. We should not be able to fail due to Tekton cc @aaronmondal in case it happens again.

I'll dig into the test now.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-:-O2Ro07B-OCWT3jt35KK:b-yf6j4m)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, integration-tests (20.04), integration-tests (22.04), pre-commit-checks, and 2 discussions need to be resolved

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-O28PecLCyANP5rbRanL:-O2LKu--2zaqh7mfz2Fr:b-we5z8s) (no related file):*
<details><summary><i>Previously, aleksdmladenovic (Aleksandar Mladenovic) wrote…</i></summary><blockquote>

cc: @allada , @MarcusSorealheis
</blockquote></details>

Needs test.

___


<!-- Sent from Reviewable.io -->

2024-07-22 23:44 UTC, MarcusSorealheis reviewed
You also have some pre-commit issues to work out. Probably something like trailing whitespace.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-:-O2RpAbT7Wl9iA3UfGkR:bj8srnf)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, integration-tests (20.04), integration-tests (22.04), pre-commit-checks, and 2 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-07-24 02:36 UTC, aleksdmladenovic reviewed
I've made it pass all CI/CD. FYI, I've installed nix environment locally and finally it went through all pre-commit checks.
For my further commits, it won't fall into pre-commit issues again. :)

Waiting for your feedback. cc: @allada, @MarcusSorealheis 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-:-O2X_qbj9Tq8o3ygpgac:b-yly4ct)* status: 0 of 1 LGTMs obtained, and pending CI: Publish nativelink-worker-init, Remote / large-ubuntu-22.04, and 2 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-07-24 16:13 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1175)* status: 0 of 1 LGTMs obtained, and 3 discussions need to be resolved

___
*[`integration_tests/store_conflict_test.sh` line 26 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-O2_W9dJ3qj8m36P2tN0:-O2_W9dJ3qj8m36P2tN1:b-a1t2i1) ([raw file](https://github.com/TraceMachina/nativelink/blob/9d5e661b0af663aaa01e6108cb56c2dc79cd70f2/integration_tests/store_conflict_test.sh#L26)):*
> ```Shell
> 
> EXIT_CODE=0
> sudo docker compose --file docker-compose.test.yml up -d
> ```

@aaronmondal , this feels like the wrong way to use docker for integration tests. Do you see any low hanging fruit on how to make this less hacky?


<!-- Sent from Reviewable.io -->

2024-07-25 01:12 UTC, aaronmondal reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1175)* status: 0 of 1 LGTMs obtained, and 3 discussions need to be resolved

___
*[`integration_tests/store_conflict_test.sh` line 26 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-O2_W9dJ3qj8m36P2tN0:-O2bPRtjEhAb8hCWsJcy:bvzvy2h) ([raw file](https://github.com/TraceMachina/nativelink/blob/9d5e661b0af663aaa01e6108cb56c2dc79cd70f2/integration_tests/store_conflict_test.sh#L26)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

@aaronmondal , this feels like the wrong way to use docker for integration tests. Do you see any low hanging fruit on how to make this less hacky?
</blockquote></details>

First I thought no, but actually yes!

For things that only need to test specific config options we can start the executable directly without wrapping it in Docker. The `nativelink-is-installable` test does this:

1. The test: https://github.com/TraceMachina/nativelink/blob/main/tools/nativelink-is-executable-test.nix (you could create the nativelink config inline in the script).
2. Import it in the flake: https://github.com/TraceMachina/nativelink/blob/357414918c4addeecd71e1c316484cadd899fd31/flake.nix#L142
3. Export it as flake output: https://github.com/TraceMachina/nativelink/blob/357414918c4addeecd71e1c316484cadd899fd31/flake.nix#L232
4. Add it as a github action or in this case just add it as a step above the step here so it can reuse the cache: https://github.com/TraceMachina/nativelink/blob/357414918c4addeecd71e1c316484cadd899fd31/.github/workflows/nix.yaml#L135


<!-- Sent from Reviewable.io -->

2024-07-25 01:14 UTC, MarcusSorealheis commented
Magicians.

2024-07-25 12:12 UTC, aleksdmladenovic reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1175)* status: 0 of 1 LGTMs obtained, and 3 discussions need to be resolved

___
*[`integration_tests/store_conflict_test.sh` line 26 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-O2_W9dJ3qj8m36P2tN0:-O2dnSJq8gVcuu25OHPw:b-u8iz2z) ([raw file](https://github.com/TraceMachina/nativelink/blob/9d5e661b0af663aaa01e6108cb56c2dc79cd70f2/integration_tests/store_conflict_test.sh#L26)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

First I thought no, but actually yes!

For things that only need to test specific config options we can start the executable directly without wrapping it in Docker. The `nativelink-is-installable` test does this:

1. The test: https://github.com/TraceMachina/nativelink/blob/main/tools/nativelink-is-executable-test.nix (you could create the nativelink config inline in the script).
2. Import it in the flake: https://github.com/TraceMachina/nativelink/blob/357414918c4addeecd71e1c316484cadd899fd31/flake.nix#L142
3. Export it as flake output: https://github.com/TraceMachina/nativelink/blob/357414918c4addeecd71e1c316484cadd899fd31/flake.nix#L232
4. Add it as a github action or in this case just add it as a step above the step here so it can reuse the cache: https://github.com/TraceMachina/nativelink/blob/357414918c4addeecd71e1c316484cadd899fd31/.github/workflows/nix.yaml#L135
</blockquote></details>

Thanks. @aaronmondal.

Let me try that way. :)


<!-- Sent from Reviewable.io -->

2024-08-02 04:27 UTC, aleksdmladenovic reviewed
Hi, I added an integration test for checking this feature in a non-hacky way using nix and github nix workflow in a way as @aaronmondal  has mentioned. :)

I hope you to check this and work on other issues.

cc: @aaronmondal . @allada , @MarcusSorealheis 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-:-O3GKakwD_e5lw-gQGIG:b-oia54p)* status: 0 of 2 LGTMs obtained, and 0 of 6 files reviewed, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 3 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-08-03 15:05 UTC, MarcusSorealheis commented
This feature is something we'd ideally like to get into the next release.

2024-08-03 17:31 UTC, MarcusSorealheis requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1175)* status: 0 of 2 LGTMs obtained, and 0 of 6 files reviewed, and 5 discussions need to be resolved

___
*[`src/bin/nativelink.rs` line 254 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-O3OHWOvEBJzIlD-bIqd:-O3OHWOw9eBoY8eqoBRc:bmtgx23) ([raw file](https://github.com/TraceMachina/nativelink/blob/101fbbceaafeb9c101465b549e2c6ff97700e952/src/bin/nativelink.rs#L254)):*
> ```XML
>                             return Err(make_err!(
>                                 Code::InvalidArgument,
>                                 "CAS and AC use the same store '{}' in the config",
> ```

The error text here should be:

`"CAS and AC cannot use the same store '{}' in the config"`

It's open question for @bclark8923 and @adam-singer as to whether or not we should also link to the documentation on this issue.
___
*[`tools/nativelink-prevent-store-conflict-test.nix` line 62 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-O3OHrLRBA8_H1d_Yz5F:-O3OHrLRBA8_H1d_Yz5G:b355pqn) ([raw file](https://github.com/TraceMachina/nativelink/blob/101fbbceaafeb9c101465b549e2c6ff97700e952/tools/nativelink-prevent-store-conflict-test.nix#L62)):*
> ```Nix
> 
>   print_error_output=$(cat <<EOF
>   Error: Error { code: InvalidArgument, messages: ["CAS and AC use the same store 'FILESYSTEM_STORE' in the config"] }
> ```

again, we should be clear that users _cannot_ use


<!-- Sent from Reviewable.io -->

2024-08-05 01:55 UTC, aleksdmladenovic reviewed
Addressed your changes. cc: @MarcusSorealheis, @allada 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-:-O3VESNe2BFPziJg2ME1:b15dfgb)* status: 0 of 2 LGTMs obtained, and 0 of 6 files reviewed, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 5 discussions need to be resolved

___
*[`src/bin/nativelink.rs` line 254 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-O3OHWOvEBJzIlD-bIqd:-O3VErZn0GoV6YUYvl3O:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/101fbbceaafeb9c101465b549e2c6ff97700e952/src/bin/nativelink.rs#L254)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

The error text here should be:

`"CAS and AC cannot use the same store '{}' in the config"`

It's open question for @bclark8923 and @adam-singer as to whether or not we should also link to the documentation on this issue.
</blockquote></details>

Done.
___
*[`tools/nativelink-prevent-store-conflict-test.nix` line 62 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1175#-O3OHrLRBA8_H1d_Yz5F:-O3VEugi5Q8kw8QZyjIs:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/101fbbceaafeb9c101465b549e2c6ff97700e952/tools/nativelink-prevent-store-conflict-test.nix#L62)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

again, we should be clear that users _cannot_ use
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-08 13:47 UTC, aleksdmladenovic commented
Rebased. cc: @MarcusSorealheis

2024-08-09 09:29 UTC, aleksdmladenovic commented
Hope you to merge this. cc: @allada, @MarcusSorealheis, @aaronmondal

2024-08-16 14:11 UTC, aleksdmladenovic commented
Rebased and handled conflicts.

Hope you to check this. cc: @MarcusSorealheis, @allada, @aaronmondal

2024-12-29 23:03 UTC, MarcusSorealheis commented
#1555 obviates this PR

2024-12-29 23:03 UTC, closed without merging