WIP switch to fred
TraceMachina/nativelink pull request #1188
Opened 2024-07-23 21:58 UTC by caass

# Description

Please include a summary of the changes and the related issue. Please also
include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-07-26 05:22 UTC, allada reviewed
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188)* status: 0 of 1 LGTMs obtained, and 1 of 11 files reviewed, and 1 discussions need to be resolved

___
*[`.bazelrc` line 62 at r9](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2gxwxn57NsGCG_2whF:-O2gxwxn57NsGCG_2whG:b-1pe2w5) ([raw file](https://github.com/TraceMachina/nativelink/blob/4d6ef5e6359036b6706b69e6dc194d4a2cae455f/.bazelrc#L62)):*
> ```
> build:asan --config=nightly
> build:asan --@rules_rust//:extra_rustc_flags=-Zsanitizer=address
> build:asan --action_env=ASAN_OPTIONS=detect_leaks=0
> ```

nit: We definitely don't want to do this. In a worst case we want to disable asan for specific targets.


<!-- Sent from Reviewable.io -->

2024-07-26 16:35 UTC, adam-singer reviewed
@caass is this wip or ready for review? 

> Reviewed 8 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-:-O2jtQff96dPV8FMvRkw:b-d7c4fw)* status: 0 of 1 LGTMs obtained, and 3 of 11 files reviewed, and 1 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-07-26 20:25 UTC, caass reviewed
@adam-singer should be good now! +@allada +@adam-singer +@zbirenbaum 

> Reviewed 2 of 10 files at r1, 3 of 4 files at r2, 1 of 2 files at r5, 2 of 2 files at r7, 2 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-:-O2kdGkf8JuvSlgw6R11:b-8790ss)* status: 0 of 3 LGTMs obtained, and all files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 3 discussions need to be resolved (waiting on @adam-singer, @allada, and @zbirenbaum)

___
*[`nativelink-error/Cargo.toml` line 16 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kdV3fB4tiQ8bQlusI:-O2kdV3fB4tiQ8bQlusJ:b2duga0) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-error/Cargo.toml#L16)):*
> ```TOML
> prost = "0.12.4"
> prost-types = "0.12.4"
> fred = "9.0.3"
> ```

FYI I don't think I needed to add any features here, since we were just dealing with the `Error` enum.
___
*[`nativelink-error/src/lib.rs` line 205 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kdil3EJWnma7GIjm5:-O2kdil3EJWnma7GIjm6:baillpi) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-error/src/lib.rs#L205)):*
> ```XML
>         use fred::error::RedisErrorKind::*;
> 
>         let code = match error.kind() {
> ```

Nit: @allada I wasn't sure exactly how to match up errors here, I gave it my best shot, but if you think anything is mismatched let me know and I'll be happy to fix it up.
___
*[`nativelink-scheduler/Cargo.toml` line 31 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kdshw3lxq6i0nFfMk:-O2kdshw3lxq6i0nFfMl:b-206b4q) ([raw file](https://github.com/TraceMachina/nativelink/blob/d37bd90a314890fe901235e0432d263faa66d221/nativelink-scheduler/Cargo.toml#L31)):*
> ```TOML
> tonic = { version = "0.11.0", features = ["gzip", "tls"] }
> tracing = "0.1.40"
> redis = { version = "0.25.2", features = ["aio", "tokio", "json"] }
> ```

This didn't require any code changes
___
*[`nativelink-store/Cargo.toml` line 31 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kdxjl3zmNq1o3ivfx:-O2kdxjl3zmNq1o3ivfy:b-g5l50w) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/Cargo.toml#L31)):*
> ```TOML
>   "sentinel-auth",
>   "subscriber-client",
>   "mocks",
> ```

Nit: We should probably gate this behind Cargo features but I couldn't get it building under bazel, even using the `cargo-features` tag. You can see in earlier revisions where I tried to do that.
___
*[`nativelink-store/src/redis_store.rs` line 46 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2keBnMECLOp7Ur3ebI:-O2keBnMECLOp7Ur3ebJ:bytytje) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L46)):*
> ```XML
> 
>     /// A dedicated client running in `subscriber` mode
>     _subscriber: SubscriberClient,
> ```

FYI this isn't used yet, but will be when we implement subscriptions.
___
*[`nativelink-store/src/redis_store.rs` line 62 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2keJoc88I2MMbLx23i:-O2keJod5zdnPhLRkd9w:b-xtia9d) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L62)):*
> ```XML
> impl RedisStore {
>     /// Create a new `RedisStore` from the given configuration
>     pub fn new(config: &nativelink_config::stores::RedisStore) -> Result<Arc<Self>, Error> {
> ```

FYI with our new library there's way more options we can expose, such as paths to custom TLS certificates or client pool size -- but this PR was already difficult enough so I left that for future work.
___
*[`nativelink-store/src/redis_store.rs` line 82 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2keTbf8NMJ61b_cl-3:-O2keTbf8NMJ61b_cl-4:b-wnn9zc) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L82)):*
> ```XML
>             return Err(make_err!(Code::Unimplemented, "Connecting directly to multiple redis nodes in a cluster is currently unsupported. Please specify a single URL to a single node, and nativelink will use cluster discover to find the other nodes."));
>         };
>         let mut redis_config = match config.mode {
> ```

FYI another cool feature of `fred.rs` is that it can auto-detect configuration based on URL patterns, so there's a world where we can accept either a string or a JSON object for configuration.
___
*[`nativelink-store/src/redis_store.rs` line 102 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kedwAAQpr37yf61kT:-O2kedwAAQpr37yf61kU:b-154sbo) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L102)):*
> ```XML
>                 ..Default::default()
>             })
>             .set_policy(ReconnectPolicy::new_constant(1, 0));
> ```

FYI retry support will go here.
___
*[`nativelink-store/src/redis_store.rs` line 111 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kehUZBk--S_lGhS21:-O2kehUZBk--S_lGhS22:b-l67c48) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L111)):*
> ```XML
>             .err_tip(|| "while creating redis subscription client")?;
> 
>         client_pool.connect();
> ```

FYI these fire off background tasks under the hood
___
*[`nativelink-store/src/redis_store.rs` line 159 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kepqm85wfP6r3UyKe:-O2kepqm85wfP6r3UyKf:bcajsj0) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L159)):*
> ```XML
>             // this command is queued in memory, but not yet sent down the pipeline; the `await` returns instantly
>             let _: () = pipeline
>                 .strlen(encoded_key.as_ref())
> ```

Fyi this `.as_ref` is needed because `Cow<'_, str>` doesn't implement `Into<RedisValue>`. I landed https://github.com/redis-rs/redis-rs/pull/1219 with the old library, but we've switched so we should submit that to the new one as well.
___
*[`nativelink-store/src/redis_store.rs` line 201 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kf6ExBnpwzBCSD26A:-O2kf6ExBnpwzBCSD26B:bi048yx) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L201)):*
> ```XML
>         // identical to the final key -- so they will always hash to the same node.
>         //
>         // TODO(caass): the stabilization PR for [`LazyCell`](`std::cell::LazyCell`) has been merged into rust-lang,
> ```

Fyi this has been merged! We're just waiting to update once `rules_rust` does.
___
*[`nativelink-store/src/redis_store.rs` line 312 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kggqM4AHgEPsu4IBj:-O2kggqM4AHgEPsu4IBk:b67lu1y) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs# [...]

2024-07-26 21:12 UTC, zbirenbaum requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188)* status: 0 of 3 LGTMs obtained, and all files reviewed, and pending CI: Cargo Dev / macos-13, Installation / macos-13, Remote / large-ubuntu-22.04, and 61 discussions need to be resolved (waiting on @adam-singer and @allada)

___
*[`-- commits` line 1 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kimHx1H9JWfrEtqa-):*
Lets make sure to squash this and put a description with short explanation.
___
*[`nativelink-store/src/redis_store.rs` line 38 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kj2Mb8iyKiXoSTNfT:-O2kj2Mb8iyKiXoSTNfU:b-ypgu95) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L38)):*
> ```XML
> 
> pub const READ_CHUNK_SIZE: usize = 64 * 1024;
> pub const CONNECTION_POOL_SIZE: usize = 3;
> ```

Nit: lets put a todo comment here reminding us to make connection pool size a config variable.
___
*[`nativelink-store/src/redis_store.rs` line 161 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kk2n7EXF-wxwSOwKO:-O2kk2n88e4iBUiOpCEt:b-sdqfe4) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L161)):*
> ```XML
>                 .strlen(encoded_key.as_ref())
>                 .await
>                 .err_tip(|| "could not call `strlen` in has_with_results")?;
> ```

nit: 
err_tip should just provide a stack trace type message since the actual error will be propagated.
`.err_tip(|| "In RedisStore::has_with_results")?;`
___
*[`nativelink-store/src/redis_store.rs` line 164 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kjY-QEnAZyL2rHfAh:-O2kjY-QEnAZyL2rHfAi:b-o3ioy0) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L164)):*
> ```XML
>         }
> 
>         // now we send the commands. kind of a weird api, maybe we could submit a patch?
> ```

nit: Lets make this something like:
`// Now we send the commands to Redis.`

If you have an idea regarding a specific improvement or patch to submit lets discuss and open a ticket for it.
___
*[`nativelink-store/src/redis_store.rs` line 167 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kkccT5EEu8xC0UXOz:-O2kkccT5EEu8xC0UXP-:b-o5buie) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L167)):*
> ```XML
>         let responses = pipeline.all::<Vec<_>>().await?;
>         let remaining_results = results.iter_mut().filter(|option| {
>             // anything that's `Some` was already set from `is_zero_digest`
> ```

nit: Capitalize and period.
___
*[`nativelink-store/src/redis_store.rs` line 247 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kkifi2G1k-GUpfw7g:-O2kkifi2G1k-GUpfw7h:b-o5buie) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L247)):*
> ```XML
>                     }
> 
>                     // reader sent empty chunk, we're done here.
> ```

nit: Capitalize and period.
___
*[`nativelink-store/src/redis_store.rs` line 251 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kkmgkE3V7a4XfCYwx:-O2kkmgkE3V7a4XfCYwy:b-3760w0) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L251)):*
> ```XML
>                 }
> 
>                 // queued
> ```

nit: Lets provide a little more context here or remove this comment.
___
*[`nativelink-store/src/redis_store.rs` line 261 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kkuQZB31PDDS7F1xR:-O2kkuQZB31PDDS7F1xS:b6j3kxa) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L261)):*
> ```XML
>             }
> 
>             // reader is empty, but we're expecting more data. execute queued appends to the temp key
> ```

nit: This is referring to the queued command correct? Lets make this:
```
// Here the reader is empty but more data is expected.
// Executing the queued commands appends the data we just received to the temp key.
```
___
*[`nativelink-store/src/redis_store.rs` line 265 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kmENk78Y6VVYdJcWD:-O2kmENk78Y6VVYdJcWE:bi6txi2) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L265)):*
> ```XML
>         }
> 
>         // We're done receiving all data, so let's
> ```

Lets break this comment up
___
*[`nativelink-store/src/redis_store.rs` line 272 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2knPHHEIEKJiuuHBQU:-O2knPHHEIEKJiuuHBQV:bx9vtvc) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L272)):*
> ```XML
>         // This is done atomically via MULTI/EXEC, so from an outside observer's perspective the key appears
>         // with all the data.
>         let tx = client.multi();
> ```

```
// All data has been received so we begin constructing the redis command.
// We want the actual key to appear with all data available to a
// MULTI/EXEC performs all operations atomically, causing the key to appear with the full data available on success.
```
___
*[`nativelink-store/src/redis_store.rs` line 274 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kostI-PYVHu40vaaj:-O2kostJ7OWFYpRY2CgN:bel9lw5) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L274)):*
> ```XML
>         let tx = client.multi();
> 
>         tx.append(final_key.as_ref(), "").await?;
> ```

nit:
`// Initialize the 'real key' to an empty value.`

Side note: why is this necessary if the operation is being performed atomically? Will this fail if the key already exists while `rename` would not?
___
*[`nativelink-store/src/redis_store.rs` line 275 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kp31n14qzyBWJ28Mp:-O2kp31n14qzyBWJ28Mq:bekhsia) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L275)):*
> ```XML
> 
>         tx.append(final_key.as_ref(), "").await?;
>         tx.rename(temp_key.get_or_init(make_temp_name), final_key.as_ref())
> ```

nit:
`// Rename the temp key so that the data appears under the 'real key'`
___
*[`nativelink-store/src/redis_store.rs` line 278 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kphgy8tWkGYkSwqXD:-O2kphgy8tWkGYkSwqXE:b-7898yu) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L278)):*
> ```XML
>             .await?;
>         if let Some(pub_sub_channel) = &self.pub_sub_channel {
>             tx.publish(pub_sub_channel, final_key.as_ref()).await?;
> ```

nit:
`// If we have a publish channel configured, send a notice that the key has been set.`
___
*[`nativelink-store/src/redis_store.rs` line 306 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kqUgC-i_pwqLisbEQ:-O2kqUgC-i_pwqLisbER:b-n6xdvv) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L306)):*
> ```XML
> 
>         if length == Some(0) {
>             // we're supposed to read 0 bytes, so just check if the key exists
> ```

Capitalize and period.
___
*[`nativelink-store/src/redis_store.rs` line 342 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kqYeX-0 [...]

2024-07-26 22:41 UTC, caass reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188)* status: 0 of 3 LGTMs obtained, and 9 of 11 files reviewed, and pending CI: pre-commit-checks, and 10 discussions need to be resolved (waiting on @adam-singer, @allada, and @zbirenbaum)

___
*[`nativelink-store/src/redis_store.rs` line 358 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kql0GBspqacmZIQ7R:-O2l9PWK9iL7iA3D7bzC:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L358)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Here too.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 364 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kqnAZ5t6lnSVWhHYJ:-O2l9WojA1azCQswP-DG:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L364)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

`Go grab the next chunk.`
</blockquote></details>

Done.
___
*[`nativelink-store/tests/redis_store_test.rs` line 176 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kqsNY3bcfPV5TY_hr:-O2lBJ0U8QtuZJmfxv87:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/tests/redis_store_test.rs#L176)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Here.
</blockquote></details>

Done.
___
*[`nativelink-store/tests/redis_store_test.rs` line 185 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kqt0e4Y2dGjdiUhSs:-O2lBJZq-lkihS4im7NJ:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/tests/redis_store_test.rs#L185)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Here.
</blockquote></details>

Done.
___
*[`nativelink-store/tests/redis_store_test.rs` line 195 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kqqsk1_Ou5PowWE0J:-O2lBJsl8Ew6FH4v-iup:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/tests/redis_store_test.rs#L195)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Here.
</blockquote></details>

Done.
___
*[`nativelink-store/tests/redis_store_test.rs` line 197 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kqrU50QIO-05cG6Eo:-O2lBKCV-FA4KHTwdzHV:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/tests/redis_store_test.rs#L197)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-26 22:45 UTC, caass reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188)* status: 0 of 3 LGTMs obtained, and 9 of 11 files reviewed, and pending CI: pre-commit-checks, and 10 discussions need to be resolved (waiting on @adam-singer, @allada, and @zbirenbaum)

___
*[`-- commits` line 1 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kimHx1H9JWfrEtqa-):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Lets make sure to squash this and put a description with short explanation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-26 22:46 UTC, caass reviewed
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188)* status: 0 of 3 LGTMs obtained, and all files reviewed, and pending CI: pre-commit-checks, and 9 discussions need to be resolved (waiting on @adam-singer, @allada, and @zbirenbaum)



<!-- Sent from Reviewable.io -->

2024-07-27 04:12 UTC, allada reviewed
Can you please rebase first?

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-:-O2mNrGvES5xHdegGAzw:b-kqjv79)* status: 0 of 3 LGTMs obtained, and all files reviewed, and pending CI: pre-commit-checks, and 9 discussions need to be resolved (waiting on @adam-singer and @zbirenbaum)



<!-- Sent from Reviewable.io -->

2024-07-27 15:56 UTC, caass reviewed
@allada Yep, done :+1: 

> Reviewed 9 of 9 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-:-O2otwXH06MWowt_mhuH:bb1rarc)* status: 0 of 3 LGTMs obtained, and all files reviewed, and pending CI: Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 9 discussions need to be resolved (waiting on @adam-singer, @allada, and @zbirenbaum)



<!-- Sent from Reviewable.io -->

2024-07-27 18:22 UTC, aaronmondal approved these changes
I like fred.

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-:-O2pNxHmDgNfTUopTlg6:bnpqu3m)* status: 0 of 3 LGTMs obtained, and all files reviewed, and 11 discussions need to be resolved (waiting on @adam-singer, @allada, and @zbirenbaum)

___
*[`nativelink-error/src/lib.rs` line 216 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2pPLB70y1OHaYGalfo:-O2pPLB70y1OHaYGalfp:bwg0uqo) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-error/src/lib.rs#L216)):*
> ```XML
> impl From<fred::error::RedisError> for Error {
>     fn from(error: fred::error::RedisError) -> Self {
>         use fred::error::RedisErrorKind::*;
> ```

nit: Consider making this explicit.
___
*[`nativelink-store/Cargo.toml` line 31 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kdxjl3zmNq1o3ivfx:-O2pK2vE-3-xbxMXXSaL:bwmk3p4) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/Cargo.toml#L31)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Nit: We should probably gate this behind Cargo features but I couldn't get it building under bazel, even using the `cargo-features` tag. You can see in earlier revisions where I tried to do that.
</blockquote></details>

fyi if you need different features for main and test, add it twice - once in `dependencies` and once in `dev-dependencies`, similar to how it was done for redis previously.
___
*[`nativelink-store/src/redis_store.rs` line 181 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2pQBcv8URyr4wlbOBO:-O2pQBcv8URyr4wlbOBP:b2ni8l0) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L181)):*
> ```XML
>             }
> 
>             *result_slot = Some(response)
> ```

nit



_Suggestion:_
```XML
*result_slot = Some(response);
```


<!-- Sent from Reviewable.io -->

2024-07-27 21:18 UTC, allada requested changes
> Reviewed 1 of 2 files at r7, 1 of 1 files at r11, 1 of 2 files at r12, 8 of 9 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188)* status: 0 of 3 LGTMs obtained, and all files reviewed, and 32 discussions need to be resolved (waiting on @adam-singer and @zbirenbaum)

___
*[`nativelink-error/src/lib.rs` line 205 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kdil3EJWnma7GIjm5:-O2pi4RFD9swplO1Vu3P:bo41mrt) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-error/src/lib.rs#L205)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Nit: @allada I wasn't sure exactly how to match up errors here, I gave it my best shot, but if you think anything is mismatched let me know and I'll be happy to fix it up.
</blockquote></details>

FYI a good resource:
https://grpc.github.io/grpc/core/md_doc_statuscodes.html
___
*[`nativelink-error/src/lib.rs` line 216 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2pPLB70y1OHaYGalfo:-O2phlRh4siGgC2JZO23:b-ymtp8j) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-error/src/lib.rs#L216)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Consider making this explicit.
</blockquote></details>

Yes, please don't use wildcards, it causes headaches for people that need to upgrade stuff later.
___
*[`nativelink-error/src/lib.rs` line 226 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2piFhC60jlBRP4nwsW:-O2piFhC60jlBRP4nwsX:b-ei8t0l) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-error/src/lib.rs#L226)):*
> ```XML
>             Timeout => Code::DeadlineExceeded,
>             NotFound => Code::NotFound,
>             Backpressure => Code::ResourceExhausted,
> ```

This is the only one that we should change to `UNAVAILABLE`. `UNAVAILABLE` is used for backpressure, `ResourceExhausted` is more of a "you don't have enough money" kind of error.
___
*[`nativelink-store/src/redis_store.rs` line 46 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2keBnMECLOp7Ur3ebI:-O2pjwKxCygPl5irrgSr:b7e5bw) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L46)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

FYI this isn't used yet, but will be when we implement subscriptions.
</blockquote></details>

Can we instead just not use it and add it in the followup PR?
___
*[`nativelink-store/src/redis_store.rs` line 102 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kedwAAQpr37yf61kT:-O2pmM8c62eCXedUXEAi:b-mz3x8i) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L102)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

FYI retry support will go here.
</blockquote></details>

Lets just add it, it looks like: `ReconnectPolicy::Exponential` supports all the fields we have.
___
*[`nativelink-store/src/redis_store.rs` line 26 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2pj8op48iTuphUJgCu:-O2pj8op48iTuphUJgCv:b-4ijmi2) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L26)):*
> ```XML
> use fred::clients::{RedisPool, SubscriberClient};
> use fred::mocks::Mocks;
> use fred::prelude::*;
> ```

nit: Please be explicit, something like:
```rs
use fred::prelude::{ClientLike, KeysInterface, PubsubInterface, TransactionInterface};
use fred::types::{Builder, ConnectionConfig, PerformanceConfig, ReconnectPolicy, RedisConfig};
```
___
*[`nativelink-store/src/redis_store.rs` line 74 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2plv9C4n9_9irVVGjf:-O2plv9C4n9_9irVVGjg:b37sew2) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L74)):*
> ```XML
>         config: &nativelink_config::stores::RedisStore,
>         temp_name_generator_fn: fn() -> String,
>         mocks: Option<Arc<dyn Mocks>>,
> ```

instead of doing this, lets pass in a `redis_config`. This way the code itself doesn't need to know about mocks at all, but tests can do manual construction for the connection.
___
*[`nativelink-store/src/redis_store.rs` line 132 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2pkhEn9pvetRl0sE7W:-O2pkhEn9pvetRl0sE7X:b-u8ca6n) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L132)):*
> ```XML
>             key_body
>         } else {
>             let mut encoded_key = String::with_capacity(self.key_prefix.len() + key_body.len());
> ```

if you take the `key_body` which is a `Cow`, so it may own the data, and use `into_owned` (so it takes ownership of the underlying or copies if not), you can use: https://doc.rust-lang.org/std/string/struct.String.html#method.insert_str

This way you can reuse the memory if the allocator allows.

If you wanted to get even fancier, you can look at the `Cow` to decide if it owns the data and if it doesn't go down this path to reduce the any chance of a needless`realloc()` call.
___
*[`nativelink-store/src/redis_store.rs` line 147 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2psFTJC95dxvl629EH:-O2psFTJC95dxvl629EI:b-rdn0sy) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L147)):*
> ```XML
>         results: &mut [Option<usize>],
>     ) -> Result<(), Error> {
>         let pipeline = self.client_pool.next().pipeline();
> ```

can we either add a todo, or just implement a quick `if keys.len() == 1` branch here? This would free up multiple needless allocs for a code that that is super common. (It's very common for `keys` to be len one).
___
*[`nativelink-store/src/redis_store.rs` line 161 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2pn8ff1TaoRrs5DiaE:-O2pn8ff1TaoRrs5DiaF:b-j7wcc0) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L161)):*
> ```XML
> 
>             // This command is queued in memory, but not yet sent down the pipeline; the `await` returns instantly.
>             let _: () = pipeline
> ```

Nit: Remove this `let _: ()`, the compiler warns if it actually has a value but not used.
___
*[`nativelink-store/src/redis_store.rs` line 163 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2prMYI7PQmJMXsFln5:-O2prMYI7PQmJMXsFln6:b-55h1hw) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L163)):*
> ```XML
>             let _: () = pipeline
>                 .strlen(encoded_key.as_ref())
>                 .await
> ```

fyi: I really don't like this design that `fred` is using. By awaiting here implies async activity can happen, but it's actually impossible for async activity to happen on a `Pipeline` (from my code path walking). They seem to do this because they use the same interface for `.strlen()` and the default forces a future, when pipeline can never be blocking.
___
*[`nativelink-store/src/redis_store.rs` line 168 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2ps-drAWYSixOvryvz:-O2ps-drAWYSixOvryw-:b4n4b9k) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L168)):*
> ```XML
> 
>         / [...]

2024-07-29 21:02 UTC, caass reviewed
Ok I might have missed something because I had to edit the tests file twice, but this should look better :+1:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-:-O3-FcFPElJZM2_Rg5Uf:b-clf3vi)* status: 0 of 3 LGTMs obtained, and 2 of 11 files reviewed, and pending CI: pre-commit-checks, and 17 discussions need to be resolved (waiting on @adam-singer, @allada, and @zbirenbaum)

___
*[`nativelink-error/src/lib.rs` line 205 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kdil3EJWnma7GIjm5:-O2qKQFG2o1z6hO1sCBA:bg2wpkx) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-error/src/lib.rs#L205)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

FYI a good resource:
https://grpc.github.io/grpc/core/md_doc_statuscodes.html
</blockquote></details>

Oooh, thanks :+1: 
___
*[`nativelink-error/src/lib.rs` line 226 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2piFhC60jlBRP4nwsW:-O2qKXjL9k7qQbOpxKtx:bb6mt9b) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-error/src/lib.rs#L226)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This is the only one that we should change to `UNAVAILABLE`. `UNAVAILABLE` is used for backpressure, `ResourceExhausted` is more of a "you don't have enough money" kind of error.
</blockquote></details>

:+1:
___
*[`nativelink-store/src/redis_store.rs` line 46 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2keBnMECLOp7Ur3ebI:-O2zVwPZ2T3OzLU409Ie:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L46)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Can we instead just not use it and add it in the followup PR?
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 102 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kedwAAQpr37yf61kT:-O2zZ64X1Q-sNeF4YsK_:b-qofo1n) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L102)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Lets just add it, it looks like: `ReconnectPolicy::Exponential` supports all the fields we have.
</blockquote></details>

I'd rather do it in a follow-up? I think we'll want to expand our configuration options anyway, so I think a PR that revamps our redis config is a good follow to this one.
___
*[`nativelink-store/src/redis_store.rs` line 74 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2plv9C4n9_9irVVGjf:-O2zYvY6-qerf6pWY_At:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L74)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

instead of doing this, lets pass in a `redis_config`. This way the code itself doesn't need to know about mocks at all, but tests can do manual construction for the connection.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 132 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2pkhEn9pvetRl0sE7W:-O2zZ_pAE_AhCPx7MQh9:b-cbtwx2) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L132)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

if you take the `key_body` which is a `Cow`, so it may own the data, and use `into_owned` (so it takes ownership of the underlying or copies if not), you can use: https://doc.rust-lang.org/std/string/struct.String.html#method.insert_str

This way you can reuse the memory if the allocator allows.

If you wanted to get even fancier, you can look at the `Cow` to decide if it owns the data and if it doesn't go down this path to reduce the any chance of a needless`realloc()` call.
</blockquote></details>

Oooooh, nice one :)
___
*[`nativelink-store/src/redis_store.rs` line 147 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2psFTJC95dxvl629EH:-O3-CAMHDigkehs64lc3:b-18aby1) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L147)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

can we either add a todo, or just implement a quick `if keys.len() == 1` branch here? This would free up multiple needless allocs for a code that that is super common. (It's very common for `keys` to be len one).
</blockquote></details>

Yep, stuck a TODO on there.
___
*[`nativelink-store/src/redis_store.rs` line 161 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2pn8ff1TaoRrs5DiaE:-O2z_rGl8dVvLPIlT7Rk:bo1py9) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L161)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Nit: Remove this `let _: ()`, the compiler warns if it actually has a value but not used.
</blockquote></details>

It's more there for type hinting, I'll put it in a turbofish
___
*[`nativelink-store/src/redis_store.rs` line 163 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2prMYI7PQmJMXsFln5:-O2za8zk3R_PlFm_I8ot:b-5m4cjv) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L163)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

fyi: I really don't like this design that `fred` is using. By awaiting here implies async activity can happen, but it's actually impossible for async activity to happen on a `Pipeline` (from my code path walking). They seem to do this because they use the same interface for `.strlen()` and the default forces a future, when pipeline can never be blocking.
</blockquote></details>

Yeah :/ maybe some future work down the line to upstream a more ergonomic design here.
___
*[`nativelink-store/src/redis_store.rs` line 168 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2ps-drAWYSixOvryvz:-O2zaPOU6Jknmj1QITIR:bfvs5nd) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L168)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

qq: I wish they had this return a stream or iterator or something, or a struct that can turn into them, then we wouldn't need to allocate to check our results.
</blockquote></details>

Yep, I had the same thought. I've already upstreamed a couple PR's (https://github.com/aembke/fred.rs/pull/268 and https://github.com/aembke/fred.rs/pull/267) to prepare for sending more substantial improvements to the API.
___
*[`nativelink-store/src/redis_store.rs` line 207 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2px2Rx1REUht4b9n28:-O2zgE1o3Rv-vTj7Xel2:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L207)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I'm not sure why this was done originally, but I find it a bit pointless because I don't think there's ever a case this won't be triggered.

I suggest just making this a string and setting it right here.

I think the original idea was to make it so if we are not in cluster mode and can  [...]

2024-07-29 21:04 UTC, caass reviewed
> Reviewed 9 of 9 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188)* status: 0 of 3 LGTMs obtained, and all files reviewed, and pending CI: pre-commit-checks, and 15 discussions need to be resolved (waiting on @adam-singer, @allada, and @zbirenbaum)



<!-- Sent from Reviewable.io -->

2024-07-29 22:21 UTC, zbirenbaum approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11, 1 of 9 files at r14, 4 of 9 files at r15, 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-:-O3-_U_87tGM9BhQmEjd:bnfp4nl)* status: 1 of 3 LGTMs obtained, and all files reviewed, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 15 discussions need to be resolved (waiting on @adam-singer and @allada)

___
*[`nativelink-store/src/redis_store.rs` line 239 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2pu9LV5ux4ILuT6MND:-O3-_1O_39jbm4LhebMo:b-lpyv14) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L239)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

This is a `DropCloserReadHalf`, do you want me to implement a `try_recv` method on that to use here? I prototyped something but it felt like kind of a lot of code to throw in to this PR. I think it might make more sense to address this in a follow-up, rather than implement a drive-by fix.
</blockquote></details>

I agree. This PR is blocking a lot of other stuff and is slowing things down a ton both here and on my end to keep rebasing. Lets address this in a followup.


<!-- Sent from Reviewable.io -->

2024-07-30 00:11 UTC, adam-singer reviewed
> Reviewed 1 of 1 files at r11, 1 of 9 files at r14, 4 of 9 files at r15, 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188)* status: 1 of 3 LGTMs obtained, and all files reviewed, and 15 discussions need to be resolved (waiting on @allada)



<!-- Sent from Reviewable.io -->

2024-07-30 01:43 UTC, adam-singer reviewed
@caass has this been smoke screened against a live redis instance, local or on a dev machine? 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-:-O30IUHT84yCfMwCBOv6:b2dtw0l)* status: 1 of 3 LGTMs obtained, and all files reviewed, and 15 discussions need to be resolved (waiting on @allada)



<!-- Sent from Reviewable.io -->

2024-07-30 04:46 UTC, allada requested changes
> Reviewed 2 of 9 files at r15, 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188)* status: 1 of 3 LGTMs obtained, and all files reviewed, and 19 discussions need to be resolved (waiting on @adam-singer)

___
*[`nativelink-error/src/lib.rs` line 216 at r16](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O30rkN6-bGaK9s5j6Av:-O30rkN6-bGaK9s5j6Aw:b-ti8ns2) ([raw file](https://github.com/TraceMachina/nativelink/blob/0f6be97694bb2353e07bfbbf58cf3b43c144a8b8/nativelink-error/src/lib.rs#L216)):*
> ```XML
> impl From<Code> for Error {
>     fn from(code: Code) -> Self {
>         make_err!(code, "")
> ```

I don't think `Code` should be translated into `Error`. `Code` is just a type of an error, not an error itself.
___
*[`nativelink-error/src/lib.rs` line 227 at r16](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O30rch_CCBOvs0rCHfd:-O30rch_CCBOvs0rCHfe:bz2hgqg) ([raw file](https://github.com/TraceMachina/nativelink/blob/0f6be97694bb2353e07bfbbf58cf3b43c144a8b8/nativelink-error/src/lib.rs#L227)):*
> ```XML
>         };
> 
>         // conversions based on https://grpc.github.io/grpc/core/md_doc_statuscodes.html
> ```

nit: Caps (and usually periods) please.
___
*[`nativelink-store/src/redis_store.rs` line 102 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kedwAAQpr37yf61kT:-O30t6MM85wYFTc_Y56k:b-q5z8oi) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L102)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

I'd rather do it in a follow-up? I think we'll want to expand our configuration options anyway, so I think a PR that revamps our redis config is a good follow to this one.
</blockquote></details>

please add a TODO and file a ticket, since we have this config already set and it does nothing now. This kind of breaking change we can't let leave around for long without removing it from the config, otherwise it will become stale and piss people off when it advertises it does something but it really doesn't.
___
*[`nativelink-store/src/redis_store.rs` line 111 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kehUZBk--S_lGhS21:-O30tXMd5mpkAbqlkFXg:b8w6x2c) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L111)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

FYI these fire off background tasks under the hood
</blockquote></details>

nit: Add this as a comment?
___
*[`nativelink-store/src/redis_store.rs` line 163 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2prMYI7PQmJMXsFln5:-O30ujAT8HovaLJ86uwv:b-7zm19a) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L163)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Yeah :/ maybe some future work down the line to upstream a more ergonomic design here.
</blockquote></details>

FYI, the big thing here is that `.await` often causes the compiler to not inline due to how much code it takes to generate a future. This is why I don't like using await when not needed.
___
*[`nativelink-store/src/redis_store.rs` line 239 at r14](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2pu9LV5ux4ILuT6MND:-O30vl6ACtsYCZZ4FdRl:b-ujzgo9) ([raw file](https://github.com/TraceMachina/nativelink/blob/c0a8b47c182e085e65d6414e07b4132c87ab570f/nativelink-store/src/redis_store.rs#L239)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

I agree. This PR is blocking a lot of other stuff and is slowing things down a ton both here and on my end to keep rebasing. Lets address this in a followup.
</blockquote></details>

We need to at minimum create a TODO and a ticket. Infinite loops are extremely dangerous. This is probably the highest priority of followup work that needs to be fixed, since we are using this store in production.
___
*[`nativelink-store/src/redis_store.rs` line 36 at r16](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O30sEkpD3aj_K_W16b6:-O30sEkpD3aj_K_W16b7:b-7kooul) ([raw file](https://github.com/TraceMachina/nativelink/blob/0f6be97694bb2353e07bfbbf58cf3b43c144a8b8/nativelink-store/src/redis_store.rs#L36)):*
> ```XML
> use crate::cas_utils::is_zero_digest;
> 
> // TODO(caass): These (and other settings) should be made configurable via nativelink-config
> ```

nit: period.
___
*[`nativelink-store/src/redis_store.rs` line 38 at r16](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O30sNYLEjTU3WBESdjJ:-O30sNYLEjTU3WBESdjK:b8h91oy) ([raw file](https://github.com/TraceMachina/nativelink/blob/0f6be97694bb2353e07bfbbf58cf3b43c144a8b8/nativelink-store/src/redis_store.rs#L38)):*
> ```XML
> // TODO(caass): These (and other settings) should be made configurable via nativelink-config
> pub const READ_CHUNK_SIZE: usize = 64 * 1024;
> pub const CONNECTION_POOL_SIZE: usize = 3;
> ```

nit: Not `pub`.
___
*[`nativelink-store/src/redis_store.rs` line 46 at r16](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O30sYOX6RCiO9SfBzA1:-O30sYOX6RCiO9SfBzA2:b-7kooul) ([raw file](https://github.com/TraceMachina/nativelink/blob/0f6be97694bb2353e07bfbbf58cf3b43c144a8b8/nativelink-store/src/redis_store.rs#L46)):*
> ```XML
>     client_pool: RedisPool,
> 
>     /// A channel to publish updates to when a key is added, removed, or modified
> ```

nit: period.
___
*[`nativelink-store/src/redis_store.rs` line 60 at r16](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O30scGK1fpG5atSgbQE:-O30scGK1fpG5atSgbQF:b-7kooul) ([raw file](https://github.com/TraceMachina/nativelink/blob/0f6be97694bb2353e07bfbbf58cf3b43c144a8b8/nativelink-store/src/redis_store.rs#L60)):*
> ```XML
> 
> impl RedisStore {
>     /// Create a new `RedisStore` from the given configuration
> ```

nit: period.
___
*[`nativelink-store/src/redis_store.rs` line 76 at r16](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O30ssh5By8ex9y3VC1k:-O30ssh6Co2QXIlaM_-7:bgaa9ni) ([raw file](https://github.com/TraceMachina/nativelink/blob/0f6be97694bb2353e07bfbbf58cf3b43c144a8b8/nativelink-store/src/redis_store.rs#L76)):*
> ```XML
>             RedisMode::Standard => RedisConfig::from_url_centralized(addr),
>         }
>         .err_tip_with_code(|_| (Code::InvalidArgument, "while parsing redis node address"))?;
> ```

nit: You probably want to also encode the error redis passed into a string, otherwise users will have no idea what they did wrong.
___
*[`nativelink-store/src/redis_store.rs` line 100 at r16](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O30tSa19ya9AgpbDrWC:-O30tSa19ya9AgpbDrWD:b-7kooul) ([raw file](https://github.com/TraceMachina/nativelink/blob/0f6be97694bb2353e07bfbbf58cf3b43c144a8b8/nativelink-store/src/redis_store.rs#L100)):*
> ```XML
>     }
> 
>     /// Used for testing, when determinism is required
> ```

nit: period.
___
*[`nativelink-store/src/redis_store.rs` line 135 at r16](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O30u2wiA7T0HBfC03wg:-O30u2wiA7T0HBfC03wh:b-ofuzj5) ([raw file](https://github.com/TraceMachina/nativelink/blob/0f6be97694bb2353e07bfbbf58cf3b43c144a8b8/nativelink-store/src/redis_store.rs#L135)):*
> ```XML
>                 }
>                 Cow::Borrowed(body) => {
>                     let mut encoded_key = self.key_prefix.clone();
> ```

nit: Do this instead to remove a (usually) forced allocation:
```rs
let mut encoded_key = String::with_capacity(self.key_prefix.len() + body.len());
encoded_key.push_str(self.key_prefix);
encoded_key.push_str(body);
Cow::Owned(encoded_key)
```
___
*[`nativelink-store/src/redis_store.rs` line 287 at r16](https://reviewable.io/reviews/TraceMachina/nativelin [...]

2024-07-30 04:46 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> % validating this on a real redis cluster.

> Reviewed 4 of 9 files at r15.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-:-O30xUHlB7BbTa6b1HU4:bdh5k3e)* status: 2 of 3 LGTMs obtained, and all files reviewed, and 19 discussions need to be resolved (waiting on @adam-singer)



<!-- Sent from Reviewable.io -->

2024-07-30 20:34 UTC, adam-singer approved these changes
> Reviewed 2 of 9 files at r15.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188)* status: 2 of 3 LGTMs obtained, and all files reviewed, and 19 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-07-31 21:57 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  Confirmed testing

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-:-O39mzWM2YcNwEZgQSrt:bcjdfpa)* status: 3 of 3 LGTMs obtained, and all files reviewed, and 19 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-07-31 22:54 UTC, caass reviewed
Excellent :)

> Reviewed 1 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-:-O39zppIBefq8VVHiFIX:b5mwpvi)* status: 3 of 3 LGTMs obtained, and all files reviewed, and 8 discussions need to be resolved

___
*[`nativelink-error/src/lib.rs` line 216 at r16](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O30rkN6-bGaK9s5j6Av:-O39wLL878R-TJ1k7cPe:b-anldbb) ([raw file](https://github.com/TraceMachina/nativelink/blob/0f6be97694bb2353e07bfbbf58cf3b43c144a8b8/nativelink-error/src/lib.rs#L216)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I don't think `Code` should be translated into `Error`. `Code` is just a type of an error, not an error itself.
</blockquote></details>

This isn't my code, but if you want I'll file a follow-up PR for this.
___
*[`nativelink-store/src/redis_store.rs` line 102 at r11](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2kedwAAQpr37yf61kT:-O39yywI-k5Jdn3Ap8-3:b6sjm5i) ([raw file](https://github.com/TraceMachina/nativelink/blob/666d8913239021e0f4bbdbe9b3ff26a150acb0b9/nativelink-store/src/redis_store.rs#L102)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

please add a TODO and file a ticket, since we have this config already set and it does nothing now. This kind of breaking change we can't let leave around for long without removing it from the config, otherwise it will become stale and piss people off when it advertises it does something but it really doesn't.
</blockquote></details>

Will do :+1:
___
*[`nativelink-store/src/redis_store.rs` line 76 at r16](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O30ssh5By8ex9y3VC1k:-O39yeUz-7JeayeEnKfV:bb0bcmb) ([raw file](https://github.com/TraceMachina/nativelink/blob/0f6be97694bb2353e07bfbbf58cf3b43c144a8b8/nativelink-store/src/redis_store.rs#L76)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: You probably want to also encode the error redis passed into a string, otherwise users will have no idea what they did wrong.
</blockquote></details>

Wait, doesn't `err_tip` propagate the source error? Either way.


<!-- Sent from Reviewable.io -->

2024-07-31 23:03 UTC, caass reviewed
Ok, this should be the end of it.

> Reviewed 4 of 4 files at r17, 2 of 2 files at r18, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-:-O3A13lg983suRl2Kcoi:b-i6azzp)* status: 3 of 3 LGTMs obtained, and all files reviewed, and pending CI: pre-commit-checks, and 8 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-07-31 23:15 UTC, caass reviewed
> Reviewed 3 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188)* status: 3 of 3 LGTMs obtained, and all files reviewed, and pending CI: Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, windows-2022 / stable, and 8 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-08-01 00:24 UTC, caass reviewed
> Dismissed @allada and @zbirenbaum from 8 discussions.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188)* status: <span>:shipit:</span> complete! 3 of 3 LGTMs obtained, and all files reviewed

___
*[`nativelink-error/src/lib.rs` line 216 at r16](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O30rkN6-bGaK9s5j6Av:-O3AJVxT3DZKqJ14HTzD:b-9jyk89) ([raw file](https://github.com/TraceMachina/nativelink/blob/0f6be97694bb2353e07bfbbf58cf3b43c144a8b8/nativelink-error/src/lib.rs#L216)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

This isn't my code, but if you want I'll file a follow-up PR for this.
</blockquote></details>

Putting this in a follow-up


<!-- Sent from Reviewable.io -->

2024-08-01 00:24 UTC, merged

2024-08-21 18:16 UTC, adam-singer reviewed
@caass awhile since this has been last updated, can we retest this still works with redis vs units? We can do that offline to confirm. 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-:-O4q8lF96bfAIOnRzqOn:b-vxnzm4)* status: <span>:shipit:</span> complete! 3 of 3 LGTMs obtained, and all files reviewed



<!-- Sent from Reviewable.io -->

2024-08-21 22:35 UTC, caass reviewed
@adam-singer sure thing, happy to collab :+1: will put some time on your calendar

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-:-O4r3tkVAlJod9KBX8sx:bz7uc8g)* status: <span>:shipit:</span> complete! 3 of 3 LGTMs obtained, and all files reviewed

___
*[`nativelink-config/examples/redis.json` line 2 at r19](https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O3BfWap7FyOEjUilb24:-O4r4-lV1-6gg6laNAoe:bctij51) ([raw file](https://github.com/TraceMachina/nativelink/blob/b993432a33678de2c7d2e7d9ee60179e39225cfc/nativelink-config/examples/redis.json#L2)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

@caass  we should revert just this file and create a simpler `redis-cluster.json` example file, some of the keys used here no longer make sense from the changes made, we are no longer in a fast/slow store configuration. 

My understanding is this change had backwards compatibility for the old configuration format correct?
</blockquote></details>

Yeah, it was designed to be backwards compatible -- an upcoming change will update the config settings.


<!-- Sent from Reviewable.io -->