Fix typos in code comments
TraceMachina/nativelink pull request #1190
Opened 2024-07-24 07:59 UTC by aleksdmladenovic

# Description

Recently, I found out that there were 2 typos remaining in this project.

1. Here, `my` should be `may`.

https://github.com/TraceMachina/nativelink/blob/d37bd90a314890fe901235e0432d263faa66d221/deployment-examples/docker-compose/Dockerfile#L21

2. Here, the code comments for `simple_cache_test.sh` and `simple_prometheus_test.sh` are the same currently.
For `simple_prometheus_test.sh`, the comment should be changed.

https://github.com/TraceMachina/nativelink/blob/d37bd90a314890fe901235e0432d263faa66d221/integration_tests/simple_cache_test.sh#L16

https://github.com/TraceMachina/nativelink/blob/d37bd90a314890fe901235e0432d263faa66d221/integration_tests/simple_prometheus_test.sh#L16

Fixes #1189 

## Type of change

Please delete options that aren't relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

## Checklist

- [x] Updated documentation if needed
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-07-24 08:00 UTC, aleksdmladenovic commented
Just caught simple issues. cc: @allada, @MarcusSorealheis 

Waiting for reviews on my previous submitted issues and wanna work on more issues. :)

2024-07-24 10:32 UTC, aaronmondal requested changes
Let's keep this one open for a while and use it to aggregate non-user-facing typo fixes.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1190#-:-O2ZH5eI3trdVMPjewPe:b-9moyq4)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04



<!-- Sent from Reviewable.io -->

2024-08-08 13:49 UTC, aleksdmladenovic commented
Rebased. cc: @aaronmondal, @MarcusSorealheis

2024-08-09 09:30 UTC, aleksdmladenovic commented
Hope you to merge this. cc: @allada, @MarcusSorealheis, @aaronmondal

2024-08-12 04:03 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1190#-:-O43kH329Acb0oyzLaf8:bnfp4nl)* status: 1 of 2 LGTMs obtained, and all files reviewed



<!-- Sent from Reviewable.io -->

2024-08-12 04:03 UTC, allada approved these changes
cc: @aaronmondal needs one more stamp.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1190#-:-O43kM0d6CGDKGGXVwoL:b-idatew)* status: 1 of 2 LGTMs obtained, and all files reviewed



<!-- Sent from Reviewable.io -->

2024-08-12 21:51 UTC, aaronmondal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1190#-:-O47ZfE39-IkDU38byyn:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained, and all files reviewed



<!-- Sent from Reviewable.io -->

2024-08-12 21:51 UTC, merged