Convert AwaitedAction to and from raw bytes
TraceMachina/nativelink pull request #1206
Opened 2024-07-27 05:10 UTC by zbirenbaum

Makes AwaitedAction Serialize/Deserialize and adds ability to convert to
and from raw bytes. This will be used to communicate operation data to
and external data storage such as Redis through the store API.

Towards #1182

Please delete options that aren't relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-07-27 06:01 UTC, allada requested changes
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1206)* status: 0 of 1 LGTMs obtained, and 1 of 4 files reviewed, and 1 discussions need to be resolved

___
*[`nativelink-scheduler/src/awaited_action_db/awaited_action.rs` line 152 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1206#-O2ml_Ge77Y1FmdcIxIS:-O2ml_Ge77Y1FmdcIxIT:b-wilz5e) ([raw file](https://github.com/TraceMachina/nativelink/blob/f975d3b96974d02d28ba4f087464ece3f716bbb2/nativelink-scheduler/src/awaited_action_db/awaited_action.rs#L152)):*
> ```XML
> }
> 
> impl TryInto<Vec<u8>> for AwaitedAction {
> ```

Can we use protos or json strings instead?

the reason is because `bincode` is not multi-language compatible and allowing users to read the state out of redis directly (for scaling cloud instances) is a real use case.


<!-- Sent from Reviewable.io -->

2024-07-27 21:46 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1206)* status: 0 of 1 LGTMs obtained, and 0 of 4 files reviewed, and pending CI: pre-commit-checks, and 1 discussions need to be resolved

___
*[`nativelink-scheduler/src/awaited_action_db/awaited_action.rs` line 152 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1206#-O2ml_Ge77Y1FmdcIxIS:-O2q3Ehe2kYkzbYDcn8D:b-rfdzqo) ([raw file](https://github.com/TraceMachina/nativelink/blob/f975d3b96974d02d28ba4f087464ece3f716bbb2/nativelink-scheduler/src/awaited_action_db/awaited_action.rs#L152)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Can we use protos or json strings instead?

the reason is because `bincode` is not multi-language compatible and allowing users to read the state out of redis directly (for scaling cloud instances) is a real use case.
</blockquote></details>

Great point, updated it to use serde_json.

As a side note I did some digging and found this really useful tool which compared the performance of various encoders/decoders and serde_json is a really poor performer in the grand scheme of things.

https://david.kolo.ski/rust_serialization_benchmark

Prost is better but would lock us out of most or possibly all redis-specific advantages for performance.

I don't think this is something to prioritize atm though, serde_json should be fine for now, and this is abstracted to just produce/consume bytes so easily updatable later.


<!-- Sent from Reviewable.io -->

2024-07-29 01:38 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1206#-:-O2w7zCY5hYZKtYzC8gi:bnfp4nl)* status: 1 of 1 LGTMs obtained, and all files reviewed, and 1 discussions need to be resolved

___
*[`nativelink-scheduler/src/awaited_action_db/awaited_action.rs` line 152 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1206#-O2ml_Ge77Y1FmdcIxIS:-O2w7lF6ASYVwE-wElzX:b-nkk3oh) ([raw file](https://github.com/TraceMachina/nativelink/blob/f975d3b96974d02d28ba4f087464ece3f716bbb2/nativelink-scheduler/src/awaited_action_db/awaited_action.rs#L152)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Great point, updated it to use serde_json.

As a side note I did some digging and found this really useful tool which compared the performance of various encoders/decoders and serde_json is a really poor performer in the grand scheme of things.

https://david.kolo.ski/rust_serialization_benchmark

Prost is better but would lock us out of most or possibly all redis-specific advantages for performance.

I don't think this is something to prioritize atm though, serde_json should be fine for now, and this is abstracted to just produce/consume bytes so easily updatable later.
</blockquote></details>

Yeah, performance is not something that is critical here, since we are going to be able to paralyze this. We could also make this a config option at some point.


<!-- Sent from Reviewable.io -->

2024-07-29 01:46 UTC, zbirenbaum reviewed
> Dismissed @allada from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1206)* status: 1 of 1 LGTMs obtained, and 2 of 4 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Cloudflare Pages, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

___
*[`nativelink-scheduler/src/awaited_action_db/awaited_action.rs` line 152 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1206#-O2ml_Ge77Y1FmdcIxIS:-O2w9aLD4NL0P20FCrdI:b-hfghm4) ([raw file](https://github.com/TraceMachina/nativelink/blob/f975d3b96974d02d28ba4f087464ece3f716bbb2/nativelink-scheduler/src/awaited_action_db/awaited_action.rs#L152)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Yeah, performance is not something that is critical here, since we are going to be able to paralyze this. We could also make this a config option at some point.
</blockquote></details>

Sounds good


<!-- Sent from Reviewable.io -->

2024-07-29 19:04 UTC, zbirenbaum reviewed
> Reviewed 1 of 4 files at r2, 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1206)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed



<!-- Sent from Reviewable.io -->

2024-07-29 19:04 UTC, merged