Migrate `docs` build system from pnpm to `bun`
TraceMachina/nativelink pull request #1268
Opened 2024-08-19 13:05 UTC by SchahinRohani

# Description

- Migrate the docs build system from pnpm to bun
- Set up GitHub workflow with Deno Deploy
- Configure Biome for code quality
- Remove unnecessary packages (Playform Compression causes issues)
- Refactore some of the Docs code for Code Quality.
- Update documentation to reflect new setup

## Type of change

Please delete options that aren't relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist

- [x] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-08-21 17:27 UTC, allada reviewed
+@blakehatch 
+@aaronmondal    

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-:-O4pyY0y0DT0KsGX_Tam:b-xxgcus)* status: 0 of 2 LGTMs obtained, and 0 of 25 files reviewed, and pending CI: Cargo Dev / macos-13 (waiting on @aaronmondal and @blakehatch)



<!-- Sent from Reviewable.io -->

2024-08-21 19:08 UTC, aaronmondal requested changes
Fantastic change! This finally gives us full control over the entire website deployment process. Also it's way nicer to work with bun and the deno deployment is even faster than cloudflare :rocket:

> Reviewed 17 of 24 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-:-O4qKZCc58O_b4Scl3Qh:b-xi2vvy)* status: 0 of 2 LGTMs obtained, and all files reviewed, and pending CI: Cargo Dev / macos-13, and 17 discussions need to be resolved (waiting on @aaronmondal and @blakehatch)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qFSjKDD8N8Ke7XjHQ):*
Add "Fixes #1082" to the commit message since it fixes that issue.
___
*[`flake.nix` line 429 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qFjp47c8AaUOGpPHr:-O4qFjp59cU-GW6Eul2c:undefined) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/flake.nix#L429)):*
> ```Nix
>               bazel
> 
>               ## Infrastructure Stack
> ```


___
*[`flake.nix` line 447 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qFocn645fYcvD4x1j:-O4qFocn645fYcvD4x1k:undefined) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/flake.nix#L447)):*
> ```Nix
>               pkgs.kustomize
> 
>               ## Web Stack
> ```


___
*[`flake.nix` line 451 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qFvp5DqIAilPm-g2-:-O4qFvp5DqIAilPm-g20:b-aarmgi) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/flake.nix#L451)):*
> ```Nix
>               pkgs.deno
>               pkgs.lychee
>               pkgs.nodejs_22 # Only for Pagefind.
> ```

Try whether we can get away with `pkgs.nodejs-slim_22` which has a smaller closure size.
___
*[`.github/workflows/native-docs.yaml` line 14 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qGZSo4ND2_gy7jqJ3:-O4qGZSo4ND2_gy7jqJ4:b10fi91) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/.github/workflows/native-docs.yaml#L14)):*
> ```YAML
>   deploy:
>     name: Docs Deployment
>     runs-on:  ubuntu-22.04
> ```

Use Ubuntu 24.04 since it might be slightly faster.
___
*[`.github/workflows/native-docs.yaml` line 29 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qGRup-w5kkIgM4nmb:-O4qGRuq8aR6NQKiluI8:b-2ljh4w) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/.github/workflows/native-docs.yaml#L29)):*
> ```YAML
>         run: |
>           nix develop --impure --command bash -c "
>             deno install -Arf jsr:@deno/deployctl &&
> ```

Pin the `@deno/deployctl` to a hashlocked version.
___
*[`.github/workflows/native-docs.yaml` line 34 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qGiyiD-eb5UO6aAa3:-O4qGiyiD-eb5UO6aAa4:b-f98rl9) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/.github/workflows/native-docs.yaml#L34)):*
> ```YAML
>           "
> 
>       - name: Cache Nix derivations
> ```

This step should come before the deploy step.
___
*[`docs/.gitignore` line 34 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qGvlk434M2SbBqXpa:-O4qGvlk434M2SbBqXpb:undefined) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/docs/.gitignore#L34)):*
> ```ignore
> stats.html
> 
> # Deno Deploy File
> ```





_Suggestion:_
```ignore
file
```
___
*[`docs/biome.json` line 10 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qH6nk5jCK-kJ7J2Xk:-O4qH6nk5jCK-kJ7J2Xl:bf8g4wx) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/docs/biome.json#L10)):*
> ```JSON
>     "enabled": true,
>     "rules": {
>       "recommended": true,
> ```

Could we put this back to "all" and disable only the warnings that really don't make sense (like the naming convention warning because of the generated md_to_mdx and metaphase types)? I'd like this to be as strict as possible.
___
*[`docs/biome.json` line 17 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qHVsw20JvTi3ZH7nD:-O4qHVsw20JvTi3ZH7nE:b-qzl56r) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/docs/biome.json#L17)):*
> ```JSON
>       }
>     },
>     "ignore": [".astro", "dist", "node_modules", ".wrangler"]
> ```

I think it's fine to remove the `.wrangler` here. It does break previous users once, but they should remove the old `.wrangler` directory anyways.
___
*[`docs/package.json` line 17 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qIApM80QKz-nU2a-d:-O4qIApN2KSD1Tti-Qi8:bf8b0o1) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/docs/package.json#L17)):*
> ```JSON
>     "fix": "bun lint && bun format && bun sync",
>     "format": "biome format --write .",
>     "lint": "biome check --write --unsafe .",
> ```

Linting should only print linter warnings, not fix them. The `format` script should instead do the file transformations.
___
*[`docs/package.json` line 21 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qIZCY-6aBbVCF25oE:-O4qIZCY-6aBbVCF25oF:bhkj94e) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/docs/package.json#L21)):*
> ```JSON
>     "serve": "deno run --allow-net --allow-read --allow-env ./dist/server/entry.mjs",
>     "deploy": "deployctl deploy --include=./dist --entrypoint=./dist/server/entry.mjs --save-config",
>     "prod": "bun install && bun docs && bun run build && bun run deploy"
> ```

I believe this `install` needs to use `--frozen-lockfile` to prevent bun from autoupdating the `bun.lockb`.
___
*[`docs/package.json` line 48 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qImCz3pJb2-kAJCzR:-O4qImCz3pJb2-kAJCzS:bn8es9y) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/docs/package.json#L48)):*
> ```JSON
>   },
>   "overrides": {
>     "playwright-core": "1.44.0"
> ```

Is `1.44.0` correct or do we have to use `1.44.1` like previrously?
___
*[`docs/README.md` line 71 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qJBtvCpkJuo77MPiH:-O4qJBtvCpkJuo77MPiI:b-c6hokw) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/docs/README.md#L71)):*
> ```Markdown
> ## 🐛 Known issues
> 
> - `bun metaphase` isn't working with the nix version of Bazel,
> ```

This is only true on MacOS. Linux doesn't require this.
___
*[`tools/nixpkgs_bun.diff` line 29 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qK8cRCvd7B8u--APl:-O4qK8cRCvd7B8u--APm:bk6y6rc) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/tools/nixpkgs_bun.diff#L29)):*
> ```Diff
>          url = "https://github.com/oven-sh/bun/releases/download/bun-v${version}/bun-darwin-x64-baseline.zip";
> -        hash = "sha256-5PLk8q3di5TW8HUfo7P3xrPWLhleAiSv9jp2XeL47Kk=";
> +        hash = "sha256-nf75MyU6ye7xHwdxJpaAGcg4MbJ7v2OUgEbepaUE5kg=";
> ```

This seems to be the wrong hash: https://github.com/TraceMachina/nativelink/actions/runs/10488998422/job/29052651314?pr=1268#step:6:286
___
*[`docs/src/styles/custom.css` line 19 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qJNXw0vmOHBAXyyPY:-O4qJNXw0vmOHBAXyyPZ:bko48p6) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/docs/src/styles/custom.css#L19)):*
> ```CSS
> 
> html {
>   scroll-behavior: smooth;
> ```

@blakehatch Do we want this globally?
___
*[`docs/src/utils/metaphase_aot.ts` line 1 [...]

2024-08-21 19:20 UTC, aaronmondal commented
@blakehatch I believe we need to adjust the github settings so that deno deploy can deploy from this repo.

We'll also need to run some tests to ensure that this works properly on PRs. @SchahinRohani We probably need to adjust the workflow with a conditional so that it only builds and lints the docs on PRs but runs the entire deploy step on pushes to main. We can do this by splitting the deno invocations in two steps and using an `if` like here: https://github.com/TraceMachina/nativelink/blob/ae0c82c06fff8753c083ee8d5e791d9807ec7498/.github/workflows/image.yaml#L55

2024-08-22 10:57 UTC, SchahinRohani reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1268)* status: 0 of 2 LGTMs obtained, and 15 of 26 files reviewed, and pending CI: Cargo Dev / macos-13, Docs Deployment, Installation / macos-13, Installation / macos-14, Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (22.04), and 17 discussions need to be resolved (waiting on @aaronmondal and @blakehatch)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qFSjKDD8N8Ke7XjHQ):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Add "Fixes #1082" to the commit message since it fixes that issue.
</blockquote></details>

done.
___
*[`flake.nix` line 429 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qFjp47c8AaUOGpPHr:-O4qwFuW6_zvOPm8vpiY:b-7rl0jd) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/flake.nix#L429)):*
> ```Nix
>               bazel
> 
>               ## Infrastructure Stack
> ```

done.
___
*[`flake.nix` line 447 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qFocn645fYcvD4x1j:-O4qwHG62dxkySOWlzNG:b-7rl0jd) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/flake.nix#L447)):*
> ```Nix
>               pkgs.kustomize
> 
>               ## Web Stack
> ```

done.
___
*[`flake.nix` line 451 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qFvp5DqIAilPm-g2-:-O4qQJxt7t3tRn8TfmFl:bf7u1wu) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/flake.nix#L451)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Try whether we can get away with `pkgs.nodejs-slim_22` which has a smaller closure size.
</blockquote></details>

Looks like we don't even need nodejs for now. It builds on my test/workflow without having nodejs.
Since the Nix Installation on MacOS is failing on https://github.com/TraceMachina/nativelink/pull/1270 i dont think its a problem with the flake dependencies.
___
*[`.github/workflows/native-docs.yaml` line 14 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qGZSo4ND2_gy7jqJ3:-O4qQIl69iJ9r_1YnIlb:b2ni9bh) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/.github/workflows/native-docs.yaml#L14)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Use Ubuntu 24.04 since it might be slightly faster.
</blockquote></details>

ok.
___
*[`.github/workflows/native-docs.yaml` line 29 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qGRup-w5kkIgM4nmb:-O4qQH2cEk3ljtwrdAuX:b2ni9bh) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/.github/workflows/native-docs.yaml#L29)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Pin the `@deno/deployctl` to a hashlocked version.
</blockquote></details>

ok.
___
*[`.github/workflows/native-docs.yaml` line 34 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qGiyiD-eb5UO6aAa3:-O4qQFw-3LynB038S0p3:b2ni9bh) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/.github/workflows/native-docs.yaml#L34)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

This step should come before the deploy step.
</blockquote></details>

ok.
___
*[`docs/.gitignore` line 34 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qGvlk434M2SbBqXpa:-O4qQEC1-2dq_O6X8pN2:b2ni9bh) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/docs/.gitignore#L34)):*
> ```ignore
> stats.html
> 
> # Deno Deploy File
> ```

ok.
___
*[`docs/biome.json` line 10 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qH6nk5jCK-kJ7J2Xk:-O4qQDLYAId1whIoFa9C:b2ni9bh) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/docs/biome.json#L10)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Could we put this back to "all" and disable only the warnings that really don't make sense (like the naming convention warning because of the generated md_to_mdx and metaphase types)? I'd like this to be as strict as possible.
</blockquote></details>

ok.
___
*[`docs/biome.json` line 17 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qHVsw20JvTi3ZH7nD:-O4qQBJb3MPFNbDbLxT3:b2ni9bh) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/docs/biome.json#L17)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

I think it's fine to remove the `.wrangler` here. It does break previous users once, but they should remove the old `.wrangler` directory anyways.
</blockquote></details>

ok.
___
*[`docs/package.json` line 17 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qIApM80QKz-nU2a-d:-O4qwIYvEdPfvoJHF1rg:bwqp8cs) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/docs/package.json#L17)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Linting should only print linter warnings, not fix them. The `format` script should instead do the file transformations.
</blockquote></details>

I have also added a check.lint for only printing linter warnings. It is convenient to work with the bun lint command.
___
*[`docs/package.json` line 21 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qIZCY-6aBbVCF25oE:-O4qPld25TooSqOYvpem:bq1jnx3) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/docs/package.json#L21)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

I believe this `install` needs to use `--frozen-lockfile` to prevent bun from autoupdating the `bun.lockb`.
</blockquote></details>

The bun.lockb should be frozen now, so the bun install should not make any difference to the lockfile.
___
*[`docs/package.json` line 48 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qImCz3pJb2-kAJCzR:-O4qPdyPAjm9eVRmN2mH:b3d7y03) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/docs/package.json#L48)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Is `1.44.0` correct or do we have to use `1.44.1` like previrously?
</blockquote></details>

I used the version thats pinned in the nixpkgs_playwright.diff.
___
*[`docs/README.md` line 71 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qJBtvCpkJuo77MPiH:-O4qvwcq6CCY8iE-SyjP:b-p8s52n) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/docs/README.md#L71)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

This is only true on MacOS. Linux doesn't require this.
</blockquote></details>

Rewrited.
___
*[`tools/nixpkgs_bun.diff` line 29 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qK8cRCvd7B8u--APl:-O4qvr_t5hKub3ULVopV:b-qssebl) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/tools/nixpkgs_bun.diff#L29)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

This seems to be the wrong hash: https://github.com/TraceMachina/nativelink/actions/runs/10488998422/job/29052651314?pr=1268#step:6:286
</blockquote></details>

 [...]

2024-08-22 11:08 UTC, SchahinRohani reviewed
@aaronmondal I have implemented a test deployment on PR and a Production Deployment on push on main.

I believe that's a good strategy to preview test deployments before merging them into main.

@blakehatch  To enable automatic authorization for deployments, please log in to [https://dash.deno.com/login](https://dash.deno.com/login) once. After that, I can invite you to the Nativelink organization, allowing you to manage the deployment of the Nativelink GitHub repository.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-:-O4tj78U23YuOwwNsak8:b-pvlwnn)* status: 0 of 2 LGTMs obtained, and 15 of 26 files reviewed, and pending CI: Docs Deployment, Installation / macos-13, Installation / macos-14, Remote / large-ubuntu-22.04, and 17 discussions need to be resolved (waiting on @aaronmondal and @blakehatch)



<!-- Sent from Reviewable.io -->

2024-08-22 11:11 UTC, SchahinRohani reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1268)* status: 0 of 2 LGTMs obtained, and 15 of 26 files reviewed, and pending CI: Docs Deployment, Installation / macos-13, Installation / macos-14, Remote / large-ubuntu-22.04, and 17 discussions need to be resolved (waiting on @aaronmondal and @blakehatch)

___
*[`tools/nixpkgs_bun.diff` line 29 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qK8cRCvd7B8u--APl:-O4tlzdS749hbCg-lyQw:bqi5l9d) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/tools/nixpkgs_bun.diff#L29)):*
<details><summary><i>Previously, SchahinRohani (Schahin) wrote…</i></summary><blockquote>

fixed.
</blockquote></details>

The sha256 of the bun package is the right version, so there was no fix fo this.


<!-- Sent from Reviewable.io -->

2024-08-22 20:51 UTC, aaronmondal requested changes
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1268)* status: 0 of 2 LGTMs obtained, and all files reviewed, and pending CI: Docs Deployment, Installation / macos-14, and 12 discussions need to be resolved (waiting on @blakehatch)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qFSjKDD8N8Ke7XjHQ):*
<details><summary><i>Previously, SchahinRohani (Schahin) wrote…</i></summary><blockquote>

done.
</blockquote></details>

Hmm maybe bugged in reviewable? It's ok I can add this when merging.
___
*[`.github/workflows/native-docs.yaml` line 29 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qGRup-w5kkIgM4nmb:-O4vO9gF0-i5luYza7tv:b-ajh0pb) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/.github/workflows/native-docs.yaml#L29)):*
<details><summary><i>Previously, SchahinRohani (Schahin) wrote…</i></summary><blockquote>

ok.
</blockquote></details>

Is there a way to pin this to a hash instead of a version? Versions could be overridden which is a supply-chain security risk.
___
*[`docs/README.md` line 71 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4voOUu-x5fdSYg9bX5:-O4voOUu-x5fdSYg9bX6:undefined) ([raw file](https://github.com/TraceMachina/nativelink/blob/7aa81c01d04afb3efe75f0549e47cc0a762406ae/docs/README.md#L71)):*
> ```Markdown
> ## 🐛 Known issues
> 
> - `bun run docs.build` isn't working on `MacOS` with the nix version of Bazel,
> ```





_Suggestion:_
```Markdown
 doesn't work
```
___
*[`docs/README.md` line 71 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4voYSJAkIXQqOaghxY:-O4voYSJAkIXQqOaghxZ:undefined) ([raw file](https://github.com/TraceMachina/nativelink/blob/7aa81c01d04afb3efe75f0549e47cc0a762406ae/docs/README.md#L71)):*
> ```Markdown
> ## 🐛 Known issues
> 
> - `bun run docs.build` isn't working on `MacOS` with the nix version of Bazel,
> ```





_Suggestion:_
```Markdown
.
```
___
*[`docs/README.md` line 71 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4vodJ5-8J0QQJyDqSJ:-O4vodJ5-8J0QQJyDqSK:undefined) ([raw file](https://github.com/TraceMachina/nativelink/blob/7aa81c01d04afb3efe75f0549e47cc0a762406ae/docs/README.md#L71)):*
> ```Markdown
> ## 🐛 Known issues
> 
> - `bun run docs.build` isn't working on `MacOS` with the nix version of Bazel,
> ```





_Suggestion:_
```Markdown
MacOS
```
___
*[`docs/README.md` line 72 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4vom296D2NlEbND9YA:-O4vom296D2NlEbND9YB:b45h) ([raw file](https://github.com/TraceMachina/nativelink/blob/7aa81c01d04afb3efe75f0549e47cc0a762406ae/docs/README.md#L72)):*
> ```Markdown
> 
> - `bun run docs.build` isn't working on `MacOS` with the nix version of Bazel,
>   The solution to this: Install Bun and Bazel on your host and build the docs outside the flake.
> ```





_Suggestion:_
```Markdown
As a workaround i
```
___
*[`docs/README.md` line 73 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4voSoZ1ajCJykb8Ga2:-O4voSoZ1ajCJykb8Ga3:undefined) ([raw file](https://github.com/TraceMachina/nativelink/blob/7aa81c01d04afb3efe75f0549e47cc0a762406ae/docs/README.md#L73)):*
> ```Markdown
> - `bun run docs.build` isn't working on `MacOS` with the nix version of Bazel,
>   The solution to this: Install Bun and Bazel on your host and build the docs outside the flake.
> - `bun dev` isn't reloading the changes in the starlight.conf.ts
> ```





_Suggestion:_
```Markdown
doesn't reload
```
___
*[`tools/nixpkgs_bun.diff` line 29 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qK8cRCvd7B8u--APl:-O4vqGa0C56QyZlmIVpj:b-dttkub) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/tools/nixpkgs_bun.diff#L29)):*
<details><summary><i>Previously, SchahinRohani (Schahin) wrote…</i></summary><blockquote>

The sha256 of the bun package is the right version, so there was no fix fo this.
</blockquote></details>

I think there is a duplicate `==` at the end now.
___
*[`docs/src/utils/md_to_mdx.ts` line 169 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4vpoUa5nCXt0NEWemd:-O4vpoUa5nCXt0NEWeme:b-rvcwd9) ([raw file](https://github.com/TraceMachina/nativelink/blob/910d5bec05bb107203c4507b8f9f93d7d8824875/docs/src/utils/md_to_mdx.ts#L169)):*
> ```XML
> }
> 
> export function preProcessMarkdown(markdown: string): string {
> ```

No need to rename this.
___
*[`docs/src/utils/md_to_mdx.ts` line 230 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4vpRT5DJTDjODmpA4s:-O4vpRT5DJTDjODmpA4t:bkjeswf) ([raw file](https://github.com/TraceMachina/nativelink/blob/7aa81c01d04afb3efe75f0549e47cc0a762406ae/docs/src/utils/md_to_mdx.ts#L230)):*
> ```XML
> }
> 
> function isSpecialLine(line: string): boolean {
> ```

This should probably be called `isAside`: https://starlight.astro.build/guides/components/#asides



_Code quote:_
```XML
SpecialLine
```


<!-- Sent from Reviewable.io -->

2024-08-23 08:27 UTC, SchahinRohani reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1268)* status: 0 of 2 LGTMs obtained, and 21 of 26 files reviewed, and pending CI: Analyze (javascript-typescript), Docs Deployment, Publish image, Publish nativelink-worker-init, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, and 12 discussions need to be resolved (waiting on @aaronmondal and @blakehatch)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qFSjKDD8N8Ke7XjHQ):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Hmm maybe bugged in reviewable? It's ok I can add this when merging.
</blockquote></details>

My bad! Now it should be in the commit message :smile: 
___
*[`docs/README.md` line 71 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4voOUu-x5fdSYg9bX5:-O4yC7OB-Ahi0Hzpu0KC:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7aa81c01d04afb3efe75f0549e47cc0a762406ae/docs/README.md#L71)):*
> ```Markdown
> ## 🐛 Known issues
> 
> - `bun run docs.build` isn't working on `MacOS` with the nix version of Bazel,
> ```

Done.
___
*[`docs/README.md` line 71 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4voYSJAkIXQqOaghxY:-O4yC7ls3eHUC4SwkDHW:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7aa81c01d04afb3efe75f0549e47cc0a762406ae/docs/README.md#L71)):*
> ```Markdown
> ## 🐛 Known issues
> 
> - `bun run docs.build` isn't working on `MacOS` with the nix version of Bazel,
> ```

Done.
___
*[`docs/README.md` line 71 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4vodJ5-8J0QQJyDqSJ:-O4yC81h4vqbVmrSEfbo:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7aa81c01d04afb3efe75f0549e47cc0a762406ae/docs/README.md#L71)):*
> ```Markdown
> ## 🐛 Known issues
> 
> - `bun run docs.build` isn't working on `MacOS` with the nix version of Bazel,
> ```

Done.
___
*[`docs/README.md` line 72 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4vom296D2NlEbND9YA:-O4yC8qLEHrRmyTHUM51:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7aa81c01d04afb3efe75f0549e47cc0a762406ae/docs/README.md#L72)):*
> ```Markdown
> 
> - `bun run docs.build` isn't working on `MacOS` with the nix version of Bazel,
>   The solution to this: Install Bun and Bazel on your host and build the docs outside the flake.
> ```

Done.
___
*[`docs/README.md` line 73 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4voSoZ1ajCJykb8Ga2:-O4yC9K-AiXUeKEaL5Ku:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7aa81c01d04afb3efe75f0549e47cc0a762406ae/docs/README.md#L73)):*
> ```Markdown
> - `bun run docs.build` isn't working on `MacOS` with the nix version of Bazel,
>   The solution to this: Install Bun and Bazel on your host and build the docs outside the flake.
> - `bun dev` isn't reloading the changes in the starlight.conf.ts
> ```

Done.
___
*[`tools/nixpkgs_bun.diff` line 29 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qK8cRCvd7B8u--APl:-O4vvFQc4afttuiTdlQO:b-3jnsmg) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/tools/nixpkgs_bun.diff#L29)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

I think there is a duplicate `==` at the end now.
</blockquote></details>

I think the sha256sum is valid for the bun package.
___
*[`.github/workflows/native-docs.yaml` line 29 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qGRup-w5kkIgM4nmb:-O4y2fY43Mxq5mS-0gTz:b-dmdfoj) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/.github/workflows/native-docs.yaml#L29)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Is there a way to pin this to a hash instead of a version? Versions could be overridden which is a supply-chain security risk.
</blockquote></details>

I moved it from the workflow in to the package.json.
___
*[`docs/src/utils/md_to_mdx.ts` line 169 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4vpoUa5nCXt0NEWemd:-O4vuwGN1ThueGKsv1W4:b2nhll9) ([raw file](https://github.com/TraceMachina/nativelink/blob/910d5bec05bb107203c4507b8f9f93d7d8824875/docs/src/utils/md_to_mdx.ts#L169)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

No need to rename this.
</blockquote></details>

Ok.
___
*[`docs/src/utils/md_to_mdx.ts` line 230 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4vpRT5DJTDjODmpA4s:-O4yBYcEE3W0cghx-hjq:b-8c8dk6) ([raw file](https://github.com/TraceMachina/nativelink/blob/7aa81c01d04afb3efe75f0549e47cc0a762406ae/docs/src/utils/md_to_mdx.ts#L230)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

This should probably be called `isAside`: https://starlight.astro.build/guides/components/#asides
</blockquote></details>

This is getting more into the actual docs generation, which should not be a part of this PR. This is only a quick fix for the successful integration of Biome without any warnings and errors.


<!-- Sent from Reviewable.io -->

2024-08-24 01:05 UTC, aaronmondal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

@blakehatch and I need to set up the repo for this before we can merge, but I think this is good now. Great job!

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-:-O50u_xFB1Ncn1qth9MP:bdno5c9)* status: 1 of 2 LGTMs obtained, and all files reviewed, and pending CI: Installation / macos-13, docker-compose-compiles-nativelink (22.04), integration-tests (22.04) (waiting on @blakehatch)



<!-- Sent from Reviewable.io -->

2024-08-24 17:44 UTC, blakehatch reviewed
<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Everything functional for me and significantly faster cuz of Bun.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-:-O54T_GGEY8NoPHb0zF5:b6zqnxk)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained, and all files reviewed

___
*[`docs/src/styles/custom.css` line 19 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-O4qJNXw0vmOHBAXyyPY:-O54TL6u7nIV2he9HfPO:bkkjnyf) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dbf9f91ddba220d363d846bf0d17f623fc856b9/docs/src/styles/custom.css#L19)):*
<details><summary><i>Previously, SchahinRohani (Schahin) wrote…</i></summary><blockquote>

Just have a look on the desktop version on https://nativelink-docs.deno.dev and use the right sidebar. You will see the effect and i would recommend it.
</blockquote></details>

For docs I would like it globally.


<!-- Sent from Reviewable.io -->

2024-09-03 11:52 UTC, aaronmondal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

I'll merge as soon as we have the deno deploy app set up.

> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1268#-:-O5riGoPAbNLDUdmIsPs:bchts5k)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained, and all files reviewed



<!-- Sent from Reviewable.io -->

2024-09-03 11:52 UTC, aaronmondal approved these changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1268)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained, and all files reviewed



<!-- Sent from Reviewable.io -->

2024-09-04 07:59 UTC, merged