Fix potential infinite loop in `RedisStore::update`
TraceMachina/nativelink pull request #1269
Opened 2024-08-21 05:55 UTC by caass

- **Drive-by ignore .zed config folder**
- **Implement `DropCloseReaderHalf::try_recv`**
- **Improve wait-for-command abilities in redis tests.**
- **Fix a possible infinite loop in `RedisStore::update`.**

# Description

There was a logic bug in our original implementation of the redis store that persisted across the rewrite to fred -- there could be an infinite loop in `RedisStore::update`. This PR fixes that.

See: https://reviewable.io/reviews/TraceMachina/nativelink/1188#-O2pu9LV5ux4ILuT6MND

## Type of change

Please delete options that aren't relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

The test suite has been validated to pass and behave as expected.

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-08-21 06:03 UTC, caass reviewed
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1269)* status: 0 of 1 LGTMs obtained, and all files reviewed, and pending CI: Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 2 discussions need to be resolved

___
*[`.gitignore` line 4 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4nViKf4_LzErWCELdr:-O4nViKf4_LzErWCELds:b-vi50gq) ([raw file](https://github.com/TraceMachina/nativelink/blob/049220e77a6ffe452c8a331e45b2b33b449c64ec/.gitignore#L4)):*
> ```ignore
> target/
> .vscode/
> .zed
> ```

FYI you can't use LLDB in zed so I'm back to println debugging...
___
*[`nativelink-store/src/redis_store.rs` line 293 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4nW1Zg7NO3smRk5Hfa:-O4nW1Zg7NO3smRk5Hfb:b3tm34x) ([raw file](https://github.com/TraceMachina/nativelink/blob/049220e77a6ffe452c8a331e45b2b33b449c64ec/nativelink-store/src/redis_store.rs#L293)):*
> ```XML
> 
>                 eof_reached = true;
>                 continue;
> ```

This is semantically equivalent to `break`, but I felt that it was more clear to specifically indicate that an empty chunk indicates `EOF`.
___
*[`nativelink-store/tests/redis_store_test.rs` line 56 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4nWS5cEhTK7euxA0xL:-O4nWS5cEhTK7euxA0xM:b-czb9kb) ([raw file](https://github.com/TraceMachina/nativelink/blob/049220e77a6ffe452c8a331e45b2b33b449c64ec/nativelink-store/tests/redis_store_test.rs#L56)):*
> ```XML
>     rx: watch::Receiver<MockCommand>,
> 
>     failing: AtomicBool,
> ```

FYI this wound up being more useful for getting helpful error messages than anything else, since we were struggling with getting tokio to only tell us about one error at a time.
___
*[`nativelink-store/tests/redis_store_test.rs` line 472 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4nWcfr8IqLPbPFKq0N:-O4nWcfsDv506GL1uxH0:b-k5jt3m) ([raw file](https://github.com/TraceMachina/nativelink/blob/049220e77a6ffe452c8a331e45b2b33b449c64ec/nativelink-store/tests/redis_store_test.rs#L472)):*
> ```XML
> async fn yield_between_sending_packets_in_update() -> Result<(), Error> {
>     let data_p1 = Bytes::from(vec![b'A'; 6 * 1024]);
>     let data_p2 = Bytes::from(vec![b'B'; 4 * 1024]);
> ```

This made debugging easier, since at a glance I could tell what data had been sent and what hadn't.
___
*[`nativelink-store/tests/redis_store_test.rs` line 553 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4nWqLb3ZYbe16OkN6K:-O4nWqLb3ZYbe16OkN6L:bdu10x6) ([raw file](https://github.com/TraceMachina/nativelink/blob/049220e77a6ffe452c8a331e45b2b33b449c64ec/nativelink-store/tests/redis_store_test.rs#L553)):*
> ```XML
>         },
>         async {
>             let mut store_rx = mocks.subscribe();
> ```

Nit this API could be more clear.
___
*[`nativelink-util/src/buf_channel.rs` line 209 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4nWuHI6mkOfD8eG1XW:-O4nWuHI6mkOfD8eG1XX:bisg3zp) ([raw file](https://github.com/TraceMachina/nativelink/blob/049220e77a6ffe452c8a331e45b2b33b449c64ec/nativelink-util/src/buf_channel.rs#L209)):*
> ```XML
>     }
> 
>     fn recv_inner(&mut self, data: Result<Bytes, Error>) -> Result<Bytes, Error> {
> ```

Nit I don't really like this function name, something better might be like `process_data`.


<!-- Sent from Reviewable.io -->

2024-08-21 06:10 UTC, caass reviewed
+@allada +@adam-singer 

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-:-O4nY_mk16FLwvLPL9Pm:bchhibo)* status: 0 of 2 LGTMs obtained, and all files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, asan / ubuntu-22.04, macos-13, pre-commit-checks, ubuntu-22.04, vale, and 1 discussions need to be resolved (waiting on @adam-singer and @allada)



<!-- Sent from Reviewable.io -->

2024-08-21 17:15 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Do we have a way to trigger this in a test bounded up to a real redis instance vs mock tests? 

Also wasn't clear if the mock tests could trigger this condition, if so can we add a test proving it won't trigger or we don't regresss back to it?

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-:-O4pvhDKEGwq5CokAjs6:bldsraw)* status: 1 of 2 LGTMs obtained, and all files reviewed, and 2 discussions need to be resolved (waiting on @allada)

___
*[`nativelink-store/src/redis_store.rs` line 293 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4nW1Zg7NO3smRk5Hfa:-O4pv4k_ElOHd4CpH3uz:bguyp45) ([raw file](https://github.com/TraceMachina/nativelink/blob/049220e77a6ffe452c8a331e45b2b33b449c64ec/nativelink-store/src/redis_store.rs#L293)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

This is semantically equivalent to `break`, but I felt that it was more clear to specifically indicate that an empty chunk indicates `EOF`.
</blockquote></details>

sg, can we leave that as a comment so forward reading of the code makes sense why its laid out with a boolean/continue as the boolean is used later in the `'inner` reader loop.
___
*[`nativelink-store/src/redis_store.rs` line 294 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4puR3I5piA7EaWZYKW:-O4puR3I5piA7EaWZYKX:b-adq63) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d0ec8d767c813aaffe3a0c8caa6c51c4c03a58d/nativelink-store/src/redis_store.rs#L294)):*
> ```XML
>                 eof_reached = true;
>                 continue;
>             }
> ```

nit: can the assignment `is_first_chunk = false` be done in the a `else {}` of this condition, I think that reads it being specifically tied to the condition of  `chunk.is_empty()` not being empty and signals that a first chunk has been ready. I do understand its logically the same. The passthrough / fall down conditions/conclusions have are a bit much to follow. Not saying that it needs to be rewritten logically, hopefully less overhead to cognitively read it. 
___
*[`nativelink-store/tests/redis_store_test.rs` line 472 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4nWcfr8IqLPbPFKq0N:-O4ptTZYDBB_EbwmMx9o:b32v57) ([raw file](https://github.com/TraceMachina/nativelink/blob/049220e77a6ffe452c8a331e45b2b33b449c64ec/nativelink-store/tests/redis_store_test.rs#L472)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

This made debugging easier, since at a glance I could tell what data had been sent and what hadn't.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2024-08-21 17:26 UTC, allada submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1269)* status: 1 of 2 LGTMs obtained, and all files reviewed, and 7 discussions need to be resolved

___
*[`nativelink-store/src/redis_store.rs` line 280 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4ptByAE6e-6hl8BH9i:-O4ptByAE6e-6hl8BH9j:bvr7dwy) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d0ec8d767c813aaffe3a0c8caa6c51c4c03a58d/nativelink-store/src/redis_store.rs#L280)):*
> ```XML
> 
>         while !eof_reached {
>             let pipe = client.pipeline();
> ```

nit: move this down below to where it is used.
___
*[`nativelink-store/src/redis_store.rs` line 303 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4pvwLSDhAGRJlqjznE:-O4pvwLSDhAGRJlqjznF:bv20m0r) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d0ec8d767c813aaffe3a0c8caa6c51c4c03a58d/nativelink-store/src/redis_store.rs#L303)):*
> ```XML
> 
>             // Opportunistically grab any other chunks already in the reader.
>             'inner: while let Some(chunk) = reader
> ```

We should probably also flush if the `pipe`'s buffer gets larger than ~5MB (we can hard code it).
___
*[`nativelink-store/src/redis_store.rs` line 310 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4pvYElETHM-ag-vIvx:-O4pvYElETHM-ag-vIvy:bk0uwwx) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d0ec8d767c813aaffe3a0c8caa6c51c4c03a58d/nativelink-store/src/redis_store.rs#L310)):*
> ```XML
>                 if chunk.is_empty() {
>                     eof_reached = true;
>                     break 'inner;
> ```

nit: No need for `'inner`.
___
*[`nativelink-store/src/redis_store.rs` line 326 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4pv63H1CYjtuAR0X09:-O4pv63H1CYjtuAR0X0A:bodffap) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d0ec8d767c813aaffe3a0c8caa6c51c4c03a58d/nativelink-store/src/redis_store.rs#L326)):*
> ```XML
> 
>         // Rename the temp key so that the data appears under the real key. Any data already present in the real key is lost.
>         client
> ```

lets try and get this onto a pipeline too, this will save a roundtrip on nearly every upload, since it is rare for `try_recv` to return None, then next iteration return an empty slice.
___
*[`nativelink-store/tests/redis_store_test.rs` line 56 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4nWS5cEhTK7euxA0xL:-O4pxYRQ-3patZ_jEN7d:b-j83ibc) ([raw file](https://github.com/TraceMachina/nativelink/blob/049220e77a6ffe452c8a331e45b2b33b449c64ec/nativelink-store/tests/redis_store_test.rs#L56)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

FYI this wound up being more useful for getting helpful error messages than anything else, since we were struggling with getting tokio to only tell us about one error at a time.
</blockquote></details>

I'm a bit confused, do you mean you were struggling to get tests to only print one of the test failures at a time? We have asserts in there, so it should hard fail.
___
*[`nativelink-store/tests/redis_store_test.rs` line 557 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4pwxZT0F7yNW1FzQm0:-O4pwxZT0F7yNW1FzQm1:bht7eku) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d0ec8d767c813aaffe3a0c8caa6c51c4c03a58d/nativelink-store/tests/redis_store_test.rs#L557)):*
> ```XML
>         },
>         async {
>             tx.send(data_p1).await?;
> ```

fyi: I now prefer `.unwrap()` in tests, since `unwrap()`  gives line numbers an `?` does not.
___
*[`nativelink-util/src/buf_channel.rs` line 209 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4pyECsD3E3U9o50YDz:-O4pyECsD3E3U9o50YE-:b-m2cvpv) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d0ec8d767c813aaffe3a0c8caa6c51c4c03a58d/nativelink-util/src/buf_channel.rs#L209)):*
> ```XML
>     }
> 
>     fn recv_inner(&mut self, data: Result<Bytes, Error>) -> Result<Bytes, Error> {
> ```

Can we revert all of this and do it in a follow up PR? This change has a very high chance of breaking things and I don't want this entire PR to be reverted because of an unrelated change.


<!-- Sent from Reviewable.io -->

2024-08-21 23:53 UTC, caass reviewed
@adam-singer we can test it the same way we tested the last redis change -- and I added a regression test.

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-:-O4rLX2fDooiYDhT4K_r:b27v7ob)* status: 1 of 2 LGTMs obtained, and all files reviewed, and pending CI: Analyze (javascript-typescript), Bazel Dev / ubuntu-22.04, Publish image, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), pre-commit-checks, ubuntu-20.04 / stable, vale, and 5 discussions need to be resolved (waiting on @allada)

___
*[`nativelink-store/src/redis_store.rs` line 303 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4pvwLSDhAGRJlqjznE:-O4rB2fM8jK4cPBLt4l-:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d0ec8d767c813aaffe3a0c8caa6c51c4c03a58d/nativelink-store/src/redis_store.rs#L303)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

We should probably also flush if the `pipe`'s buffer gets larger than ~5MB (we can hard code it).
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 310 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4pvYElETHM-ag-vIvx:-O4rB6o2AOzi9N5nABOa:bb74ce2) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d0ec8d767c813aaffe3a0c8caa6c51c4c03a58d/nativelink-store/src/redis_store.rs#L310)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: No need for `'inner`.
</blockquote></details>

Sure
___
*[`nativelink-store/src/redis_store.rs` line 326 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4pv63H1CYjtuAR0X09:-O4rCNRH-L54_fWuB9ZC:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d0ec8d767c813aaffe3a0c8caa6c51c4c03a58d/nativelink-store/src/redis_store.rs#L326)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

lets try and get this onto a pipeline too, this will save a roundtrip on nearly every upload, since it is rare for `try_recv` to return None, then next iteration return an empty slice.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 281 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4rLewwCBhnC_ZGfNlr:-O4rLewwCBhnC_ZGfNls:b-hlyyxh) ([raw file](https://github.com/TraceMachina/nativelink/blob/be34eca8f29c759b330a34a892107d597c23145e/nativelink-store/src/redis_store.rs#L281)):*
> ```XML
> 
>         while !eof_reached {
>             pipe = client.pipeline();
> ```

This weird double-declaration of `pipe` is because sending commands on a pipeline doesn't actually clear it -- so we need to drop the old pipeline every iteration.

The reason to put the pipeline here is so that the logic in the EOF handling uses a fresh pipe, and not one that contains stale data.
___
*[`nativelink-store/tests/redis_store_test.rs` line 56 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4nWS5cEhTK7euxA0xL:-O4rCOqY-blaho3U1ynM:bn4zrzv) ([raw file](https://github.com/TraceMachina/nativelink/blob/049220e77a6ffe452c8a331e45b2b33b449c64ec/nativelink-store/tests/redis_store_test.rs#L56)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I'm a bit confused, do you mean you were struggling to get tests to only print one of the test failures at a time? We have asserts in there, so it should hard fail.
</blockquote></details>

It had to do with `spawn`ing tokio stuff, where panics inside a task that wasn't awaited would silently die without killing the test.

[Context here](https://stackoverflow.com/questions/75520495/how-to-make-tokio-test-fail-if-thread-panicked)
___
*[`nativelink-util/src/buf_channel.rs` line 209 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4pyECsD3E3U9o50YDz:-O4rD80OBhRFeCZF-fnt:b-7f9kw8) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d0ec8d767c813aaffe3a0c8caa6c51c4c03a58d/nativelink-util/src/buf_channel.rs#L209)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Can we revert all of this and do it in a follow up PR? This change has a very high chance of breaking things and I don't want this entire PR to be reverted because of an unrelated change.
</blockquote></details>

Unfortunately this change was a pre-req for everything else :( if you want, I can split this out into its own PR and we can test that first, but it would need to land before the rest of the redis stuff can land.


<!-- Sent from Reviewable.io -->

2024-08-22 20:19 UTC, adam-singer requested changes
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1269)* status: 1 of 2 LGTMs obtained, and all files reviewed, and 6 discussions need to be resolved (waiting on @allada)

___
*[`nativelink-store/src/redis_store.rs` line 309 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4vjKrc5YJqucZqfAXD:-O4vjKrc5YJqucZqfAXE:b4qp3wx) ([raw file](https://github.com/TraceMachina/nativelink/blob/be34eca8f29c759b330a34a892107d597c23145e/nativelink-store/src/redis_store.rs#L309)):*
> ```XML
>                         .err_tip(|| "While appending to temp key in RedisStore::update")?;
>                 } else {
>                     // Case 3, regular EOF.
> ```

Sorry, what I meant was `eof_reached = true;` goes into this block, not an empty block


<!-- Sent from Reviewable.io -->

2024-08-23 14:55 UTC, caass reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1269)* status: 1 of 2 LGTMs obtained, and all files reviewed, and 6 discussions need to be resolved (waiting on @allada)

___
*[`nativelink-store/src/redis_store.rs` line 309 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4vjKrc5YJqucZqfAXD:-O4zioqyA6Qkxh6e_a_G:b-3o4ct6) ([raw file](https://github.com/TraceMachina/nativelink/blob/be34eca8f29c759b330a34a892107d597c23145e/nativelink-store/src/redis_store.rs#L309)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Sorry, what I meant was `eof_reached = true;` goes into this block, not an empty block
</blockquote></details>

Right, but don't we actually want to set `eof_reached = true` in both cases 2 and 3?


<!-- Sent from Reviewable.io -->

2024-08-23 19:36 UTC, adam-singer requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1269)* status: 1 of 2 LGTMs obtained, and all files reviewed, and 6 discussions need to be resolved (waiting on @allada)

___
*[`nativelink-store/src/redis_store.rs` line 309 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4vjKrc5YJqucZqfAXD:-O5-jEFB1vnn97bgleuy:b-veygyy) ([raw file](https://github.com/TraceMachina/nativelink/blob/be34eca8f29c759b330a34a892107d597c23145e/nativelink-store/src/redis_store.rs#L309)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Right, but don't we actually want to set `eof_reached = true` in both cases 2 and 3?
</blockquote></details>

ah ok, never mind then, the `else {}` here is pointless, it read differently to me in a different patch, remove the `else {}` condition here. 


<!-- Sent from Reviewable.io -->

2024-08-30 17:04 UTC, adam-singer approved these changes
@caass did you test it the same way or is that still to be done?


<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-:-O5ZENas4KC_EpHLBepd:b-1x3czc)* status: 1 of 2 LGTMs obtained, and all files reviewed, and 6 discussions need to be resolved (waiting on @allada)

___
*[`nativelink-store/src/redis_store.rs` line 309 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4vjKrc5YJqucZqfAXD:-O5ZEDdXCLZ7br2LnJC3:b-hpaqvc) ([raw file](https://github.com/TraceMachina/nativelink/blob/fd5a815e281a70c464da9aa53ca5012f7b1b6a50/nativelink-store/src/redis_store.rs#L309)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

ah ok, never mind then, the `else {}` here is pointless, it read differently to me in a different patch, remove the `else {}` condition here.
</blockquote></details>

@caass ^^


<!-- Sent from Reviewable.io -->

2024-09-17 16:58 UTC, caass reviewed
@adam-singer I tested it on cloud and it seemed to do the same thing as `main`

> Reviewed 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-:-O7-uT8XCaXYV4Dd9Y-N:b-xmbzpr)* status: 1 of 2 LGTMs obtained, and all files reviewed, and pending CI: pre-commit-checks, and 5 discussions need to be resolved (waiting on @allada)

___
*[`nativelink-store/src/redis_store.rs` line 309 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-O4vjKrc5YJqucZqfAXD:-O7-uEwvA81C5TEA292h:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/fd5a815e281a70c464da9aa53ca5012f7b1b6a50/nativelink-store/src/redis_store.rs#L309)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

@caass ^^
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-17 17:01 UTC, caass reviewed
> Dismissed @adam-singer and @allada from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1269)* status: 1 of 2 LGTMs obtained, and all files reviewed, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache (Legacy Dockerfile Test), Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @allada)



<!-- Sent from Reviewable.io -->

2024-09-17 17:32 UTC, caass reviewed
-@allada 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1269#-:-O701RIx20KP3naj-MjP:b-r9zead)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed



<!-- Sent from Reviewable.io -->

2024-09-17 17:41 UTC, merged