Eliminate 150 Vale Warnings
TraceMachina/nativelink pull request #1276
Opened 2024-08-22 21:01 UTC by Evaan2001

# Description

This commit only edits documentation material. The goal was to eliminate a significant chunk of vale warnings. I resolved 150 warnings from 13 files, constituting about 35% of total warnings.

I had a question about one particular warning. Whenever "execute" or "execution" was present in the text, vale would throw
`Be careful with 'Execution', it’s profane in some cases.       alex.ProfanityUnlikely `. In the beginning, I replaced "execution" with "processing" or "operation".  But then I started coming across proper nouns such as Remote Execution Protocol and Local Remote Execution (LRE). Unsure about removing "execution" from these, I purposely ignored these warnings. Let me know if y'all would like me to revert my earlier swapping of execution with process/operation or leave things be as they are currently.

Fixes # 1150

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

I went to the root directory and ran `cargo test --all`, which conducted 316 tests and my branch passed all of them. Since I was solely editing documentation, I wasn't expecting any tests to fail ...

2024-08-23 04:30 UTC, allada reviewed
Thanks for the PR, there was recently a big change on the documentation code. Would you mind rebasing?

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1276#-:-O4xUyYq-g5X8sUCZgIz:b2ys3dj)* status: 0 of 2 LGTMs obtained, and 0 of 13 files reviewed, and pending CI: pre-commit-checks



<!-- Sent from Reviewable.io -->

2024-08-23 06:00 UTC, Evaan2001 commented
@allada, I rebased and resolved the conflicts (there were 3 conflicting links and I accepted the new fixed links). 

I'm surprised that some of the CI tests are failing. I only edited md and mdx files. I ran `cargo test --all` and passed all the tests. I also ran `pre-commit run -a` and all of the checks passed ("forbid-binary-files" got skipped as there were "no files to check"). 

I saw some error messages mention "Unsupported OS version"; I'm using MacOS 14.6.1 Sonoma on Apple silicon. Thoughts?

2024-08-24 19:36 UTC, aaronmondal requested changes
Wow, nice work!

Regarding the `execution` term, it's a but suboptimal, but I think we need to keep it since the RBE is the remote build **execution** protocol.

> Reviewed 8 of 13 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1276#-:-O54smVV7iM4PI6DT1wg:b-yzuzr2)* status: 0 of 2 LGTMs obtained, and all files reviewed, and pending CI: docker-compose-compiles-nativelink (22.04), integration-tests (22.04), and 21 discussions need to be resolved

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1276#-O54l7IaCWpypFpT1V1Z):*
nit: Add this to link the commit to the vale issue:

```
Towards #1086
```
___
*[`README.md` line 19 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1276#-O54lrD5Bi2_GYaWARtm:-O54lrD5Bi2_GYaWARtn:b2wyjtb) ([raw file](https://github.com/TraceMachina/nativelink/blob/0e0311380a4f5fb8a8558ae039e2737337a92548/README.md#L19)):*
> ```Markdown
> [![License](https://img.shields.io/badge/License-Apache_2.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)
> 
> ## What's NativeLink
> ```

nit: This looks a bit off. Maybe change it to `## About NativeLink`
___
*[`README.md` line 21 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1276#-O54m0R6Cy2aXjz75wBv:-O54m0R6Cy2aXjz75wBw:b-sxyu5v) ([raw file](https://github.com/TraceMachina/nativelink/blob/0e0311380a4f5fb8a8558ae039e2737337a92548/README.md#L21)):*
> ```Markdown
> ## What's NativeLink
> 
> NativeLink is an efficient, high-performance build cache and remote operation system that accelerates software compilation and testing while reducing infrastructure costs. It optimizes build processes for projects of all sizes by intelligently caching build artifacts and distributing tasks across several machines.
> ```

I think it's fine to use the term `execution` here, since `RBE` stands for `Remote Build Execution` and NativeLink is essentially an implementation of that protocol.

To allow the term you can add `[Ee]xecution` to this file: https://github.com/TraceMachina/nativelink/blob/main/.github/styles/config/vocabularies/TraceMachina/accept.txt



_Code quote:_
```Markdown
operation
```
___
*[`README.md` line 35 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1276#-O54mtZz5Nw0dJg_yZly:-O54mtZz5Nw0dJg_yZlz:bribihm) ([raw file](https://github.com/TraceMachina/nativelink/blob/c21d59f104cb7910e05e2633693d2c5203c6fb74/README.md#L35)):*
> ```Markdown
>    - Significantly reduces build times, especially for incremental changes
> 
> 2. **Efficient Remote Execution**:
> ```

As above.
___
*[`README.md` line 45 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1276#-O54mzKZDaU9SlTC3OtA:-O54mzKZDaU9SlTC3OtB:undefined) ([raw file](https://github.com/TraceMachina/nativelink/blob/0e0311380a4f5fb8a8558ae039e2737337a92548/README.md#L45)):*
> ```Markdown
> ## 🚀 Quickstart
> 
> To start, you can deploy NativeLink as a Docker image (as shown below) or by using a cloud-hosted solution provided by the NativeLink team - [NativeLink Cloud](https://app.nativelink.com). It's **FREE** for individuals, open-source projects, and cloud production environments, with support for unlimited team members.
> ```





_Suggestion:_
```Markdown
the
```
___
*[`README.md` line 45 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1276#-O54n45J1UPkNICS_YOO:-O54n45J1UPkNICS_YOP:b45h) ([raw file](https://github.com/TraceMachina/nativelink/blob/0e0311380a4f5fb8a8558ae039e2737337a92548/README.md#L45)):*
> ```Markdown
> ## 🚀 Quickstart
> 
> To start, you can deploy NativeLink as a Docker image (as shown below) or by using a cloud-hosted solution provided by the NativeLink team - [NativeLink Cloud](https://app.nativelink.com). It's **FREE** for individuals, open-source projects, and cloud production environments, with support for unlimited team members.
> ```





_Suggestion:_
```Markdown
container
```
___
*[`SECURITY.md` line 35 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1276#-O54nVRd0vDJlGmTwWbG:-O54nVRd0vDJlGmTwWbH:b1nfdzy) ([raw file](https://github.com/TraceMachina/nativelink/blob/0e0311380a4f5fb8a8558ae039e2737337a92548/SECURITY.md#L35)):*
> ```Markdown
> Nix derivation hash tag the images. The latest pushed image
> corresponds to the `main` branch. GitHub action producing an image signs that
> image. Note that the [OCI workflow](https://github.com/TraceMachina/nativelink/actions/workflows/image.yaml) might take some time to publish the latest image.
> ```

This change looks wrong. (It's also a bit risky to change since it's part of the security related information. Feel free to omit it from this PR)
___
*[`deployment-examples/chromium/README.md` line 33 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1276#-O54o-ZJ7rcP3Rl-Grex:-O54o-ZJ7rcP3Rl-Grey:b3zctrs) ([raw file](https://github.com/TraceMachina/nativelink/blob/0e0311380a4f5fb8a8558ae039e2737337a92548/deployment-examples/chromium/README.md#L33)):*
> ```Markdown
> > the stack with `pulumi stack` and `pulumi destroy`.
> 
> Next, start some standard deployments. This step includes building and preparing the remote containers for use in the cluster.:
> ```

nit: line break at 80 characters
___
*[`docs/src/content/docs/deployment-examples/on-prem-overview.mdx` line 18 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1276#-O54pZDA1AWnFoeQAA25:-O54pZDA1AWnFoeQAA26:undefined) ([raw file](https://github.com/TraceMachina/nativelink/blob/0e0311380a4f5fb8a8558ae039e2737337a92548/docs/src/content/docs/deployment-examples/on-prem-overview.mdx#L18)):*
> ```MDX
> 
> Each example leverages some latest, cutting-edge Kubernetes
> configurations, but with a simplified architecture that prioritizes
> ```





_Suggestion:_
```MDX
Each example leverages Kubernetes with a simplified architecture that prioritizes
```
___
*[`docs/src/content/docs/faq/remote-execution.mdx` line 7 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1276#-O54pxlq3vZh4aMrglg0:-O54pxlq3vZh4aMrglg1:undefined) ([raw file](https://github.com/TraceMachina/nativelink/blob/0e0311380a4f5fb8a8558ae039e2737337a92548/docs/src/content/docs/faq/remote-execution.mdx#L7)):*
> ```MDX
> ---
> 
> Remote processing is a powerful feature that allows you to distribute build
> ```





_Suggestion:_
```MDX
execution
```
___
*[`docs/src/content/docs/faq/remote-execution.mdx` line 14 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1276#-O54q8TKBUzTthq4BZQJ:-O54q8TKBUzTthq4BZQK:undefined) ([raw file](https://github.com/TraceMachina/nativelink/blob/0e0311380a4f5fb8a8558ae039e2737337a92548/docs/src/content/docs/faq/remote-execution.mdx#L14)):*
> ```MDX
> 
> - **Faster build and test operation**: By distributing actions across different nodes,
> you can carry out builds and tests in parallel, reducing the time required.
> ```





_Suggestion:_
```MDX
run
```
___
*[`docs/src/content/docs/faq/remote-execution.mdx` line 15 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1276#-O54qDJR6G1BmOJLmY4j:-O54qDJR6G1BmOJLmY4k:undefined) ([raw file](https://github.com/TraceMachina/nativelink/blob/0e0311380a4f5fb8a8558ae039e2737337a92548/docs/src/content/docs/faq/remote-execution.mdx#L15)):*
> ```MDX
> - **Faster build and test operation**: By distributing actions across different nodes,
> you can carry out builds and tests in parallel, reducing the time required.
> - **Consistent processing environment**: Remote processing ensures that all members of
> ```





_Suggestion:_
```MDX
execution
```
___
*[`docs/src/content/docs/faq/remote-execution.mdx` line 17 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1276#-O54qKL15Jx2ggBvFroe:-O54qKL15Jx2ggBvFrof:b-b70zqc) ([raw file](https://github.com/TraceMachina/nativelink/blob/0e0311380a4f5fb8a8558ae039e2737337a92548/docs/src/content/docs/faq/remote-execution.mdx#L17)):*
> ```MDX
> - **Consistent processing environment**: Remote processing ensures that all me [...]

2024-08-26 23:43 UTC, Evaan2001 commented
@aaronmondal sorry for my late reply, and thanks for going through all of my changes. I'll incorporate the changes you recommended shortly. Alongside [Ee]xecution, I'll also add [Ee]xecute to the list of accepted words and I'll revert my previous execution -> operation/processing changes.  

Quick question about "works on my machine". I'm aware it's a common figure of speech. I changed it as Vale would warn against using "my". One way to bypass this could be to add this phrase to the list of accepted words; I'll have to test if phrases (multiple words = multiple spaces) get parsed as expected. Alternatively, we can ignore this warning for now. What do you think would be the most sustainable approach?

2024-08-31 21:26 UTC, Evaan2001 commented
@aaronmondal your suggestions have been incorporated. Have a look!

2025-05-02 00:33 UTC, closed without merging