Introduce NativeLink Web App
TraceMachina/nativelink pull request #1285
Opened 2024-08-27 21:01 UTC by SchahinRohani

### Introducing Nativelink Web App and Migrated Documentation

This update introduces the new Nativelink web application, built using Astro and Qwik, along with the migration of the existing documentation. It also includes significant improvements to website performance.

### What's Included?

- Basic structure and functionality of the web app (website)
- Migrated documentation to support users

### What’s Still to Come?
This is a draft PR, and there's some work left to be done before it's ready:

- Nodemailer integration
- Completion of the products page
- Desktop version for the community and company pages
- Fixing a Motion/Qwik bug related to scrolling and reloading
- Further updates to the documentation
- Adding missing Tailwind styling in several areas

## Type of change

- [x] This change requires a documentation update

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-08-27 23:14 UTC, allada reviewed
+@blakehatch please work with @aaronmondal and @SchahinRohani on this.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-:-O5L6XMm28nvhIfzCPYN:b39zb2n)* status: 0 of 2 LGTMs obtained, and 0 of 111 files reviewed (waiting on @blakehatch)



<!-- Sent from Reviewable.io -->

2024-09-10 18:52 UTC, blakehatch commented
> +@blakehatch please work with @aaronmondal and @SchahinRohani on this.
> 
> > _[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-:-O5L6XMm28nvhIfzCPYN:b39zb2n)_ status: 0 of 2 LGTMs obtained, and 0 of 111 files reviewed (waiting on @blakehatch)

Will do @allada, meeting on this tmrw morning.

2024-09-10 21:59 UTC, aaronmondal requested changes
Great work! I marked various development artifacts that can probably be removed. I'll defer the content review to @blakehatch. From a code-perspective this mostly looks fine to me, modulo mostly formatting nits.

One thing we might think about is getting the various colors into some unified palette (and maybe some of the styles?) At the moment it looks like the inline tailwind usage is fairly manageable though. +@bclark8923 might be able to evaluate this better and #1289 might play a role in this as well. 

Performance-wise the site is incredible, especially considering the many images, videos etc. As a follow-up we should definitely add dedicated lightouse workflows to prevent regressions on the top-level pages and especially to ensure good accessibility. It looks like the few points we're missing are mostly due to the imports from wix. Moving to another CDN probably gets us to perfect scores, though this seems more like a mid-term goal.

> Reviewed 5 of 104 files at r3, 135 of 135 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-:-O6SrmojBsIpX_C19gNg:b-eisidx)* status: 0 of 2 LGTMs obtained, and all files reviewed, and 48 discussions need to be resolved (waiting on @bclark8923 and @blakehatch)

___
*[`.github/styles/config/vocabularies/TraceMachina/accept.txt` line 71 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SjoEl1QtQfebauIyh:-O6SjoEl1QtQfebauIyi:bhl0jno) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/.github/styles/config/vocabularies/TraceMachina/accept.txt#L71)):*
> ```help
> Bruer
> Eagan
> plattform
> ```

remove 'platform'
___
*[`web/platform/src/assets/astro.svg` line 1 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6Sl9KD-_bzfcGmubmb:-O6Sl9KD-_bzfcGmubmc:b-l6mwxj) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/assets/astro.svg#L1)):*
> ```SVG
> <?xml version="1.0" encoding="UTF-8" standalone="no"?>
> ```

remove
___
*[`web/platform/src/assets/cloud.svg` line 1 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SlDJx8p-UMJOpW8-m:-O6SlDJx8p-UMJOpW8-n:b-mlqc3c) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/assets/cloud.svg#L1)):*
> ```SVG
> <svg data-bbox="0.139 0.322 20.698 13.356" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 21 14" height="14" width="21" data-type="ugc">
> ```

not sure if this is used, if it isn't, remove
___
*[`web/platform/src/assets/qwik.svg` line 1 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SlMTB5rZsou0ICEvM:-O6SlMTCAqe_DZf8yKY9:b-l6mwxj) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/assets/qwik.svg#L1)):*
> ```SVG
> <?xml version="1.0" encoding="UTF-8" standalone="no"?>
> ```

remove
___
*[`web/platform/src/components/qwik/components/cards.tsx` line 20 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SmAR17fREMfqXXX9l:-O6SmAR17fREMfqXXX9m:bng95qk) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/qwik/components/cards.tsx#L20)):*
> ```XML
>       <div class="flex h-auto w-5/6 flex-col items-start justify-start md:w-[277px] md:gap-0">
>         <div>{icon}</div>
>         <div class="bg-gradient-to-r from-white to-[#707098] bg-clip-text py-4 pr-6 text-[25px] text-transparent md:h-[120px] md:px-0 md:py-6">
> ```

Could we merge the colors in some global palette? I.e have a unified place where all the hashtag values live
___
*[`web/platform/src/components/qwik/components/cards.tsx` line 89 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SmMaECRBEtp7Ftikt:-O6SmMaECRBEtp7Ftiku:b-1e99qz) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/qwik/components/cards.tsx#L89)):*
> ```XML
>           id="Card"
>           key={plan.title}
>           class="flex flex-col gap-5 items-center justify-between p-6 w-80 rounded-lg bg-[rgba(205,193,193,0.46)] rounded-xl shadow-lg shadow-[0_4px_30px_rgba(0,0,0,0.1)] backdrop-blur-[9px] border border-[rgba(205,193,193,0.92)]"
> ```

same for these rgba values
___
*[`web/platform/src/components/qwik/components/codeTabs.tsx` line 55 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SmkD--o4EEpVAptey:-O6SmkD09g3FUWSJZsxG:b-qv2dye) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/qwik/components/codeTabs.tsx#L55)):*
> ```XML
>                 -v $(pwd)/basic_cas.json:/config \{"\n"}
>                 -p 50051:50051 \{"\n"}
>                 ghcr.io/tracemachina/nativelink:v0.5.1 \{"\n"}
> ```

nit: change this one (and the one below) to 0.5.3. Mid-term we should probably pass the version via e.g. an external environment variable so that this stays up-to-date.
___
*[`web/platform/src/components/qwik/components/faq.tsx` line 1 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6Sn0OgDLup1BZllHQk:-O6Sn0OgDLup1BZllHQl:b-l6mwxj) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/qwik/components/faq.tsx#L1)):*
> ```XML
> import { component$ } from "@builder.io/qwik";
> ```

remove
___
*[`web/platform/src/components/qwik/components/some-islands.tsx` line 1 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SoJxt-xk9AvdB3gaF:-O6SoJxt-xk9AvdB3gaG:b-ttmk9z) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/qwik/components/some-islands.tsx#L1)):*
> ```XML
> import { $, component$, useOnDocument, useSignal } from "@builder.io/qwik";
> ```

what is this for?
___
*[`web/platform/src/components/qwik/components/counter/counter.tsx` line 5 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SoUNi7GijXQ0P4SiS:-O6SoUNi7GijXQ0P4SiT:b-jrxcue) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/qwik/components/counter/counter.tsx#L5)):*
> ```XML
> export const Counter = component$((props: { initialVal: number }) => {
>   const counter = useSignal<number>(props.initialVal);
>   // console.log(counter)
> ```

comment
___
*[`web/platform/src/components/qwik/pages/company.tsx` line 7 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6Sp9ew7_8p1MpYswW4:-O6Sp9ew7_8p1MpYswW5:b-jrxcue) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/qwik/pages/company.tsx#L7)):*
> ```XML
> // const _cards = [
> //   {
> //     title: "Media Kit",
> ```

comment
___
*[`web/platform/src/components/react/faq.tsx` line 5 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SpizPCP3KTFkZ55Rt:-O6SpizPCP3KTFkZ55Ru:b-jrxcue) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/react/faq.tsx#L5)):*
> ```XML
> import { useState } from "react";
> 
> // import { qwikify$ } from "@builder.io/qwik-react";
> ```

comment
___
*[`web/platform/src/components/react/faq.tsx` line 145 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SpmJFDIk9PbcIgxhd:-O6SpmJFDIk9PbcIgxhe:b-jrxcue) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/react/faq.tsx#L145)):*
> ```XML
> };
> 
> // export const QFAQ = qwikify$(FAQ);
> ```

comment
___
*[`web/platform/src/components/react/react-counter.tsx` line 1 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SpqPb8wpq7Erjrowg:-O6SpqPb8wpq7 [...]

2024-09-15 12:37 UTC, SchahinRohani reviewed
Thank you @aaronmondal!

We should definitely remove all the Wix assets and provide some kind of dedicated file storage for the assets used on the web.

More on, we should also have a way to pass env variables to be able to use some third-party provider for e.g. SMTP.

But this should be a good starting point now!

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-:-O6ef5QbDhtDw_JKiK0q:b1lbpxd)* status: 0 of 2 LGTMs obtained, and 91 of 143 files reviewed, and pending CI: Installation / macos-13, and 39 discussions need to be resolved (waiting on @bclark8923 and @blakehatch)

___
*[`.github/styles/config/vocabularies/TraceMachina/accept.txt` line 71 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SjoEl1QtQfebauIyh:-O6a8_Z-6TBA1Q1J6qAO:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/.github/styles/config/vocabularies/TraceMachina/accept.txt#L71)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

remove 'platform'
</blockquote></details>

Done.
___
*[`web/platform/src/components/qwik/components/cards.tsx` line 20 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SmAR17fREMfqXXX9l:-O6pXbDS24n1SR7avlkU:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/qwik/components/cards.tsx#L20)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Could we merge the colors in some global palette? I.e have a unified place where all the hashtag values live
</blockquote></details>

Done.
___
*[`web/platform/src/components/qwik/components/cards.tsx` line 89 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SmMaECRBEtp7Ftikt:-O6pXe6Z80pw3ckHTNna:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/qwik/components/cards.tsx#L89)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

same for these rgba values
</blockquote></details>

Done.
___
*[`web/platform/src/components/qwik/components/some-islands.tsx` line 1 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SoJxt-xk9AvdB3gaF:-O6aBQAI4oA5h6n66LIT:b-yffhk1) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/qwik/components/some-islands.tsx#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

what is this for?
</blockquote></details>

The some-islands.tsx is for understanding how you can communicate between different micro-frontend components like qwik, react, vue, svelte etc. Here we use it for communicate between the qwik counter component and "some-island" qwik component.
We should keep it.
___
*[`web/platform/src/components/qwik/components/counter/counter.tsx` line 5 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SoUNi7GijXQ0P4SiS:-O6aCHXyDfvbT0Yzn9-m:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/qwik/components/counter/counter.tsx#L5)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

comment
</blockquote></details>

Done.
___
*[`web/platform/src/components/qwik/pages/company.tsx` line 7 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6Sp9ew7_8p1MpYswW4:-O6aDkRt3boCqgd1z5H1:b-j8wg80) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/qwik/pages/company.tsx#L7)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

comment
</blockquote></details>

We actually need them, i put them below the team array.
___
*[`web/platform/src/components/react/faq.tsx` line 5 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SpizPCP3KTFkZ55Rt:-O6aFCWE4h4w1MRI_wW6:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/react/faq.tsx#L5)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

comment
</blockquote></details>

Done.
___
*[`web/platform/src/components/react/faq.tsx` line 145 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SpmJFDIk9PbcIgxhd:-O6pYhCd3Zs_aPm5_8KE:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/react/faq.tsx#L145)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

comment
</blockquote></details>

Done.
___
*[`web/platform/src/components/react/react-counter.tsx` line 1 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SpqPb8wpq7Erjrowg:-O6aFc_B8HbLt5Ao28g0:bnvfv7h) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/react/react-counter.tsx#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

is this file needed?
</blockquote></details>

Yes, to have a react test component for communicating with other components.
___
*[`web/platform/src/components/react/react-counter.tsx` line 4 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SpnpM-HkDNK8JcxQ9:-O6ebRYy7vT_XYaZqHyC:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/react/react-counter.tsx#L4)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

comment
</blockquote></details>

Done.
___
*[`web/platform/src/components/react/react-counter.tsx` line 19 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6Spola0jjXdCxEL60I:-O6ebS3K7liknUMXiTBr:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/react/react-counter.tsx#L19)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

comment
</blockquote></details>

Done.
___
*[`web/platform/src/components/react/aceternity/index.ts` line 4 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SpulS0pc1-zGKT9KD:-O6aFtwZ-JhNxoVrLaV_:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/components/react/aceternity/index.ts#L4)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: add a comment here to explain why this exists
</blockquote></details>

Done.
___
*[`web/platform/src/assets/astro.svg` line 1 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6Sl9KD-_bzfcGmubmb:-O6aRQlM4LnzZA0f6fOl:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/assets/astro.svg#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`web/platform/src/assets/cloud.svg` line 1 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-O6SlDJx8p-UMJOpW8-m:-O6efGIU3pnzzjGY0dl1:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e64b1760e662558401be04bfb513d7ca88d8de8b/web/platform/src/assets/cloud.svg#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

not sure if this is used, if it isn't, remove
 [...]

2024-09-23 21:01 UTC, blakehatch reviewed
<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> will swap out DNS before merge

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-:-O7Vg5wODupxwST1rtHE:bxf9dv2)* status: 1 of 2 LGTMs obtained, and 81 of 148 files reviewed, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, Web Platform Deployment / macos-14, docker-compose-compiles-nativelink (22.04), windows-2022 / stable, and 39 discussions need to be resolved (waiting on @bclark8923)



<!-- Sent from Reviewable.io -->

2024-09-23 21:07 UTC, aaronmondal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 29 of 52 files at r5, 28 of 30 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-:-O7VhUPa-2GZMMdyGUEx:bnfp4nl)* status: 1 of 2 LGTMs obtained, and 140 of 148 files reviewed, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, Remote / large-ubuntu-22.04, Web Platform Deployment / macos-14, docker-compose-compiles-nativelink (22.04), windows-2022 / stable (waiting on @bclark8923)



<!-- Sent from Reviewable.io -->

2024-09-23 21:11 UTC, aaronmondal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 52 files at r5.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-:-O7ViUgi8TOUweogkHL9:bnfp4nl)* status: 1 of 2 LGTMs obtained, and all files reviewed, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, Remote / large-ubuntu-22.04, Web Platform Deployment / macos-14, docker-compose-compiles-nativelink (22.04), windows-2022 / stable (waiting on @bclark8923)



<!-- Sent from Reviewable.io -->

2024-09-23 22:48 UTC, aaronmondal approved these changes
-@bclark8923 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1285#-:-O7W3ajXAjFkf-3TZi6h:b897mdz)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained, and all files reviewed



<!-- Sent from Reviewable.io -->

2024-09-23 22:50 UTC, blakehatch approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1285)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained, and all files reviewed



<!-- Sent from Reviewable.io -->

2024-09-23 22:51 UTC, merged