Add tekton operator to local dev cluster
TraceMachina/nativelink pull request #1337
Opened 2024-09-08 14:41 UTC by SchahinRohani

# Description

This PR introduces the Tekton operator with a TektonConfig to replace the existing Tekton pipelines, triggers, and dashboard.

## Known Issue:
There is currently a bug where we are only waiting for 120 seconds for the webhooks, instead of checking if they have reached a running/ready status, so there is a possibility that the tekton-webhooks are in an unready state when trying to deploy the tasks and pipelines.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-09-08 15:06 UTC, SchahinRohani commented
Is this PR better @MarcusSorealheis ?

2024-09-08 16:02 UTC, aaronmondal requested changes
A very nice improvement!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1337#-:-O6HJDPED6o5y4W0irj_:b9t8x1k)* status: 0 of 2 LGTMs obtained, and all files reviewed, and 3 discussions need to be resolved

___
*[`native-cli/components/embedded/tekton-config.yaml` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1337#-O6HKV4P20mJ9KxNgrHT:-O6HKV4P20mJ9KxNgrHU:b5kxb36) ([raw file](https://github.com/TraceMachina/nativelink/blob/8849b4778fb7ffd591ccaff5ae6cef813a1aa54a/native-cli/components/embedded/tekton-config.yaml#L1)):*
> ```YAML
> ---
> ```

I believe this can be simplified by using kustomize to patch the default configuration. This way it'll also be clearer where we deviate from defaults.
___
*[`native-cli/components/embedded/tekton-config.yaml` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1337#-O6HLuiH4VHr1G5rysbI:-O6HLuiH4VHr1G5rysbJ:buuoetd) ([raw file](https://github.com/TraceMachina/nativelink/blob/8849b4778fb7ffd591ccaff5ae6cef813a1aa54a/native-cli/components/embedded/tekton-config.yaml#L2)):*
> ```YAML
> ---
> apiVersion: operator.tekton.dev/v1alpha1
> ```

I remember running into issues where the operator had incompatible api versions. Why does this config work without adjustments to the pipeline implementations? I assume some config option here sets the api versions?
___
*[`native-cli/programs/local.go` line 83 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1337#-O6HKnV-2BALBDK1xhPP:-O6HKnV-2BALBDK1xhPQ:b20gbph) ([raw file](https://github.com/TraceMachina/nativelink/blob/8849b4778fb7ffd591ccaff5ae6cef813a1aa54a/native-cli/programs/local.go#L83)):*
> ```Go
> 			Dependencies: slices.Concat(
> 				cilium,
> 				tektonOperator,
> ```

Flux shouldn't depend on the tekton operator.

It seems like a good idea to make flux depend on cilium though. Looks like this was an oversight in the previous implementation.


<!-- Sent from Reviewable.io -->

2024-09-08 20:56 UTC, SchahinRohani reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1337)* status: 0 of 2 LGTMs obtained, and 2 of 5 files reviewed, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable, and 3 discussions need to be resolved

___
*[`native-cli/programs/local.go` line 83 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1337#-O6HKnV-2BALBDK1xhPP:-O6IOfgb0YCTOHqZ2rdj:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/8849b4778fb7ffd591ccaff5ae6cef813a1aa54a/native-cli/programs/local.go#L83)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Flux shouldn't depend on the tekton operator.

It seems like a good idea to make flux depend on cilium though. Looks like this was an oversight in the previous implementation.
</blockquote></details>

Done.
___
*[`native-cli/components/embedded/tekton-config.yaml` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1337#-O6HKV4P20mJ9KxNgrHT:-O6IOrCl0OLjvpa58nta:bna9o5c) ([raw file](https://github.com/TraceMachina/nativelink/blob/8849b4778fb7ffd591ccaff5ae6cef813a1aa54a/native-cli/components/embedded/tekton-config.yaml#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

I believe this can be simplified by using kustomize to patch the default configuration. This way it'll also be clearer where we deviate from defaults.
</blockquote></details>

I reworked it and now we fetch it from tektoncd itself and apply the changes in that step. It's kinda the way you did it before.
___
*[`native-cli/components/embedded/tekton-config.yaml` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1337#-O6HLuiH4VHr1G5rysbI:-O6IPN2i8ntEpqDgkTL7:b-9b2b01) ([raw file](https://github.com/TraceMachina/nativelink/blob/8849b4778fb7ffd591ccaff5ae6cef813a1aa54a/native-cli/components/embedded/tekton-config.yaml#L2)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

I remember running into issues where the operator had incompatible api versions. Why does this config work without adjustments to the pipeline implementations? I assume some config option here sets the api versions?
</blockquote></details>

I just took the latest version of the config and it works. 


<!-- Sent from Reviewable.io -->

2024-09-09 09:32 UTC, aaronmondal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1337#-:-O6L78p93F8uAZXeTmX-:bnfp4nl)* status: 1 of 2 LGTMs obtained, and all files reviewed, and 1 discussions need to be resolved

___
*[`native-cli/components/tekton.go` line 70 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1337#-O6L6NbJ6ULe1AZx5Ejz:-O6L6NbJ6ULe1AZx5Ek-:b6q42w2) ([raw file](https://github.com/TraceMachina/nativelink/blob/c2ebd7bd0533bbf063d49803352af8f0a111d77a/native-cli/components/tekton.go#L70)):*
> ```Go
> func waitForTektonToBeReady() bool {
> 	// Simulate Tekton State Gathering
> 	time.Sleep(60 * time.Second) //nolint:mnd
> ```

nit: Create an issue that this should use a proper polling mechanism and reference that issue as a `TODO` here. This way it's clear that this is a workaround.


<!-- Sent from Reviewable.io -->

2024-11-28 21:03 UTC, aaronmondal commented
@SchahinRohani Could you rebase this? It's likely more reliable than the current setup and will make it easier for me to move it over to flux.

2024-11-29 22:46 UTC, SchahinRohani reviewed
@aaronmondal  rebased.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1337#-:-OCu5P6CAGVWh5qDhyxQ:b-e68wzn)* status: 1 of 1 LGTMs obtained, and 3 of 5 files reviewed, and 1 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-11-29 22:48 UTC, aaronmondal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1337#-:-OCu69Oy6kSvAlw7SikO:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed



<!-- Sent from Reviewable.io -->

2024-11-29 22:49 UTC, merged