Convert usize to u64 in Store trait APIs
TraceMachina/nativelink pull request #1344
Opened 2024-09-10 14:51 UTC by aleksdmladenovic

# Description

APIs in `StoreLike` now uses `u64` instead of `usize` It's because `u64` expresses the size of the data, but `usize` expresses local memory limits.

It includes bunch of files changed.

Fixes #1328 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [x] This change requires a documentation update

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/1344)

2024-09-10 19:48 UTC, allada requested changes
> Reviewed 5 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1344)* status: 0 of 2 LGTMs obtained, and 5 of 39 files reviewed, and 12 discussions need to be resolved

___
*[`nativelink-config/src/stores.rs` line 766 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6SOUHk2WioZwfMLeHo:-O6SOUHk2WioZwfMLeHp:b-6vcyzj) ([raw file](https://github.com/TraceMachina/nativelink/blob/18578da4d80a1998ab0c71561ab5070a96d53466/nativelink-config/src/stores.rs#L766)):*
> ```XML
>     ///
>     /// Default: 5MB.
>     pub max_retry_buffer_per_request: Option<u64>,
> ```

nit: These should be u32.
___
*[`nativelink-service/src/bytestream_server.rs` line 272 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6SOisp-O1wLJAHBNpq:-O6SOisp-O1wLJAHBNpr:b-rh7bro) ([raw file](https://github.com/TraceMachina/nativelink/blob/18578da4d80a1998ab0c71561ab5070a96d53466/nativelink-service/src/bytestream_server.rs#L272)):*
> ```XML
>         read_request: ReadRequest,
>     ) -> Result<Response<ReadStream>, Error> {
>         let read_limit = read_request.read_limit as u64;
> ```

nit: Use `u64::try_from`
___
*[`nativelink-service/src/bytestream_server.rs` line 296 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6SOlxiEpV9mPpDnl3_:-O6SOlxiEpV9mPpDnl3a:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/18578da4d80a1998ab0c71561ab5070a96d53466/nativelink-service/src/bytestream_server.rs#L296)):*
> ```XML
>             get_part_fut: Box::pin(async move {
>                 store
>                     .get_part(digest, tx, read_request.read_offset as u64, read_limit)
> ```

ditto.
___
*[`nativelink-store/src/ac_utils.rs` line 37 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6SOrem3WV0AhuDc_0g:-O6SOrem3WV0AhuDc_0h:bs0dm41) ([raw file](https://github.com/TraceMachina/nativelink/blob/18578da4d80a1998ab0c71561ab5070a96d53466/nativelink-store/src/ac_utils.rs#L37)):*
> ```XML
> /// into memory. If we don't bound the max size of the object we enable users
> /// to use up all the memory on this machine.
> const MAX_ACTION_MSG_SIZE: u64 = 10 << 20; // 10mb.
> ```

nit: Keep as `usize`.
___
*[`nativelink-store/src/ac_utils.rs` line 72 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6SOuBMEUGmb3eJhAOB:-O6SOuBMEUGmb3eJhAOC:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/18578da4d80a1998ab0c71561ab5070a96d53466/nativelink-store/src/ac_utils.rs#L72)):*
> ```XML
>     }
>     let store_data = store_data_resp?;
>     let store_data_len = store_data.len() as u64;
> ```

ditto.
___
*[`nativelink-store/src/completeness_checking_store.rs` line 142 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6SPDC80pKzZUjvPjGv:-O6SPDC80pKzZUjvPjGw:bdxcngu) ([raw file](https://github.com/TraceMachina/nativelink/blob/18578da4d80a1998ab0c71561ab5070a96d53466/nativelink-store/src/completeness_checking_store.rs#L142)):*
> ```XML
>             results: &'a mut [Option<u64>],
>             digests_to_check: Vec<StoreKey<'a>>,
>             digests_to_check_idxs: Vec<u64>,
> ```

nit: should be `usize`.
___
*[`nativelink-store/src/compression_store.rs` line 180 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6SPYnRC6LeZ5HfCTmj:-O6SPYnRC6LeZ5HfCTmk:b-lsrf46) ([raw file](https://github.com/TraceMachina/nativelink/blob/18578da4d80a1998ab0c71561ab5070a96d53466/nativelink-store/src/compression_store.rs#L180)):*
> ```XML
>                     ..Default::default()
>                 };
>                 max_index_count as usize
> ```

nit: Please make this function return `Result<Self, Error>` and make this `usize::try_from`
___
*[`nativelink-store/src/dedup_store.rs` line 55 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6SQOzR7RVcI9CbTa62:-O6SQOzR7RVcI9CbTa63:b5gvpkm) ([raw file](https://github.com/TraceMachina/nativelink/blob/18578da4d80a1998ab0c71561ab5070a96d53466/nativelink-store/src/dedup_store.rs#L55)):*
> ```XML
>     fast_cdc_decoder: FastCDC,
>     #[metric(help = "Maximum number of concurrent fetches per get")]
>     max_concurrent_fetch_per_get: u64,
> ```

Should keep a `usize`.
___
*[`nativelink-store/src/dedup_store.rs` line 89 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6SQCxCCEbOW1501Vfw:-O6SQCxCCEbOW1501Vfx:bvx3l7q) ([raw file](https://github.com/TraceMachina/nativelink/blob/18578da4d80a1998ab0c71561ab5070a96d53466/nativelink-store/src/dedup_store.rs#L89)):*
> ```XML
>             content_store,
>             fast_cdc_decoder: FastCDC::new(
>                 min_size as usize,
> ```

ditto. This needs to be `usize::try_from` and have this function return `Result<Self, Error>`
___
*[`nativelink-store/src/dedup_store.rs` line 314 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6SRlWoECDvJf1PUIqE:-O6SRlWp7ohUxSc4Q5FI:b-x7mgor) ([raw file](https://github.com/TraceMachina/nativelink/blob/18578da4d80a1998ab0c71561ab5070a96d53466/nativelink-store/src/dedup_store.rs#L314)):*
> ```XML
>         // streamed data.
>         // Note: Need to take special care to ensure we send the proper slice of data requested.
>         let mut bytes_to_skip = offset - start_byte_in_stream;
> ```

nit: Cast this using `usize::try_from`
___
*[`nativelink-store/src/dedup_store.rs` line 324 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6SR7K58z4pL-niAm9w:-O6SR7K58z4pL-niAm9x:b-r0411v) ([raw file](https://github.com/TraceMachina/nativelink/blob/18578da4d80a1998ab0c71561ab5070a96d53466/nativelink-store/src/dedup_store.rs#L324)):*
> ```XML
>                 data.len()
>             );
>             let end_pos = cmp::min(data.len() as u64, bytes_to_send + bytes_to_skip);
> ```

nit: cast this to a `usize`.
___
*[`nativelink-store/src/fast_slow_store.rs` line 110 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6ST_N4C2UPnZ8wOHyu:-O6ST_N4C2UPnZ8wOHyv:b2i0j3h) ([raw file](https://github.com/TraceMachina/nativelink/blob/18578da4d80a1998ab0c71561ab5070a96d53466/nativelink-store/src/fast_slow_store.rs#L110)):*
> ```XML
>     // elsewhere in the code.
>     pub fn calculate_range(
>         received_range: &Range<usize>,
> ```

nit: I think these two args should be `Range<u64>` and the result should be `Range<usize>`


<!-- Sent from Reviewable.io -->

2024-09-10 19:48 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1344)* status: 0 of 2 LGTMs obtained, and 5 of 39 files reviewed, and 13 discussions need to be resolved

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6STkZ_2IhNZhqZLX9W:-O6STkZ_2IhNZhqZLX9X:b82nyul) (no related file):*
I still have more to review, but figured I'd post what I've done so far

___


<!-- Sent from Reviewable.io -->

2024-09-11 00:36 UTC, aleksdmladenovic commented
Thanks, @allada.

I could see general rule in adding `try_from` and when to use `u64` and `usize`, from your review. ;) 
I will update your current opinions as well as other codes based on the general rule.

2024-09-11 15:57 UTC, aleksdmladenovic reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1344)* status: 0 of 2 LGTMs obtained, and 1 of 40 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Docs Deployment / macos-14, Docs Deployment / ubuntu-24.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache (Legacy Dockerfile Test), Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, and 5 discussions need to be resolved

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6STkZ_2IhNZhqZLX9W:-O6Wn4eyEJ9Qg6fUbFMn:b-hjj4hr) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I still have more to review, but figured I'd post what I've done so far
</blockquote></details>

I've addressed all changes you asked.

Hope you to review again.

cc: @allada, @MarcusSorealheis

___
___
*[`nativelink-service/src/bytestream_server.rs` line 296 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6SOlxiEpV9mPpDnl3_:-O6WmjgM8obNxsk0wDBf:bmfxro8) ([raw file](https://github.com/TraceMachina/nativelink/blob/18578da4d80a1998ab0c71561ab5070a96d53466/nativelink-service/src/bytestream_server.rs#L296)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.ar
___
*[`nativelink-store/src/ac_utils.rs` line 72 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6SOuBMEUGmb3eJhAOB:-O6Wmld6BBynqB6D1peO:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/18578da4d80a1998ab0c71561ab5070a96d53466/nativelink-store/src/ac_utils.rs#L72)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`nativelink-store/src/dedup_store.rs` line 55 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6SQOzR7RVcI9CbTa62:-O6WmvWr2sPZp8um1Vvs:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/18578da4d80a1998ab0c71561ab5070a96d53466/nativelink-store/src/dedup_store.rs#L55)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Should keep a `usize`.
</blockquote></details>

Done.
___
*[`nativelink-store/src/dedup_store.rs` line 89 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6SQCxCCEbOW1501Vfw:-O6WmwfN2h7EcyeuyoQi:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/18578da4d80a1998ab0c71561ab5070a96d53466/nativelink-store/src/dedup_store.rs#L89)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto. This needs to be `usize::try_from` and have this function return `Result<Self, Error>`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-11 18:54 UTC, allada requested changes
> Reviewed 10 of 39 files at r1, 8 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1344)* status: 0 of 2 LGTMs obtained, and 19 of 40 files reviewed, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Docs Deployment / macos-14, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable, and 34 discussions need to be resolved

___
*[`nativelink-store/src/fast_slow_store.rs` line 123 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6Wo-nr5AKbpHoqTqD2:-O6Wo-nr5AKbpHoqTqD3:buyq525) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/src/fast_slow_store.rs#L123)):*
> ```XML
>             // Offset both to the start of the received_range.
>             Ok(Some(
>                 usize::try_from(start - received_range.start)
> ```

nit, can we put these as variables to make it more readable?
___
*[`nativelink-store/src/filesystem_store.rs` line 47 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6WoMzm7sLPvQPp7e1v:-O6WoMzm7sLPvQPp7e1w:bl6gc2t) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/src/filesystem_store.rs#L47)):*
> ```XML
> 
> // Default size to allocate memory of the buffer when reading files.
> const DEFAULT_BUFF_SIZE: u64 = 32 * 1024;
> ```

nit: Stay usize.
___
*[`nativelink-store/src/filesystem_store.rs` line 403 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6Wo9brBiuinACed1jZ:-O6Wo9brBiuinACed1j_:b-gz6on7) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/src/filesystem_store.rs#L403)):*
> ```XML
> /// The number of files to read the metadata for at the same time when running
> /// add_files_to_cache.
> const SIMULTANEOUS_METADATA_READS: u64 = 200;
> ```

nit: keep as `usize`
___
*[`nativelink-store/src/filesystem_store.rs` line 531 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6WoKnE2AZIahDElEIn:-O6WoKnE2AZIahDElEIo:bds6gai) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/src/filesystem_store.rs#L531)):*
> ```XML
>     block_size: u64,
>     #[metric(help = "Size of the configured read buffer size")]
>     read_buffer_size: u64,
> ```

nit: This should stay usize.
___
*[`nativelink-store/src/grpc_store.rs` line 452 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6Wr7Ep67YTu32tVbJY:-O6Wr7Ep67YTu32tVbJZ:bclwapl) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/src/grpc_store.rs#L452)):*
> ```XML
>         digest: DigestInfo,
>         writer: &mut DropCloserWriteHalf,
>         offset: u64,
> ```

nit: These two should stay `usize`, because this function is for in-memory data.
___
*[`nativelink-store/src/grpc_store.rs` line 671 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6WrWLq57nb9AsDsk7e:-O6WrWLq57nb9AsDsk7f:b3jx44v) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/src/grpc_store.rs#L671)):*
> ```XML
>         if matches!(self.store_type, nativelink_config::stores::StoreType::ac) {
>             return self
>                 .get_action_result_as_part(digest, writer, offset, length)
> ```

nit: Do conversion here.
___
*[`nativelink-store/src/memory_store.rs` line 250 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6WrlYX6wVF-G9Of3AQ:-O6WrlYX6wVF-G9Of3AR:byjkvsa) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/src/memory_store.rs#L250)):*
> ```XML
>         key: StoreKey<'_>,
>         writer: &mut DropCloserWriteHalf,
>         offset: u64,
> ```

nit: `offset` should stay `u64` here, but convert it to `usize` immediately in the function.

`length` on the other hand should stay u64, but conversion will look more like...
___
*[`nativelink-store/src/memory_store.rs` line 267 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6WsQvo2FYG4DSSMRZO:-O6WsQvo2FYG4DSSMRZP:bmn7avj) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/src/memory_store.rs#L267)):*
> ```XML
>         let default_len =
>             u64::try_from(value.len()).err_tip(|| "Could not convert value.len() to u64")? - offset;
>         let length = length.unwrap_or(default_len).min(default_len);
> ```

```rs
let default_len = value.len().saturating_sub(usize::try_from(offset).unwrap_or(usize::MAX));
let length = length.unwrap_or(default_len).min(default_len);
```
___
*[`nativelink-store/src/redis_store.rs` line 337 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6X-fOY-CWLHqtP05AO:-O6X-fOY-CWLHqtP05AP:bhph4d8) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/src/redis_store.rs#L337)):*
> ```XML
>         key: StoreKey<'_>,
>         writer: &mut DropCloserWriteHalf,
>         offset: u64,
> ```

nit: Lets keep this `u64`, but then immediately in the function convert them to `usize` using `try_from`. 

The redis library we use forces `usize`, so we might as well leverage this.
___
*[`nativelink-store/src/s3_store.rs` line 77 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6XPR9_3uXC9HJq6vtk:-O6XPR9_3uXC9HJq6vtl:b-lqf3dc) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/src/s3_store.rs#L77)):*
> ```XML
> // S3 parts cannot be more than this number. See:
> // https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html
> const MAX_UPLOAD_PARTS: u64 = 10_000;
> ```

nit: `usize`
___
*[`nativelink-store/src/s3_store.rs` line 81 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6XPNXT6EfGzraTY4PK:-O6XPNXT6EfGzraTY4PL:b-ho03gk) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/src/s3_store.rs#L81)):*
> ```XML
> // Default max buffer size for retrying upload requests.
> // Note: If you change this, adjust the docs in the config.
> const DEFAULT_MAX_RETRY_BUFFER_PER_REQUEST: u32 = 5 * 1024 * 1024; // 5MB.
> ```

nit: This should be `usize`.
___
*[`nativelink-store/src/s3_store.rs` line 85 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6XPPTOBfcnt8qHVVOK:-O6XPPTOBfcnt8qHVVOL:b-lqf3dc) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/src/s3_store.rs#L85)):*
> ```XML
> // Default limit for concurrent part uploads per multipart upload.
> // Note: If you change this, adjust the docs in the config.
> const DEFAULT_MULTIPART_MAX_CONCURRENT_UPLOADS: u64 = 10;
> ```

nit: `usize`
___
*[`nativelink-store/src/s3_store.rs` line 253 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6XPIU98YCRAR7UUnJ-:-O6XPIU98YCRAR7UUnJ0:b-nhe32m) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/src/s3_store.rs#L253)):*
> ```XML
>     consider_expired_after_s: i64,
>     #[metric(help = "The number of bytes to buffer for retrying requests")]
>     max_retry_buffer_per_request: u64,
> ```

nit: This should be `usize`
___
*[`nativelink-store/src/s3_store.rs` line 255 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6XPLHF3m75DRu--7vy:-O6XPLHF3m75DRu--7vz:b-nhe32m) ([raw file](https://github.com/T [...]

2024-09-12 02:16 UTC, aleksdmladenovic reviewed
I've addressed all changes you asked.
Waiting review on this again.

Thanks!

cc: @allada, @MarcusSorealheis 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-:-O6Z02xGCBAr3t0xQA8b:b-nm18fd)* status: 0 of 2 LGTMs obtained, and 13 of 40 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache (Legacy Dockerfile Test), Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 15 discussions need to be resolved

___
*[`nativelink-store/src/memory_store.rs` line 267 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6WsQvo2FYG4DSSMRZO:-O6Z-DS21stsIvXinVgH:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/src/memory_store.rs#L267)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

```rs
let default_len = value.len().saturating_sub(usize::try_from(offset).unwrap_or(usize::MAX));
let length = length.unwrap_or(default_len).min(default_len);
```
</blockquote></details>

Done.
___
*[`nativelink-store/src/verify_store.rs` line 171 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6XPjF37R3uPki7RXcg:-O6Z-i192YjBe6Y1ZjOD:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/src/verify_store.rs#L171)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

the values in `UploadSizeInfo` should be a `u64`
</blockquote></details>

Done.
___
*[`nativelink-store/tests/compression_store_test.rs` line 147 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6XQ0f1BFgae0Fidlmq:-O6Z-kKH3wnUR-PPV9aX:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/tests/compression_store_test.rs#L147)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto, just cast directly for tests.
</blockquote></details>

Done.
___
*[`nativelink-store/tests/fast_slow_store_test.rs` line 117 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6XQ7xhAmNtP7ljOfR7:-O6Z-ltHATUkBuDXq7Pp:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/tests/fast_slow_store_test.rs#L117)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto, just cast directly for tests.
</blockquote></details>

Done.
___
*[`nativelink-store/tests/fast_slow_store_test.rs` line 124 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6XQ92L9F8gV-yaiWzN:-O6Z-mOYAFL3QMxE3FvV:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/tests/fast_slow_store_test.rs#L124)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto, just cast directly for tests.
</blockquote></details>

Done.
___
*[`nativelink-store/tests/fast_slow_store_test.rs` line 298 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6XQHaC1Z9BvB8v5kvy:-O6Z-q2v4qqjvUXq8EbY:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/tests/fast_slow_store_test.rs#L298)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto, just cast directly for tests.
</blockquote></details>

Done.
___
*[`nativelink-store/tests/fast_slow_store_test.rs` line 449 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6XQI5W7plOeYg2fS_9:-O6Z-rKY2aSN48BuTTHh:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/tests/fast_slow_store_test.rs#L449)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto, just cast directly for tests.
</blockquote></details>

Done.
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1361 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6XQJcu9gv9VzycffgF:-O6Z-s45A9BYjDctoPbp:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/tests/filesystem_store_test.rs#L1361)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto, just cast directly for tests. and others in this file
</blockquote></details>

Done.
___
*[`nativelink-store/tests/redis_store_test.rs` line 201 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6XQNSv0ZgcPSrI8E2c:-O6Z-uII2VNgVWgbxqqZ:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/tests/redis_store_test.rs#L201)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto, just cast directly for tests. and others in this file.
</blockquote></details>

Done.
___
*[`nativelink-store/tests/shard_store_test.rs` line 169 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6XQRlR4g7-jiLXuCUs:-O6Z-vug2ij4n6SKy5bj:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/97e17138f4545883d4512f2a7da034fbdd1193c5/nativelink-store/tests/shard_store_test.rs#L169)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto, just cast directly for tests.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-13 04:45 UTC, allada requested changes
Looks good. Just a few more minor requests.

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 39 files at r1, 7 of 26 files at r2, 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-:-O6dgqhP7EEwTer28R2J:b-ulbeuz)* status: 1 of 2 LGTMs obtained, and all files reviewed, and 10 discussions need to be resolved

___
*[`nativelink-store/src/existence_cache_store.rs` line 32 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6dcOr--q-9v7fKhKu8:-O6dcOr--q-9v7fKhKu9:bpoyhh) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8114b42f8c917311affeea574e57abaddce67fd/nativelink-store/src/existence_cache_store.rs#L32)):*
> ```XML
> 
> #[derive(Clone, Debug)]
> struct ExistanceItem(usize);
> ```

nit: This should be `u64`
___
*[`nativelink-store/src/grpc_store.rs` line 662 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6ddYpQEoScZt1SlVnz:-O6ddYpQEoScZt1SlVo-:bpgudns) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8114b42f8c917311affeea574e57abaddce67fd/nativelink-store/src/grpc_store.rs#L662)):*
> ```XML
>     ) -> Result<(), Error> {
>         let digest = key.into_digest();
>         let offset = usize::try_from(offset).err_tip(|| "Could not convert offset to usize")?;
> ```

nit: This should only happen if it's a `StoreType::ac`. Other data queries should use `u64`.
___
*[`nativelink-store/src/grpc_store.rs` line 698 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6ddjXa38qwwA6TG-Ve:-O6ddjXa38qwwA6TG-Vf:b-e4ftw7) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8114b42f8c917311affeea574e57abaddce67fd/nativelink-store/src/grpc_store.rs#L698)):*
> ```XML
>             resource_name,
>             writer,
>             read_offset: offset as i64,
> ```

nit: use `try_from`.
___
*[`nativelink-store/src/grpc_store.rs` line 699 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6ddlu02RkYlvgQwTCa:-O6ddlu02RkYlvgQwTCb:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8114b42f8c917311affeea574e57abaddce67fd/nativelink-store/src/grpc_store.rs#L699)):*
> ```XML
>             writer,
>             read_offset: offset as i64,
>             read_limit: length.unwrap_or(0) as i64,
> ```

ditto.
___
*[`nativelink-store/src/memory_store.rs` line 254 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6de91p1NQ2Jq8Ww-9L:-O6de91p1NQ2Jq8Ww-9M:b-nm9j6h) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8114b42f8c917311affeea574e57abaddce67fd/nativelink-store/src/memory_store.rs#L254)):*
> ```XML
>     ) -> Result<(), Error> {
>         let offset = usize::try_from(offset).err_tip(|| "Could not convert offset to usize")?;
>         let length: Option<usize> = match length {
> ```

nit:
```rs
let length = length.map(|v| usize::try_from(v).err_tip(|| "Could not convert length to usize")).transpose()?;
```
___
*[`nativelink-store/src/redis_store.rs` line 362 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6dee5q8vaD9BwtLebW:-O6dee5q8vaD9BwtLebX:b-mpyvg4) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8114b42f8c917311affeea574e57abaddce67fd/nativelink-store/src/redis_store.rs#L362)):*
> ```XML
>     ) -> Result<(), Error> {
>         let offset = usize::try_from(offset).err_tip(|| "Could not convert offset to usize")?;
>         let length: Option<usize> = match length {
> ```

ditto above.
___
*[`nativelink-store/tests/shard_store_test.rs` line 169 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6dg7tt0w8FqEMXDb0x:-O6dg7tt0w8FqEMXDb0y:b-ipfb2u) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8114b42f8c917311affeea574e57abaddce67fd/nativelink-store/tests/shard_store_test.rs#L169)):*
> ```XML
>             .await,
>         Ok(vec![
>             Some(original_data1.clone().len() as u64),
> ```

nit: Data doesn't need to be cloned to get length.
___
*[`nativelink-store/tests/shard_store_test.rs` line 170 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6dgBZ20ZZRuZxoHRVL:-O6dgBZ20ZZRuZxoHRVM:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8114b42f8c917311affeea574e57abaddce67fd/nativelink-store/tests/shard_store_test.rs#L170)):*
> ```XML
>         Ok(vec![
>             Some(original_data1.clone().len() as u64),
>             Some(original_data2.clone().len() as u64)
> ```

ditto.
___
*[`nativelink-util/src/evicting_map.rs` line 48 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6dgPyyAfMLpHfIO1fb:-O6dgPyyAfMLpHfIO1fc:bvxxqmo) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8114b42f8c917311affeea574e57abaddce67fd/nativelink-util/src/evicting_map.rs#L48)):*
> ```XML
> pub trait LenEntry: 'static {
>     /// Length of referenced data.
>     fn len(&self) -> usize;
> ```

These need to be `u64`.

filesystem store needs to serve as `u64`, but memory store will need to convert from `usize`.
___
*[`nativelink-util/src/store_trait.rs` line 726 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6dglAi5MOcHExCxNJA:-O6dglAi5MOcHExCxNJB:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8114b42f8c917311affeea574e57abaddce67fd/nativelink-util/src/store_trait.rs#L726)):*
> ```XML
>         length: Option<u64>,
>     ) -> Result<Bytes, Error> {
>         let length_usize: Option<usize> = match length {
> ```

ditto.


<!-- Sent from Reviewable.io -->

2024-09-13 08:51 UTC, aleksdmladenovic reviewed
Thanks. @allada .

Addressed all your changes asked.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-:-O6e_8FL1uoI6W71WRUP:b-6x8wl3)* status: 1 of 2 LGTMs obtained, and 29 of 40 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache (Legacy Dockerfile Test), Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, and 5 discussions need to be resolved

___
*[`nativelink-store/src/grpc_store.rs` line 699 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6ddlu02RkYlvgQwTCa:-O6e_1C06gPatoN9wJlM:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8114b42f8c917311affeea574e57abaddce67fd/nativelink-store/src/grpc_store.rs#L699)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 362 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6dee5q8vaD9BwtLebW:-O6e_48cDWcTJ6Cig4eX:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8114b42f8c917311affeea574e57abaddce67fd/nativelink-store/src/redis_store.rs#L362)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto above.
</blockquote></details>

Done.
___
*[`nativelink-util/src/evicting_map.rs` line 48 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6dgPyyAfMLpHfIO1fb:-O6e_61O8FUv1P8jc98I:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8114b42f8c917311affeea574e57abaddce67fd/nativelink-util/src/evicting_map.rs#L48)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

These need to be `u64`.

filesystem store needs to serve as `u64`, but memory store will need to convert from `usize`.
</blockquote></details>

Done.
___
*[`nativelink-util/src/store_trait.rs` line 726 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6dglAi5MOcHExCxNJA:-O6e_6xO9J1OAmt5aa44:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8114b42f8c917311affeea574e57abaddce67fd/nativelink-util/src/store_trait.rs#L726)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-15 03:30 UTC, allada approved these changes
+@adam-singer for second review

> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-:-O6nigqX-Vp49NWje616:bq4jux9)* status: 1 of 2 LGTMs obtained, and all files reviewed, and pending CI: windows-2022 / stable (waiting on @adam-singer)



<!-- Sent from Reviewable.io -->

2024-09-16 02:21 UTC, aleksdmladenovic commented
Rebased changes. Hope you to check this.

cc: @adam-singer, @allada

2024-09-16 17:36 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 12 of 39 files at r1, 7 of 26 files at r2, 7 of 17 files at r3, 9 of 11 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-:-O6vu3x7-nwejFe0Ipy-:bnfp4nl)* status: 2 of 2 LGTMs obtained, and all files reviewed, and 1 discussions need to be resolved

___
*[`nativelink-store/src/compression_store.rs` line 166 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6vt-HrA0qYrj8rqqRF:-O6vt-HrA0qYrj8rqqRG:b-nkybdg) ([raw file](https://github.com/TraceMachina/nativelink/blob/588f301882c2b318def8820fcb68967af27b2cb0/nativelink-store/src/compression_store.rs#L166)):*
> ```XML
>         };
> 
>         let max_index_count = (input_max_size / store.config.block_size as u64) + 1;
> ```

@allada do we have any concern that compression store is using u32 due to lz4 max block size being a u32 and here we up converting and doing a `+1` ? Logically we were doing that in the previous code so non-blocker 


<!-- Sent from Reviewable.io -->

2024-09-18 00:46 UTC, aleksdmladenovic reviewed
Just resolved merge conflicts and rebased.
Since it's a huge PR, I hope you to merge this soon so I can get rid of resolving merge conflicts every time main branch is updated... :)
Thanks.

cc: @allada, @adam-singer, @MarcusSorealheis 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-:-O71SrIF1Xfp8DMr33OG:b6salik)* status: 2 of 2 LGTMs obtained, and 37 of 40 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache (Legacy Dockerfile Test), Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 1 discussions need to be resolved

___
*[`nativelink-store/src/compression_store.rs` line 166 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6vt-HrA0qYrj8rqqRF:-O71U5uu2EUd8mxeBLiB:b1dvyek) ([raw file](https://github.com/TraceMachina/nativelink/blob/588f301882c2b318def8820fcb68967af27b2cb0/nativelink-store/src/compression_store.rs#L166)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

@allada do we have any concern that compression store is using u32 due to lz4 max block size being a u32 and here we up converting and doing a `+1` ? Logically we were doing that in the previous code so non-blocker
</blockquote></details>

Here, in this PR. we updated `UploadSizeInfo` to have `u64` instead of `usize`.
`LZ4Config`'s `block_size` is declared as `u32` type and it doesn't need to be updated cuz its size is explicit and constant.

I think there won't be any critical problem raising because we are just up-converting ( padding with 0 maybe? ) from u32 to u64 and it's been working like this from previous versions as this. ( `usize`, in fact, is `u64` in most systems, cuz almost every system uses 64bit, not 32 bit )

cc: @adam-singer, @allada 


<!-- Sent from Reviewable.io -->

2024-09-20 03:23 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1344)* status: 2 of 2 LGTMs obtained, and 37 of 40 files reviewed

___
*[`nativelink-store/src/compression_store.rs` line 166 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1344#-O6vt-HrA0qYrj8rqqRF:-O7CS1N-ETtkQTGhc6Xl:bqr4tlm) ([raw file](https://github.com/TraceMachina/nativelink/blob/588f301882c2b318def8820fcb68967af27b2cb0/nativelink-store/src/compression_store.rs#L166)):*
<details><summary><i>Previously, aleksdmladenovic (Aleksandar Mladenovic) wrote…</i></summary><blockquote>

Here, in this PR. we updated `UploadSizeInfo` to have `u64` instead of `usize`.
`LZ4Config`'s `block_size` is declared as `u32` type and it doesn't need to be updated cuz its size is explicit and constant.

I think there won't be any critical problem raising because we are just up-converting ( padding with 0 maybe? ) from u32 to u64 and it's been working like this from previous versions as this. ( `usize`, in fact, is `u64` in most systems, cuz almost every system uses 64bit, not 32 bit )

cc: @adam-singer, @allada
</blockquote></details>

Yeah I noticed this too, but when I looked over the logic, this is happening at a 1 time cost and the division operation is taking the safe route (upcasting), so I wasn't worried.


<!-- Sent from Reviewable.io -->

2024-09-20 03:24 UTC, allada approved these changes
> Reviewed 3 of 4 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1344)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained, and all files reviewed



<!-- Sent from Reviewable.io -->

2024-09-20 03:24 UTC, merged