Add graceful shutdown to worker instances
TraceMachina/nativelink pull request #1394
Opened 2024-10-04 22:15 UTC by SchahinRohani

# Description

This PR implements graceful shutdown for worker instances to ensure that the scheduler is properly notified when workers are shutting down.

**Key changes:**

- **Added an `Instance` struct**:
  - Introduced a generic `Instance` struct that holds a vector of `LocalWorker` instances.
  - This struct manages the lifecycle of all worker instances.

- **Implemented `shutdown` method in `LocalWorker`**:
  - Each `LocalWorker` now has an asynchronous `shutdown` method.
  - The `shutdown` method sends a `going_away` message to the scheduler using the `going_away` function from the `WorkerApiClientTrait`.
  - Properly handles the case where the `grpc_client` or `worker_id` may not be available.

- **Signal handling for graceful shutdown**:
  - Added signal handlers for `SIGINT` and `SIGTERM` to initiate the shutdown process.
  - On receiving a signal, the application locks the `Instance` and calls the `graceful_shutdown` method.
  - Ensures that all workers are notified and have a chance to clean up before the application exits.

- **Updated the `main` function**:
  - Adjusted the `main` function to create and manage the `Instance` struct.
  - Cloned the `Arc` of `Instance` to pass it into the signal handling closures.
  - Awaited the `graceful_shutdown` method to ensure all workers have completed shutdown procedures.

## How Has This Been Tested?

`bazel test ...`

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-10-07 16:17 UTC, adam-singer requested changes
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1394)* status: 0 of 1 LGTMs obtained, and 3 of 6 files reviewed, and 3 discussions need to be resolved

___
*[`nativelink-worker/src/local_worker.rs` line 486 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O8bjxHRD4Ned7wkYPDI:-O8bjxHRD4Ned7wkYPDJ:brbeuyh) ([raw file](https://github.com/TraceMachina/nativelink/blob/0dd859615e88990e0837811ead27a6c91e60aa97/nativelink-worker/src/local_worker.rs#L486)):*
> ```XML
> 
>     pub async fn shutdown(&self) {
>         println!("Shutting down worker: {}", self.name());
> ```

should be a tracing log statement and not println statements, for example https://github.com/TraceMachina/nativelink/blob/553f33c682d849020ca9e407c1a6c47cc49bc598/nativelink-util/src/common.rs#L237 
___
*[`nativelink-worker/src/local_worker.rs` line 488 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O8bkLmo4a71M1i06GUN:-O8bkLmo4a71M1i06GUO:bzdb549) ([raw file](https://github.com/TraceMachina/nativelink/blob/0dd859615e88990e0837811ead27a6c91e60aa97/nativelink-worker/src/local_worker.rs#L488)):*
> ```XML
>         println!("Shutting down worker: {}", self.name());
> 
>         let max_wait_duration = Duration::from_secs(60);
> ```

I think this would be better named as a shutdown deadline and a configuration option. I wonder if this would get out of sync with request timeouts and cause hard to catch behavior if shorter than upstream timeouts.
___
*[`nativelink-worker/src/local_worker.rs` line 525 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O8bkuRf90-cm5vJrbRG:-O8bkuRf90-cm5vJrbRH:b-4edpjt) ([raw file](https://github.com/TraceMachina/nativelink/blob/0dd859615e88990e0837811ead27a6c91e60aa97/nativelink-worker/src/local_worker.rs#L525)):*
> ```XML
>             } else {
>                 println!("No worker_id available; cannot notify scheduler.");
>                 return;
> ```

This would be panic or return Err / make_err type situation


<!-- Sent from Reviewable.io -->

2024-10-10 04:49 UTC, allada requested changes
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1394)* status: 0 of 1 LGTMs obtained, and 2 of 6 files reviewed, and 7 discussions need to be resolved

___
*[`nativelink-worker/src/local_worker.rs` line 365 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O8bVE3i0A1dSgml5W0p:-O8bVE3i0A1dSgml5W0q:b-v2rjgl) ([raw file](https://github.com/TraceMachina/nativelink/blob/0dd859615e88990e0837811ead27a6c91e60aa97/nativelink-worker/src/local_worker.rs#L365)):*
> ```XML
>     running_actions_manager: Arc<U>,
>     connection_factory: ConnectionFactory<T>,
>     sleep_fn: Mutex<Option<SleepFnType>>,
> ```

nit: I don't think you need a mutex here, just add `+ 'static` to the end of `Sync` in the `SleepFnType`.
___
*[`src/bin/nativelink.rs` line 1060 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O8oir_bBhYBU82ZK2Pa:-O8oir_bBhYBU82ZK2Pb:b-tmnf7l) ([raw file](https://github.com/TraceMachina/nativelink/blob/8fa78c24530d54a47c132b0456d0f2c29c8887ae/src/bin/nativelink.rs#L1060)):*
> ```XML
> 
>         // Create a broadcast channel for shutdown signals
>         let (shutdown_tx, _) = broadcast::channel::<()>(16);
> ```

lets send a`Arc<tokio::sync::oneshot::Sender<()>>`...

This will allow us to create a oneshot pair, every receiver will now receive a copy of the Arc, but be unable to do anything with it, since Arc prevents it from being mutable.

We can then `await` on the `Receiver<()>` side... it'll always return the `Err` side, but `Err` means all receivers dropped the reference to the `Arc`.

What this means is that now we have a way to know when the workers are done, because all they have to do is drop the `Arc`.
___
*[`src/bin/nativelink.rs` line 1067 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O8oju1f9gUtWTuR115r:-O8oju1g0zLeYm-ksRLz:b-gph14n) ([raw file](https://github.com/TraceMachina/nativelink/blob/8fa78c24530d54a47c132b0456d0f2c29c8887ae/src/bin/nativelink.rs#L1067)):*
> ```XML
>                 .await
>                 .expect("Failed to listen to SIGINT");
>             if shutdown_tx_clone.send(()).is_err() {
> ```

lets do nothing special for `sigint`.
___
*[`src/bin/nativelink.rs` line 1093 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O8ok-JV-y3m3MSVQxMh:-O8ok-JV-y3m3MSVQxMi:b9m4o3j) ([raw file](https://github.com/TraceMachina/nativelink/blob/8fa78c24530d54a47c132b0456d0f2c29c8887ae/src/bin/nativelink.rs#L1093)):*
> ```XML
>         let _ = runtime.block_on(Arc::new(OriginContext::new()).wrap_async(
>             trace_span!("main"),
>             inner_main(cfg, server_start_time, shutdown_tx.clone()),
> ```

send the `shutdown_rx`.


<!-- Sent from Reviewable.io -->

2024-10-11 04:22 UTC, SchahinRohani reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1394)* status: 0 of 1 LGTMs obtained, and 2 of 6 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Coverage, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache / macos-14, NativeLink.com Cloud / Remote Cache / ubuntu-24.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 6 discussions need to be resolved

___
*[`nativelink-worker/src/local_worker.rs` line 486 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O8bjxHRD4Ned7wkYPDI:-O8qCNaj8EhyPQKkjp1P:b-fqvrmg) ([raw file](https://github.com/TraceMachina/nativelink/blob/0dd859615e88990e0837811ead27a6c91e60aa97/nativelink-worker/src/local_worker.rs#L486)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

should be a tracing log statement and not println statements, for example https://github.com/TraceMachina/nativelink/blob/553f33c682d849020ca9e407c1a6c47cc49bc598/nativelink-util/src/common.rs#L237
</blockquote></details>

Removed due to reimplentation of a different approach
___
*[`nativelink-worker/src/local_worker.rs` line 488 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O8bkLmo4a71M1i06GUN:-O8qCXKSArYY97_OYCHd:b-fqvrmg) ([raw file](https://github.com/TraceMachina/nativelink/blob/0dd859615e88990e0837811ead27a6c91e60aa97/nativelink-worker/src/local_worker.rs#L488)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

I think this would be better named as a shutdown deadline and a configuration option. I wonder if this would get out of sync with request timeouts and cause hard to catch behavior if shorter than upstream timeouts.
</blockquote></details>

Removed due to reimplentation of a different approach
___
*[`nativelink-worker/src/local_worker.rs` line 525 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O8bkuRf90-cm5vJrbRG:-O8qCXoXDcwUCdCi8r48:b-fqvrmg) ([raw file](https://github.com/TraceMachina/nativelink/blob/0dd859615e88990e0837811ead27a6c91e60aa97/nativelink-worker/src/local_worker.rs#L525)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

This would be panic or return Err / make_err type situation
</blockquote></details>

Removed due to reimplentation of a different approach
___
*[`src/bin/nativelink.rs` line 1060 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O8oir_bBhYBU82ZK2Pa:-O8tnCXs9SlciArIs5GL:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/8fa78c24530d54a47c132b0456d0f2c29c8887ae/src/bin/nativelink.rs#L1060)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

lets send a`Arc<tokio::sync::oneshot::Sender<()>>`...

This will allow us to create a oneshot pair, every receiver will now receive a copy of the Arc, but be unable to do anything with it, since Arc prevents it from being mutable.

We can then `await` on the `Receiver<()>` side... it'll always return the `Err` side, but `Err` means all receivers dropped the reference to the `Arc`.

What this means is that now we have a way to know when the workers are done, because all they have to do is drop the `Arc`.
</blockquote></details>

Done.
___
*[`src/bin/nativelink.rs` line 1067 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O8oju1f9gUtWTuR115r:-O8s1CXTAmwVGQYTQwuf:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/8fa78c24530d54a47c132b0456d0f2c29c8887ae/src/bin/nativelink.rs#L1067)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

lets do nothing special for `sigint`.
</blockquote></details>

Done.
___
*[`src/bin/nativelink.rs` line 1093 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O8ok-JV-y3m3MSVQxMh:-O8s1CxB676ZkEnwvkWs:bv2v7bj) ([raw file](https://github.com/TraceMachina/nativelink/blob/8fa78c24530d54a47c132b0456d0f2c29c8887ae/src/bin/nativelink.rs#L1093)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

send the `shutdown_rx`.
</blockquote></details>

That's not possible because broadcast::Receiver() doesn't implement clone.


<!-- Sent from Reviewable.io -->

2024-10-22 17:48 UTC, allada requested changes
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1394)* status: 0 of 1 LGTMs obtained, and 3 of 6 files reviewed, and 22 discussions need to be resolved

___
*[`nativelink-worker/src/local_worker.rs` line 353 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pI8kPEjgVIf7YyO2U:-O9pI8kPEjgVIf7YyO2V:bzgy732) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/nativelink-worker/src/local_worker.rs#L353)):*
> ```XML
>                 },
>                 res = futures.next() => res.err_tip(|| "Keep-alive should always pending. Likely unable to send data to scheduler")??,
>                 // Handle shutdown signal
> ```

nit: period on comments.
___
*[`nativelink-worker/src/local_worker.rs` line 355 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pIBUd8lduKMsGdjW7:-O9pIBUd8lduKMsGdjW8:bjucwnr) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/nativelink-worker/src/local_worker.rs#L355)):*
> ```XML
>                 // Handle shutdown signal
>                 complete_msg = shutdown_rx.recv().fuse() => {
>                     println!("Shutdown signal received. Shutting down worker...");
> ```

nit: Don't use `println!`, use `event!`
___
*[`nativelink-worker/src/local_worker.rs` line 357 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pIAbEEKuzIq75ipdN:-O9pIAbEEKuzIq75ipdO:b-5v3gaq) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/nativelink-worker/src/local_worker.rs#L357)):*
> ```XML
>                     println!("Shutdown signal received. Shutting down worker...");
> 
>                     // Perform worker cleanup tasks
> ```

nit: ditto.
___
*[`nativelink-worker/src/local_worker.rs` line 359 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pJMUw5Hjn2q8IXcqh:-O9pJMUw5Hjn2q8IXcqi:b1rbanb) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/nativelink-worker/src/local_worker.rs#L359)):*
> ```XML
>                     // Perform worker cleanup tasks
>                     let mut grpc_client = self.grpc_client.clone();
>                     let _ = grpc_client.going_away(GoingAwayRequest { worker_id: self.worker_id.clone() }).await;
> ```

It is a bad idea to `.await` in this loop as it could cause GRPC to disconnect, since it cannot process them while waiting.

What you probably want to do is put these promises in the `futures` struct.
___
*[`nativelink-worker/src/local_worker.rs` line 363 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pIUUGAZYKGFdMxNPD:-O9pIUUHDn_Rpf6z2C45:b-jj35vl) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/nativelink-worker/src/local_worker.rs#L363)):*
> ```XML
> 
>                     // Drop the Result<Arc<Sender<()>>, RecvError> to trigger the oneshot err.
>                     drop(complete_msg);
> ```

This already gets dropped here.

You don't want to do this here anyway. You need to stash this message somewhere and only when no more actions are running drop it (and any others that might be pending).
___
*[`nativelink-worker/tests/utils/local_worker_test_utils.rs` line 197 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pJiup2mGPFxWxLMwN:-O9pJiup2mGPFxWxLMwO:bjyelub) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/nativelink-worker/tests/utils/local_worker_test_utils.rs#L197)):*
> ```XML
>         Box::new(move |_| Box::pin(async move { /* No sleep */ })),
>     );
>     // Create a shutdown channel for the test
> ```

nit: Period.
___
*[`nativelink-worker/tests/utils/local_worker_test_utils.rs` line 198 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pJoXk7KWMQu1FgMaM:-O9pJoXk7KWMQu1FgMaN:b-uxixmy) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/nativelink-worker/tests/utils/local_worker_test_utils.rs#L198)):*
> ```XML
>     );
>     // Create a shutdown channel for the test
>     let (shutdown_tx_test, _) = broadcast::channel::<Arc<oneshot::Sender<()>>>(16);
> ```

nit: make magic number a const.
___
*[`src/bin/nativelink.rs` line 781 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pK-kW35tMqWNFzOCG:-O9pK-kX4o8CYM9dp6OL:b-7kooul) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/src/bin/nativelink.rs#L781)):*
> ```XML
>         event!(Level::WARN, "Ready, listening on {socket_addr}",);
>         root_futures.push(Box::pin(async move {
>             // Subscribe to the shutdown signal
> ```

nit: period.
___
*[`src/bin/nativelink.rs` line 786 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pK08v-0eDL0J6nL67:-O9pK08v-0eDL0J6nL68:b-qt19ay) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/src/bin/nativelink.rs#L786)):*
> ```XML
>             loop {
>                 select! {
>                     // Listen for incoming TCP connections
> ```

nit: needless comment.
___
*[`src/bin/nativelink.rs` line 879 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pK59TBDY_rhmOdrip:-O9pJzgF47kDIkjac583:b-h4ru7g) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/src/bin/nativelink.rs#L879)):*
> ```XML
>                     },
> 
>                     // Listen for shutdown signal
> ```

nit: period.nit: needless comment.
___
*[`src/bin/nativelink.rs` line 887 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pK1CrET4v5BGv-RZD:-O9pK1CrET4v5BGv-RZE:b-ewew6g) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/src/bin/nativelink.rs#L887)):*
> ```XML
>             }
> 
>             // Perform any necessary cleanup after exiting the loop
> ```

nit: comment is not true.
___
*[`src/bin/nativelink.rs` line 959 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pKC98AK4OH9TZ3_tv:-O9pKC98AK4OH9TZ3_tw:b-lq9crp) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/src/bin/nativelink.rs#L959)):*
> ```XML
>                     worker_metrics.insert(name.clone(), metrics);
> 
>                     // Subscribe to the shutdown channel
> ```

nit: Comment has no value.
___
*[`src/bin/nativelink.rs` line 977 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pKEU1969t21mFndr4:-O9pKEU1969t21mFndr5:blpgvrk) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/src/bin/nativelink.rs#L977)):*
> ```XML
> 
>     Ok(())
>     // unreachable!("All tasks should have terminated gracefully.");
> ```

nit: remove.
___
*[`src/bin/nativelink.rs` line 1057 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pKJqrBmrJpmdJn3nz:-O9pKJqrBmrJpmdJn3o-:b-7kooul) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/src/bin/nativelink.rs#L1057)):*
> ```XML
>             .build()?;
> 
>         // Create a broadcast channel for shutdown signals
> ```

nit: period.
___
*[`src/bin/nativelink.rs` line 1058 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pKIEsESY_CPkVz9xh:-O9pKIEsESY_CPkVz9xi:bgkaz6g) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/src/bin/nativelink.rs#L1058)):*
> ```XML
> 
>         // Create a broadcast channel for shutdown signals
>         let (shutdown_tx, _) = broadcast::channel::<Arc<oneshot::Sender<()>>>(16);
> ```

nit: Magic number needs const.
___
*[`src/bin/nativelink.rs` line 1061 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pKNni64M5EqQK [...]

2024-10-23 16:09 UTC, SchahinRohani reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1394)* status: 0 of 1 LGTMs obtained, and 0 of 6 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / macos-13, Bazel Dev / ubuntu-24.04, Cargo Dev / ubuntu-22.04, Coverage, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, and 5 discussions need to be resolved

___
*[`nativelink-worker/src/local_worker.rs` line 359 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pJMUw5Hjn2q8IXcqh:-O9u7Im53Hy6ITaYli7q:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/nativelink-worker/src/local_worker.rs#L359)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

It is a bad idea to `.await` in this loop as it could cause GRPC to disconnect, since it cannot process them while waiting.

What you probably want to do is put these promises in the `futures` struct.
</blockquote></details>

Done.
___
*[`nativelink-worker/src/local_worker.rs` line 363 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9pIUUGAZYKGFdMxNPD:-O9u7HBz2pKqNMVn2oqS:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/967073deccde15ce4004ac51c48c967d7ab1878b/nativelink-worker/src/local_worker.rs#L363)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This already gets dropped here.

You don't want to do this here anyway. You need to stash this message somewhere and only when no more actions are running drop it (and any others that might be pending).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-23 18:05 UTC, allada approved these changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1394)* status: 0 of 1 LGTMs obtained, and all files reviewed, and pending CI: Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, and 14 discussions need to be resolved

___
*[`nativelink-worker/src/local_worker.rs` line 358 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uVGRJ38mJ2RFS8xO_:-O9uVGRJ38mJ2RFS8xOa:b-n9m406) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/nativelink-worker/src/local_worker.rs#L358)):*
> ```XML
>                     let worker_id = self.worker_id.clone();
>                     let running_actions_manager = self.running_actions_manager.clone();
>                     let complete_msg_clone = complete_msg.expect("Failed to receive shutdown message").clone();
> ```

nit: Don't use `expect()` as it will panic. Instead use `.err_tip()` or just log the event.
___
*[`nativelink-worker/src/local_worker.rs` line 358 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uVSr002qEuTceJsnT:-O9uVSr002qEuTceJsnU:bg3wro5) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/nativelink-worker/src/local_worker.rs#L358)):*
> ```XML
>                     let worker_id = self.worker_id.clone();
>                     let running_actions_manager = self.running_actions_manager.clone();
>                     let complete_msg_clone = complete_msg.expect("Failed to receive shutdown message").clone();
> ```

nit: Do you need to clone here?
___
*[`nativelink-worker/src/local_worker.rs` line 361 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uUwSG7x3ndHE44Wa5:-O9uUwSG7x3ndHE44Wa6:b-prswno) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/nativelink-worker/src/local_worker.rs#L361)):*
> ```XML
>                     let shutdown_future = async move {
>                         if let Err(e) = grpc_client.going_away(GoingAwayRequest { worker_id }).await {
>                             eprintln!("Failed to send GoingAwayRequest: {e}");
> ```

nit: use `event!`
___
*[`nativelink-worker/src/running_actions_manager.rs` line 1893 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uVtNGDPegHIDFOszL:-O9uVtNGDPegHIDFOszM:b8sbtan) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/nativelink-worker/src/running_actions_manager.rs#L1893)):*
> ```XML
>                 let running_actions = self.running_actions.lock();
>                 if running_actions.is_empty() {
>                     drop(complete_msg.clone());
> ```

nit: Shouldn't we return/break here?
___
*[`nativelink-worker/src/running_actions_manager.rs` line 1896 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uVjEH2RPNSyfqQMpq:-O9uVjEH2RPNSyfqQMpr:b6stwqa) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/nativelink-worker/src/running_actions_manager.rs#L1896)):*
> ```XML
>                 }
>             }
>             if receiver.changed().await.is_err() {
> ```

nit: Please add a comment here why we are using `err` in such a strange way.
___
*[`nativelink-worker/tests/utils/local_worker_test_utils.rs` line 197 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uVzGG6TAy0H31ibpf:-O9uVzGG6TAy0H31ibpg:bast8j7) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/nativelink-worker/tests/utils/local_worker_test_utils.rs#L197)):*
> ```XML
>         Box::new(move |_| Box::pin(async move { /* No sleep */ })),
>     );
>     const MAX_CONCURRENT_CHANNEL: usize = 16;
> ```

nit: Put this at the top of the file and make a comment what it is doing.

Also, the name probably needs more elaboration.
___
*[`nativelink-worker/tests/utils/mock_running_actions_manager.rs` line 15 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uWBWD5adLDmKOGPab:-O9uWBWD5adLDmKOGPac:bbfeukb) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/nativelink-worker/tests/utils/mock_running_actions_manager.rs#L15)):*
> ```XML
> // limitations under the License.
> 
> use futures::Future;
> ```

nit: this line should go in the lower block.
___
*[`src/bin/nativelink.rs` line 874 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uWkyo6C-LlKCTDAA6:-O9uWkyo6C-LlKCTDAA7:bv42dyk) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/src/bin/nativelink.rs#L874)):*
> ```XML
>                         }
>                     },
>                     _ = shutdown_rx.recv() => {
> ```

nit: Please make a comment here explaining the way we are abusing `broadcast::Sender`. (
___
*[`src/bin/nativelink.rs` line 875 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uWYdE47jML4jdpJJl:-O9uWYdE47jML4jdpJJm:b-c3is4d) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/src/bin/nativelink.rs#L875)):*
> ```XML
>                     },
>                     _ = shutdown_rx.recv() => {
>                         event!(Level::INFO, "Shutdown signal received. Stopping server loop.");
> ```

nit: Make this a `WARN`
___
*[`src/bin/nativelink.rs` line 1045 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uXMQ30kn_f6Otrf_e:-O9uXMQ30kn_f6Otrf_f:b-4i0k1u) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/src/bin/nativelink.rs#L1045)):*
> ```XML
>             .build()?;
> 
>         const MAX_CONCURRENT_CHANNEL: usize = 16;
> ```

nit: ditto. Also, shouldn't this be 1?
___
*[`src/bin/nativelink.rs` line 1072 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uXF1k0taYax43iQ5h:-O9uXF1k0taYax43iQ5i:b-n1yyb8) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/src/bin/nativelink.rs#L1072)):*
> ```XML
>                     .map_err(|e| eprintln!("Failed to send shutdown signal: {e}"));
>                 if let Err(_e) = complete_rx.await {
>                     eprintln!("Successfully shut down.");
> ```

nit: Use `event!`


<!-- Sent from Reviewable.io -->

2024-10-24 09:31 UTC, SchahinRohani reviewed
There is still sometimes an error when nativelink tries to shutdown:

```
2024-10-24T09:25:53.598383Z ERROR nativelink_worker::local_worker: Worker disconnected from scheduler, err: Error { code: Internal, messages: ["UpdateForWorker stream closed early"] }
    at nativelink-worker/src/local_worker.rs:599
    in nativelink::worker with name: "worker_0"

  2024-10-24T09:25:53.598546Z ERROR nativelink_worker::local_worker: Error, err: Error { code: Internal, messages: ["UpdateForWorker stream closed early"] }
    at nativelink-worker/src/local_worker.rs:544
    in nativelink::worker with name: "worker_0"
```

How should i handle this?

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-:-O9xqKsu8ZZ6R2W83T86:bx4bw4z)* status: 0 of 1 LGTMs obtained, and 1 of 6 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Coverage, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache / macos-14, NativeLink.com Cloud / Remote Cache / ubuntu-24.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 9 discussions need to be resolved

___
*[`nativelink-worker/src/local_worker.rs` line 358 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uVGRJ38mJ2RFS8xO_:-O9xX1l054MtrrtmoFJg:b94ob7d) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/nativelink-worker/src/local_worker.rs#L358)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Don't use `expect()` as it will panic. Instead use `.err_tip()` or just log the event.
</blockquote></details>

The type of the complete_msg is a `Result<Arc<Sender<()>>, RecvError>`. I can't access the RecvErr with `.err_tip()`
Reworked this part.
___
*[`nativelink-worker/src/local_worker.rs` line 358 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uVSr002qEuTceJsnT:-O9xZNo36xz80HeP_TGz:bvdawoe) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/nativelink-worker/src/local_worker.rs#L358)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Do you need to clone here?
</blockquote></details>

If we want to await all actions to be complete we need a way to drop the the complete_msg in the complete_actions fn.
___
*[`nativelink-worker/src/running_actions_manager.rs` line 1893 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uVtNGDPegHIDFOszL:-O9xZiwXEuC9ioV0mJkE:b-7vjdes) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/nativelink-worker/src/running_actions_manager.rs#L1893)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Shouldn't we return/break here?
</blockquote></details>

This is actually the signal that ends the process, so it doesn't matter if we return/break here, since it is only going to be used to check if all running_actions are completed than just ends the whole process.
___
*[`nativelink-worker/src/running_actions_manager.rs` line 1896 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uVjEH2RPNSyfqQMpq:-O9xpU6z6tvbbdFTjytt:b-keonmn) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/nativelink-worker/src/running_actions_manager.rs#L1896)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Please add a comment here why we are using `err` in such a strange way.
</blockquote></details>

Reworked the fn. 
___
*[`nativelink-worker/tests/utils/local_worker_test_utils.rs` line 197 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uVzGG6TAy0H31ibpf:-O9x_LeyEXF4s1tjMlAi:b-el4ivm) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/nativelink-worker/tests/utils/local_worker_test_utils.rs#L197)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Put this at the top of the file and make a comment what it is doing.

Also, the name probably needs more elaboration.
</blockquote></details>

This was my mistake, the number is the capacity and there is a note here: https://docs.rs/tokio/latest/tokio/sync/broadcast/fn.channel.html
`The actual capacity may be greater than the provided `capacity`.`

So setting it to one 1 and renaming it BROADCAST_CAPACITY should work!
___
*[`src/bin/nativelink.rs` line 874 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uWkyo6C-LlKCTDAA6:-O9xlX2m7WwP-VABM543:bkt3y6h) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/src/bin/nativelink.rs#L874)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Please make a comment here explaining the way we are abusing `broadcast::Sender`. (
</blockquote></details>

Removed it it because we actually don't need it here. With the previous approach i tried to returning from all running loops so that the main function exits naturally. With the actual approach this is out of scope, i guess.

However, the server loop approch could be interesting for the graceful shutdown of the scheduler.


<!-- Sent from Reviewable.io -->

2024-10-24 21:51 UTC, allada reviewed
> Reviewed 3 of 5 files at r5.
> Dismissed @adam-singer from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1394)* status: 0 of 1 LGTMs obtained, and 4 of 6 files reviewed, and 9 discussions need to be resolved

___
*[`nativelink-worker/src/local_worker.rs` line 358 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-O9uVGRJ38mJ2RFS8xO_:-OA-CkPKEE2m_2FXvYrM:b-9wvlb2) ([raw file](https://github.com/TraceMachina/nativelink/blob/5166b4a726ccd28c2425dada9cdaed4d5f2f7d27/nativelink-worker/src/local_worker.rs#L358)):*
<details><summary><i>Previously, SchahinRohani (Schahin) wrote…</i></summary><blockquote>

The type of the complete_msg is a `Result<Arc<Sender<()>>, RecvError>`. I can't access the RecvErr with `.err_tip()`
Reworked this part.
</blockquote></details>

Try: `.map_err(|e| make_err!(Code::Internal, "Failed to receive shutdown message: {e:?}"))?;`
___
*[`nativelink-worker/src/running_actions_manager.rs` line 1887 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-OA-VGR4A1waCsMP4_0B:-OA-VGR4A1waCsMP4_0C:b-9g6u29) ([raw file](https://github.com/TraceMachina/nativelink/blob/01c2250bdbe3ff41874e791b761b64912a763641/nativelink-worker/src/running_actions_manager.rs#L1887)):*
> ```XML
>     }
> 
>     async fn complete_actions(&self, complete_msg: Arc<oneshot::Sender<()>>) {
> ```

nit: Please add comment here about why we use `oneshot::Sender`.
___
*[`nativelink-worker/src/running_actions_manager.rs` line 1894 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-OA-DX8A2AnqBM_sxyiV:-OA-DX8A2AnqBM_sxyiW:b-k8hq9u) ([raw file](https://github.com/TraceMachina/nativelink/blob/01c2250bdbe3ff41874e791b761b64912a763641/nativelink-worker/src/running_actions_manager.rs#L1894)):*
> ```XML
>             .await;
>         // Dropping the sender will notify any receivers waiting on it and exit the process.
>         drop(complete_msg);
> ```

nit: This is needless, it happens automatically.
___
*[`src/bin/nativelink.rs` line 1040 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-OA-VKBrC_KCoKFvIdQb:-OA-VKBrC_KCoKFvIdQc:bw1w2t1) ([raw file](https://github.com/TraceMachina/nativelink/blob/01c2250bdbe3ff41874e791b761b64912a763641/src/bin/nativelink.rs#L1040)):*
> ```XML
>             .build()?;
> 
>         let (shutdown_tx, _) = broadcast::channel::<Arc<oneshot::Sender<()>>>(BROADCAST_CAPACITY);
> ```

nit: Please add comment here explaining why we use `oneshot::Sender`.
___
*[`src/bin/nativelink.rs` line 1064 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-OA-VQmN7VHnunDvZHBI:-OA-VQmN7VHnunDvZHBJ:b-r0j2tr) ([raw file](https://github.com/TraceMachina/nativelink/blob/01c2250bdbe3ff41874e791b761b64912a763641/src/bin/nativelink.rs#L1064)):*
> ```XML
>                     .send(complete_tx)
>                     .map_err(|e| eprintln!("Failed to send shutdown signal: {e}"));
>                 if let Err(_e) = complete_rx.await {
> ```

nit: Please add comment here explaining why we don't care about the err.
___
*[`src/bin/nativelink.rs` line 1064 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-OA-Va4c6OPD3wrUvYzq:-OA-Va4c6OPD3wrUvYzr:bjyb1w3) ([raw file](https://github.com/TraceMachina/nativelink/blob/01c2250bdbe3ff41874e791b761b64912a763641/src/bin/nativelink.rs#L1064)):*
> ```XML
>                     .send(complete_tx)
>                     .map_err(|e| eprintln!("Failed to send shutdown signal: {e}"));
>                 if let Err(_e) = complete_rx.await {
> ```

nit: lets just use `let _ = complete_rx.await;` with the comment above... if it fails or passes it is the same thing.


<!-- Sent from Reviewable.io -->

2024-10-24 21:56 UTC, allada reviewed
The `select!` logic needs to be reworked a little to get rid of this.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-:-OA-WyX9-7HreFvysCbD:bfkvdgl)* status: 0 of 1 LGTMs obtained, and 4 of 6 files reviewed, and 9 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-10-28 18:07 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-:-OAJIslG428R5XO-oKS4:bnfp4nl)* status: 1 of 1 LGTMs obtained, and all files reviewed, and 3 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-10-28 19:57 UTC, SchahinRohani reviewed
-@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1394#-:-OAJguxJ9EWEYVA0kAeD:b-sd1e3m)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed



<!-- Sent from Reviewable.io -->

2024-10-28 20:01 UTC, allada approved these changes

2024-10-28 20:02 UTC, allada approved these changes

2024-10-28 20:05 UTC, merged