Fix clippy::used_underscore_binding
TraceMachina/nativelink pull request #1417
Opened 2024-10-17 21:50 UTC by SchahinRohani

## How Has This Been Tested?

`bazel test ...`

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-10-18 15:46 UTC, aaronmondal requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1417)* status: 0 of 1 LGTMs obtained, and all files reviewed, and pending CI: Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, and 1 discussions need to be resolved

___
*[`nativelink-store/src/s3_store.rs` line 175 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1417#-O9VIMxWCs3Dj_qa1I5U:-O9VIMxXC3p-S-wcS827:b-vhxp8x) ([raw file](https://github.com/TraceMachina/nativelink/blob/aba982280353c963ad9632a423775b51f3b052a0/nativelink-store/src/s3_store.rs#L175)):*
> ```XML
>     ) -> Result<ConnectionWithPermit<MaybeHttpsStream<TcpStream>>, Error> {
>         let retry_stream_fn = unfold(self.connector.clone(), move |mut connector| async move {
>             match connector.call(req.clone()).await {
> ```

IIUC the issue here is that the semaphore isn't shared? Is it really correct to remove this then? If it is it probably shouldn't be called `ConnectionWithPermit` anymore.


<!-- Sent from Reviewable.io -->

2024-10-18 21:34 UTC, SchahinRohani reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1417)* status: 0 of 1 LGTMs obtained, and all files reviewed, and pending CI: Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, and 1 discussions need to be resolved

___
*[`nativelink-store/src/s3_store.rs` line 175 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1417#-O9VIMxWCs3Dj_qa1I5U:-O9WTw-UAMHcyo4hJUbA:b-tto513) ([raw file](https://github.com/TraceMachina/nativelink/blob/aba982280353c963ad9632a423775b51f3b052a0/nativelink-store/src/s3_store.rs#L175)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

IIUC the issue here is that the semaphore isn't shared? Is it really correct to remove this then? If it is it probably shouldn't be called `ConnectionWithPermit` anymore.
</blockquote></details>

As i understand, the _permit wasnt used at all, thats why i removed it. 

@allada do you know how to handle this?


<!-- Sent from Reviewable.io -->

2024-10-23 19:46 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1417)* status: 0 of 1 LGTMs obtained, and all files reviewed, and pending CI: Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, and 1 discussions need to be resolved

___
*[`nativelink-store/src/s3_store.rs` line 175 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1417#-O9VIMxWCs3Dj_qa1I5U:-O9uuKRA6EPcQALcrwBz:b-p41dyz) ([raw file](https://github.com/TraceMachina/nativelink/blob/aba982280353c963ad9632a423775b51f3b052a0/nativelink-store/src/s3_store.rs#L175)):*
<details><summary><i>Previously, SchahinRohani (Schahin) wrote…</i></summary><blockquote>

As i understand, the _permit wasnt used at all, thats why i removed it. 

@allada do you know how to handle this?
</blockquote></details>

This is actually used. `SemaphorePermit` is used for it's `drop` function. The semaphore is telling the semaphore counter that there is still a lease out on a file descriptor. When the semaphore is dropped it lets the counter know there's one available again waking up one of the waiters (if there are any).


So, in this case it'll need to have an exception to this linter.


<!-- Sent from Reviewable.io -->

2024-11-04 00:47 UTC, aaronmondal reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1417)* status: 0 of 1 LGTMs obtained, and all files reviewed, and pending CI: Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, and 1 discussions need to be resolved

___
*[`nativelink-store/src/s3_store.rs` line 175 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1417#-O9VIMxWCs3Dj_qa1I5U:-OAocPyL7TKA2i08ElPE:b-m9blg4) ([raw file](https://github.com/TraceMachina/nativelink/blob/aba982280353c963ad9632a423775b51f3b052a0/nativelink-store/src/s3_store.rs#L175)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This is actually used. `SemaphorePermit` is used for it's `drop` function. The semaphore is telling the semaphore counter that there is still a lease out on a file descriptor. When the semaphore is dropped it lets the counter know there's one available again waking up one of the waiters (if there are any).


So, in this case it'll need to have an exception to this linter.
</blockquote></details>

Looks like a bug. If we remove the underscore from the `_permit` we get dead-code warnings from rustc. So in it's current state this really doesn't do anything.


<!-- Sent from Reviewable.io -->

2025-06-10 11:22 UTC, palfrey commented
https://github.com/TraceMachina/nativelink/pull/1819 is a more up-to-date version of this change

2025-07-03 13:35 UTC, closed without merging