Use an empty instance_name in docker compose example
TraceMachina/nativelink pull request #1486
Opened 2024-11-19 19:05 UTC by swarren12

# Description

Previously, the `docker compose` example used a default `instance_name` of "main", which meant that `--remote_instance_name=main` needed to be added to Bazel to get it to work as expected. This can be confusing for people who are just getting started and unfamiliar with all of the available configuration options. Since the value defaults to an empty string if this configuration item isn't provided, using that in the example should make it easier for someone to spin-up.

Fixes #1484

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually

## Checklist

- [x] Updated documentation if needed (n/a)
- [x] Tests added/amended (n/a)
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-11-19 19:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TraceMachina/nativelink?pullRequest=1486) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TraceMachina/nativelink?pullRequest=1486) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TraceMachina/nativelink?pullRequest=1486) it.</sub>

2024-11-21 10:23 UTC, aaronmondal requested changes
Thanks a lot! The failing sanitizer CI job was a flake that shouldn't be affected by this change. If you push an updated PR it should start working again (if it doesn't I can restart it)

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1486#-:-OCDES6b6czwZe9miCo7:b-xnk25j)* status: 0 of 2 LGTMs obtained, and all files reviewed, and pending CI: asan / ubuntu-22.04, and 4 discussions need to be resolved

___
*[`.bazelrc` line 36 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1486#-OCDE7PJ4XxyI1wqKZU_:-OCDE7PJ4XxyI1wqKZUa:bf8ilwu) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8c45d44fc0cf91215d1d0cbd39a53349a068403/.bazelrc#L36)):*
> ```
> build:debug -c dbg
> 
> build:self_test --remote_instance_name=
> ```

I believe we can remove this line entirely now.
___
*[`.bazelrc` line 40 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1486#-OCDEBIN54oD6V-midnA:-OCDEBIN54oD6V-midnB:buo9nmt) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8c45d44fc0cf91215d1d0cbd39a53349a068403/.bazelrc#L40)):*
> ```
> 
> build:self_execute --remote_executor=grpc://127.0.0.1:50052
> build:self_execute --remote_instance_name=
> ```

Same here
___
*[`.github/workflows/main.yml` line 162 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1486#-OCDEEymEuU8l54HFc_0:-OCDEEymEuU8l54HFc_1:bkkjs1q) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8c45d44fc0cf91215d1d0cbd39a53349a068403/.github/workflows/main.yml#L162)):*
> ```YAML
>           bazel clean && \
>           bazel test //... \
>           --remote_instance_name= \
> ```

And here
___
*[`.github/workflows/main.yml` line 170 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1486#-OCDEDFVCNSJCjJer2pn:-OCDEDFVCNSJCjJer2po:b-tg1clw) ([raw file](https://github.com/TraceMachina/nativelink/blob/a8c45d44fc0cf91215d1d0cbd39a53349a068403/.github/workflows/main.yml#L170)):*
> ```YAML
>           bazel clean && \
>           bazel test //... \
>           --remote_instance_name= \
> ```

And here :D


<!-- Sent from Reviewable.io -->

2024-11-21 12:27 UTC, aaronmondal approved these changes
nit: Remember also updating the README: https://github.com/TraceMachina/nativelink/blob/main/deployment-examples/docker-compose/README.md#docker-setup


<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

+@SchahinRohani 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1486#-:-OCDg8wy2E8q3aWZ9f4E:bw8lklo)* status: 1 of 2 LGTMs obtained, and all files reviewed, and pending CI: Bazel Dev / macos-13 (waiting on @SchahinRohani)



<!-- Sent from Reviewable.io -->

2024-11-21 17:08 UTC, SchahinRohani approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1486#-:-OCEgF-5-21P5Q3g2dxe:bnfp4nl)* status: 2 of 2 LGTMs obtained, and all files reviewed, and pending CI: Remote / large-ubuntu-22.04, windows-2022 / stable



<!-- Sent from Reviewable.io -->

2024-11-25 20:26 UTC, aaronmondal approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1486)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained, and all files reviewed



<!-- Sent from Reviewable.io -->

2024-11-25 20:26 UTC, merged

2024-11-25 20:27 UTC, aaronmondal commented
Whoops, sry this took so long to merge. It slipped through my notifications :sweat_smile: