Implement Local Remote Execution for Rust
TraceMachina/nativelink pull request #1510
Opened 2024-12-02 22:23 UTC by aaronmondal

This change implements ~40 Rust toolchains that reuse Nix's executables and make them available via Bazel.

The new setup is fully reproducible, supports musl and glibc and works from all nix-supported hosts to all sensible crosscompilation targets seamlessly through remote and local execution.

For instance, you can now run this command on a MacOS host to build a statically linked executable for x86_64-linux on a remote arm worker:

```bash
bazel build \
    nativelink \
    --extra_execution_platforms=@local-remote-execution//lre-rs:aarch64-unknown-linux-gnu \
    --platforms=@local-remote-execution//lre-rs:x86_64-unknown-linux-musl
```

2024-12-11 01:18 UTC, aaronmondal reviewed
+@SchahinRohani +@allada

cc @kubevalet The relevant changes for the cloud are the addition of the "lre-rs" field in the scheduler and cas here:
- https://github.com/TraceMachina/nativelink/pull/1510/files#diff-de0cfdee9e6995d07ae45d7469bbcebb53a26fed8e5a12052c953da7086cee87
- https://github.com/TraceMachina/nativelink/pull/1510/files#diff-e9a419d385a5eed08ea9f70b9682f7e4241d283e60b89e1058c28bdfdad57d1a

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-:-ODnHP8aClQ-eCB27bZv:be6f4mq)* status: 0 of 2 LGTMs obtained, and 0 of 38 files reviewed, and pending CI: Cargo Dev / macos-13, Installation / macos-13 (waiting on @allada and @SchahinRohani)



<!-- Sent from Reviewable.io -->

2024-12-11 12:02 UTC, aaronmondal reviewed
cc @bclark8923 @MarcusSorealheis

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-:-ODp_uCoEiHg6O5EZrDN:bphc9ei)* status: 0 of 2 LGTMs obtained, and 0 of 38 files reviewed (waiting on @allada and @SchahinRohani)



<!-- Sent from Reviewable.io -->

2024-12-11 12:14 UTC, SchahinRohani approved these changes
Nothing other than great work!
Also, a clean and modular implementation!


<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-:-ODpaTvU2BTruRtKojTj:bki8eez)* status: 1 of 2 LGTMs obtained, and all files reviewed (waiting on @allada)



<!-- Sent from Reviewable.io -->

2024-12-11 19:59 UTC, allada requested changes
> Reviewed 8 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1510)* status: 1 of 2 LGTMs obtained, and all files reviewed, and 4 discussions need to be resolved

___
*[`local-remote-execution/rust/BUILD.bazel` line 77 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-ODrHP7J1velmiEDVfUB:-ODrHP7J1velmiEDVfUC:b-9y1d5v) ([raw file](https://github.com/TraceMachina/nativelink/blob/2a92b5a96d04fffc29f4d5a4531338525bceb95d/local-remote-execution/rust/BUILD.bazel#L77)):*
> ```Starlark
>         clippy_driver = "@lre-rs-{}-{}//:clippy-driver".format(channel, nix_system),
>         debug_info = {
>             "dbg": "2",
> ```

nit: Lets document on why these defaults.
___
*[`local-remote-execution/rust/BUILD.bazel` line 109 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-ODrHYNQ9Hi7mFz1MkME:-ODrHYNQ9Hi7mFz1MkMF:b-ngcblz) ([raw file](https://github.com/TraceMachina/nativelink/blob/2a92b5a96d04fffc29f4d5a4531338525bceb95d/local-remote-execution/rust/BUILD.bazel#L109)):*
> ```Starlark
>         # llvm_tools,
>         opt_level = {
>             "dbg": "0",
> ```

nit: ditto...

Also, IIRC `fastbuild` is opt=1
___
*[`local-remote-execution/rust/BUILD.bazel` line 123 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-ODrHhEV8tC2ij34CvoB:-ODrHhEV8tC2ij34CvoC:b-ihyr0e) ([raw file](https://github.com/TraceMachina/nativelink/blob/2a92b5a96d04fffc29f4d5a4531338525bceb95d/local-remote-execution/rust/BUILD.bazel#L123)):*
> ```Starlark
>             {
>                 "@local-remote-execution//libc:glibc": [
>                     "-fuse-ld=mold",
> ```

Don't we want to include these libs as part of the toolchain and/or put the full paths?
___
*[`local-remote-execution/overlays/lre-rs.nix` line 152 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-ODrGx_pCUlXbvf56lE1:-ODrGx_q3sRxxCPRikde:bbd66xj) ([raw file](https://github.com/TraceMachina/nativelink/blob/2a92b5a96d04fffc29f4d5a4531338525bceb95d/local-remote-execution/overlays/lre-rs.nix#L152)):*
> ```Nix
>         name = "aarch64-apple-darwin",
>         exec_properties = {
>             # nix eval .#packages.aarch64-darwin.nativelink-worker-lre-rs.imageTag
> ```

nit: Why duplicate this as it is listed one line below on all of these?


<!-- Sent from Reviewable.io -->

2024-12-11 22:28 UTC, SchahinRohani submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1510)* status: 1 of 2 LGTMs obtained, and 37 of 38 files reviewed, and pending CI: Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Coverage, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / lre-cc / ubuntu-24.04, Local / lre-rs / macos-14, Local / lre-rs / ubuntu-24.04, NativeLink.com Cloud / Remote Cache / macos-14, NativeLink.com Cloud / Remote Cache / ubuntu-24.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / lre-cc / large-ubuntu-22.04, Remote / lre-rs / large-ubuntu-22.04, Web Platform Deployment / macos-14, Web Platform Deployment / ubuntu-24.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 6 discussions need to be resolved (waiting on @allada)

___
*[`web/platform/src/content/docs/docs/contribute/bazel.mdx` line 29 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-ODrpF4_05bhigmszwBN:-ODrpF4_05bhigmszwBO:b-7k2j53) ([raw file](https://github.com/TraceMachina/nativelink/blob/110af23965777068a1880121aeb1228dce75d358/web/platform/src/content/docs/docs/contribute/bazel.mdx#L29)):*
> ```MDX
>     ```sh
>     bazel run nativelink -- \
>         $(pwd)/nativelink-config/examples/basic_cas.json
> ```

this should be `/basic_cas.json5`
___
*[`web/platform/src/content/docs/docs/contribute/bazel.mdx` line 58 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-ODrp5aB1VoBjoy5kCpB:-ODrp5aB1VoBjoy5kCpC:bb7eybp) ([raw file](https://github.com/TraceMachina/nativelink/blob/110af23965777068a1880121aeb1228dce75d358/web/platform/src/content/docs/docs/contribute/bazel.mdx#L58)):*
> ```MDX
>     ```sh
>     bazel run -c opt --extra_toolchains=@rust_toolchains//:all nativelink -- \
>         $(pwd)/nativelink-config/examples/basic_cas.json
> ```

dito


<!-- Sent from Reviewable.io -->

2024-12-11 22:33 UTC, aaronmondal reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1510)* status: 1 of 2 LGTMs obtained, and 36 of 38 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Coverage, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / lre-cc / ubuntu-24.04, Local / lre-rs / macos-14, Local / lre-rs / ubuntu-24.04, NativeLink.com Cloud / Remote Cache / macos-14, NativeLink.com Cloud / Remote Cache / ubuntu-24.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / lre-cc / large-ubuntu-22.04, Remote / lre-rs / large-ubuntu-22.04, Web Platform Deployment / macos-14, Web Platform Deployment / ubuntu-24.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 4 discussions need to be resolved (waiting on @allada)

___
*[`local-remote-execution/overlays/lre-rs.nix` line 152 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-ODrGx_pCUlXbvf56lE1:-ODrgTxO7hTxq2tSD02t:b962p1y) ([raw file](https://github.com/TraceMachina/nativelink/blob/2a92b5a96d04fffc29f4d5a4531338525bceb95d/local-remote-execution/overlays/lre-rs.nix#L152)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Why duplicate this as it is listed one line below on all of these?
</blockquote></details>

This comment is there so that the generated file shows how to get this tag: https://github.com/TraceMachina/nativelink/pull/1510/files#diff-5a46d2c5053d31d4bf9ad698fbfb1187e54d6131385a01c8c502ae8ab838dff3

The setup automatically adds these flake outputs when the lre flake module is enabled, so we can be sure that these paths are correct.

The idea is that e.g. cloud users only need to look at the platform definitions on the Bazel side to figure out how to get these hashes without going into the nix generator code.
___
*[`local-remote-execution/rust/BUILD.bazel` line 77 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-ODrHP7J1velmiEDVfUB:-ODro8xu0R-j2OwXHK_z:b7ew4mh) ([raw file](https://github.com/TraceMachina/nativelink/blob/2a92b5a96d04fffc29f4d5a4531338525bceb95d/local-remote-execution/rust/BUILD.bazel#L77)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Lets document on why these defaults.
</blockquote></details>

Done. These are `rules_rust`'s default, but I've already experimented with adjustments to these and we'll likely want to change them in the future.
___
*[`local-remote-execution/rust/BUILD.bazel` line 109 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-ODrHYNQ9Hi7mFz1MkME:-ODroYU_8r4eqIriGXf6:bpbj1xd) ([raw file](https://github.com/TraceMachina/nativelink/blob/2a92b5a96d04fffc29f4d5a4531338525bceb95d/local-remote-execution/rust/BUILD.bazel#L109)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: ditto...

Also, IIRC `fastbuild` is opt=1
</blockquote></details>

Done. Left a comment that this is the default. This seems to be a deliberate choice by rules_rust. It seems better to investigate further before we deviate from this.

I already noticed though that since we have much more scaling we can probably start doing something like `codegen-units=1` for opt builds in the future as the Bazel builds with mold seem fast enough to handle it. For now we can still override the behavior via the `extra_rustc_flags` setting in a `.bazelrc`.
___
*[`local-remote-execution/rust/BUILD.bazel` line 123 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-ODrHhEV8tC2ij34CvoB:-ODrhFKI2ke44zlD89Nw:b9lxy19) ([raw file](https://github.com/TraceMachina/nativelink/blob/2a92b5a96d04fffc29f4d5a4531338525bceb95d/local-remote-execution/rust/BUILD.bazel#L123)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Don't we want to include these libs as part of the toolchain and/or put the full paths?
</blockquote></details>

Ah this is a tricky one. The actual search paths to these aren't actually specified, but set by the linker which sets them via (capital) `-L`. In a wrapper.

You can inspect this behavior like this:

```bash
bazel build local-remote-execution/examples:lre-rs --platforms=@local-remote-execution//rust/platforms:x86_64-unknown-linux-gnu


INFO: Invocation ID: 9a4841c6-358b-4ec4-b1d8-3429f5216c2b
WARNING: Build option --platforms has changed, discarding analysis cache (this can be expensive, see https://bazel.build/advanced/performance/iteration-speed).
INFO: Analyzed target //local-remote-execution/examples:lre-rs (0 packages loaded, 1822 targets configured).
INFO: From Compiling Rust bin lre-rs (1 files):
LC_ALL="C" PATH="bazel-out/k8-fastbuild/bin/external/local-remote-execution~/rust/rust-stable-x86_64-linux_impl/lib/rustlib/x86_64-unknown-linux-gnu/bin:/nix/store/kl18sr2a45vyyqv39clrjclmadacy9mc-rust-default-1.82.0/lib/rustlib/x86_64-unknown-linux-gnu/bin:/nix/store/kl18sr2a45vyyqv39clrjclmadacy9mc-rust-default-1.82.0/lib/rustlib/x86_64-unknown-
linux-gnu/bin:/bin:/usr/bin:/usr/local/bin" VSLANG="1033" "/nix/store/lw8g7lpw6rwjmz6wxp2grzaixlvn02a7-customClang/bin/customClang" "-m64" "/tmp/rustcByxKBc/symbols.o" "bazel-out/k8-fastbuild/bin/local-remote-execution/examples/lre_rs.lre_rs.c59005c95ffd25cf-cgu.0.rcgu.o" "bazel-out/k8-fastbuild/bin/local-remote-execution/examples/lre_rs.936mcif4h
kbf22dehgh7mxezr.rcgu.o" "-Wl,--as-needed" "-Wl,-Bstatic" "/nix/store/8xz2aamlsz0136jzlv15v9cyjdy8kd5l-rust-std-1.82.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-22be60875a4ac8d7.rlib" "/nix/store/8xz2aamlsz0136jzlv15v9cyjdy8kd5l-rust-std-1.82.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpani
c_unwind-4b832a03827ff95e.rlib" "/nix/store/8xz2aamlsz0136jzlv15v9cyjdy8kd5l-rust-std-1.82.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-a25e7f31e2204719.rlib" "/nix/store/8xz2aamlsz0136jzlv15v9cyjdy8kd5l-rust-std-1.82.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-1f1858edbb50ccb5.rli
b" "/nix/store/8xz2aamlsz0136jzlv15v9cyjdy8kd5l-rust-std-1.82.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-1319b75889377807.rlib" "/nix/store/8xz2aamlsz0136jzlv15v9cyjdy8kd5l-rust-std-1.82.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-c9972d847170eb93.rlib" "/nix/store/8xz2aamlsz01
36jzlv15v9cyjdy8kd5l-rust-std-1.82.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-0868a75d0b80f801.rlib" "/nix/store/8xz2aamlsz0136jzlv15v9cyjdy8kd5l-rust-std-1.82.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-f4254a923640cbea.rlib" "/nix/store/8xz2aamlsz0136jzlv15v9cyjdy8k
d5l-rust-std-1.82.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-f21de9b2e2c92770.rlib" "/nix/store/8xz2aamlsz0136jzlv15v9cyjdy8kd5l-rust-std-1.82.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-cf868f78468d45dd.rlib" "/nix/store/8xz2aamlsz0136jzlv15v9cyjdy8kd5l-rus
t-std-1.82.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-cce9a55233783113.rlib" "/nix/store/8xz2aamlsz0136jzlv15v9cyjdy8kd5l-rust-std-1.82.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-6ef1f692f91f321e.rlib" "/nix/store/8xz2aamlsz0136jzlv15v9cyjdy8kd5l-rust-std-1.82.0-x86_64-unkno
wn-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-d2b4a3bc57672e2c.rlib" "/nix/store/8xz2aamlsz0136jzlv15v9cyjdy8kd5l-rust-std-1.82.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if- [...]

2024-12-11 22:33 UTC, SchahinRohani reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1510)* status: 1 of 2 LGTMs obtained, and 37 of 38 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Coverage, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / lre-cc / ubuntu-24.04, Local / lre-rs / macos-14, Local / lre-rs / ubuntu-24.04, NativeLink.com Cloud / Remote Cache / macos-14, NativeLink.com Cloud / Remote Cache / ubuntu-24.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / lre-cc / large-ubuntu-22.04, Remote / lre-rs / large-ubuntu-22.04, Web Platform Deployment / macos-14, Web Platform Deployment / ubuntu-24.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 2 discussions need to be resolved (waiting on @allada)



<!-- Sent from Reviewable.io -->

2024-12-12 01:01 UTC, MarcusSorealheis reviewed
The biggest gap that I see here is the absence of a README that explains clearly how to use this addition. I understand it will be used automatically, but we need to spell it out for our users and there needs to be a documentation page that ales it easy to exploit. 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-:-ODsN8N_73uyKaOnVsxF:b-vuo1op)* status: 1 of 2 LGTMs obtained, and 37 of 38 files reviewed, and pending CI: docker-compose-compiles-nativelink (22.04), and 2 discussions need to be resolved (waiting on @allada)



<!-- Sent from Reviewable.io -->

2024-12-12 18:24 UTC, aaronmondal reviewed
> The biggest gap that I see here is the absence of a README that explains clearly how to use this addition. I understand it will be used automatically, but we need to spell it out for our users and there needs to be a documentation page that ales it easy to exploit.

I agree, but I'd prefer to do this in a separate change so that I can create uniform docs between `lre-cc` and `lre-rs` without expanding the (already pretty massive) scope of this PR further. Definitely will need docs and example setups though.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-:-ODw5F8e95LVkplMSH5x:b-9qq6pw)* status: 1 of 2 LGTMs obtained, and 37 of 43 files reviewed, and pending CI: Analyze (python), Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Coverage, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / lre-cc / ubuntu-24.04, Local / lre-rs / macos-14, Local / lre-rs / ubuntu-24.04, NativeLink.com Cloud / Remote Cache / macos-14, NativeLink.com Cloud / Remote Cache / ubuntu-24.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / lre-cc / large-ubuntu-22.04, Remote / lre-rs / large-ubuntu-22.04, Web Platform Deployment / macos-14, Web Platform Deployment / ubuntu-24.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 2 discussions need to be resolved (waiting on @allada)



<!-- Sent from Reviewable.io -->

2024-12-14 00:39 UTC, aaronmondal reviewed
> Reviewed 34 of 38 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 5 of 5 files at r4, 3 of 3 files at r5, all commit messages.
> Dismissed @allada from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1510)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained, and all files reviewed

___
*[`.github/workflows/main.yml` line 162 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-OE-zsjV0DGu-Vcevllb:-OE1_lTW6KufuCxfr8uK:b7agq2) ([raw file](https://github.com/TraceMachina/nativelink/blob/abdde8b042d166aeb01ad1419d045059c0291038/.github/workflows/main.yml#L162)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

These should probably not use this, since this workflow is testing docker compose and we'd rather test the default toolchains before anything else.
</blockquote></details>

Done. This is actually correct as using `rules_rust`'s default toolchains requires explicitly registering these. Previously we did this via the `.bazelrc` but since we have multiple toolchain configurations now it's no longer possible to do this as it would override the `lre-rs` toolchain configuration. I've fixed the example in the docker-compose readme and added an explainer.
___
*[`local-remote-execution/examples/BUILD.bazel` line 8 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1510#-OE0-QgYC8kptOM-C_h5:-OE1aUGk0GGWtDnlc9xa:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/abdde8b042d166aeb01ad1419d045059c0291038/local-remote-execution/examples/BUILD.bazel#L8)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

can we remove verbose? It makes the stderr/stdout really noisy for me.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-14 00:41 UTC, merged