Add example for Reclient.
TraceMachina/nativelink pull request #286
Opened 2023-09-15 12:37 UTC by chrisstaite-menlo

2023-09-15 18:13 UTC, allada requested changes
Thanks for doing this!

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-:-NeP21WZBT1JK64ZNXSW:bxgavm9)* status: all files reviewed, 10 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`deployment-examples/docker-compose-reclient/docker-compose.yml` line 19 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeP0uNQ8HRt1KUmuScV:-NeP0uNQ8HRt1KUmuScW:b-9nauyw) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/docker-compose.yml#L19)):*
> ```YAML
> services:
>   turbo_cache_local_cas:
>     image: allada/turbo-cache:latest
> ```

nit: can we use "extends" similar to how it's done here?
https://github.com/TraceMachina/turbo-cache/pull/267/files#diff-419ec2b388f508c75e39af538e03dd9959467d6bea1bf45b8fcda943687d27b3R19
___
*[`deployment-examples/docker-compose-reclient/docker-compose.yml` line 67 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeP1CbZ5a3W9oa1zwko:-NeP1CbZ5a3W9oa1zwkp:b-rxmj99) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/docker-compose.yml#L67)):*
> ```YAML
>         target: /var/run/docker.sock
>     environment:
>       RUST_LOG: info
> ```

fyi: this will certainly slow everything down due to the amount of logs being generated. I would suggest `warn`.

It might be worth for me to spend time evaluating what is "info" and what is "debug", right now they are mixed.
___
*[`deployment-examples/docker-compose-reclient/README.md` line 11 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeOwvauDlOk_tMfSY4l:-NeOwvav7JnXOKw5661r:b5sswku) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/README.md#L11)):*
> ```Markdown
> ## Roles
> 
> There a number of roles required to perform a Reclient set up:
> ```

nit: `There are`
___
*[`deployment-examples/docker-compose-reclient/README.md` line 14 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeP25VeD9Tleg6BGGy2:-NeP25VeD9Tleg6BGGy3:b-dvchjc) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/README.md#L14)):*
> ```Markdown
> 
>  - Turbo Cache Scheduler - The Turbo Cache instance that communicates with the
>    Goma proxy and handles scheduling of tasks to workers within the Turbo Cache
> ```

Doesn't REclient replace goma?
___
*[`deployment-examples/docker-compose-reclient/README.md` line 39 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeOx_iQ9tQYkoqq0RB2:-NeOx_iQ9tQYkoqq0RB3:b-qsncue) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/README.md#L39)):*
> ```Markdown
> # Required because the default is projects/rbe-chrome-untrusted/instances/default_instance
> # and we do not support instance names with / in currently.
> export RBE_instance=main
> ```

nit: I'd remove this as it's about to be fixed.
___
*[`deployment-examples/docker-compose-reclient/README.md` line 52 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeOyI6zB_4eQYr0PPJM:-NeOyI6zB_4eQYr0PPJN:b-gtqve7) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/README.md#L52)):*
> ```Markdown
> 
> Now that the environment is set up you simply need to enable it for your
> Chromium build by modifying your `args.gn` file to contain:
> ```

note: You can also use:
```sh
gn gen --args="use_goma=true rbe_cfg_dir=\"../../buildtools/reclient_cfgs/linux\"" out/Default
```
___
*[`deployment-examples/docker-compose-reclient/run_in_container.sh` line 13 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeOycvM0uZMkdpv61kz:-NeOycvM0uZMkdpv61l-:b9qibya) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/run_in_container.sh#L13)):*
> ```Shell
>     WORK_DIRECTORY=$(pwd | cut -c25-94)
>     WORKING_DIRECTORY=$(pwd | cut -c95-)
>     exec docker run --rm -w /work${WORKING_DIRECTORY} -v ${HOST_ROOT}${WORK_DIRECTORY}:/work $(echo "$CONTAINER" | cut -c10-) /bin/env "$@"
> ```

oh the memories.

It turns out this has a high chance of causing spurious errors (from experience). We got around these random docker failures by running a script in docker that would collect the exit code and write it to a file then outside docker read the file. If the file was not written too, it'd kill/restart the worker and inform the scheduler to disconnect all future work (because it means docker, kernel or other system failure if no exit code).

no action, but FYI.
___
*[`deployment-examples/docker-compose-reclient/run_in_container.sh` line 13 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeOzjFG04JPTuJbXhWU:-NeOzjFG04JPTuJbXhWV:bk0bvfx) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/run_in_container.sh#L13)):*
> ```Shell
>     WORK_DIRECTORY=$(pwd | cut -c25-94)
>     WORKING_DIRECTORY=$(pwd | cut -c95-)
>     exec docker run --rm -w /work${WORKING_DIRECTORY} -v ${HOST_ROOT}${WORK_DIRECTORY}:/work $(echo "$CONTAINER" | cut -c10-) /bin/env "$@"
> ```

nit: Shouldn't it be `cut -c9-`?
___
*[`deployment-examples/docker-compose-reclient/worker.json` line 55 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeP1k_vE2pu5g5zrYuM:-NeP1k_vE2pu5g5zrYuN:byef9q8) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/worker.json#L55)):*
> ```JSON
>         },
>         // Need to specify a placeholder here otherwise Priority scheduling does
>         // not work.
> ```

hmmm, is this a bug? Shouldn't we just be able to pass an empty array?

If not can we file a ticket and reference it?
___
*[`deployment-examples/docker-compose-reclient/worker_precondition_script.sh` line 3 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeP1TFCCtcgxvJ5Ozck:-NeP1TFCCtcgxvJ5Ozcl:b5srm4x) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/worker_precondition_script.sh#L3)):*
> ```Shell
> #!/bin/sh
> set -eu
> ```

nit: Can we add a comment here stating when and how this file runs?
___
*[`deployment-examples/docker-compose-reclient/worker_precondition_script.sh` line 5 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeP03laCRdkxs3SZoW4:-NeP03laCRdkxs3SZoW5:b-7kooul) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/worker_precondition_script.sh#L5)):*
> ```Shell
> 
> AVAILABLE_MEMORY_KB=$(awk '/MemAvailable/ { printf "%d \n", $2 }' /proc/meminfo);
> # At least 2Gb of RAM currently available
> ```

nit: period.


<!-- Sent from Reviewable.io -->

2023-09-18 09:11 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/286)* status: all files reviewed, 10 unresolved discussions (waiting on @allada)

___
*[`deployment-examples/docker-compose-reclient/docker-compose.yml` line 67 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeP1CbZ5a3W9oa1zwko:-NebXNrV-YEkaw0wvZe8:bswsgra) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/docker-compose.yml#L67)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

fyi: this will certainly slow everything down due to the amount of logs being generated. I would suggest `warn`.

It might be worth for me to spend time evaluating what is "info" and what is "debug", right now they are mixed.
</blockquote></details>

Yeah, this is a lay-over from debugging that I forgot to remove.
___
*[`deployment-examples/docker-compose-reclient/README.md` line 14 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeP25VeD9Tleg6BGGy2:-NebXSKCEMLIWVCrLQSn:bj9ku4p) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/README.md#L14)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Doesn't REclient replace goma?
</blockquote></details>

Can you tell this was copy-amended?
___
*[`deployment-examples/docker-compose-reclient/README.md` line 39 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeOx_iQ9tQYkoqq0RB2:-NebXV-zEk-MJt0MqzF4:b-fvitlk) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/README.md#L39)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: I'd remove this as it's about to be fixed.
</blockquote></details>

It was really just a reminder to me to remove it once it is fixed.
___
*[`deployment-examples/docker-compose-reclient/run_in_container.sh` line 13 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeOycvM0uZMkdpv61kz:-NebX_OL6xHpA_1KHRdd:bia1ylk) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/run_in_container.sh#L13)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

oh the memories.

It turns out this has a high chance of causing spurious errors (from experience). We got around these random docker failures by running a script in docker that would collect the exit code and write it to a file then outside docker read the file. If the file was not written too, it'd kill/restart the worker and inform the scheduler to disconnect all future work (because it means docker, kernel or other system failure if no exit code).

no action, but FYI.
</blockquote></details>

Yeah, I've been there too... I hope this doesn't come back to bite me
___
*[`deployment-examples/docker-compose-reclient/run_in_container.sh` line 13 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeOzjFG04JPTuJbXhWU:-NebXgAd8dqmbTNiVYD1:bj8y4lp) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/run_in_container.sh#L13)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Shouldn't it be `cut -c9-`?
</blockquote></details>

I don't think so, it appears to be working fine for me.
___
*[`deployment-examples/docker-compose-reclient/worker.json` line 55 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeP1k_vE2pu5g5zrYuM:-NebYdonDnQz0FuYpXvL:bwd3aww) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/worker.json#L55)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

hmmm, is this a bug? Shouldn't we just be able to pass an empty array?

If not can we file a ticket and reference it?
</blockquote></details>

Yeah, I wasn't sure to be honest how it was supposed to work.


<!-- Sent from Reviewable.io -->

2023-09-26 23:44 UTC, allada commented
Did you forget to push the changes? It looks nearly ready to land.

2023-09-27 07:19 UTC, chrisstaite-menlo commented
Mostly I've been busy sorting other stuff to get this over the line.  But also, there's a few glitches with set-up that I wanted to iron out so the README just worked out of the box that I haven't had time to finalise yet.

2023-10-11 13:56 UTC, chrisstaite-menlo reviewed
I've updated the README such that it actually works now.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-:-NgU-I0x6HcdjecfU3_L:ba1bu6u)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @allada)

___
*[`deployment-examples/docker-compose-reclient/README.md` line 52 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/286#-NeOyI6zB_4eQYr0PPJM:-NgU-bnJ-zRvvMG4_Obd:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/09510bfef032ab88549fd9f25e9f3eceeea43052/deployment-examples/docker-compose-reclient/README.md#L52)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

note: You can also use:
```sh
gn gen --args="use_goma=true rbe_cfg_dir=\"../../buildtools/reclient_cfgs/linux\"" out/Default
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-12 02:49 UTC, allada commented
Is it ok to defer this and have @blakehatch or @aaronmondal do it?

They are going to be ramping up over the next week and this would even be better to have completely fresh eyes on it.

2023-10-19 08:26 UTC, chrisstaite-menlo commented
Apparently `extends` support doesn't exist in docker-compose anymore?? docker/compose#4315

2023-10-19 15:15 UTC, allada reviewed
> Reviewed 1 of 4 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/286)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @chrisstaite-menlo)



<!-- Sent from Reviewable.io -->

2023-12-04 09:39 UTC, chrisstaite-menlo commented
Little bump on this.





<!-- Sent from Reviewable.io -->

2023-12-05 04:16 UTC, allada reviewed
How about +@adam-singer why don't you take a look at this first, then I'll do one final review. Hopefully this will help you get some knowledge on deployment examples?

> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/286#-:-NksAyvj6xexcR_ihcLj:buo9k34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adam-singer)



<!-- Sent from Reviewable.io -->

2023-12-06 06:51 UTC, adam-singer requested changes
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/286)* status: all files reviewed, 9 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`deployment-examples/docker-compose-reclient/docker-compose.yml` line 1 at r4](https://reviewable.io/reviews/tracemachina/native-link/286#-NkxtDlCEE-Feflxb0LB:-NkxtDlCEE-Feflxb0LC:bwo4n7v) ([raw file](https://github.com/tracemachina/native-link/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/docker-compose.yml#L1)):*
> ```YAML
> # Copyright 2023 The Turbo Cache Authors. All rights reserved.
> ```

Mentioned a few times below, the project name has recently changed, could we apply those changes to this patch "Turbo Cache" -> "Native Link"
___
*[`deployment-examples/docker-compose-reclient/docker-compose.yml` line 19 at r4](https://reviewable.io/reviews/tracemachina/native-link/286#-NkxsnL07NhodzQepy5l:-NkxsnL07NhodzQepy5m:beq7d94) ([raw file](https://github.com/tracemachina/native-link/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/docker-compose.yml#L19)):*
> ```YAML
> services:
>   turbo_cache_local_cas:
>     image: allada/turbo-cache:latest
> ```

@allada do we have a different/canonical location for this image?
___
*[`deployment-examples/docker-compose-reclient/README.md` line 13 at r4](https://reviewable.io/reviews/tracemachina/native-link/286#-NkxjqLK88xqZA7Fv92F:-NkxjqLK88xqZA7Fv92G:biwog2e) ([raw file](https://github.com/tracemachina/native-link/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/README.md#L13)):*
> ```Markdown
> There are a number of roles required to perform a Reclient set up:
> 
>  - Turbo Cache Scheduler - The Turbo Cache instance that handles all of the
> ```

The project has been renamed to "Native Link", lets word towards that
___
*[`deployment-examples/docker-compose-reclient/README.md` line 49 at r4](https://reviewable.io/reviews/tracemachina/native-link/286#-NkxsCxj7azNmbvJ2wU2:-NkxsCxj7azNmbvJ2wU3:bm46jos) ([raw file](https://github.com/tracemachina/native-link/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/README.md#L49)):*
> ```Markdown
> fail_early_min_fallback_ratio=0.5
> deps_cache_max_mb=256
> # TODO(b/276727504) Re-enable once noop build shutdown time bug is fixed
> ```

This looks like an internal bug link, can we remove or specific a bit more what the bug is related to?
___
*[`deployment-examples/docker-compose-reclient/run_in_container.sh` line 15 at r4](https://reviewable.io/reviews/tracemachina/native-link/286#-NkxrWhV1O5kQGMsp_HO:-NkxrWhV1O5kQGMsp_HP:bpwgrsl) ([raw file](https://github.com/tracemachina/native-link/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/run_in_container.sh#L15)):*
> ```Shell
>     # on the host and we need to account for that.  This strips off the
>     # /root/.cache/turbo-cache and that is populated with $HOST_ROOT from the
>     # worker.json which is then populated by ${TURBO_CACHE_DIR} from the
> ```

`TURBO_CACHE_DIR` -> `NATIVE_LINK_DIR`
___
*[`deployment-examples/docker-compose-reclient/run_in_container.sh` line 17 at r4](https://reviewable.io/reviews/tracemachina/native-link/286#-Nkxrv4M856yd2vMpS_Z:-Nkxrv4M856yd2vMpS__:bhi1a6d) ([raw file](https://github.com/tracemachina/native-link/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/run_in_container.sh#L17)):*
> ```Shell
>     # worker.json which is then populated by ${TURBO_CACHE_DIR} from the
>     # docker-compose.yml.
>     WORK_DIRECTORY=$(pwd | cut -c25-94)
> ```

for the pipes to `cut` what kind of assumptions are those character ranges making? It is unclear what they might be
___
*[`deployment-examples/docker-compose-reclient/worker.json` line 13 at r4](https://reviewable.io/reviews/tracemachina/native-link/286#-NkxkG03B6Ket0NhTrky:-NkxkG03B6Ket0NhTrkz:bb1sl0f) ([raw file](https://github.com/tracemachina/native-link/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/worker.json#L13)):*
> ```JSON
>       "grpc": {
>         "instance_name": "main",
>         "endpoints": ["grpc://${CAS_ENDPOINT:-127.0.0.1}:50051"],
> ```

Both environment variables are `CAS_ENDPOINT`, is there a situation where we would have a difference between these endpoints and their logical hosts?
___
*[`deployment-examples/docker-compose-reclient/worker.json` line 21 at r4](https://reviewable.io/reviews/tracemachina/native-link/286#-NkxkpGa10mEJJd_Or9z:-NkxkpGa10mEJJd_OrA-:b-oap4e4) ([raw file](https://github.com/tracemachina/native-link/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/worker.json#L21)):*
> ```JSON
>         "fast": {
>           "filesystem": {
>             "content_path": "/root/.cache/turbo-cache/data-worker-test/content_path-cas",
> ```

`turbo-cache` -> `native-link`, same below
___
*[`deployment-examples/docker-compose-reclient/worker.json` line 45 at r4](https://reviewable.io/reviews/tracemachina/native-link/286#-Nkxl0d8ChEedkcF6XwS:-Nkxl0d8ChEedkcF6XwT:bpwgrsl) ([raw file](https://github.com/tracemachina/native-link/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/worker.json#L45)):*
> ```JSON
>       "additional_environment": {
>         "CONTAINER": {"Property": "container-image"},
>         "HOST_ROOT": {"Value": "${TURBO_CACHE_DIR}"},
> ```

`TURBO_CACHE_DIR` -> `NATIVE_LINK_DIR`


<!-- Sent from Reviewable.io -->

2023-12-12 11:14 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/286)* status: all files reviewed, 9 unresolved discussions (waiting on @adam-singer)

___
*[`deployment-examples/docker-compose-reclient/docker-compose.yml` line 1 at r4](https://reviewable.io/reviews/tracemachina/nativelink/286#-NkxtDlCEE-Feflxb0LB:-NlSib5V7UE5v8-Zvs5M:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/docker-compose.yml#L1)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Mentioned a few times below, the project name has recently changed, could we apply those changes to this patch "Turbo Cache" -> "Native Link"
</blockquote></details>

Done.
___
*[`deployment-examples/docker-compose-reclient/README.md` line 13 at r4](https://reviewable.io/reviews/tracemachina/nativelink/286#-NkxjqLK88xqZA7Fv92F:-NlSijo38oeqGvtg874J:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/README.md#L13)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

The project has been renamed to "Native Link", lets word towards that
</blockquote></details>

Done.
___
*[`deployment-examples/docker-compose-reclient/README.md` line 49 at r4](https://reviewable.io/reviews/tracemachina/nativelink/286#-NkxsCxj7azNmbvJ2wU2:-NlSikbd64SJoah3I8ZR:b-v4rpbc) ([raw file](https://github.com/tracemachina/nativelink/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/README.md#L49)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

This looks like an internal bug link, can we remove or specific a bit more what the bug is related to?
</blockquote></details>

This is a Chromium bug link, those that work on Chromium will understand and there's no reason to be using this if you don't work on Chromium.
___
*[`deployment-examples/docker-compose-reclient/run_in_container.sh` line 15 at r4](https://reviewable.io/reviews/tracemachina/nativelink/286#-NkxrWhV1O5kQGMsp_HO:-NlSiqUzCGynDHQ4Ud0N:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/run_in_container.sh#L15)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

`TURBO_CACHE_DIR` -> `NATIVE_LINK_DIR`
</blockquote></details>

Done.
___
*[`deployment-examples/docker-compose-reclient/run_in_container.sh` line 17 at r4](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nkxrv4M856yd2vMpS_Z:-NlSirc_109aT8ll0ARK:bu5e4c3) ([raw file](https://github.com/tracemachina/nativelink/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/run_in_container.sh#L17)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

for the pipes to `cut` what kind of assumptions are those character ranges making? It is unclear what they might be
</blockquote></details>

There's a whole comment explaining that above.
___
*[`deployment-examples/docker-compose-reclient/worker.json` line 13 at r4](https://reviewable.io/reviews/tracemachina/nativelink/286#-NkxkG03B6Ket0NhTrky:-NlSixkn0SbWeJupO8Z0:b-jiwbvo) ([raw file](https://github.com/tracemachina/nativelink/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/worker.json#L13)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Both environment variables are `CAS_ENDPOINT`, is there a situation where we would have a difference between these endpoints and their logical hosts?
</blockquote></details>

Yes, but this is simply an example deployment, one wouldn't usually run the worker on the same node as the scheduler, build and CAS.
___
*[`deployment-examples/docker-compose-reclient/worker.json` line 21 at r4](https://reviewable.io/reviews/tracemachina/nativelink/286#-NkxkpGa10mEJJd_Or9z:-NlSj2eM10pa_vFK3zEm:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/worker.json#L21)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

`turbo-cache` -> `native-link`, same below
</blockquote></details>

Done.
___
*[`deployment-examples/docker-compose-reclient/worker.json` line 45 at r4](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nkxl0d8ChEedkcF6XwS:-NlSj3-R3jejDytSukop:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/worker.json#L45)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

`TURBO_CACHE_DIR` -> `NATIVE_LINK_DIR`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-12 11:20 UTC, chrisstaite-menlo reviewed
> Reviewed 1 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/286)* status: 3 of 8 files reviewed, 9 unresolved discussions (waiting on @adam-singer and @allada)



<!-- Sent from Reviewable.io -->

2023-12-12 22:08 UTC, adam-singer reviewed
> Reviewed 4 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/286)* status: all files reviewed, 2 unresolved discussions (waiting on @allada and @chrisstaite-menlo)

___
*[`deployment-examples/docker-compose-reclient/run_in_container.sh` line 17 at r4](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nkxrv4M856yd2vMpS_Z:-NlV2Omv1uuTnY-w5X4N:b-9uy064) ([raw file](https://github.com/tracemachina/nativelink/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/run_in_container.sh#L17)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

There's a whole comment explaining that above.
</blockquote></details>

agree, maybe non action here,  was confused on how we know these exact value lengths to cut are static. I will give this patch a spin locally, that will probably clarify up for myself. 


<!-- Sent from Reviewable.io -->

2023-12-12 22:29 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/286)* status: all files reviewed, 2 unresolved discussions (waiting on @allada and @chrisstaite-menlo)

___
*[`deployment-examples/docker-compose-reclient/docker-compose.yml` line 19 at r4](https://reviewable.io/reviews/tracemachina/nativelink/286#-NkxsnL07NhodzQepy5l:-NlV7O2iBW7VImcPn_O-:bcm4aap) ([raw file](https://github.com/tracemachina/nativelink/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/docker-compose.yml#L19)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

FYI: This isn't updated in docker-compose/docker-compose.yml.
</blockquote></details>

@chrisstaite-menlo looks like we will have a few more days of breaking changes, do you mind if we leave this open and revisit it next week for landing. At that point we should have stabilized image and binary command name. Thank you for this and patients around breaking changes   


<!-- Sent from Reviewable.io -->

2023-12-20 23:48 UTC, MarcusSorealheis commented
@adam-singer and @allada I think we can look back into getting this working again.

2023-12-21 00:45 UTC, aaronmondal reviewed
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/286)* status: 0 of 1 LGTMs obtained, and pending CI: publish-image, windows-2022 / beta (waiting on @adam-singer)

___
*[`deployment-examples/docker-compose-reclient/docker-compose.yml` line 19 at r4](https://reviewable.io/reviews/tracemachina/nativelink/286#-NkxsnL07NhodzQepy5l:-Nm8odbT98kb5G1THlgU:bkg87n7) ([raw file](https://github.com/tracemachina/nativelink/blob/790d78552bc09996733a8bfdc58c763434cf04f1/deployment-examples/docker-compose-reclient/docker-compose.yml#L19)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

@chrisstaite-menlo looks like we will have a few more days of breaking changes, do you mind if we leave this open and revisit it next week for landing. At that point we should have stabilized image and binary command name. Thank you for this and patients around breaking changes
</blockquote></details>

This image is now now be `ghcr.io/tracemachina/nativelink:wm6l3qi72hv9phn44853ir1dxs3q7k65` instead of `tracemachina/nativelink:latest`. I *think* it's a drop-in replacement, but I'm not 100% sure. Might need some adjustments to mount paths. The new image already has the `cas` executable set as entrypoint, so the command to run should just be the path to the config file, i.e.

```yaml
command: /root/local-storage-cas.json
```


<!-- Sent from Reviewable.io -->

2023-12-21 01:10 UTC, adam-singer requested changes
@MarcusSorealheis agree.
@chrisstaite-menlo we are ready to review this, pointed out some breaking changes since `0.1.0` release, also will likely need to revert Cargo.lock file.

> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/286#-:-Nm8d2DqC7ZYAuS4pGmv:bmm7m9w)* status: 0 of 1 LGTMs obtained, and pending CI: publish-image, windows-2022 / beta

___
*[`deployment-examples/docker-compose-reclient/scheduler.json` line 7 at r6](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nm8h0UL6fZpixfokqj5:-Nm8h0UL6fZpixfokqj6:b-vugfwq) ([raw file](https://github.com/tracemachina/nativelink/blob/92f025a60241dd664d5d8962f8b7e177492903d0/deployment-examples/docker-compose-reclient/scheduler.json#L7)):*
> ```JSON
>         "instance_name": "main",
>         "endpoints": ["grpc://${CAS_ENDPOINT:-127.0.0.1}:50051"],
>         "store_type": "CAS"
> ```

`CAS` -> `cas`
___
*[`deployment-examples/docker-compose-reclient/scheduler.json` line 14 at r6](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nm8gzZI4SvsVwFZrRA_:-Nm8gzZI4SvsVwFZrRAa:bnv6j00) ([raw file](https://github.com/tracemachina/nativelink/blob/92f025a60241dd664d5d8962f8b7e177492903d0/deployment-examples/docker-compose-reclient/scheduler.json#L14)):*
> ```JSON
>         "instance_name": "main",
>         "endpoints": ["grpc://${CAS_ENDPOINT:-127.0.0.1}:50051"],
>         "store_type": "AC"
> ```

`AC` -> `ac`
___
*[`deployment-examples/docker-compose-reclient/scheduler.json` line 28 at r6](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nm8gn9OENAapdEbwiJL:-Nm8gn9OENAapdEbwiJM:be0s4ba) ([raw file](https://github.com/tracemachina/nativelink/blob/92f025a60241dd664d5d8962f8b7e177492903d0/deployment-examples/docker-compose-reclient/scheduler.json#L28)):*
> ```JSON
>           "simple": {
>             "supported_platform_properties": {
>               "cpu_count": "Minimum",
> ```

`Minimum` -> `minimum`
___
*[`deployment-examples/docker-compose-reclient/scheduler.json` line 29 at r6](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nm8gqy67qhzbvRR16WC:-Nm8gqy67qhzbvRR16WD:b-phjohg) ([raw file](https://github.com/tracemachina/nativelink/blob/92f025a60241dd664d5d8962f8b7e177492903d0/deployment-examples/docker-compose-reclient/scheduler.json#L29)):*
> ```JSON
>             "supported_platform_properties": {
>               "cpu_count": "Minimum",
>               "container-image": "Priority"
> ```

`Priority` -> `priority`
___
*[`deployment-examples/docker-compose-reclient/scheduler.json` line 72 at r6](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nm8gJJ11I72Ks2Pf1uC:-Nm8gJJ11I72Ks2Pf1uD:bb9eqh1) ([raw file](https://github.com/tracemachina/nativelink/blob/92f025a60241dd664d5d8962f8b7e177492903d0/deployment-examples/docker-compose-reclient/scheduler.json#L72)):*
> ```JSON
>     }
>   }, {
>     "listen_address": "0.0.0.0:50061",
> ```

This has changed to the following format https://github.com/adam-singer/native-link/blob/d8239640a9fa26c932a4c234ee2d263837159388/nativelink-config/examples/basic_cas.json#L131

```
    "listener": {
      "http": {
        "socket_address": "0.0.0.0:50061"
      }
    },
```
___
*[`deployment-examples/docker-compose-reclient/scheduler.json` line 81 at r6](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nm8gTPs1mnKvRUrPoaV:-Nm8gTPs1mnKvRUrPoaW:bhcl705) ([raw file](https://github.com/tracemachina/nativelink/blob/92f025a60241dd664d5d8962f8b7e177492903d0/deployment-examples/docker-compose-reclient/scheduler.json#L81)):*
> ```JSON
>         "scheduler": "MAIN_SCHEDULER",
>       },
>       "prometheus": {
> ```

`prometheus` -> `experimental_prometheus`


<!-- Sent from Reviewable.io -->

2024-02-16 11:17 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/286)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @adam-singer)

___
*[`deployment-examples/docker-compose-reclient/scheduler.json` line 7 at r6](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nm8h0UL6fZpixfokqj5:-NqlcgNA6FN9aTQMchQ9:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/92f025a60241dd664d5d8962f8b7e177492903d0/deployment-examples/docker-compose-reclient/scheduler.json#L7)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

`CAS` -> `cas`
</blockquote></details>

Done.
___
*[`deployment-examples/docker-compose-reclient/scheduler.json` line 28 at r6](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nm8gn9OENAapdEbwiJL:-NqlcfsU3glPbb6QYejv:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/92f025a60241dd664d5d8962f8b7e177492903d0/deployment-examples/docker-compose-reclient/scheduler.json#L28)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

`Minimum` -> `minimum`
</blockquote></details>

Done.
___
*[`deployment-examples/docker-compose-reclient/scheduler.json` line 29 at r6](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nm8gqy67qhzbvRR16WC:-Nqlcf_A7GvflaorWTyT:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/92f025a60241dd664d5d8962f8b7e177492903d0/deployment-examples/docker-compose-reclient/scheduler.json#L29)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

`Priority` -> `priority`
</blockquote></details>

Done.
___
*[`deployment-examples/docker-compose-reclient/scheduler.json` line 72 at r6](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nm8gJJ11I72Ks2Pf1uC:-NqlcdoqEprf58W19EuU:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/92f025a60241dd664d5d8962f8b7e177492903d0/deployment-examples/docker-compose-reclient/scheduler.json#L72)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

This has changed to the following format https://github.com/adam-singer/native-link/blob/d8239640a9fa26c932a4c234ee2d263837159388/nativelink-config/examples/basic_cas.json#L131

```
    "listener": {
      "http": {
        "socket_address": "0.0.0.0:50061"
      }
    },
```
</blockquote></details>

Done.
___
*[`deployment-examples/docker-compose-reclient/scheduler.json` line 81 at r6](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nm8gTPs1mnKvRUrPoaV:-NqlcdWh8YYB0tgXYaiZ:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/92f025a60241dd664d5d8962f8b7e177492903d0/deployment-examples/docker-compose-reclient/scheduler.json#L81)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

`prometheus` -> `experimental_prometheus`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-16 11:18 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/286)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @adam-singer)

___
*[`deployment-examples/docker-compose-reclient/scheduler.json` line 14 at r6](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nm8gzZI4SvsVwFZrRA_:-Nqlcund3LmRPhHG6jT0:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/92f025a60241dd664d5d8962f8b7e177492903d0/deployment-examples/docker-compose-reclient/scheduler.json#L14)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

`AC` -> `ac`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-21 05:48 UTC, adam-singer reviewed
> Reviewed 1 of 1 files at r7, 7 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/286)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks, vale



<!-- Sent from Reviewable.io -->

2024-02-27 06:37 UTC, adam-singer reviewed
@chrisstaite-menlo was able to test this patch against latest main with the following adjustments to the `worker.json` https://gist.github.com/adam-singer/a7aa64abf6445eb5752f418a457ca25a#file-gistfile0-txt-L28 (breaking changes from previous release)

Followed instructions in the read me, but instead of creating / updating the `reproxy.cfg` used the following cli to forward all reclient parameters required 


```
RBE_reclient_timeout=60m RBE_exec_timeout=4m RBE_instance=main RBE_service=127.0.0.1:50052 RBE_alsologtostderr=true RBE_service_no_security=true RBE_service_no_auth=true RBE_local_resource_fraction=0.00001 RBE_automatic_auth=false RBE_gcert_refresh_timeout=20 RBE_compression_threshold=-1 RBE_metrics_namespace=main RBE_platform= RBE_experimental_credentials_helper= RBE_experimental_credentials_helper_args= autoninja -v -j 1 -C out/Default unit_tests
```
 
Checked out the chromium codebase from a client machine using the following instructions https://chromium.googlesource.com/chromium/src/+/main/docs/linux/build_instructions.md 

Can you apply the changes and land this? 

> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/286#-:-NrdFyqsC8Cvs5Kl--Sj:bsmswsp)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks, vale



<!-- Sent from Reviewable.io -->

2024-02-27 07:12 UTC, allada reviewed
Awesome, thanks @chrisstaite-menlo, I am going to try this in a day or so and double check everything works.


We are trying to be a lot more diligent on documentation (due to feedback from users). This quarter we are planning on making compiling chrome our base case, meaning we are going to build a bit of CI and tests and such around this PR that we are going to use as a large integration & performance test.

Thanks again :smile: 

> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/286#-:-NrdOSVJAo6WIBjMEO-u:bywaclx)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks, vale (waiting on @adam-singer)



<!-- Sent from Reviewable.io -->

2024-03-02 03:53 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/286)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks, vale (waiting on @adam-singer)

*[a discussion](https://reviewable.io/reviews/tracemachina/nativelink/286#-NrxHTYR4UJfJqvSFbiK:-NrxHTYR4UJfJqvSFbiL:b-ae7ncn) (no related file):*
Note: I suggest reading all the comments before any actions are done.

Second: Could you rebase, there's some breaking changes.

Last: I did test it and although it was not easy to setup, I did get it to work. We are going to be doing a lot of work here over the next couple months so assume lots of changes (hopefully to make your life better too).

Thanks again, awesome as usual :smile: 

___
___
*[`deployment-examples/docker-compose-reclient/docker-compose.yml` line 1 at r8](https://reviewable.io/reviews/tracemachina/nativelink/286#-NrvouxvCRb_d5EQoTxm:-NrvouxvCRb_d5EQoTxn:bpz07zd) ([raw file](https://github.com/tracemachina/nativelink/blob/fd1072d43e0bcebbdf2025d4753bb2ee873fc258/deployment-examples/docker-compose-reclient/docker-compose.yml#L1)):*
> ```YAML
> # Copyright 2023 The Native Link Authors. All rights reserved.
> ```

nit: `NativeLink`
___
*[`deployment-examples/docker-compose-reclient/README.md` line 13 at r8](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nrvp15B3QyE22tQWHi6:-Nrvp15B3QyE22tQWHi7:b-of33tp) ([raw file](https://github.com/tracemachina/nativelink/blob/fd1072d43e0bcebbdf2025d4753bb2ee873fc258/deployment-examples/docker-compose-reclient/README.md#L13)):*
> ```Markdown
> There are a number of roles required to perform a Reclient set up:
> 
>  - Native Link Scheduler - The Native Link instance that handles all of the
> ```

nit: `NativeLink` (and others in this file)
___
*[`deployment-examples/docker-compose-reclient/README.md` line 28 at r8](https://reviewable.io/reviews/tracemachina/nativelink/286#-NrxFSle6NCX_dNlUF0v:-NrxFSle6NCX_dNlUF0w:b991vgs) ([raw file](https://github.com/tracemachina/nativelink/blob/fd1072d43e0bcebbdf2025d4753bb2ee873fc258/deployment-examples/docker-compose-reclient/README.md#L28)):*
> ```Markdown
> ## Running
> 
> To start Native Link simply execute `docker-compose up` from this directory.
> ```

Lets add a section telling users to follow the instructions here on how to install and setup chrome:
https://chromium.googlesource.com/chromium/src/+/main/docs/linux/build_instructions.md

Lets also state that we will assume the user's checked out chrome to `~/chromium/src`

This way when we talk about things that need to be in `~/chromium` so we can explicitly mark it as well as assume we are building on linux.
___
*[`deployment-examples/docker-compose-reclient/README.md` line 32 at r8](https://reviewable.io/reviews/tracemachina/nativelink/286#-NrwLRZ748uUIWej14Qq:-NrwLRZ748uUIWej14Qr:b-t19yab) ([raw file](https://github.com/tracemachina/nativelink/blob/fd1072d43e0bcebbdf2025d4753bb2ee873fc258/deployment-examples/docker-compose-reclient/README.md#L32)):*
> ```Markdown
> port 50052.
> 
> Create the file buildtools/reclient_cfgs/reproxy.cfg with the following:
> ```

nit: Please mention this change needs to happen in chrome's checkout.
___
*[`deployment-examples/docker-compose-reclient/README.md` line 32 at r8](https://reviewable.io/reviews/tracemachina/nativelink/286#-NrwjTU_-O83BOT3-7kE:-NrwjTU_-O83BOT3-7kF:by61dka) ([raw file](https://github.com/tracemachina/nativelink/blob/fd1072d43e0bcebbdf2025d4753bb2ee873fc258/deployment-examples/docker-compose-reclient/README.md#L32)):*
> ```Markdown
> port 50052.
> 
> Create the file buildtools/reclient_cfgs/reproxy.cfg with the following:
> ```

It think we should have users modify `reproxy.cfg.template` instead? This way `gclient sync` or `gclient runhooks` does the work for us?
___
*[`deployment-examples/docker-compose-reclient/README.md` line 34 at r8](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nrwl5nLCHfJIlOQhUZH:-Nrwl5nLCHfJIlOQhUZI:b-hp9xms) ([raw file](https://github.com/tracemachina/nativelink/blob/fd1072d43e0bcebbdf2025d4753bb2ee873fc258/deployment-examples/docker-compose-reclient/README.md#L34)):*
> ```Markdown
> Create the file buildtools/reclient_cfgs/reproxy.cfg with the following:
> ```
> instance=main
> ```

I suggest modifying template (as stated above), then:
```
instance=$rbe_instance
service=127.0.0.1:50052
log_format=reducedtext
$auth_flags
fail_early_min_action_count=4000
fail_early_min_fallback_ratio=0.5
deps_cache_max_mb=256
# TODO(b/276727504) Re-enable once noop build shutdown time bug is fixed
# enable_deps_cache=true
async_reproxy_termination=true
use_unified_uploads=true
fast_log_collection=true
depsscanner_address=$depsscanner_address

# Improve upload/download concurrency
max_concurrent_streams_per_conn=50
max_concurrent_requests_per_conn=50
min_grpc_connections=50
cas_concurrency=1000

# TODO(allada) Native Link doesn't yet support compressed blob upload
compression_threshold=-1
use_batches=false

# Metric metadata
metrics_namespace=$rbe_project

# Disables both TLS and authentication
service_no_security=true
# Required to stop autoninja from complaining about authentication despite being
# implied by service_no_security
service_no_auth=true
```

Then in the readme ask people to modify `~/chromium/.gclient` with something like:
```
solutions = [
  {
    "name": "src",
    "url": "https://chromium.googlesource.com/chromium/src.git",
    "managed": False,
    "custom_deps": {},
    "custom_vars": {
      "rbe_instance": "main",
      "rbe_project": "main",
      "depsscanner_address": "exec:///home/allada/chromium/src/buildtools/reclient/scandeps_server",
    },
  },
]

```

I'm going to see about pushing an upstream chrome change to make `remotebuildexecution.googleapis.com:443` a variable too. This would eventually streamline everything once we enable a few more features.
___
*[`deployment-examples/docker-compose-reclient/README.md` line 65 at r8](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nrwy_Cm5lq9hwzWyPjB:-Nrwy_Cm5lq9hwzWyPjC:b-9whayl) ([raw file](https://github.com/tracemachina/nativelink/blob/fd1072d43e0bcebbdf2025d4753bb2ee873fc258/deployment-examples/docker-compose-reclient/README.md#L65)):*
> ```Markdown
> 
> Now that the environment is set up you simply need to enable it for your
> Chromium build by modifying your `args.gn` file to contain:
> ```

Maybe suggest calling `gn args out/Default` and pasting it in there instead?
___
*[`deployment-examples/docker-compose-reclient/worker.json` line 41 at r8](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nrvr4RmCzczc0CbjGIh:-Nrvr4RmCzczc0CbjGIi:b-bij14l) ([raw file](https://github.com/tracemachina/nativelink/blob/fd1072d43e0bcebbdf2025d4753bb2ee873fc258/deployment-examples/docker-compose-reclient/worker.json#L41)):*
> ```JSON
>     }
>   },
>   "workers": [{
> ```

nit corrected for latest main changes:
```json5
  "workers": [{
    "local": {
      "worker_api_endpoint": {
        "uri": "grpc://${SCHEDULER_ENDPOINT:-127.0.0.1}:50061",
      },
      "entrypoint": "/root/run_in_container.sh",
      "additional_environment": {
        "CONTAINER": {
          "property": "container-image"
        },
        "HOST_ROOT": {
          "value": "${NATIVE_LINK_DIR}"
        }
      },
      "cas_fast_slow_store": "WORKER_FAST_SLOW_STORE",
      "upload_action_result": {
        "ac_store": "GRPC_LOCAL_AC_STORE"
      },
      "work_directory": "/root/.cache/nativelink/work",
      "platform_properties": {
        "OSFamily": {
          "values": ["Linux"]
        },
        "cpu_count": {
          "query_cmd": "nproc"
        },
        // Need to specify a placeholder here otherwise Priority scheduling does
        // not work.
        "container-image": {
          "values": ["placeholder"]
        }
      },
      "experimental_precondition_script": "/root/worker_precondition_script.sh"
    }
  }],
```
___
*[`deployment-examples/docker-compose-reclient/worker.json` line 48 at r8](https://reviewable.io/reviews/trac [...]

2024-03-02 04:20 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/286)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks, vale (waiting on @adam-singer)

___
*[`deployment-examples/docker-compose-reclient/README.md` line 34 at r8](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nrwl5nLCHfJIlOQhUZH:-NrxHzej2Vj8PHpTQ3te:b5u78yy) ([raw file](https://github.com/tracemachina/nativelink/blob/fd1072d43e0bcebbdf2025d4753bb2ee873fc258/deployment-examples/docker-compose-reclient/README.md#L34)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I suggest modifying template (as stated above), then:
```
instance=$rbe_instance
service=127.0.0.1:50052
log_format=reducedtext
$auth_flags
fail_early_min_action_count=4000
fail_early_min_fallback_ratio=0.5
deps_cache_max_mb=256
# TODO(b/276727504) Re-enable once noop build shutdown time bug is fixed
# enable_deps_cache=true
async_reproxy_termination=true
use_unified_uploads=true
fast_log_collection=true
depsscanner_address=$depsscanner_address

# Improve upload/download concurrency
max_concurrent_streams_per_conn=50
max_concurrent_requests_per_conn=50
min_grpc_connections=50
cas_concurrency=1000

# TODO(allada) Native Link doesn't yet support compressed blob upload
compression_threshold=-1
use_batches=false

# Metric metadata
metrics_namespace=$rbe_project

# Disables both TLS and authentication
service_no_security=true
# Required to stop autoninja from complaining about authentication despite being
# implied by service_no_security
service_no_auth=true
```

Then in the readme ask people to modify `~/chromium/.gclient` with something like:
```
solutions = [
  {
    "name": "src",
    "url": "https://chromium.googlesource.com/chromium/src.git",
    "managed": False,
    "custom_deps": {},
    "custom_vars": {
      "rbe_instance": "main",
      "rbe_project": "main",
      "depsscanner_address": "exec:///home/allada/chromium/src/buildtools/reclient/scandeps_server",
    },
  },
]

```

I'm going to see about pushing an upstream chrome change to make `remotebuildexecution.googleapis.com:443` a variable too. This would eventually streamline everything once we enable a few more features.
</blockquote></details>

corrections:
```
instance=$rbe_instance
service=127.0.0.1:50051
log_format=reducedtext
# auth_flags # NativeLink chrome demo does not use credentails.
fail_early_min_action_count=4000
fail_early_min_fallback_ratio=0.5
deps_cache_max_mb=256
# TODO(b/276727504) Re-enable once noop build shutdown time bug is fixed
# enable_deps_cache=true
async_reproxy_termination=true
use_unified_uploads=true
fast_log_collection=true
depsscanner_address=$depsscanner_address

# Improve upload/download concurrency
max_concurrent_streams_per_conn=50
max_concurrent_requests_per_conn=50
min_grpc_connections=50
cas_concurrency=1000

# TODO(allada) Native Link doesn't yet support compressed blob upload
compression_threshold=-1
use_batches=false

# Metric metadata
metrics_namespace=$rbe_project

# Disables both TLS and authentication
service_no_security=true
# Required to stop autoninja from complaining about authentication despite being
# implied by service_no_security
service_no_auth=true
```

And

```
solutions = [
  {
    "name": "src",
    "url": "https://chromium.googlesource.com/chromium/src.git",
    "managed": False,
    "custom_deps": {},
    "custom_vars": {
      "rbe_instance": "main",
      "rbe_project": "main",
      "depsscanner_address": "exec://%s/buildtools/reclient/scandeps_server",
    },
  },
]
```


<!-- Sent from Reviewable.io -->

2024-03-02 04:22 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/286)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks, vale (waiting on @adam-singer)

___
*[`deployment-examples/docker-compose-reclient/scheduler.json` line 23 at r8](https://reviewable.io/reviews/tracemachina/nativelink/286#-NrxOG1qDLebv_Ie_3rY:-NrxOG1qDLebv_Ie_3rZ:bbwy9t9) ([raw file](https://github.com/tracemachina/nativelink/blob/fd1072d43e0bcebbdf2025d4753bb2ee873fc258/deployment-examples/docker-compose-reclient/scheduler.json#L23)):*
> ```JSON
>   },
>   "schedulers": {
>     "MAIN_SCHEDULER": {
> ```

suggest:
```
    "MAIN_SCHEDULER": {
      "property_modifier": {
        "modifications": [
          {"add": {"name": "cpu_count", "value": "1"}}
        ],
        "scheduler": {
          "simple": {
            "supported_platform_properties": {
              "cpu_count": "minimum",
              "OSFamily": "exact",
              "InputRootAbsolutePath": "priority",
              "container-image": "priority",
              "label:action_default": "priority",
              "label:action_large": "priority"
            }
          }
        }
      }
    }
```
___
*[`deployment-examples/docker-compose-reclient/worker.json` line 41 at r8](https://reviewable.io/reviews/tracemachina/nativelink/286#-Nrvr4RmCzczc0CbjGIh:-NrxOUWf5vclEJvvoiOg:b-22bkoi) ([raw file](https://github.com/tracemachina/nativelink/blob/fd1072d43e0bcebbdf2025d4753bb2ee873fc258/deployment-examples/docker-compose-reclient/worker.json#L41)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit corrected for latest main changes:
```json5
  "workers": [{
    "local": {
      "worker_api_endpoint": {
        "uri": "grpc://${SCHEDULER_ENDPOINT:-127.0.0.1}:50061",
      },
      "entrypoint": "/root/run_in_container.sh",
      "additional_environment": {
        "CONTAINER": {
          "property": "container-image"
        },
        "HOST_ROOT": {
          "value": "${NATIVE_LINK_DIR}"
        }
      },
      "cas_fast_slow_store": "WORKER_FAST_SLOW_STORE",
      "upload_action_result": {
        "ac_store": "GRPC_LOCAL_AC_STORE"
      },
      "work_directory": "/root/.cache/nativelink/work",
      "platform_properties": {
        "OSFamily": {
          "values": ["Linux"]
        },
        "cpu_count": {
          "query_cmd": "nproc"
        },
        // Need to specify a placeholder here otherwise Priority scheduling does
        // not work.
        "container-image": {
          "values": ["placeholder"]
        }
      },
      "experimental_precondition_script": "/root/worker_precondition_script.sh"
    }
  }],
```
</blockquote></details>

Corrected again for what I think is better:
```
  "workers": [{
    "local": {
      "worker_api_endpoint": {
        "uri": "grpc://${SCHEDULER_ENDPOINT:-127.0.0.1}:50061",
      },
      "entrypoint": "/root/run_in_container.sh",
      "additional_environment": {
        "CONTAINER": {
          "property": "container-image"
        },
        "HOST_ROOT": {
          "value": "${NATIVE_LINK_DIR}"
        }
      },
      "cas_fast_slow_store": "WORKER_FAST_SLOW_STORE",
      "upload_action_result": {
        "ac_store": "GRPC_LOCAL_AC_STORE"
      },
      "work_directory": "/root/.cache/nativelink/work",
      "platform_properties": {
        "OSFamily": {
          "values": ["Linux"]
        },
        "cpu_count": {
          "query_cmd": "nproc"
        },
        // Need to specify a placeholder here otherwise Priority scheduling does
        // not work.
        "container-image": {
          "values": ["placeholder"]
        },
        "InputRootAbsolutePath": {
          "values": ["placeholder"]
        },
        "label:action_default": {
          "values": ["placeholder"]
        },
        "label:action_large": {
          "values": ["placeholder"]
        }
      },
      "experimental_precondition_script": "/root/worker_precondition_script.sh"
    }
  }],
```


<!-- Sent from Reviewable.io -->

2024-03-03 02:19 UTC, allada reviewed
> Reviewed 1 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/286)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks, vale (waiting on @adam-singer)



<!-- Sent from Reviewable.io -->

2024-05-15 21:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TraceMachina/nativelink?pullRequest=286) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TraceMachina/nativelink?pullRequest=286) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TraceMachina/nativelink?pullRequest=286) it.</sub>

2024-06-19 13:41 UTC, aaronmondal commented
This information is now in the chromium example https://github.com/TraceMachina/nativelink/tree/main/deployment-examples/chromium

2024-06-19 13:41 UTC, closed without merging