Added redis store integration
TraceMachina/nativelink pull request #393
Opened 2023-11-14 17:11 UTC by blakehatch

# Description

Added a Redis Store.

Fixes #302

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Uses the redis_test library to create a mock instance that expects certain commands to be called exactly and confirms that the data is structured correctly when being stored. Had to add custom functionality to connection configuration to make the Native Link store config system work with this mock library.

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/turbo-cache/393)

2023-11-16 14:56 UTC, aaronmondal submitted a review, later dismissed
> Reviewed 8 of 14 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/393)* status: all files reviewed, 7 unresolved discussions (waiting on @allada and @blakehatch)

___
*[`cas/store/BUILD` line 547 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/393#-NjNWkeV4A1LtTBQe4Of:-NjNWkeV4A1LtTBQe4Og:bmkc4b3) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/c374aaf349a9ca86673a0f5556b9fbd0d54500f0/cas/store/BUILD#L547)):*
> ```Starlark
>         "@crate_index//:tokio",
>     ],
> )
> ```

Newline
___
*[`cas/store/default_store_factory.rs` line 49 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/393#-NjNX4KMBIS80UgrhH7H:-NjNX4KNCXekthkax0Cg:bm1mdko) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/c374aaf349a9ca86673a0f5556b9fbd0d54500f0/cas/store/default_store_factory.rs#L49)):*
> ```XML
>             StoreConfig::memory(config) => Arc::new(MemoryStore::new(config)),
>             StoreConfig::s3_store(config) => Arc::new(S3Store::new(config)?),
>             StoreConfig::redis_store(config) => {
> ```

Would be nice if this was called in a similar way as the other stores.
___
*[`cas/store/redis_store.rs` line 72 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/393#-NjNYpqy7tT730qiSK3w:-NjNYpqy7tT730qiSK3x:b-eajiwd) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/c374aaf349a9ca86673a0f5556b9fbd0d54500f0/cas/store/redis_store.rs#L72)):*
> ```XML
> 
>     async fn configure_connection(config: &config::stores::RedisStore) -> Result<Arc<Mutex<T>>, Error> {
>         let conn = if let Some(use_mock) = config.use_mock {
> ```

I believe you could remove the duplicate "else" branches here making `use_mock` not an option but a bool.
___
*[`cas/store/redis_store.rs` line 74 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/393#-NjN_UD08buRQCt-0z1S:-NjN_UD08buRQCt-0z1T:b-6hm9i) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/c374aaf349a9ca86673a0f5556b9fbd0d54500f0/cas/store/redis_store.rs#L74)):*
> ```XML
>         let conn = if let Some(use_mock) = config.use_mock {
>             if use_mock {
>                 let mock_commands = config.mock_commands.clone().unwrap_or_default();
> ```

Since this is specific to mocking, would it make sense to move this to the impl for the MockRedisConnection?
___
*[`cas/store/redis_store.rs` line 138 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/393#-NjN_jyf1ELmysCnvcVz:-NjN_jyf1ELmysCnvcW-:b-2pmmjq) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/c374aaf349a9ca86673a0f5556b9fbd0d54500f0/cas/store/redis_store.rs#L138)):*
> ```XML
>                 Ok::<(usize, _), Error>((index, exists))
>             })
>             .collect();
> ```

This can probably be optimized, but I don't think it matters for the initial implementation. We can always add benchmarks and optimizations later.
___
*[`cas/store/tests/redis_store_test.rs` line 59 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/393#-NjNbv3qD2nccdDWivG6:-NjNbv3qD2nccdDWivG7:b-aircl9) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/c374aaf349a9ca86673a0f5556b9fbd0d54500f0/cas/store/tests/redis_store_test.rs#L59)):*
> ```XML
>     #[tokio::test]
>     async fn insert_one_item_then_update_and_get() -> Result<(), Error> {
>         let data1 = Bytes::from_static(b"13");
> ```

It looks like this (and the ones in the other test) can be `const`.
___
*[`config/stores.rs` line 454 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/393#-NjNbb3v59sb2xafKdEb:-NjNbb3v59sb2xafKdEc:bnq9w6s) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/c374aaf349a9ca86673a0f5556b9fbd0d54500f0/config/stores.rs#L454)):*
> ```XML
> 
>     /// If store is being used in unit tests set this to true
>     pub use_mock: Option<bool>,
> ```

I think this can just be a bool.
___
*[`config/examples/basic_cas.json` line 147 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/393#-NjNcEc19szxbNsRpJ9E:-NjNcEc19szxbNsRpJ9F:blvj5ve) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/c374aaf349a9ca86673a0f5556b9fbd0d54500f0/config/examples/basic_cas.json#L147)):*
> ```JSON
>     "max_open_files": 512
>   }
> }
> ```

Newline/unnecessary change


<!-- Sent from Reviewable.io -->

2024-03-23 21:41 UTC, MarcusSorealheis submitted a review, later dismissed
I'm not sure how we could possibly merge this without documenting its usage.

2024-03-23 21:41 UTC, MarcusSorealheis commented on nativelink-store/src/mock_redis.rs
> +// Copyright 2024 The Turbo Cache Authors. All rights reserved.
NativeLink

2024-03-23 21:41 UTC, MarcusSorealheis commented on nativelink-store/src/redis_store.rs
> +// Copyright 2024 The Turbo Cache Authors. All rights reserved.
NativeLink

2024-03-23 21:41 UTC, MarcusSorealheis commented on nativelink-store/tests/redis_store_test.rs
> +// Copyright 2024 The Turbo Cache Authors. All rights reserved.
NativeLink

2024-03-24 16:57 UTC, blakehatch reviewed
It's usage is documented in the stores config same as all the other stores are, this info will be surfaced with rustdocs as well.

> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393#-:-NtlMomp1jxv8qO22uLM:b-wk2i1c)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

___
*[`nativelink-store/src/mock_redis.rs` line 1 at r3](https://reviewable.io/reviews/tracemachina/nativelink/393#gh-1536696088:-NtlN-v51jK1OQx19fRW:b3fleo8) ([raw file](https://github.com/tracemachina/nativelink/blob/9b429efa665caaa84feb7cc9b085baeabd4c0856/nativelink-store/src/mock_redis.rs#L1)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

NativeLink 
</blockquote></details>

Good catch left that from the rebase.
___
*[`nativelink-store/src/redis_store.rs` line 1 at r3](https://reviewable.io/reviews/tracemachina/nativelink/393#gh-1536696098:-NtlN3NbEXcy5dLyVga3:bt2vr1b) ([raw file](https://github.com/tracemachina/nativelink/blob/9b429efa665caaa84feb7cc9b085baeabd4c0856/nativelink-store/src/redis_store.rs#L1)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

NativeLink
</blockquote></details>

Fixed.
___
*[`nativelink-store/tests/redis_store_test.rs` line 1 at r3](https://reviewable.io/reviews/tracemachina/nativelink/393#gh-1536696304:-NtlN4Oa92G_f23fFIm1:bt2vr1b) ([raw file](https://github.com/tracemachina/nativelink/blob/9b429efa665caaa84feb7cc9b085baeabd4c0856/nativelink-store/tests/redis_store_test.rs#L1)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

NativeLink
</blockquote></details>

Fixed.
___
*[`cas/store/BUILD` line 547 at r2](https://reviewable.io/reviews/tracemachina/nativelink/393#-NjNWkeV4A1LtTBQe4Of:-NtlN8GV7USKuWV-GSna:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/c374aaf349a9ca86673a0f5556b9fbd0d54500f0/cas/store/BUILD#L547)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Newline
</blockquote></details>

Done.
___
*[`cas/store/default_store_factory.rs` line 49 at r2](https://reviewable.io/reviews/tracemachina/nativelink/393#-NjNX4KMBIS80UgrhH7H:-NtlN9CI2ctKKbIPdnIr:bt2vr1b) ([raw file](https://github.com/tracemachina/nativelink/blob/c374aaf349a9ca86673a0f5556b9fbd0d54500f0/cas/store/default_store_factory.rs#L49)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Would be nice if this was called in a similar way as the other stores.
</blockquote></details>

Fixed.
___
*[`cas/store/redis_store.rs` line 72 at r2](https://reviewable.io/reviews/tracemachina/nativelink/393#-NjNYpqy7tT730qiSK3w:-NtlNAWBECEzN9k2K2j-:b9t9syp) ([raw file](https://github.com/tracemachina/nativelink/blob/c374aaf349a9ca86673a0f5556b9fbd0d54500f0/cas/store/redis_store.rs#L72)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

I believe you could remove the duplicate "else" branches here making `use_mock` not an option but a bool.
</blockquote></details>

Removed all Mock integrations to an extremely minimal external file, not extremely happy with this and would like to move these trait implementations to the test crate, however you can't impl outside of the crate itself. If there are any patterns that anyone recommends to clean up this would be amazing.
___
*[`cas/store/redis_store.rs` line 74 at r2](https://reviewable.io/reviews/tracemachina/nativelink/393#-NjN_UD08buRQCt-0z1S:-NtlNT3z6YnTv3e7UPgj:bl9c204) ([raw file](https://github.com/tracemachina/nativelink/blob/c374aaf349a9ca86673a0f5556b9fbd0d54500f0/cas/store/redis_store.rs#L74)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Since this is specific to mocking, would it make sense to move this to the impl for the MockRedisConnection?
</blockquote></details>

Was actually able to extract this section to a function that just lives in the redis_test file.
___
*[`cas/store/redis_store.rs` line 138 at r2](https://reviewable.io/reviews/tracemachina/nativelink/393#-NjN_jyf1ELmysCnvcVz:-NtlNcuf8kfxyTIoRSPr:b3jtdnu) ([raw file](https://github.com/tracemachina/nativelink/blob/c374aaf349a9ca86673a0f5556b9fbd0d54500f0/cas/store/redis_store.rs#L138)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

This can probably be optimized, but I don't think it matters for the initial implementation. We can always add benchmarks and optimizations later.
</blockquote></details>

Yeah there are a few optimizations, I also upgraded the crate and used a better connection type that they recommend called MultiplexedConnection, I imagine a lot of the optimizations would be around utilizing this effectively. Would love benchmarks on this though especially as we test different Redis API compatible stores.
___
*[`cas/store/tests/redis_store_test.rs` line 59 at r2](https://reviewable.io/reviews/tracemachina/nativelink/393#-NjNbv3qD2nccdDWivG6:-NtlO-aI9K7CH4vRiFxF:b-fzzbgc) ([raw file](https://github.com/tracemachina/nativelink/blob/c374aaf349a9ca86673a0f5556b9fbd0d54500f0/cas/store/tests/redis_store_test.rs#L59)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

It looks like this (and the ones in the other test) can be `const`.
</blockquote></details>

Rebase changed file locations not sure what line this is referring to.
___
*[`config/stores.rs` line 454 at r2](https://reviewable.io/reviews/tracemachina/nativelink/393#-NjNbb3v59sb2xafKdEb:-NtlOCX_AsjQrd1RIeBg:b-89a4l7) ([raw file](https://github.com/tracemachina/nativelink/blob/c374aaf349a9ca86673a0f5556b9fbd0d54500f0/config/stores.rs#L454)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

I think this can just be a bool.
</blockquote></details>

Ditto
___
*[`config/examples/basic_cas.json` line 147 at r2](https://reviewable.io/reviews/tracemachina/nativelink/393#-NjNcEc19szxbNsRpJ9E:-NtlODZqEVf5qIr1eGxF:bt2vr1b) ([raw file](https://github.com/tracemachina/nativelink/blob/c374aaf349a9ca86673a0f5556b9fbd0d54500f0/config/examples/basic_cas.json#L147)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Newline/unnecessary change
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2024-03-25 00:24 UTC, adam-singer requested changes
> Reviewed 3 of 27 files at r3, 2 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

___
*[`nativelink-config/src/stores.rs` line 599 at r4](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntmz3cP9oSlLKUv-5NT:-Ntmz3cP9oSlLKUv-5NU:bpzv0uc) ([raw file](https://github.com/tracemachina/nativelink/blob/b79be6cd44767745bc38a477912208b488912953/nativelink-config/src/stores.rs#L599)):*
> ```XML
>     /// The hostname or IP address of the Redis server can include username, passowrd, tls, and database number.
>     #[serde(default, deserialize_with = "convert_string_with_shellexpand")]
>     pub url: String,
> ```

to be consistent with other parts of the config I think this should be called "address", `GrpcEndpoint` and `HttpListener` use that term. If there are other fields such as tls should that be different structures? 


<!-- Sent from Reviewable.io -->

2024-03-26 18:48 UTC, blakehatch reviewed
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 0 of 1 LGTMs obtained, and pending CI: Vercel, pre-commit-checks

___
*[`nativelink-config/src/stores.rs` line 599 at r4](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntmz3cP9oSlLKUv-5NT:-Ntw3K8MEfsd3VARC-6-:b-spxo51) ([raw file](https://github.com/tracemachina/nativelink/blob/b79be6cd44767745bc38a477912208b488912953/nativelink-config/src/stores.rs#L599)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

to be consistent with other parts of the config I think this should be called "address", `GrpcEndpoint` and `HttpListener` use that term. If there are other fields such as tls should that be different structures?
</blockquote></details>

Done. I can add options to enable and disable TLS, backoff, retry, etc. Lots of options in the crate idk if expanding this is worth just creating another PR for.


<!-- Sent from Reviewable.io -->

2024-03-27 04:33 UTC, allada requested changes
> Reviewed 6 of 27 files at r3, 1 of 5 files at r4, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

___
*[`nativelink-config/src/stores.rs` line 599 at r4](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntmz3cP9oSlLKUv-5NT:-NtxmtUz-FTcQw7cr0Ny:bvxj7nn) ([raw file](https://github.com/tracemachina/nativelink/blob/b79be6cd44767745bc38a477912208b488912953/nativelink-config/src/stores.rs#L599)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Done. I can add options to enable and disable TLS, backoff, retry, etc. Lots of options in the crate idk if expanding this is worth just creating another PR for.
</blockquote></details>

Lets do it as a different PR, as it'll make reviews easier.
___
*[`nativelink-config/src/stores.rs` line 166 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxm4TX-iN7BqamCKVK:-Ntxm4TX-iN7BqamCKVL:b-9vjg63) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-config/src/stores.rs#L166)):*
> ```XML
>     grpc(GrpcStore),
> 
>     /// Stores data in a Redis store or any stores compatible with Redis APIs.
> ```

nit: No point in saying "Redis store or any store compatible..." just say "any store compatible ...".
___
*[`nativelink-config/src/stores.rs` line 170 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-NtxmI86-SljUeJv-1a7:-NtxmI86-SljUeJv-1a8:brg1nvs) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-config/src/stores.rs#L170)):*
> ```XML
>     /// This store pairs well with the SizePartitioning store to accept only
>     /// small data that is optimally sized to fit in the Redis store. As Redis
>     /// and other in-memory stores are generally fast as well it is also
> ```

The way this reads is strange. Instead just say it pairs well with `SizePartitioning and/or FastSlow` then say reasons and other limitations.

One limitation that is worth noting here is that most redis implementations have size limits per object, which is an easy foot-gun for people that don't know that.
___
*[`nativelink-config/src/stores.rs` line 597 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxn7cy0H4XC7TFn-Lz:-Ntxn7cy0H4XC7TFn-M-:bye8zd0) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-config/src/stores.rs#L597)):*
> ```XML
> #[derive(Serialize, Deserialize, Debug, Clone)]
> pub struct RedisStore {
>     /// The hostname or IP address of the Redis server can include username, passowrd, tls, and database number.
> ```

nit: Please give an example.
___
*[`nativelink-config/src/stores.rs` line 599 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxp8wPBonVEtE0gZjn:-Ntxp8wPBonVEtE0gZjo:bv986sb) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-config/src/stores.rs#L599)):*
> ```XML
>     /// The hostname or IP address of the Redis server can include username, passowrd, tls, and database number.
>     #[serde(default, deserialize_with = "convert_string_with_shellexpand")]
>     pub address: String,
> ```

even though the redis client implementation for rust does not support multiple multiplexing on different addresses, I think we should future-proof our config by making this a `Vec<String>` and documenting that it currently only exactly 1 address and in the code enforce it. This will prevent a future breaking change.

In the future adding manual multiplexing should be straight forward.
___
*[`nativelink-error/BUILD.bazel` line 11 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-NtxpkgM41I_8es-cCEy:-NtxpkgM41I_8es-cCEz:ba3dfmt) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-error/BUILD.bazel#L11)):*
> ```Starlark
>     deps = [
>         "//nativelink-proto",
>         #"@crates//:futures-rustls",
> ```

Remove.
___
*[`nativelink-error/BUILD.bazel` line 15 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxpw2R7sky21sQ2cw3:-Ntxpw2R7sky21sQ2cw4:b-akaggx) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-error/BUILD.bazel#L15)):*
> ```Starlark
>         "@crates//:prost",
>         "@crates//:prost-types",
>         "@crates//:redis",
> ```

Sadly, we cannot/shouldnot do this. We'll have to write a helper for this.

It doesn't make sense to force every create to import redis just to convert the error types for a single store implementation detail.
___
*[`nativelink-error/src/lib.rs` line 123 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-NtxqNz9Cxd8lJxM30B4:-NtxqNz9Cxd8lJxM30B5:b7hy6zv) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-error/src/lib.rs#L123)):*
> ```XML
> impl From<redis::RedisError> for Error {
>     fn from(err: redis::RedisError) -> Self {
>         Error::new(Code::Internal, format!("Redis error: {}", err))
> ```

fyi: I'm a bit afraid that we might mask a lot of these in `Internal` errors when they are not-founds or other kind of errors that are not internal.
___
*[`nativelink-store/BUILD.bazel` line 53 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxq_ZN6qIArIWPI_Ye:-Ntxq_ZN6qIArIWPI_Yf:b-lsjvio) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-store/BUILD.bazel#L53)):*
> ```Starlark
>         "@crates//:filetime",
>         "@crates//:futures",
>         #"@crates//:futures-rustls",
> ```

nit: Remove.
___
*[`nativelink-store/BUILD.bazel` line 112 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxqbyo5EGj1nyZOurw:-Ntxqbyo5EGj1nyZOurx:b-lsjvio) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-store/BUILD.bazel#L112)):*
> ```Starlark
>         "@crates//:filetime",
>         "@crates//:futures",
>         #"@crates//:futures-rustls",
> ```

nit: Remove.
___
*[`nativelink-store/Cargo.toml` line 31 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxqmn39HdEm95eOM6a:-Ntxqmn39HdEm95eOM6b:bf4puz7) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-store/Cargo.toml#L31)):*
> ```TOML
> rand = "0.8.5"
> redis = { version = "0.25.2", features = ["tokio-comp", "tokio-rustls-comp"] }
> redis-test = { version = "0.4.0", features = ["aio"] }
> ```

I think this should be a dev-dependency or at least masked behind a cfg test.
___
*[`nativelink-store/src/default_store_factory.rs` line 25 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxr9hU3uiOGrTBfP14:-Ntxr9hU3uiOGrTBfP15:bj6e5x9) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-store/src/default_store_factory.rs#L25)):*
> ```XML
> use nativelink_util::metrics_utils::Registry;
> use nativelink_util::store_trait::Store;
> use redis::aio::MultiplexedConnection;
> ```

This should be under `RedisStore`, no code outside of `redis_store.rs` or `redis_store_test.rs` should import the `redis` create.
___
*[`nativelink-store/src/mock_redis.rs` line 1 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-NtxrT4v2fCr5SkjnA4b:-NtxrT4v2fCr5SkjnA4c:b-qqbmn3) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-store/src/mock_redis.rs#L1)):*
> ```XML
> // Copyright 2024 The NativeLink Authors. All rights reserved.
> ```

This file is small enough to just put it in with the test.
___
*[`nativelink-store/src/redis_store.rs` line 37 at r6](https://reviewable.io/reviews/tracemachina/ [...]

2024-04-02 05:08 UTC, adam-singer reviewed
> Reviewed 4 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), pre-commit-checks, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 29 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-04-02 05:10 UTC, blakehatch reviewed
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), pre-commit-checks, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 20 discussions need to be resolved

___
*[`nativelink-config/src/stores.rs` line 599 at r4](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntmz3cP9oSlLKUv-5NT:-Nu4dFO-AZsCJyqbN8rw:brxp9sq) ([raw file](https://github.com/tracemachina/nativelink/blob/b79be6cd44767745bc38a477912208b488912953/nativelink-config/src/stores.rs#L599)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Lets do it as a different PR, as it'll make reviews easier.
</blockquote></details>

Sounds good.
___
*[`nativelink-config/src/stores.rs` line 166 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxm4TX-iN7BqamCKVK:-NuAVDkr1dzeANwfFq_1:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-config/src/stores.rs#L166)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: No point in saying "Redis store or any store compatible..." just say "any store compatible ...".
</blockquote></details>

Done.
___
*[`nativelink-config/src/stores.rs` line 170 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-NtxmI86-SljUeJv-1a7:-NuFzT0U9hS5RwjekVVD:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-config/src/stores.rs#L170)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

The way this reads is strange. Instead just say it pairs well with `SizePartitioning and/or FastSlow` then say reasons and other limitations.

One limitation that is worth noting here is that most redis implementations have size limits per object, which is an easy foot-gun for people that don't know that.
</blockquote></details>

Done.
___
*[`nativelink-config/src/stores.rs` line 597 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxn7cy0H4XC7TFn-Lz:-NuAVpOy0RQiIrs8Tu-4:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-config/src/stores.rs#L597)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Please give an example.
</blockquote></details>

Done.
___
*[`nativelink-config/src/stores.rs` line 599 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxp8wPBonVEtE0gZjn:-Nu4eILZ7VNy6X1f2VY2:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-config/src/stores.rs#L599)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

even though the redis client implementation for rust does not support multiple multiplexing on different addresses, I think we should future-proof our config by making this a `Vec<String>` and documenting that it currently only exactly 1 address and in the code enforce it. This will prevent a future breaking change.

In the future adding manual multiplexing should be straight forward.
</blockquote></details>

Done.
___
*[`nativelink-store/BUILD.bazel` line 53 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxq_ZN6qIArIWPI_Ye:-NuAVq_f1oNCmxamN9MP:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-store/BUILD.bazel#L53)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Remove.
</blockquote></details>

Done.
___
*[`nativelink-store/BUILD.bazel` line 112 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxqbyo5EGj1nyZOurw:-NuAVvGW8NLx10Ca7bWH:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-store/BUILD.bazel#L112)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Remove.
</blockquote></details>

Done.
___
*[`nativelink-store/Cargo.toml` line 31 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxqmn39HdEm95eOM6a:-NuAhsYj6uv60R_4H2gv:b-4a592t) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-store/Cargo.toml#L31)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I think this should be a dev-dependency or at least masked behind a cfg test.
</blockquote></details>

Can't be moved as the mock implementation (That can't be pushed to tests as it is in a different crate) needs it.
___
*[`nativelink-store/src/default_store_factory.rs` line 25 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxr9hU3uiOGrTBfP14:-NuFzY1331-HGfpsSDTQ:b-rl2ej) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-store/src/default_store_factory.rs#L25)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This should be under `RedisStore`, no code outside of `redis_store.rs` or `redis_store_test.rs` should import the `redis` create.
</blockquote></details>

Need to specify the implementation of the generic RedisStore to MultiplexedConnection.
___
*[`nativelink-store/src/redis_store.rs` line 37 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxrirw63_jRmwpwJJr:-NuAfCu179S3mIAt_7zI:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-store/src/redis_store.rs#L37)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: These are public APIs so they should be documented.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 40 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-NtxrnY08t1Gdp-hF1-n:-NuAfCM69lBJuITCF48c:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-store/src/redis_store.rs#L40)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: ditto.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 51 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-NtxsVpEB0yXOqVSlVtw:-NuG-XXGCq2KQTD6sVIy:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-store/src/redis_store.rs#L51)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Shouldn't we use `get_multiplexed_tokio_connection_with_response_timeouts`? Otherwise won't
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 51 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-NtxuY976s0hfLKb8h3z:-NuAb_Vo4a-tTlAIDEAn:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-store/src/redis_store.rs#L51)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Use `.err_tip()` to give searchable points in code instead of straight question-marks.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 58 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-NtxurDd5yr474zM6vlG:-NuAfFNz5wLndupItzyJ:b-ifszsl) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-store/src/redis_store.rs#L58)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i> [...]

2024-04-02 18:50 UTC, allada requested changes
> Reviewed 4 of 12 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 36 discussions need to be resolved

___
*[`nativelink-config/src/stores.rs` line 168 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUrfm92Mmi8rig1bl6:-NuUrfm92Mmi8rig1bl7:b5ce8sk) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-config/src/stores.rs#L168)):*
> ```XML
>     /// Stores data in any stores compatible with Redis APIs.
>     ///
>     /// Paris well with SizePartitioning and/or FastSlow stores.
> ```

nit: `s/Paris/Pairs/`
___
*[`nativelink-config/src/stores.rs` line 170 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUrp5EBxOPMc9-8qks:-NuUrp5EBxOPMc9-8qkt:bwownn6) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-config/src/stores.rs#L170)):*
> ```XML
>     /// Paris well with SizePartitioning and/or FastSlow stores.
>     /// Ideal for accepting small object sizes, most redis implementations
>     /// have size limits per object.
> ```

Probably worth putting a note here saying that a gotcha is that most redis store services have a max file upload of between 256Mb-512Mb.
___
*[`nativelink-config/src/stores.rs` line 603 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUsDPV26W0QthlhABT:-NuUsDPV26W0QthlhABU:b-67hlqw) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-config/src/stores.rs#L603)):*
> ```XML
> 
>     #[serde(default)]
>     /// The response timeout for the Redis connection in seconds.
> ```

Defaults?
___
*[`nativelink-config/src/stores.rs` line 607 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUsGIz-dxxRvWWAz8r:-NuUsGIz-dxxRvWWAz8s:b-67hlqw) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-config/src/stores.rs#L607)):*
> ```XML
> 
>     #[serde(default)]
>     /// The connection timeout for the Redis connection in seconds.
> ```

Defaults?
___
*[`nativelink-store/BUILD.bazel` line 60 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUsNb28Yiu786SRM__:-NuUsNb28Yiu786SRM_a:b-ybp31q) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/BUILD.bazel#L60)):*
> ```Starlark
>         "@crates//:rand",
>         "@crates//:redis",
>         "@crates//:redis-test",
> ```

nit: Not needed.
___
*[`nativelink-store/Cargo.toml` line 31 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxqmn39HdEm95eOM6a:-NuUrKgp5IDSqn7cGbQD:b-s98d7) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-store/Cargo.toml#L31)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Can't be moved as the mock implementation (That can't be pushed to tests as it is in a different crate) needs it.
</blockquote></details>

The mock is part of the test now, so it can be moved to a `dev-dependency`. Also if you are creating test-only crates, put them under `tests` folder then this won't be an issue.
___
*[`nativelink-store/src/default_store_factory.rs` line 25 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUsfhL3gfFBqn4DFQ_:-NuUsfhL3gfFBqn4DFQa:bu0a9ra) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/default_store_factory.rs#L25)):*
> ```XML
> use nativelink_util::metrics_utils::Registry;
> use nativelink_util::store_trait::Store;
> use redis::aio::MultiplexedConnection;
> ```

Remove this dependency and instead make the default store template use `MultiplexedConnection`. The syntax is kinda weird in rust, but this might help: https://stackoverflow.com/questions/67657529/how-to-pass-default-generic-type-in-rust-function
___
*[`nativelink-store/src/default_store_factory.rs` line 58 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUsWpz5FH-qRr9zaGB:-NuUsWpz5FH-qRr9zaGC:b-2z2f02) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/default_store_factory.rs#L58)):*
> ```XML
>             StoreConfig::experimental_s3_store(config) => Arc::new(S3Store::new(config).await?),
>             StoreConfig::redis_store(config) => {
>                 Arc::new(RedisStore::<MultiplexedConnection>::new(config, || Uuid::new_v4()).await?)
> ```

nit: Remove the dependency of UUID and make it defaulted to Uuid inside the `new()` function.
___
*[`nativelink-store/src/redis_store.rs` line 33 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUu8ZoBh9nrzFfC4Dz:-NuUu8ZoBh9nrzFfC4E-:bxv1ccm) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L33)):*
> ```XML
> 
> pub struct RedisStore<T: ConnectionLike + Unpin + Clone + Send + Sync = MultiplexedConnection> {
>     pub conn: T,
> ```

nit: Why are these `pub`? It's very rare to expose internal properties via `pub` when it's not a library.
___
*[`nativelink-store/src/redis_store.rs` line 34 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUuIgqErvglZM7RGD5:-NuUuIgqErvglZM7RGD6:bmfn8y1) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L34)):*
> ```XML
> pub struct RedisStore<T: ConnectionLike + Unpin + Clone + Send + Sync = MultiplexedConnection> {
>     pub conn: T,
>     pub temp_name_generator: fn() -> uuid::Uuid,
> ```

nit: Don't have it return a uuid, have it return a string or something... whatever redis takes for the key.
___
*[`nativelink-store/src/redis_store.rs` line 43 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUvsc3-bVKFoiW-NDU:-NuUvsc3-bVKFoiW-NDV:b-ckrld3) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L43)):*
> ```XML
>     ) -> Result<RedisStore<MultiplexedConnection>, Error> {
>         // Note: Currently only one connection is supported, so use the first address in the list.
>         let client = redis::Client::open(config.address[0].clone());
> ```

We need to `error_if!(config.addresses.len() != 1, "message here");` otherwise it'll just panic here with a useless error message.

Note: The comment can be part of the error message, so need to add that comment.
___
*[`nativelink-store/src/redis_store.rs` line 45 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUwIcD3890MVD0GOnQ:-NuUwIcD3890MVD0GOnR:budsqcj) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L45)):*
> ```XML
>         let client = redis::Client::open(config.address[0].clone());
> 
>         let client_res: Result<redis::Client, Error> = match client {
> ```

nit: Why not use `.map_err(|e| handle_redis_error(redis_error))?`
___
*[`nativelink-store/src/redis_store.rs` line 51 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUwZjw9-jzsLGuQwXj:-NuUwZjw9-jzsLGuQwXk:bpdiau5) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L51)):*
> ```XML
> 
>         let conn = client_res
>             .err_tip(|| "Failed to create Redis client")?
> ```

nit: You just created the error message above, why not just do all the work above?
___
*[`nativelink-store/src/redis_store.rs` line 54 at r8](https://revi [...]

2024-04-08 18:55 UTC, blakehatch reviewed
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks, and 28 discussions need to be resolved

___
*[`nativelink-config/src/stores.rs` line 168 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUrfm92Mmi8rig1bl6:-NuVIW0Z7BlLZafk8FtQ:b-meebe4) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-config/src/stores.rs#L168)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: `s/Paris/Pairs/`
</blockquote></details>

Must've made that change while I was there lol, fixed.
___
*[`nativelink-config/src/stores.rs` line 170 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUrp5EBxOPMc9-8qks:-NuVMVCq-5SxA6OSkZyg:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-config/src/stores.rs#L170)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Probably worth putting a note here saying that a gotcha is that most redis store services have a max file upload of between 256Mb-512Mb.
</blockquote></details>

Done.
___
*[`nativelink-config/src/stores.rs` line 603 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUsDPV26W0QthlhABT:-NuVj3fg4qRjjadrrNFT:b-3uu4qg) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-config/src/stores.rs#L603)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Defaults?
</blockquote></details>

Done, there might be cleaner way to do this.
___
*[`nativelink-config/src/stores.rs` line 607 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUsGIz-dxxRvWWAz8r:-NuVj5zn7ZamrgRS38X2:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-config/src/stores.rs#L607)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Defaults?
</blockquote></details>

Done.
___
*[`nativelink-store/BUILD.bazel` line 60 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUsNb28Yiu786SRM__:-NuVMw8tDVh2WehMxph3:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/BUILD.bazel#L60)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Not needed.
</blockquote></details>

Done.
___
*[`nativelink-store/Cargo.toml` line 31 at r6](https://reviewable.io/reviews/tracemachina/nativelink/393#-Ntxqmn39HdEm95eOM6a:-NuVN2rU9vQoWdCt0JRX:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/3ff63f5b2f079f8e7bc83f88d66142aade90bb7f/nativelink-store/Cargo.toml#L31)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

The mock is part of the test now, so it can be moved to a `dev-dependency`. Also if you are creating test-only crates, put them under `tests` folder then this won't be an issue.
</blockquote></details>

Done.
___
*[`nativelink-store/src/default_store_factory.rs` line 25 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUsfhL3gfFBqn4DFQ_:-NuWRwce2y-1QxCKwP0P:b-kte657) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/default_store_factory.rs#L25)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Remove this dependency and instead make the default store template use `MultiplexedConnection`. The syntax is kinda weird in rust, but this might help: https://stackoverflow.com/questions/67657529/how-to-pass-default-generic-type-in-rust-function
</blockquote></details>

Found a cleaner solution by implementing a non-generic version of RedisStore so I don't have to pass in a type.
___
*[`nativelink-store/src/default_store_factory.rs` line 58 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUsWpz5FH-qRr9zaGB:-NuWSvQh53XIIJ_6Yis7:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/default_store_factory.rs#L58)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Remove the dependency of UUID and make it defaulted to Uuid inside the `new()` function.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 33 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUu8ZoBh9nrzFfC4Dz:-NuVPWrx9bwwNtZ5wKYh:bx5upuq) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L33)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Why are these `pub`? It's very rare to expose internal properties via `pub` when it's not a library.
</blockquote></details>

Needed to make it pub to pull new_ext out into redis_test out for mocking a redis connection instead of implementing a new function for Mocks to redis_store. This redis_test mocking library is just super rigid and not feature rich, makes it difficult to do these little things cleanly.
___
*[`nativelink-store/src/redis_store.rs` line 34 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUuIgqErvglZM7RGD5:-NuVRR5vA_oADDYW2tGp:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L34)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Don't have it return a uuid, have it return a string or something... whatever redis takes for the key.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 43 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUvsc3-bVKFoiW-NDU:-NuVQmQb8zIERdIEw-n8:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L43)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

We need to `error_if!(config.addresses.len() != 1, "message here");` otherwise it'll just panic here with a useless error message.

Note: The comment can be part of the error message, so need to add that comment.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 45 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUwIcD3890MVD0GOnQ:-NuVUWEL4E4aM21U4YO4:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L45)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Why not use `.map_err(|e| handle_redis_error(redis_error))?`
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 51 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUwZjw9-jzsLGuQwXj:-NuVUl155eyo0jvpxJr7:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L51)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: You just created the error message above, why not just do all the work above?
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 54 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUwfedDFLipCkzneBS:-NuVUrgv4bF1mhjKRSae:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L54 [...]

2024-04-09 23:37 UTC, adam-singer reviewed
> Reviewed 4 of 7 files at r9.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-22.04, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 28 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-04-10 04:51 UTC, adam-singer reviewed
> Reviewed 2 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-22.04, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 29 discussions need to be resolved

___
*[`nativelink-config/src/stores.rs` line 603 at r9](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nv5KUTJDFpT1nokn_cn:-Nv5KUTJDFpT1nokn_co:b-649qxh) ([raw file](https://github.com/tracemachina/nativelink/blob/d12d78f46a5dd91acf56e2f60e723592376eb1bc/nativelink-config/src/stores.rs#L603)):*
> ```XML
>     #[serde(default = "default_response_timeout")]
>     /// The response timeout for the Redis connection in seconds.
>     /// ///
> ```

nit: extra `///` are here 


<!-- Sent from Reviewable.io -->

2024-04-10 15:41 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-22.04, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 23 discussions need to be resolved

___
*[`nativelink-config/src/stores.rs` line 601 at r9](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nv7aZnh-jeVVgTZXChP:-Nv7aZnh-jeVVgTZXChQ:b-31q2v3) ([raw file](https://github.com/tracemachina/nativelink/blob/d12d78f46a5dd91acf56e2f60e723592376eb1bc/nativelink-config/src/stores.rs#L601)):*
> ```XML
>     pub addresses: Vec<String>,
> 
>     #[serde(default = "default_response_timeout")]
> ```

nit: just make this `#[serde(default)]` Then when it's being used check if it's zero and then set it to a constant.
___
*[`nativelink-config/src/stores.rs` line 605 at r9](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nv7aLbFEa6wOC2yNHOF:-Nv7aLbFEa6wOC2yNHOG:bv2d7c3) ([raw file](https://github.com/tracemachina/nativelink/blob/d12d78f46a5dd91acf56e2f60e723592376eb1bc/nativelink-config/src/stores.rs#L605)):*
> ```XML
>     /// ///
>     /// Default: 10
>     pub response_timeout: u64,
> ```

nit: `response_timeout_s`
___
*[`nativelink-config/src/stores.rs` line 607 at r9](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nv7aoYTCcBJSx6MUlrO:-Nv7aoYTCcBJSx6MUlrP:b-rqxvo7) ([raw file](https://github.com/tracemachina/nativelink/blob/d12d78f46a5dd91acf56e2f60e723592376eb1bc/nativelink-config/src/stores.rs#L607)):*
> ```XML
>     pub response_timeout: u64,
> 
>     #[serde(default = "default_connection_timeout")]
> ```

ditto.
___
*[`nativelink-store/src/redis_store.rs` line 33 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUu8ZoBh9nrzFfC4Dz:-Nv7b55G7j_Geh9hsjtr:bs9fuaw) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L33)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Needed to make it pub to pull new_ext out into redis_test out for mocking a redis connection instead of implementing a new function for Mocks to redis_store. This redis_test mocking library is just super rigid and not feature rich, makes it difficult to do these little things cleanly.
</blockquote></details>

Generally the pattern we use in nativelink is to use `new_with_conn_and_name_generator()` or something.
___
*[`nativelink-store/src/redis_store.rs` line 79 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuV7cpc9XDTFU6-5Mxs:-Nv7bvqIELUq6f6XOnSr:b-l0jxde) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L79)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

I assume the hash_str() includes that info if used as the key?
</blockquote></details>

No, it only includes the string representation of the hash, not the size.

```rs
format!("{}-{}", digest.hash_str(), digest.size_bytes)
```

Otherwise we won't be following spec. The size is part of the unique key.
___
*[`nativelink-store/src/redis_store.rs` line 80 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUxEMR3sWzOOo5lpTr:-Nv7do9ODmW3b3OnPFlk:b-aknu9n) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L80)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

It's impossible to unit test pipelines with the redis_test crate as I encountered with an earlier approach for `update`.
</blockquote></details>

I think we need to discuss this part, because I can't imagine it not working with pipe's as it's so popular.
___
*[`nativelink-store/src/redis_store.rs` line 46 at r9](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nv7bMWv0fKzVmYPeaFn:-Nv7bMWv0fKzVmYPeaFo:b415lod) ([raw file](https://github.com/tracemachina/nativelink/blob/d12d78f46a5dd91acf56e2f60e723592376eb1bc/nativelink-store/src/redis_store.rs#L46)):*
> ```XML
>     ) -> Result<RedisStore<MultiplexedConnection>, Error> {
>         // Note: Currently only one connection is supported.
>         error_if!(config.addresses.len() != 1, "message here");
> ```

nit: `message here`.
___
*[`nativelink-store/src/redis_store.rs` line 76 at r9](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nv7eHpO5ogjmUbbVIss:-Nv7eHpO5ogjmUbbVIst:bjti2hn) ([raw file](https://github.com/tracemachina/nativelink/blob/d12d78f46a5dd91acf56e2f60e723592376eb1bc/nativelink-store/src/redis_store.rs#L76)):*
> ```XML
>             .map(|(index, digest)| async move {
>                 let mut conn = self.conn.clone();
>                 let exists: bool = conn
> ```

lets not call this and instead only use `strlen`. The problem with doing this is that `strlen` returns zero if the payload does not exist, which we need to handle when the payload really is zero.

To get around this there's some utility code that we have in: `cas_utils::is_zero_digest()` that we can use during upload/download to bypass this, because zero digests must ALWAYS exist even if they have not been uploaded according to bazel spec.
___
*[`nativelink-store/src/redis_store.rs` line 82 at r9](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nv7cFCH5WYTxZZJs07K:-Nv7cFCH5WYTxZZJs07L:b-5v3gaq) ([raw file](https://github.com/tracemachina/nativelink/blob/d12d78f46a5dd91acf56e2f60e723592376eb1bc/nativelink-store/src/redis_store.rs#L82)):*
> ```XML
> 
>                 let size = conn
>                     .strlen(digest.hash_str())
> ```

nit: ditto.


<!-- Sent from Reviewable.io -->

2024-04-10 16:19 UTC, blakehatch reviewed
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-22.04, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 23 discussions need to be resolved

___
*[`nativelink-store/src/redis_store.rs` line 80 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUxEMR3sWzOOo5lpTr:-Nv7nHY49oVtMb7UqXAM:bb7fwu3) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L80)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I think we need to discuss this part, because I can't imagine it not working with pipe's as it's so popular.
</blockquote></details>

You're right I just saw in a rustdoc comment that using `with_values` instead of `new` in MockCmd allows me to mock a pipeline.

```
    /// Create a new `MockCommand` given a Redis command/pipeline and a vector of value convertible
    /// to a `redis::Value` or a `RedisError`.
```


<!-- Sent from Reviewable.io -->

2024-04-10 17:32 UTC, blakehatch reviewed
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-22.04, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 14 discussions need to be resolved

___
*[`nativelink-config/src/stores.rs` line 601 at r9](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nv7aZnh-jeVVgTZXChP:-Nv80sqL4uMqyIHV6T1r:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/d12d78f46a5dd91acf56e2f60e723592376eb1bc/nativelink-config/src/stores.rs#L601)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: just make this `#[serde(default)]` Then when it's being used check if it's zero and then set it to a constant.
</blockquote></details>

Done.
___
*[`nativelink-config/src/stores.rs` line 603 at r9](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nv5KUTJDFpT1nokn_cn:-Nv80Mzy7XxtpxcUzOlL:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/d12d78f46a5dd91acf56e2f60e723592376eb1bc/nativelink-config/src/stores.rs#L603)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: extra `///` are here
</blockquote></details>

Done.
___
*[`nativelink-config/src/stores.rs` line 605 at r9](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nv7aLbFEa6wOC2yNHOF:-Nv80Q1d3mAdUABCMEJN:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/d12d78f46a5dd91acf56e2f60e723592376eb1bc/nativelink-config/src/stores.rs#L605)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: `response_timeout_s`
</blockquote></details>

Done.
___
*[`nativelink-config/src/stores.rs` line 607 at r9](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nv7aoYTCcBJSx6MUlrO:-Nv80Qno0pX_OQ859mDi:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/d12d78f46a5dd91acf56e2f60e723592376eb1bc/nativelink-config/src/stores.rs#L607)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 33 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUu8ZoBh9nrzFfC4Dz:-Nv83BR_6FmJHBGT0OuS:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L33)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Generally the pattern we use in nativelink is to use `new_with_conn_and_name_generator()` or something.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 79 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuV7cpc9XDTFU6-5Mxs:-Nv8-neW7JShS2q7kkzn:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L79)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

No, it only includes the string representation of the hash, not the size.

```rs
format!("{}-{}", digest.hash_str(), digest.size_bytes)
```

Otherwise we won't be following spec. The size is part of the unique key.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 80 at r8](https://reviewable.io/reviews/tracemachina/nativelink/393#-NuUxEMR3sWzOOo5lpTr:-Nv7zyLN5ElH2JWq8rZY:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/93be3e6ae07f26be8c8ee5d95d6d291f114064d7/nativelink-store/src/redis_store.rs#L80)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

You're right I just saw in a rustdoc comment that using `with_values` instead of `new` in MockCmd allows me to mock a pipeline.

```
    /// Create a new `MockCommand` given a Redis command/pipeline and a vector of value convertible
    /// to a `redis::Value` or a `RedisError`.
```
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 46 at r9](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nv7bMWv0fKzVmYPeaFn:-Nv80gQO0h1ALQEGPyCl:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/d12d78f46a5dd91acf56e2f60e723592376eb1bc/nativelink-store/src/redis_store.rs#L46)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: `message here`.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 76 at r9](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nv7eHpO5ogjmUbbVIss:-Nv8-grl0Tk1LINEntsL:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/d12d78f46a5dd91acf56e2f60e723592376eb1bc/nativelink-store/src/redis_store.rs#L76)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

lets not call this and instead only use `strlen`. The problem with doing this is that `strlen` returns zero if the payload does not exist, which we need to handle when the payload really is zero.

To get around this there's some utility code that we have in: `cas_utils::is_zero_digest()` that we can use during upload/download to bypass this, because zero digests must ALWAYS exist even if they have not been uploaded according to bazel spec.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 82 at r9](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nv7cFCH5WYTxZZJs07K:-Nv80Ay_1hJbiEUrw8LP:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/d12d78f46a5dd91acf56e2f60e723592376eb1bc/nativelink-store/src/redis_store.rs#L82)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: ditto.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-19 19:00 UTC, allada requested changes
> Reviewed 2 of 7 files at r9, 1 of 7 files at r11, 4 of 6 files at r12, 7 of 7 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 22 discussions need to be resolved

___
*[`nativelink-config/src/stores.rs` line 601 at r12](https://reviewable.io/reviews/tracemachina/nativelink/393#-NvlkBCB9KcTb0bLqg2d:-NvlkBCB9KcTb0bLqg2e:brm6u7r) ([raw file](https://github.com/tracemachina/nativelink/blob/c334ebbea1a8e8fec9158e427909b8ab502e764b/nativelink-config/src/stores.rs#L601)):*
> ```XML
> #[derive(Serialize, Deserialize, Debug, Clone)]
> pub struct RedisStore {
>     //(TODO: Reduce to 80 characters)
> ```

reminder
___
*[`nativelink-config/src/stores.rs` line 608 at r12](https://reviewable.io/reviews/tracemachina/nativelink/393#-NvlkOlW7rBdMWqdkhh6:-NvlkOlW7rBdMWqdkhh7:b-sf4u1h) ([raw file](https://github.com/tracemachina/nativelink/blob/c334ebbea1a8e8fec9158e427909b8ab502e764b/nativelink-config/src/stores.rs#L608)):*
> ```XML
>     pub addresses: Vec<String>,
> 
>     #[serde(default)]
> ```

nit: Styling, we put these under the comments.
___
*[`nativelink-store/src/redis_store.rs` line 75 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nvre5BA1h8xrbl0Hrli:-Nvre5BA1h8xrbl0Hrlj:b-a8n6k7) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/src/redis_store.rs#L75)):*
> ```XML
> 
>         // Start connecting to redis, but don't block our construction on it.
>         tokio::spawn(conn_fut.clone());
> ```

nit: Lets wrap this and print any errors this future returns to `error!()`, this will give a nice startup error if it cannot connect, rather than having to wait for a request to come in before erroring.
___
*[`nativelink-store/src/redis_store.rs` line 136 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-NvreUOT221caXzC1kKx:-NvreUOT221caXzC1kKy:bbau6si) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/src/redis_store.rs#L136)):*
> ```XML
>             .query_async::<_, Vec<usize>>(&mut conn)
>             .await
>             .map_err(from_redis_err)?;
> ```

nit: Needs `err_tip`
___
*[`nativelink-store/src/redis_store.rs` line 170 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nvrf5Pg5XologR1ONNR:-Nvrf5Pg5XologR1ONNS:bozp3l4) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/src/redis_store.rs#L170)):*
> ```XML
> 
>         let mut first_run = true;
>         while first_run || !reader.is_empty() {
> ```

There's a bug here, this needs to be wrapped in another `loop`.

Sadly because this was caught in code review we need to write a test for this too.

The condition case is we need to send a few packets in, but then yield, then send the rest of the packets. With the way the code is written right now, it won't receive those last packets and it'll commit them partially.
___
*[`nativelink-store/src/redis_store.rs` line 198 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-NvrfUtwExI7jfEX9XZI:-NvrfUtwExI7jfEX9XZJ:b-qj4yg3) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/src/redis_store.rs#L198)):*
> ```XML
>             tokio::task::yield_now().await;
> 
>             pipe.query_async(&mut conn)
> ```

once the above comment is addressed, this needs to be moved to the outer loop.
___
*[`nativelink-store/tests/redis_store_test.rs` line 60 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nvrgi-5DLDSq88Heoc0:-Nvrgi-5DLDSq88Heoc1:b848mxa) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/tests/redis_store_test.rs#L60)):*
> ```XML
>                     command.arg(arg);
>                 }
>                 for res in result.as_ref().unwrap().iter() {
> ```

nit: Why `.unwrap()` here? Maybe using `RedisResult` is not the right one?
___
*[`nativelink-store/tests/redis_store_test.rs` line 62 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nvrgy1R2LNyJ62akoQo:-Nvrgy1R2LNyJ62akoQp:b-lsjvio) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/tests/redis_store_test.rs#L62)):*
> ```XML
>                 for res in result.as_ref().unwrap().iter() {
>                     res_vec.push(res.clone());
>                     println!("{:?}", res.clone());
> ```

nit: Remove.
___
*[`nativelink-store/tests/redis_store_test.rs` line 135 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-NvriJkY-sUstmJidUgM:-NvriJkY-sUstmJidUgN:b7gtcd6) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/tests/redis_store_test.rs#L135)):*
> ```XML
>         let data = Bytes::from_static(b"");
> 
>         let digest = DigestInfo::new(
> ```

make `ZERO_BYTE_DIGESTS` public then import it here, so we don't need to do this.
___
*[`nativelink-store/tests/redis_store_test.rs` line 143 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-NvriUTB9ucZvqOkrz5G:-NvriUTB9ucZvqOkrz5H:b-wl5xe) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/tests/redis_store_test.rs#L143)):*
> ```XML
>             0,
>         );
>         let dl = data.len();
> ```

nit: unused.
___
*[`nativelink-store/tests/redis_store_test.rs` line 144 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-NvriRT321MPXX314A-2:-NvriRT321MPXX314A-3:b-lsjvio) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/tests/redis_store_test.rs#L144)):*
> ```XML
>         );
>         let dl = data.len();
>         println!("DATA LEN: {dl:?}");
> ```

nit: Remove.
___
*[`nativelink-store/tests/redis_store_test.rs` line 148 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nvribd_3Np_aJXz7Q4I:-Nvribd_3Np_aJXz7Q4J:bilygjg) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/tests/redis_store_test.rs#L148)):*
> ```XML
>         let redis_connection = MockRedisConnectionBuilder::new()
>             .cmd("RENAME", &[TEMP_UUID, &digest.clone().hash_str()], Ok("1"))
>             .pipe(&[(
> ```

this one should not happen. I'm pretty sure it should not have any redis calls.


<!-- Sent from Reviewable.io -->

2024-04-19 21:50 UTC, blakehatch reviewed
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 16 discussions need to be resolved

___
*[`nativelink-config/src/stores.rs` line 601 at r12](https://reviewable.io/reviews/tracemachina/nativelink/393#-NvlkBCB9KcTb0bLqg2d:-NvrmS_M4FBIH-TAObWA:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/c334ebbea1a8e8fec9158e427909b8ab502e764b/nativelink-config/src/stores.rs#L601)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

reminder
</blockquote></details>

Done.
___
*[`nativelink-config/src/stores.rs` line 608 at r12](https://reviewable.io/reviews/tracemachina/nativelink/393#-NvlkOlW7rBdMWqdkhh6:-NvrlwbZAEjbruhk-GhN:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/c334ebbea1a8e8fec9158e427909b8ab502e764b/nativelink-config/src/stores.rs#L608)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Styling, we put these under the comments.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 75 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nvre5BA1h8xrbl0Hrli:-NvruX-z5IjHJtna60kN:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/src/redis_store.rs#L75)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Lets wrap this and print any errors this future returns to `error!()`, this will give a nice startup error if it cannot connect, rather than having to wait for a request to come in before erroring.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 136 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-NvreUOT221caXzC1kKx:-Nvruq472krmAIlrS1hI:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/src/redis_store.rs#L136)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Needs `err_tip`
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 170 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nvrf5Pg5XologR1ONNR:-Nvs3hFFCjrifI59Kfa6:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/src/redis_store.rs#L170)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

There's a bug here, this needs to be wrapped in another `loop`.

Sadly because this was caught in code review we need to write a test for this too.

The condition case is we need to send a few packets in, but then yield, then send the rest of the packets. With the way the code is written right now, it won't receive those last packets and it'll commit them partially.
</blockquote></details>

Done.
___
*[`nativelink-store/src/redis_store.rs` line 198 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-NvrfUtwExI7jfEX9XZI:-NvrxszZEiVeMjTL-QdK:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/src/redis_store.rs#L198)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

once the above comment is addressed, this needs to be moved to the outer loop.
</blockquote></details>

Done.
___
*[`nativelink-store/tests/redis_store_test.rs` line 60 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nvrgi-5DLDSq88Heoc0:-NvrvDImDXrxUvtBImdK:b-ze4fa0) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/tests/redis_store_test.rs#L60)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Why `.unwrap()` here? Maybe using `RedisResult` is not the right one?
</blockquote></details>

The pipe returns a RedisResult which contains multiple items when the value is a Bulk, I then need to pass these into MockCmd::with_values which takes a vec of results so I need to unwrap to convert the value into the vec form.

```
    fn execute_transaction(&self, con: &mut dyn ConnectionLike) -> RedisResult<Value> {
        let mut resp = con.req_packed_commands(
            &encode_pipeline(&self.commands, true),
            self.commands.len() + 1,
            1,
        )?;
        match resp.pop() {
            Some(Value::Nil) => Ok(Value::Nil),
            Some(Value::Bulk(items)) => Ok(self.make_pipeline_results(items)),
            _ => fail!((
                ErrorKind::ResponseError,
                "Invalid response when parsing multi response"
            )),
        }
```
___
*[`nativelink-store/tests/redis_store_test.rs` line 62 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nvrgy1R2LNyJ62akoQo:-Nvrw5KI7h7dc3Y7vOu0:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/tests/redis_store_test.rs#L62)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Remove.
</blockquote></details>

Done.
___
*[`nativelink-store/tests/redis_store_test.rs` line 135 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-NvriJkY-sUstmJidUgM:-NvrxuX30Vx4v_vwe3IL:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/tests/redis_store_test.rs#L135)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

make `ZERO_BYTE_DIGESTS` public then import it here, so we don't need to do this.
</blockquote></details>

Done.
___
*[`nativelink-store/tests/redis_store_test.rs` line 143 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-NvriUTB9ucZvqOkrz5G:-NvrwApp6ODwu-2L7YoQ:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/tests/redis_store_test.rs#L143)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: unused.
</blockquote></details>

Done.
___
*[`nativelink-store/tests/redis_store_test.rs` line 144 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-NvriRT321MPXX314A-2:-Nvrw8f_Bz-5CgaM5U4Z:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/tests/redis_store_test.rs#L144)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Remove.
</blockquote></details>

Done.
___
*[`nativelink-store/tests/redis_store_test.rs` line 148 at r13](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nvribd_3Np_aJXz7Q4I:-Nvrwtku0iZ_izbYGaU7:byoimdz) ([raw file](https://github.com/tracemachina/nativelink/blob/6c2982f776d37f14bb9ad933c5bf6678e8793967/nativelink-store/tests/redis_store_test.rs#L148)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

this one should not happen. I'm pretty sure it should not have any redis calls.
</blockquote></details>

Done. It actually wasn't calling them I didn't realize the test crate doesn't error out from extra calls just when it doesn't match up the calls that happen.


<!-- Sent from Reviewable.io -->

2024-04-19 22:08 UTC, allada reviewed
> Reviewed 4 of 4 files at r14, all commit messages.
> Dismissed @MarcusSorealheis and @aaronmondal from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 12 discussions need to be resolved

___
*[`nativelink-store/tests/redis_store_test.rs` line 232 at r14](https://reviewable.io/reviews/tracemachina/nativelink/393#-NvsOa7xDErDhV9lCHET:-NvsOa7xDErDhV9lCHEU:byuytnn) ([raw file](https://github.com/tracemachina/nativelink/blob/414f01f89a35ddee3fa58a0e3c886b8dc6eec410/nativelink-store/tests/redis_store_test.rs#L232)):*
> ```XML
>     #[tokio::test]
>     async fn yield_between_sending_packets_in_update() -> Result<(), Error> {
>         let data: Bytes = Bytes::from(vec![0u8; 10 * 1024]);
> ```

nit: Don't declare the type when it's already clear.


<!-- Sent from Reviewable.io -->

2024-04-19 22:08 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393#-:-NvsOsx82dPzej-nd4c-:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 12 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-04-19 22:08 UTC, allada reviewed
> Dismissed @MarcusSorealheis from a discussion.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 11 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-04-19 22:09 UTC, allada reviewed
> Dismissed @aaronmondal from 6 discussions.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 10 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-04-20 03:49 UTC, blakehatch reviewed
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 9 discussions need to be resolved

___
*[`nativelink-store/tests/redis_store_test.rs` line 232 at r14](https://reviewable.io/reviews/tracemachina/nativelink/393#-NvsOa7xDErDhV9lCHET:-NvtaisYElx7voj_-0qK:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/414f01f89a35ddee3fa58a0e3c886b8dc6eec410/nativelink-store/tests/redis_store_test.rs#L232)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Don't declare the type when it's already clear.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-21 23:32 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393#-:-Nw2-BpYA7WZ6FsEzTtA:bnfp4nl)* status: 2 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 9 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-04-22 04:10 UTC, allada reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 2 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 9 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-04-22 18:44 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393)* status: 2 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 10 discussions need to be resolved

___
*[`nativelink-store/tests/redis_store_test.rs` line 34 at r15](https://reviewable.io/reviews/tracemachina/nativelink/393#-Nw66VGK1tQ7GE0rzKoX:-Nw66VGL889GC5Z_zMNR:b-lfu8rh) ([raw file](https://github.com/tracemachina/nativelink/blob/a6126e10b1377c7ee2cea24791bd0d10b8758326/nativelink-store/tests/redis_store_test.rs#L34)):*
> ```XML
> 
> fn mock_uuid_generator() -> String {
>     uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000")
> ```

nit: try something like:

```rs
const UUID: &str = "550e8400-e29b-41d4-a716-446655440000";
const TEMP_UUID: &str = concat!("temp-", UUID);

fn mock_uuid_generator() -> String {
  UUID.to_string()
}
```

Or better yet replace all `mock_uuid_generator` calls with `|| UUID.to_string()`


<!-- Sent from Reviewable.io -->

2024-04-22 20:19 UTC, aaronmondal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/393#-:-Nw6SaYH59wPbFkLdM8X:bnfp4nl)* status: 3 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13, Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), windows-2022 / stable, and 1 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-04-22 20:34 UTC, merged