Removes Dash from our Name for Simplicity
TraceMachina/nativelink pull request #463
Opened 2023-12-09 06:33 UTC by MarcusSorealheis

# Description

renames everything but need to generate new protos.

Fixes # (issue)

## Type of change

Docs

Please delete options that are not relevant.

- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

CI

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2023-12-09 07:15 UTC, MarcusSorealheis commented
fixed protos

2023-12-10 16:54 UTC, blakehatch requested changes
Lots of errors with screaming snake case, I would figure out a way to replace "nativelink_" with "NATIVELINK_" although there are a smaller number of cases where it is regular snake case and shouldn't be replaced. Probably should figure out how to grep whether the character after _ is lowercase or not to handle that case.

> Reviewed 163 of 166 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/463#-:-NlJYAus83YnXzpRmPKQ:b-8al06b)* status: all files reviewed, 103 unresolved discussions (waiting on @aaronmondal, @allada, and @MarcusSorealheis)

___
*[`run_integration_tests.sh` line 87 at r2](https://reviewable.io/reviews/tracemachina/nativelink/463#-NlJWHHq7yi9AW5uoOIV:-NlJWHHq7yi9AW5uoOIW:brhjamr) ([raw file](https://github.com/tracemachina/nativelink/blob/9c546e8b194837027862a3ca49129a64d1e9feca/run_integration_tests.sh#L87)):*
> ```Shell
> DID_FAIL=0
> 
> export nativelink_DIR="$CACHE_DIR/nativelink"
> ```

Fix screaming snake case so it is "NATIVELINK_DIR"
___
*[`run_integration_tests.sh` line 93 at r2](https://reviewable.io/reviews/tracemachina/nativelink/463#-NlJWXPa4t56KeoKXSO5:-NlJWXPa4t56KeoKXSO6:b-7ropln) ([raw file](https://github.com/tracemachina/nativelink/blob/9c546e8b194837027862a3ca49129a64d1e9feca/run_integration_tests.sh#L93)):*
> ```Shell
>   find "$SELF_DIR/integration_tests/" -name "$pattern" -type f -print0 | while IFS= read -r -d $'\0' fullpath; do
>     # Cleanup.
>     echo "Cleaning up cache directories TURBOC_CACHE_DIR: $nativelink_DIR"
> ```

ditto
___
*[`run_integration_tests.sh` line 94 at r2](https://reviewable.io/reviews/tracemachina/nativelink/463#-NlJWYZj50cSo7_Sf9_V:-NlJWYZj50cSo7_Sf9_W:b-7ropln) ([raw file](https://github.com/tracemachina/nativelink/blob/9c546e8b194837027862a3ca49129a64d1e9feca/run_integration_tests.sh#L94)):*
> ```Shell
>     # Cleanup.
>     echo "Cleaning up cache directories TURBOC_CACHE_DIR: $nativelink_DIR"
>     echo "Checking for existince of the nativelink_DIR"
> ```

ditto
___
*[`run_integration_tests.sh` line 95 at r2](https://reviewable.io/reviews/tracemachina/nativelink/463#-NlJWZSU-Chl6V6I8-MG:-NlJWZSU-Chl6V6I8-MH:b-7ropln) ([raw file](https://github.com/tracemachina/nativelink/blob/9c546e8b194837027862a3ca49129a64d1e9feca/run_integration_tests.sh#L95)):*
> ```Shell
>     echo "Cleaning up cache directories TURBOC_CACHE_DIR: $nativelink_DIR"
>     echo "Checking for existince of the nativelink_DIR"
>     if [ -d "$nativelink_DIR" ]; then
> ```

ditto
___
*[`run_integration_tests.sh` line 96 at r2](https://reviewable.io/reviews/tracemachina/nativelink/463#-NlJW_ITBQkvIJaVN6RY:-NlJW_ITBQkvIJaVN6RZ:b-7ropln) ([raw file](https://github.com/tracemachina/nativelink/blob/9c546e8b194837027862a3ca49129a64d1e9feca/run_integration_tests.sh#L96)):*
> ```Shell
>     echo "Checking for existince of the nativelink_DIR"
>     if [ -d "$nativelink_DIR" ]; then
>       sudo find "$nativelink_DIR" -delete
> ```

ditto
___
*[`run_integration_tests.sh` line 98 at r2](https://reviewable.io/reviews/tracemachina/nativelink/463#-NlJW_vu8AgJzlBhxkUw:-NlJW_vu8AgJzlBhxkUx:b-7ropln) ([raw file](https://github.com/tracemachina/nativelink/blob/9c546e8b194837027862a3ca49129a64d1e9feca/run_integration_tests.sh#L98)):*
> ```Shell
>       sudo find "$nativelink_DIR" -delete
>     else
>       echo "Directory $nativelink_DIR does not exist."
> ```

ditto
___
*[`deployment-examples/docker-compose/docker-compose.yml` line 27 at r2](https://reviewable.io/reviews/tracemachina/nativelink/463#-NlJWpAt2-Cp9hOppt-p:-NlJWpAt2-Cp9hOppt-q:b-qq8jqr) ([raw file](https://github.com/tracemachina/nativelink/blob/9c546e8b194837027862a3ca49129a64d1e9feca/deployment-examples/docker-compose/docker-compose.yml#L27)):*
> ```YAML
>         - ADDITIONAL_SETUP_WORKER_CMD=${ADDITIONAL_SETUP_WORKER_CMD:-}
>     volumes:
>       - ${nativelink_DIR:-~/.cache/nativelink}:/root/.cache/nativelink
> ```

Fix screaming snake case
___
*[`deployment-examples/docker-compose/docker-compose.yml` line 65 at r2](https://reviewable.io/reviews/tracemachina/nativelink/463#-NlJWtMH2qcOn5AMw20H:-NlJWtMH2qcOn5AMw20I:b-qq8jqr) ([raw file](https://github.com/tracemachina/nativelink/blob/9c546e8b194837027862a3ca49129a64d1e9feca/deployment-examples/docker-compose/docker-compose.yml#L65)):*
> ```YAML
>         - ADDITIONAL_SETUP_WORKER_CMD=${ADDITIONAL_SETUP_WORKER_CMD:-}
>     volumes:
>       - ${nativelink_DIR:-~/.cache/nativelink}:/root/.cache/nativelink
> ```

Fix screaming snake case
___
*[`deployment-examples/docker-compose/README.md` line 46 at r2](https://reviewable.io/reviews/tracemachina/nativelink/463#-NlJWyckCVmz5PTYl-xl:-NlJWyckCVmz5PTYl-xm:b-qq8jqr) ([raw file](https://github.com/tracemachina/nativelink/blob/9c546e8b194837027862a3ca49129a64d1e9feca/deployment-examples/docker-compose/README.md#L46)):*
> ```Markdown
>         - ADDITIONAL_SETUP_WORKER_CMD=${ADDITIONAL_SETUP_WORKER_CMD:-}
>     volumes:
>       - ${nativelink_DIR:-~/.cache/nativelink}:/root/.cache/nativelink
> ```

Fix screaming snake case
___
*[`deployment-examples/docker-compose/README.md` line 102 at r2](https://reviewable.io/reviews/tracemachina/nativelink/463#-NlJX-jNE0i2h876oFx1:-NlJX-jNE0i2h876oFx2:b-qq8jqr) ([raw file](https://github.com/tracemachina/nativelink/blob/9c546e8b194837027862a3ca49129a64d1e9feca/deployment-examples/docker-compose/README.md#L102)):*
> ```Markdown
>         - ADDITIONAL_SETUP_WORKER_CMD=${ADDITIONAL_SETUP_WORKER_CMD:-}
>     volumes:
>       - ${nativelink_DIR:-~/.cache/nativelink}:/root/.cache/nativelink
> ```

Fix screaming snake case
___
*[`deployment-examples/terraform/AWS/scripts/cas.json` line 13 at r2](https://reviewable.io/reviews/tracemachina/nativelink/463#-NlJXJNW3Q8_CKsdShtA:-NlJXJNW3Q8_CKsdShtB:b-qq8jqr) ([raw file](https://github.com/tracemachina/nativelink/blob/9c546e8b194837027862a3ca49129a64d1e9feca/deployment-examples/terraform/AWS/scripts/cas.json#L13)):*
> ```JSON
>               "memory": {
>                 "eviction_policy": {
>                   "max_bytes": "${nativelink_AC_CONTENT_LIMIT:-100000000}",
> ```

Fix screaming snake case
___
*[`deployment-examples/terraform/AWS/scripts/cas.json` line 23 at r2](https://reviewable.io/reviews/tracemachina/nativelink/463#-NlJXLI0CAW6nTXczHkT:-NlJXLI0CAW6nTXczHkU:b-89a4l7) ([raw file](https://github.com/tracemachina/nativelink/blob/9c546e8b194837027862a3ca49129a64d1e9feca/deployment-examples/terraform/AWS/scripts/cas.json#L23)):*
> ```JSON
>               // to distinguish each shard based on the key.
>               "s3_store": {
>                 "region": "${nativelink_AWS_REGION:-us-east-1}",
> ```

Ditto
___
*[`deployment-examples/terraform/AWS/scripts/cas.json` line 24 at r2](https://reviewable.io/reviews/tracemachina/nativelink/463#-NlJXMyP2xVoGkyXpT22:-NlJXMyP2xVoGkyXpT23:b-89a4l7) ([raw file](https://github.com/tracemachina/nativelink/blob/9c546e8b194837027862a3ca49129a64d1e9feca/deployment-examples/terraform/AWS/scripts/cas.json#L24)):*
> ```JSON
>               "s3_store": {
>                 "region": "${nativelink_AWS_REGION:-us-east-1}",
>                 "bucket": "${nativelink_AWS_S3_CAS_BUCKET:-not_set}",
> ```

Ditto
___
*[`deployment-examples/terraform/AWS/scripts/cas.json` line 47 at r2](https://reviewable.io/reviews/tracemachina/nativelink/463#-NlJXNmJ4UauYsNZkr8d:-NlJXNmJ4UauYsNZkr8e:b-89a4l7) ([raw file](https://github.com/tracemachina/nativelink/blob/9c546e8b194837027862a3ca49129a64d1e9feca/deployment-examples/terraform/AWS/scripts/cas.json#L47)):*
> ```JSON
>                   "memory": {
>                     "eviction_policy": {
>                       "max_bytes": "${nativelink_CAS_INDEX_CACHE_LIMIT:-100000000}",
> ```

Ditto
___
*[`deployment-examples/terraform/AWS/scripts/cas.json` line 57 at r2](https://reviewable.io/reviews/tracemachina/nativelink/463#-NlJXOY8AqYpWrTuuwna:-NlJXOY8AqYpWrTuuwnb:b-89a4l7) ([raw file](https://github.com/tracemachina/nativelink/blob/9c546e8b194837027862a3ca49129 [...]

2023-12-11 02:33 UTC, MarcusSorealheis reviewed
I think I fixed all these errors but Reviewable does not update outdated files. 

> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/463#-:-NlLi78m9jpvnSwVRv0z:buy0k0n)* status: 152 of 166 files reviewed, 103 unresolved discussions (waiting on @aaronmondal, @allada, and @blakehatch)



<!-- Sent from Reviewable.io -->

2023-12-11 22:20 UTC, aaronmondal approved these changes
> Reviewed 149 of 166 files at r1, 3 of 3 files at r2, 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/463)* status: all files reviewed, 103 unresolved discussions (waiting on @allada, @blakehatch, and @MarcusSorealheis)



<!-- Sent from Reviewable.io -->

2023-12-11 22:21 UTC, aaronmondal commented
Since cache is failing, you can try to disable/remove these lines:

https://github.com/TraceMachina/nativelink/blob/d26462407cdc04b5a4eb4dc4d46b298db996c43f/.github/workflows/image.yaml#L31-L33

2023-12-11 22:26 UTC, blakehatch approved these changes
Yup all SSC cases look to be fixed, also reviewable did seem to screw something up with the files will have to look into that.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/463#-:-NlPz2-LB8rsMrp2P6lZ:bb0gzmi)* status: all files reviewed, 103 unresolved discussions (waiting on @adam-singer, @allada, and @MarcusSorealheis)



<!-- Sent from Reviewable.io -->

2023-12-12 00:43 UTC, merged