Fix case where filesystem store future dropping causes issues
TraceMachina/nativelink pull request #496
Opened 2023-12-16 22:33 UTC by allada

In a rare case where a file is uploaded, but while the rename() function is called the future is dropped the filesystem store can get into a bad state.

fixes: #495

2023-12-16 22:42 UTC, allada reviewed
+@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/496#-:-Nlomu0L6S-PCWE4F2gO:b-bn1n1c)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @adam-singer)



<!-- Sent from Reviewable.io -->

2023-12-17 08:49 UTC, MarcusSorealheis approved these changes
LGTM

2023-12-17 08:49 UTC, MarcusSorealheis commented on nativelink-store/tests/filesystem_store_test.rs
> +    async fn update_file_future_drops_before_rename() -> Result<(), Error> {
nice

2023-12-18 06:19 UTC, adam-singer requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/496)* status: all files reviewed, 3 unresolved discussions (waiting on @allada)

___
*[`nativelink-store/src/filesystem_store.rs` line 583 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/496#-NlvZ7ms4aJQasBM8ENI:-NlvZ7ms4aJQasBM8ENJ:bgfr8bs) ([raw file](https://github.com/TraceMachina/nativelink/blob/bd61f02ca6f2383e1cc1527f382484aff6b5f5e9/nativelink-store/src/filesystem_store.rs#L583)):*
> ```XML
>                 let from_path = encoded_file_path.get_file_path();
>                 // Internally tokio spawns fs commands onto a blocking thread anyways.
>                 // Since we are already on a blocking thread, we just need the `fs` wrapper to manage
> ```

maybe spell out `std::fs::rename`.

Given its the std::fs::rename it manages open-file permit (via FnOnce) or is the `call_with_permit` missing here?
___
*[`nativelink-util/src/fs.rs` line 246 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/496#-NlvYJ6a1mvBW8DPp9rc:-NlvYJ6a1mvBW8DPp9rd:b-dbus1m) ([raw file](https://github.com/TraceMachina/nativelink/blob/bd61f02ca6f2383e1cc1527f382484aff6b5f5e9/nativelink-util/src/fs.rs#L246)):*
> ```XML
> /// Acquire a permit from the open file semaphore and call a raw function.
> #[inline]
> pub async fn call_with_permit<R>(func: impl FnOnce() -> Result<R, Error>) -> Result<R, Error> {
> ```

Defined but not used? 


<!-- Sent from Reviewable.io -->

2023-12-18 17:51 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/496#-:-Nly2Swi51UxPk4eLNxm:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @allada)



<!-- Sent from Reviewable.io -->

2023-12-18 18:54 UTC, adam-singer approved these changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/496)* status: all files reviewed, 3 unresolved discussions (waiting on @allada)



<!-- Sent from Reviewable.io -->

2024-01-17 22:13 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> Dismissed @MarcusSorealheis from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/496#-:-NoOU7ha3G6F2FUZRyen:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-01-18 01:42 UTC, adam-singer approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/496)* status: 1 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04



<!-- Sent from Reviewable.io -->

2024-01-18 01:42 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/496#-:-NoPDwiFCXXxBfXQtoMV:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04



<!-- Sent from Reviewable.io -->

2024-01-18 14:53 UTC, merged