Add blake3 support for verify store
TraceMachina/nativelink pull request #575
Opened 2023-12-22 10:43 UTC by steed924

# Description

I've added Blake3 hash support Verify Store.
I just used the `digest_hasher` utiliy module to keep consistency.
For simplicity, I just used the default hash function which is set from the global config.
I've done integration tests on my machine to verify blake3 function actually works.
But since the global hash function is `OnceLock` and it can't be set twice, I couldn't add specific unit tests for blake3 and sha256 separately.
May it would be better if we add hash function config variable for the Verify Store Config?
Or is it just adding extra complexity?
I'd like to make this clear.

Fixes #444 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2023-12-22 10:44 UTC, steed924 commented
Hope you to review this. cc: @allada, @MarcusSorealheis, @aaronmondal

2023-12-22 16:14 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/575)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/575#-NmHHvmk0z-NriHBUVTD:-NmHHvmk0z-NriHBUVTE:blhimt) (no related file):*
Sadly I don't think we should do it this way. The original request knows what hash function to use and here we just assume it's the default.

I'd rather do it the right way.

I'm not sure what the best way to do this is. On first glance it feels like adding the hash enum type to `DigestInfo` seems like the right way, but we frequently cast `DigestInfo` into the proto's `Digest` which looses this information.

Another possible option is to change the store api so it passes the digest function along with the requests. This will require a lot of pluming though and should be done in multiple PRs if this is the right way.

As for right now I'm not sure what the best option is.

___


<!-- Sent from Reviewable.io -->

2023-12-22 17:07 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/575)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/575#-NmHHvmk0z-NriHBUVTD:-NmHUO_UEgO4Evvx2srX:bp14ta2) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Sadly I don't think we should do it this way. The original request knows what hash function to use and here we just assume it's the default.

I'd rather do it the right way.

I'm not sure what the best way to do this is. On first glance it feels like adding the hash enum type to `DigestInfo` seems like the right way, but we frequently cast `DigestInfo` into the proto's `Digest` which looses this information.

Another possible option is to change the store api so it passes the digest function along with the requests. This will require a lot of pluming though and should be done in multiple PRs if this is the right way.

As for right now I'm not sure what the best option is.
</blockquote></details>

I thought about this a bit more and did some rough tests to see how difficult it would be for a refactor in this area, and believe that adding a config for what hash function to use on the config for this store is the right way for now.

So if we change the config to support a hash function I think we can proceed.

___


<!-- Sent from Reviewable.io -->

2023-12-22 18:20 UTC, steed924 reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/575)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/575#-NmHHvmk0z-NriHBUVTD:-NmHh3eND6TUACu8LitS:b-it4a14) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I thought about this a bit more and did some rough tests to see how difficult it would be for a refactor in this area, and believe that adding a config for what hash function to use on the config for this store is the right way for now.

So if we change the config to support a hash function I think we can proceed.
</blockquote></details>

Thanks for your feedback, @allada . Let me do work in that way. 

___


<!-- Sent from Reviewable.io -->

2023-12-22 18:54 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/575)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/575#-NmHsGT9BWfmvM3Dnctm:-NmHsGT9BWfmvM3Dnctn:b-1d0yws) (no related file):*
Also needs tests.

___


<!-- Sent from Reviewable.io -->

2023-12-26 16:11 UTC, allada requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/575)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04

___
*[`nativelink-config/src/stores.rs` line 17 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/575#-NmaqLqT1mkvv1pb5OBi:-NmaqLqU0pRgnOjl3cDW:b-s7twh3) ([raw file](https://github.com/TraceMachina/nativelink/blob/e669c0aec0104d1ba3c3745b9c8af22fc0d62e0f/nativelink-config/src/stores.rs#L17)):*
> ```XML
> use serde::{Deserialize, Serialize};
> 
> use crate::cas_server::ConfigDigestHashFunction;
> ```

Lets move this into this crate. By doing this, it creates a circular reference, which is bad practice.
___
*[`nativelink-config/src/stores.rs` line 338 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/575#-NmasdGc6eZ9oCHEoGIx:-NmasdGc6eZ9oCHEoGIy:b-kidtiu) ([raw file](https://github.com/TraceMachina/nativelink/blob/e669c0aec0104d1ba3c3745b9c8af22fc0d62e0f/nativelink-config/src/stores.rs#L338)):*
> ```XML
>     /// This should be set to false for AC, but true for CAS stores.
>     #[serde(default)]
>     pub verify_hash: bool,
> ```

nit: Lets rename this:
`hash_verification_function` and make it an `Option<ConfigDigestHashFunction>`

Also add a comment above saying that `None` means it won't verify the hash.
___
*[`nativelink-store/src/verify_store.rs` line 60 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/575#-NmarIRx-QbCWqzz6MJs:-NmarIRx-QbCWqzz6MJt:b-n474mq) ([raw file](https://github.com/TraceMachina/nativelink/blob/e669c0aec0104d1ba3c3745b9c8af22fc0d62e0f/nativelink-store/src/verify_store.rs#L60)):*
> ```XML
>         mut rx: DropCloserReadHalf,
>         size_info: UploadSizeInfo,
>         mut maybe_hasher: Option<([u8; 32], DigestHasher)>,
> ```

nit: Lets split this up. Les pass 
___
*[`nativelink-store/src/verify_store.rs` line 83 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/575#-Nmar1_i2E4d8mCyFBRi:-Nmar1_i2E4d8mCyFBRj:bq61y34) ([raw file](https://github.com/TraceMachina/nativelink/blob/e669c0aec0104d1ba3c3745b9c8af22fc0d62e0f/nativelink-store/src/verify_store.rs#L83)):*
> ```XML
>                 }
>                 if let Some((original_hash, hasher)) = maybe_hasher.as_mut() {
>                     let hash_result: [u8; 32] = hasher.finalize_digest(i64::try_from(sum_size)?).packed_hash;
> ```

nit: We can't trust this size. But we also don't need it. So instead, lets pass `-1` here and make a comment that this digest is only validating the hash.


<!-- Sent from Reviewable.io -->

2023-12-27 02:01 UTC, MarcusSorealheis requested changes
I'll defer to  Blaise on this one, as I think his comments point in the right direction and you have done some important work to get started. At a high level:

Tests, as Blaise said
Config, as Blaise said. You already have a lot in place for that direction.
The only thing I would think about on the code is making the implementation in `verify_store.rs` less coupled to one hashing algo or another. It should be straightforward but happy to help (or ask someone else) if needed.

Nice work and thank you for the contribution.

2023-12-27 02:01 UTC, MarcusSorealheis commented on nativelink-config/src/stores.rs
> +    /// Default: ConfigDigestHashFunction::sha256
maybe specify what another option might be here in the comments. `Blake3`

2023-12-27 02:01 UTC, MarcusSorealheis commented on nativelink-config/src/cas_server.rs
>  pub enum ConfigDigestHashFunction {
oh, just below the changed line, we have the enum we need. to build upon to support sha256 or Blake3.

2023-12-27 02:01 UTC, MarcusSorealheis commented on nativelink-store/src/verify_store.rs
> +                    self.digest_hash_function.unwrap_or(ConfigDigestHashFunction::sha256),
why is this here? Im confused.

2023-12-27 02:01 UTC, MarcusSorealheis commented on nativelink-store/src/verify_store.rs
> +                if let Some((original_hash, hasher)) = maybe_hasher.as_mut() {
I think the `if let` conditional is fine, but computing the hash should live elsewhere. That way, here you can still have the comparator on current line 84 (`if *original_hash != hash_result`), with which type of hash being used is outside of the block. It should work for either hashing algorithm.

Right now, `hash_result` depends on Blake3 and that would be bad.

2023-12-27 11:11 UTC, steed924 reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/575)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), pre-commit-checks, publish-image, ubuntu-20.04, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/575#-NmHsGT9BWfmvM3Dnctm:-Nmex6n94ZBd4_KuGXiw:b-896fix) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Also needs tests.
</blockquote></details>

Done.

___
___
*[`nativelink-config/src/cas_server.rs` line 548 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/575#gh-1436654169:-NmeyCDs3W6iAI5N0sNb:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e669c0aec0104d1ba3c3745b9c8af22fc0d62e0f/nativelink-config/src/cas_server.rs#L548)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

oh, just below the changed line, we have the enum we need. to build upon to support sha256 or Blake3.
</blockquote></details>

Done.
___
*[`nativelink-config/src/stores.rs` line 17 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/575#-NmaqLqT1mkvv1pb5OBi:-NmeyCsM4MRbEVKO9wUX:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e669c0aec0104d1ba3c3745b9c8af22fc0d62e0f/nativelink-config/src/stores.rs#L17)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Lets move this into this crate. By doing this, it creates a circular reference, which is bad practice.
</blockquote></details>

Done.
___
*[`nativelink-config/src/stores.rs` line 342 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/575#gh-1436640937:-NmeyDph0B3VwTtLwOFz:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e669c0aec0104d1ba3c3745b9c8af22fc0d62e0f/nativelink-config/src/stores.rs#L342)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

maybe specify what another option might be here in the comments. `Blake3`
</blockquote></details>

Done.
___
*[`nativelink-store/src/verify_store.rs` line 82 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/575#gh-1436690298:-NmeyH7PEtISj2QlrpFu:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e669c0aec0104d1ba3c3745b9c8af22fc0d62e0f/nativelink-store/src/verify_store.rs#L82)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

I think the `if let` conditional` is fine, but computing the hash should live elsewhere. That way, here you can still have the comparator on current line 84 (`if *original_hash != hash_result`), with which type of hash being used is outside of the block. It should work for either hashing algorithm.

Right now, `hash_result` depends on Blake3 and that would be bad. 
</blockquote></details>

Done.
___
*[`nativelink-store/src/verify_store.rs` line 146 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/575#gh-1436688467:-NmeyI3Y-GkpBobxwxoC:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e669c0aec0104d1ba3c3745b9c8af22fc0d62e0f/nativelink-store/src/verify_store.rs#L146)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

why is this here? Im confused.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-27 21:33 UTC, allada reviewed
> Reviewed 8 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/575)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

___
*[`nativelink-config/src/stores.rs` line 342 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/575#gh-1436640937:-Nmh6nh-9JEtZNmzxucL:b-ic32gw) ([raw file](https://github.com/TraceMachina/nativelink/blob/e669c0aec0104d1ba3c3745b9c8af22fc0d62e0f/nativelink-config/src/stores.rs#L342)):*
<details><summary><i>Previously, steed924 (Steed) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think we should encourage `blake3`. Sha256 is what the default is for most implementations. Using blake3 requires the client to be setup for blake3 (which none to my knowledge do by default. They all use sha256 by default).

I'd rather just say "Like sha256" and not even mention blake3, since it requires a lot to go right.
___
*[`nativelink-store/src/verify_store.rs` line 141 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/575#-NmhATV346006MOx54R3:-NmhATV346006MOx54R4:b-k7vhl0) ([raw file](https://github.com/TraceMachina/nativelink/blob/c6cd61642d394a019c701f4e38aa40e5e0ef625a/nativelink-store/src/verify_store.rs#L141)):*
> ```XML
>         }
> 
>         let mut hasher = None;
> ```

nit: use (you can inline this too after it's done):
```rs
let hasher = self.hash_verification_function.map(|v| DigestHasher::from(DigestHasherFunc::from(v)));
```
___
*[`nativelink-store/src/verify_store.rs` line 186 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/575#-NmhB9ED-rAuqA2fgYgX:-NmhB9ED-rAuqA2fgYgY:b-i1l87o) ([raw file](https://github.com/TraceMachina/nativelink/blob/c6cd61642d394a019c701f4e38aa40e5e0ef625a/nativelink-store/src/verify_store.rs#L186)):*
> ```XML
>             "If the verification store is verifying the size of the data",
>         );
>         if let Some(hash_verification_function) = self.hash_verification_function {
> ```

nit: Just use:
```rs
c.publish("hash_verification_function", format!("{:?}", self.hash_verification_function));
```


<!-- Sent from Reviewable.io -->

2023-12-27 23:21 UTC, steed924 reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/575)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), pre-commit-checks, publish-image, ubuntu-20.04, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

___
*[`nativelink-config/src/stores.rs` line 342 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/575#gh-1436640937:-Nmh_B5r0xXVvoS3cJ-W:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/e669c0aec0104d1ba3c3745b9c8af22fc0d62e0f/nativelink-config/src/stores.rs#L342)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I don't think we should encourage `blake3`. Sha256 is what the default is for most implementations. Using blake3 requires the client to be setup for blake3 (which none to my knowledge do by default. They all use sha256 by default).

I'd rather just say "Like sha256" and not even mention blake3, since it requires a lot to go right.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-28 00:48 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 11 files at r3, 2 of 2 files at r4, all commit messages.
> Dismissed @MarcusSorealheis from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/575#-:-NmhtEy4EYCVKDoOo8WM:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, pre-commit-checks



<!-- Sent from Reviewable.io -->

2024-01-02 18:32 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/575#-:-NnARkhc4oNzTITaxcLP:bnfp4nl)* status: 2 of 1 LGTMs obtained, and pending CI: pre-commit-checks



<!-- Sent from Reviewable.io -->

2024-01-05 04:11 UTC, MarcusSorealheis approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/575)* status: 2 of 1 LGTMs obtained, and pending CI: pre-commit-checks



<!-- Sent from Reviewable.io -->

2024-01-05 04:12 UTC, MarcusSorealheis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/575#-:-NnMoWhHALtAxiFKt3r5:bnfp4nl)* status: 3 of 1 LGTMs obtained, and pending CI: pre-commit-checks



<!-- Sent from Reviewable.io -->

2024-01-08 21:46 UTC, allada approved these changes
@steed924 , can you rebase and we'll get this landed.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/575#-:-Nnf1fFA4cWiD3mmZiZI:btfdaee)* status: 3 of 1 LGTMs obtained, and pending CI: pre-commit-checks



<!-- Sent from Reviewable.io -->

2024-01-08 21:58 UTC, steed924 commented
> @steed924 , can you rebase and we'll get this landed.
> 
> > _[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/575#-:-Nnf1fFA4cWiD3mmZiZI:btfdaee)_ status: 3 of 1 LGTMs obtained, and pending CI: pre-commit-checks

Just done.

2024-01-09 15:10 UTC, aaronmondal approved these changes
FYI @steed924 The failing CI job are the pre-commit hooks. I think it's trailing whitespace in the README.
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/575#-:-NnikLYy94HoDawf6adk:b-vrx0zk)* status: 4 of 1 LGTMs obtained, and pending CI: pre-commit-checks



<!-- Sent from Reviewable.io -->

2024-01-09 17:10 UTC, steed924 commented
> FYI @steed924 The failing CI job are the pre-commit hooks. I think it's trailing whitespace in the README. <img alt=":lgtm:" width="61" height="20" src="https://camo.githubusercontent.com/8b6b85592234eb2e495981b9faffb5423a6b40eca0f02d87e8b28c73b95dcd6d/68747470733a2f2f72657669657761626c652e696f2f6c67746d2e706e67">
> 
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/575#-:-NnikLYy94HoDawf6adk:b-vrx0zk)_ status: 4 of 1 LGTMs obtained, and pending CI: pre-commit-checks

Thanks, @aaronmondal . Just fixed that issue. ;)

2024-01-09 17:42 UTC, merged