Evict on touch failure
TraceMachina/nativelink pull request #613
Opened 2024-01-17 16:11 UTC by chrisstaite-menlo

# Description

There's an unknown failure occuring under load where the filesystem store ends up with an entry in the temp path that doesn't exist.  I can't find that fault, but rather than persisting, it makes sense to avoid the failure persisting by removing it from the eviciting map in that case.

Therefore, this change introduces a change to the LenEntry such that touch() returns a bool.  If it returns false then it is removed from the EvictingMap immediately.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Running the code up on my cluster.

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-01-17 20:22 UTC, adam-singer reviewed
@chrisstaite-menlo there are some similarities in problem and solution at https://github.com/TraceMachina/nativelink/pull/601 , would you want to pull in that pr and see if it solves issue? I think there are bits that could be merged in terms of implementation here. What isn't obvious is how the unit tests aren't failing with this patch compared to #601     

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/613#-:-NoO3c6xDmBWDU8Kp_v_:b-86zlfi)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04



<!-- Sent from Reviewable.io -->

2024-01-17 21:13 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/613)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/613#-NoOFQvs4X0yTa2v_5qI:-NoOFQvs4X0yTa2v_5qJ:b56j5g6) (no related file):*
Is it possible the root cause is what is being addressed in:
https://github.com/TraceMachina/nativelink/pull/496

?

What you would be seeing is the file being added to the eviction map, the future then is dropped before `fs::rename` happens. This results in:
```rs
            encoded_file_path.path_type = PathType::Content;
            encoded_file_path.digest = final_digest;
```

never being triggered, so the entry in the evicting map is now pointing to the wrong file, and the file ends up being in temp, but not reachable.

___


<!-- Sent from Reviewable.io -->

2024-01-19 11:24 UTC, chrisstaite-menlo commented
*[`nativelink-util/src/evicting_map.rs` line 308 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/613#-NoWSluj-Uvw8OHJJTUv:-NoWSluj-Uvw8OHJJTUw:bboasiv) ([raw file](https://github.com/TraceMachina/nativelink/blob/067eccd2f7bbf9fe77749ab86d2fc163e2992bae/nativelink-util/src/evicting_map.rs#L308)):*
> ```XML
>                         // Important to track the eviction size, otherwise if we
>                         // reach the maximum we end up eviciting everything!
>                         sum_store_size -= entry.data.len() as u64;
> ```

@allada @adam-singer In implementing this I spotted this fatal bug!


<!-- Sent from Reviewable.io -->

2024-01-19 11:57 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/613)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04)

___
*[`nativelink-util/src/evicting_map.rs` line 338 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/613#-NoW_Hyd71ysJb-xhYQ_:-NoW_Hyd71ysJb-xhYQa:b-to8piw) ([raw file](https://github.com/TraceMachina/nativelink/blob/554bd6732cb68115b130ed63c479e9f8ef7bf283/nativelink-util/src/evicting_map.rs#L338)):*
> ```XML
>             async move {
>                 for digest in remove_digests {
>                     // Do not use inner_remove as it calls evict_items, which
> ```

And this one too...


<!-- Sent from Reviewable.io -->

2024-01-24 00:48 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/613)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-util/src/evicting_map.rs` line 308 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/613#-NoWSluj-Uvw8OHJJTUv:-Nosut1Y-xh_wcNDL1uI:b-cdvq37) ([raw file](https://github.com/TraceMachina/nativelink/blob/067eccd2f7bbf9fe77749ab86d2fc163e2992bae/nativelink-util/src/evicting_map.rs#L308)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

@allada @adam-singer In implementing this I spotted this fatal bug!
</blockquote></details>

wow great catch! Guessing our tests don't have something around eviction for `max_bytes` / `max_count` settings. Could you include test coverage for that in fixing this bug? Should be able to get a few tests in that validate this as a bug and provide the tests as a protection against regression, `evicting_map_test.rs` and adjusting the  `EvictionPolicy` should be enough to provide/show/protect against it again

```
&EvictionPolicy {
                max_count: 0,
                max_seconds: 0,
                max_bytes: 0,
                evict_bytes: 0,
            },
```
___
*[`nativelink-util/src/evicting_map.rs` line 338 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/613#-NoW_Hyd71ysJb-xhYQ_:-NosvxI74-v0hKdxqQxn:b-28jtts) ([raw file](https://github.com/TraceMachina/nativelink/blob/554bd6732cb68115b130ed63c479e9f8ef7bf283/nativelink-util/src/evicting_map.rs#L338)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

And this one too...
</blockquote></details>

another great catch! Was hoping for the freebie on that call :/ 


<!-- Sent from Reviewable.io -->

2024-01-26 09:52 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/613)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-util/src/evicting_map.rs` line 308 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/613#-NoWSluj-Uvw8OHJJTUv:-Np4AKYi3dY-GL0St1cM:by2n9do) ([raw file](https://github.com/TraceMachina/nativelink/blob/067eccd2f7bbf9fe77749ab86d2fc163e2992bae/nativelink-util/src/evicting_map.rs#L308)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

wow great catch! Guessing our tests don't have something around eviction for `max_bytes` / `max_count` settings. Could you include test coverage for that in fixing this bug? Should be able to get a few tests in that validate this as a bug and provide the tests as a protection against regression, `evicting_map_test.rs` and adjusting the  `EvictionPolicy` should be enough to provide/show/protect against it again

```
&EvictionPolicy {
                max_count: 0,
                max_seconds: 0,
                max_bytes: 0,
                evict_bytes: 0,
            },
```
</blockquote></details>

I'm not actually sure if we can get to this state here now I think about it, because we would have evicted on insertion if we were over the size or length limits, right?  So perhaps this isn't as bad as I thought.  However, the lower call to evict_items for every removal by calling `remove_internal` will have definitely been significantly slower.


<!-- Sent from Reviewable.io -->

2024-01-26 16:36 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/613#-:-Np5cISv3-P-4hK8AVh-:bnfp4nl)* status: 1 of 1 LGTMs obtained

___
*[`nativelink-util/src/evicting_map.rs` line 308 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/613#-NoWSluj-Uvw8OHJJTUv:-Np5awXU4OQ0VpM1qRuV:b-i5c2vj) ([raw file](https://github.com/TraceMachina/nativelink/blob/067eccd2f7bbf9fe77749ab86d2fc163e2992bae/nativelink-util/src/evicting_map.rs#L308)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

I'm not actually sure if we can get to this state here now I think about it, because we would have evicted on insertion if we were over the size or length limits, right?  So perhaps this isn't as bad as I thought.  However, the lower call to evict_items for every removal by calling `remove_internal` will have definitely been significantly slower.
</blockquote></details>

Yeah, evicting on insert was an original design decision. I think the code was safe the way it was, but doing what you have is technically safer.
___
*[`nativelink-util/src/evicting_map.rs` line 298 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/613#-Np5bPhW3jTumBEvXRm8:-Np5bPhW3jTumBEvXRm9:b-5nb5uw) ([raw file](https://github.com/TraceMachina/nativelink/blob/554bd6732cb68115b130ed63c479e9f8ef7bf283/nativelink-util/src/evicting_map.rs#L298)):*
> ```XML
>         let mut lru_len = state.lru.len();
>         let mut sum_store_size = state.sum_store_size;
>         let digest_entries: Vec<Option<T>> = digests
> ```

nit: Maybe call this `to_touch_or_remove` or something?


<!-- Sent from Reviewable.io -->

2024-01-26 17:58 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/613#-:-Np5uyZ_1joWrxYhWXmw:bnfp4nl)* status: 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-01-29 11:05 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/613)* status: 2 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/613#-NoOFQvs4X0yTa2v_5qI:-NpJt9Gu10RPGFTxO9c3:bfbo17u) (no related file):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

That is the root cause, but I think it would be prudent for the EvicitingMap to handle the case where the conditions under it change (such as an external factor deleting a file).  This would allow recovery without restarting the process.
</blockquote></details>

@allada just waiting on a resolution to this comment to merge.

___


<!-- Sent from Reviewable.io -->

2024-01-29 17:14 UTC, allada approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/613)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-01-29 19:28 UTC, merged