GrpcStore retry first
TraceMachina/nativelink pull request #616
Opened 2024-01-17 18:00 UTC by chrisstaite-menlo

# Description

We see the first request in a GrpcStore request failing but this bypasses the retry logic because it's already passed out of the retry function.

Read the first message from the upstream GrpcStore within the retry logic, only exit from the retry logic after the first message was recieved.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-01-17 18:11 UTC, chrisstaite-menlo commented
This was an attempt to fix #610 however, it doesn't appear to have made any difference.

2024-01-17 21:06 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/616)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04

___
*[`nativelink-store/src/grpc_store.rs` line 68 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/616#-NoOAtDG4JEqLJ9qqfZI:-NoOAtDG4JEqLJ9qqfZJ:b-qcqw0u) ([raw file](https://github.com/TraceMachina/nativelink/blob/68564f679f0c81a423798f1497bed8329922bc9c/nativelink-store/src/grpc_store.rs#L68)):*
> ```XML
> }
> 
> struct FirstStream {
> ```

nit: Lets add some documentation above this on why we read the first stream item and how this helps.
___
*[`nativelink-store/src/grpc_store.rs` line 672 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/616#-NoOB3UG7qD1IuowQJvS:-NoOB3UG7qD1IuowQJvT:b-31n45l) ([raw file](https://github.com/TraceMachina/nativelink/blob/68564f679f0c81a423798f1497bed8329922bc9c/nativelink-store/src/grpc_store.rs#L672)):*
> ```XML
> 
>         loop {
>             let message = match future::poll_fn(|cx| Pin::new(&mut stream).poll_next(cx)).await {
> ```

nit: You should be able to import `futures::StreamExt` then call `stream.next().await`
___
*[`nativelink-util/src/buf_channel.rs` line 167 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/616#-NoOBT9r-2ICNZu2NbUm:-NoO903k-6y0wYTSmEEs:bwscjef) ([raw file](https://github.com/TraceMachina/nativelink/blob/68564f679f0c81a423798f1497bed8329922bc9c/nativelink-util/src/buf_channel.rs#L167)):*
> ```XML
>         let maybe_chunk = match self.partial.take() {
>             // Only return bytes if we haven't already reached EOF.
>             Some(result_bytes) => self.close_tx.is_some().then_some(result_bytes),
> ```

Oh interesting.

Lets reword this comment:
```
// `partial` is allowed to have empty bytes that represent EOF, but `self.rx.recv()` should never
// respond with empty bytes as EOF. If the `partial` is an empty bytes pass None to simulate
// the stream's version of EOF.
```
___
*[`nativelink-util/src/buf_channel.rs` line 167 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/616#-NoOEa026ZjGwg0nr_AL:-NoOEa026ZjGwg0nr_AM:biyrjdo) ([raw file](https://github.com/TraceMachina/nativelink/blob/68564f679f0c81a423798f1497bed8329922bc9c/nativelink-util/src/buf_channel.rs#L167)):*
> ```XML
>         let maybe_chunk = match self.partial.take() {
>             // Only return bytes if we haven't already reached EOF.
>             Some(result_bytes) => self.close_tx.is_some().then_some(result_bytes),
> ```

Do we really want to check `self.close_tx`? Shouldn't we just check if `result_bytes` is empty?


<!-- Sent from Reviewable.io -->

2024-01-19 09:40 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/616)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04

___
*[`nativelink-util/src/buf_channel.rs` line 167 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/616#-NoOBT9r-2ICNZu2NbUm:-NoW4gCwCpjVN8VeMQn9:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/68564f679f0c81a423798f1497bed8329922bc9c/nativelink-util/src/buf_channel.rs#L167)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Oh interesting.

Lets reword this comment:
```
// `partial` is allowed to have empty bytes that represent EOF, but `self.rx.recv()` should never
// respond with empty bytes as EOF. If the `partial` is an empty bytes pass None to simulate
// the stream's version of EOF.
```
</blockquote></details>

Done.
___
*[`nativelink-util/src/buf_channel.rs` line 167 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/616#-NoOEa026ZjGwg0nr_AL:-NoW4gWm5per_lPrcxfH:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/68564f679f0c81a423798f1497bed8329922bc9c/nativelink-util/src/buf_channel.rs#L167)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Do we really want to check `self.close_tx`? Shouldn't we just check if `result_bytes` is empty?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-24 01:30 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/616#-:-Not4bCX1mSql1COB-Pr:bnfp4nl)* status: 1 of 1 LGTMs obtained

___
*[`nativelink-store/src/grpc_store.rs` line 72 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/616#-Not3pu3C7fBsrZmytut:-Not3pu3C7fBsrZmytuu:b-xf44ib) ([raw file](https://github.com/TraceMachina/nativelink/blob/76d141ad485b9d79dbdea4f912cdd0843071a6f8/nativelink-store/src/grpc_store.rs#L72)):*
> ```XML
> /// the connection establishes fine, but reading the first byte of the file
> /// fails we have the ability to retry before returning to the caller.
> struct FirstStream {
> ```

nit: wondering out loud if this kind of trick would have been needed if we "warm up" clients, meaning before service is fully ready we do some no-op operations across clients so machinery / connections are established? 
 Does this kind of stream read failure happen regardless even if clients are warn/connected? 


<!-- Sent from Reviewable.io -->

2024-01-24 09:35 UTC, chrisstaite-menlo commented
*[`nativelink-store/src/grpc_store.rs` line 72 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/616#-Not3pu3C7fBsrZmytut:-NouoJOJAywGm3XS0K-g:bqf9xiy) ([raw file](https://github.com/TraceMachina/nativelink/blob/76d141ad485b9d79dbdea4f912cdd0843071a6f8/nativelink-store/src/grpc_store.rs#L72)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: wondering out loud if this kind of trick would have been needed if we "warm up" clients, meaning before service is fully ready we do some no-op operations across clients so machinery / connections are established? 
 Does this kind of stream read failure happen regardless even if clients are warn/connected?
</blockquote></details>

I'm not really sure, I haven't had the issue since the file store fix has been put in place, but having said that I'm also running this code too, so maybe I have?

I am still having horrid issues with a GoAway frame being sent by the upstream store which then appears to drop all requests to that store.  I think we need to add a limit to the number of concurrent upstream GrpcStore requests we perform to avoid this.


<!-- Sent from Reviewable.io -->

2024-01-26 17:50 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Sorry for delay.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/616#-:-Np5tA0P4iMDDOWt5-hf:ba5hwtw)* status: 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-01-26 17:51 UTC, merged