Reenable caching for nix workflows
TraceMachina/nativelink pull request #631
Opened 2024-01-25 07:20 UTC by aaronmondal

This has been fixed upstream. Pull the change in early to speed up all our workflows significantly.

Fixes: https://github.com/TraceMachina/nativelink/issues/464

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2024-01-26 07:35 UTC, MarcusSorealheis requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/631)* status: 0 of 1 LGTMs obtained

___
*[`.github/workflows/image.yaml` line 30 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/631#-Np3g2Q7D7g8nbG6g4ep:-Np3g2Q7D7g8nbG6g4eq:b-orekcg) ([raw file](https://github.com/TraceMachina/nativelink/blob/8ee4ad9c1f693e43c428999bceafdf23f6fcaee1/.github/workflows/image.yaml#L30)):*
> ```YAML
>         with:
>           github-token: ${{ secrets.GITHUB_TOKEN }}
>           # TODO(aaronmondal): Remove after:
> ```

I am seeing this comment a few places but this PR was recently merged. As a result, should we remove it? I wasn't sure what was meant by the comment. Should this section be removed since 820 was merged or does it get skipped after, which is now, since it was just merged?


<!-- Sent from Reviewable.io -->

2024-01-26 16:45 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> % what marcus brought up.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/631#-:-Np5eFcM-zrNK1XnP88J:b6zzrvp)* status: 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-01-26 21:48 UTC, adam-singer approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/631)* status: 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-01-27 04:59 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/631#-:-Np8HKo5D8tpW7-73eO5:bnfp4nl)* status: 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-01-30 04:55 UTC, allada approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/631)* status: 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-01-30 09:18 UTC, MarcusSorealheis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/631#-:-NpOeVye25ZuC6NZwvDI:bnfp4nl)* status: 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-01-30 22:39 UTC, aaronmondal reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/631)* status: 2 of 1 LGTMs obtained

___
*[`.github/workflows/image.yaml` line 30 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/631#-Np3g2Q7D7g8nbG6g4ep:-NpRWcGL6b8AWf6XmXMe:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/8ee4ad9c1f693e43c428999bceafdf23f6fcaee1/.github/workflows/image.yaml#L30)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

I am seeing this comment a few places but this PR was recently merged. As a result, should we remove it? I wasn't sure what was meant by the comment. Should this section be removed since 820 was merged or does it get skipped after, which is now, since it was just merged?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-30 22:40 UTC, aaronmondal reviewed
My bad. Added reviewers in the wrong way.

+@MarcusSorealheis +@adam-singer +@allada 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/631#-:-NpRWlzV8IM0a8lug2BI:b-53hib6)* status: 2 of 3 LGTMs obtained (waiting on @adam-singer)



<!-- Sent from Reviewable.io -->

2024-01-30 22:44 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/631#-:-NpRXpIR8NftPBeNSPKB:bnfp4nl)* status: 2 of 2 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-01-30 22:44 UTC, allada approved these changes
-@MarcusSorealheis

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/631#-:-NpRXs1CAY7yaJUr9mQ3:b8cg3jw)* status: 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-01-30 22:46 UTC, allada approved these changes
> Dismissed @MarcusSorealheis from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/631)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-01-30 22:47 UTC, merged

2024-01-31 00:21 UTC, adam-singer reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/631#-:-NpRt8YJ3PLX6WrY8RWA:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->