Don't retry permanent failures
TraceMachina/nativelink pull request #634
Opened 2024-01-25 13:40 UTC by chrisstaite-menlo

# Description

The retrier always retries on error.  However, some errors are permanent, for example NotFound.  This means that if a request is made to get something from the CAS (or GrpcStore AC) which is not there, it keeps trying even though it's still not there.  This defines the set of errors which shoudl be retried and fails otherwise.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Remote proxy getting data from the action cache now doesn't retry ad infinitum.

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TraceMachina/nativelink/634)

2024-01-26 17:27 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/634)* status: 0 of 1 LGTMs obtained

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/634#-Np5mt-E7nl9S_6pFUbb):*
Actually, I'm not sure we should encode this strictly in the code, instead lets make this a config on every retry config.

Then make what you have the default.

The reason is because some S3 store implementations will return `NotFound` even though the item is there because it's eventual consistency. I is silly, but I've personally seen this and if you delay the read just a few micros it comes into existence.

I suggest make a `ErrorRetryMapping` struct in the config, but super simple, maybe just:
```rs
struct ErrorRetryMapping {
  not_found: bool,
  other: bool,
}
```

We can add more special cases to this later, and the default with be `{ not_found: false, other: true }`.

Thoughts?


<!-- Sent from Reviewable.io -->

2024-01-26 18:08 UTC, chrisstaite-menlo commented
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/634#-Np5mt-E7nl9S_6pFUbb):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Actually, I'm not sure we should encode this strictly in the code, instead lets make this a config on every retry config.

Then make what you have the default.

The reason is because some S3 store implementations will return `NotFound` even though the item is there because it's eventual consistency. I is silly, but I've personally seen this and if you delay the read just a few micros it comes into existence.

I suggest make a `ErrorRetryMapping` struct in the config, but super simple, maybe just:
```rs
struct ErrorRetryMapping {
  not_found: bool,
  other: bool,
}
```

We can add more special cases to this later, and the default with be `{ not_found: false, other: true }`.

Thoughts?
</blockquote></details>

Sure.


<!-- Sent from Reviewable.io -->

2024-01-29 19:50 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/634)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-config/src/stores.rs` line 597 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/634#-NpLALTo5ncSb_I1xD34:-NpLkFDHA-L1fxnTlfAW:bteqvux) ([raw file](https://github.com/TraceMachina/nativelink/blob/7c8a40e3ffed5d0ba9a32d55335bbc6ef210ab03/nativelink-config/src/stores.rs#L597)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

eeh, I've been trying to avoid setting anything that is not default to a non-default value in the config.

I'm actually thinking if maybe we should do this struct as an enum, then have it:

```rs
no_retry_errors: Option<HashSet<ErrorCode>>
```

The nice thing about doing it this way is `ErrorCode` can easily be used in other configs in the future (if needed).
</blockquote></details>

I'd like there to be a set of sensible codes that don't retry by default rather than requiring the user to specify them though, also requiring users to know error codes rather than nice strings seems a bit much.
___
*[`nativelink-error/src/lib.rs` line 315 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/634#-NpLBfbV4iUOXMf6jx0m:-NpLkSV39-DCOCRq2BIh:b-i6j14j) ([raw file](https://github.com/TraceMachina/nativelink/blob/7c8a40e3ffed5d0ba9a32d55335bbc6ef210ab03/nativelink-error/src/lib.rs#L315)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

:-(
</blockquote></details>

Can't have exhaustive `match` outside of a module :'(


<!-- Sent from Reviewable.io -->

2024-01-29 19:51 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/634)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Local / ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable

___
*[`nativelink-config/src/stores.rs` line 597 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/634#-NpLALTo5ncSb_I1xD34:-NpLlXQ606zuo1zTf-Kb:b7vqv7z) ([raw file](https://github.com/TraceMachina/nativelink/blob/7c8a40e3ffed5d0ba9a32d55335bbc6ef210ab03/nativelink-config/src/stores.rs#L597)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

I'd like there to be a set of sensible codes that don't retry by default rather than requiring the user to specify them though, also requiring users to know error codes rather than nice strings seems a bit much.
</blockquote></details>

Perhaps we could rename this to `do_not_retry_other` and then invert the boolean?


<!-- Sent from Reviewable.io -->

2024-01-29 20:10 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/634)* status: 0 of 1 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04)

___
*[`nativelink-util/src/retry.rs` line 97 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/634#-NpLmiKM3961qKVRzw3a:-NpLpsf_62hmolq-_y2C:b-bnway6) ([raw file](https://github.com/TraceMachina/nativelink/blob/7c8a40e3ffed5d0ba9a32d55335bbc6ef210ab03/nativelink-util/src/retry.rs#L97)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: not that we support other backoff functions yet, having backoff as a configuration would be a nice to have, non-blocker and maybe something to explore at a later point in time.  Exponential backoff is def most common/graceful in general scenarios
</blockquote></details>

Yes, that was one of the motivations for moving the configuration into `Retry` so it can be easily modified later without having to modify other parts of the system such as `GrpcStore` or `S3Store`.


<!-- Sent from Reviewable.io -->

2024-01-30 04:54 UTC, allada requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/634)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-config/src/stores.rs` line 597 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/634#-NpLALTo5ncSb_I1xD34:-NpNhFR-5xQVPWgX-JI1:bakp56f) ([raw file](https://github.com/TraceMachina/nativelink/blob/7c8a40e3ffed5d0ba9a32d55335bbc6ef210ab03/nativelink-config/src/stores.rs#L597)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Perhaps we could rename this to `do_not_retry_other` and then invert the boolean?
</blockquote></details>

Oh, I am saying we should default `None` to what you have defaulted now. I'm just afraid we are going to lock ourselves in as we add new implementations of stores that use this retry trait. For example, `RedisStore` might have a spurious bug where the credentials are only updated on failure (sounds dumb, but I'm sure you've seen dumber bugs), to which a user would just want to retry on `Unauthenticated` to get around this issue, but by default we should not do this.

Again, I don't want to block you, I just want to make sure we design our public api's with good thought.


<!-- Sent from Reviewable.io -->

2024-01-31 00:33 UTC, adam-singer approved these changes
> Reviewed 1 of 8 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/634)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-01-31 17:43 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/634)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-config/src/stores.rs` line 597 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/634#-NpLALTo5ncSb_I1xD34:-NpVbVcL1wZntO9QgEYM:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7c8a40e3ffed5d0ba9a32d55335bbc6ef210ab03/nativelink-config/src/stores.rs#L597)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Oh, I am saying we should default `None` to what you have defaulted now. I'm just afraid we are going to lock ourselves in as we add new implementations of stores that use this retry trait. For example, `RedisStore` might have a spurious bug where the credentials are only updated on failure (sounds dumb, but I'm sure you've seen dumber bugs), to which a user would just want to retry on `Unauthenticated` to get around this issue, but by default we should not do this.

Again, I don't want to block you, I just want to make sure we design our public api's with good thought.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-02 02:44 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/634#-:-Npbgyvp0w6s-F-m2Tss:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-02-02 09:32 UTC, merged