Introduce component based health
TraceMachina/nativelink pull request #636
Opened 2024-01-25 19:22 UTC by adam-singer

# Description

Draft

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [ ] Updated documentation if needed
- [x] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-01-25 19:38 UTC, allada commented on nativelink-util/src/health_utils.rs
> +pub trait HealthStatusIndicator<'a>: Sync + Send + Unpin {
`'a` seems to be not-needed.

2024-01-26 08:06 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), pre-commit-checks, publish-image, ubuntu-20.04, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

___
*[`nativelink-util/src/health_utils.rs` line 30 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/636#gh-1466840047:-Np3nCyT7YwFutKD32xl:bt9z32x) ([raw file](https://github.com/TraceMachina/nativelink/blob/355ce2fe207065ba831b5ddd0475e9a85f7f844c/nativelink-util/src/health_utils.rs#L30)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

`'a` seems to be not-needed.
</blockquote></details>

Done. ... When trying to use this trait outside of a test context, ran into a bunch of lifetime problems which probably got infected by pingponging error message suggestions


<!-- Sent from Reviewable.io -->

2024-01-27 03:59 UTC, allada reviewed
+@blakehatch Can you first-pass this?

> Reviewed 2 of 6 files at r1, 5 of 11 files at r2, 5 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636#-:-Np83fMd6WdSfbdTqXn6:bshw0xj)* status: 0 of 1 LGTMs obtained (waiting on @blakehatch)

___
*[`nativelink-util/src/store_trait.rs` line 185 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Np83YPu6E_J86hYqi6I:-Np83YPu6E_J86hYqi6J:bmz1oo4) ([raw file](https://github.com/TraceMachina/nativelink/blob/01188aea8ca9a854c41f0fbe338ab044c73f02d3/nativelink-util/src/store_trait.rs#L185)):*
> ```XML
>     fn register_metrics(self: Arc<Self>, _registry: &mut Registry) {}
> 
>     fn register_health(self: Arc<Self>, _registry: &mut HealthRegistry) {}
> ```

nit: This is a public/stable api, so it needs comments.


<!-- Sent from Reviewable.io -->

2024-01-31 23:52 UTC, blakehatch requested changes
> Reviewed 1 of 11 files at r2, 3 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-util/src/health_utils.rs` line 89 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpWqe5MCYZNPeEkiv17:-NpWqe5MCYZNPeEkiv18:b-se6p70) ([raw file](https://github.com/TraceMachina/nativelink/blob/01188aea8ca9a854c41f0fbe338ab044c73f02d3/nativelink-util/src/health_utils.rs#L89)):*
> ```XML
>         parent_component: &HealthComponent,
>         component: &HealthComponent,
>         indicators: &Vec<Arc<dyn HealthStatusIndicator>>,
> ```

If indicator and registry are turned into slices of `Arc<dyn HealthStatusIndicator>` you should be able to avoid a deep copy. Allowing you to just pass around references to flatten and check health directly while iterating over them.

However, if this is not a large performance bottleneck at the scale this will run I would not recommend refactoring and having to fight the restructured lifetimes.
___
*[`nativelink-util/src/health_utils.rs` line 94 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpWuA2sE1H2wZvDcXZY:-NpWuA2sE1H2wZvDcXZZ:bf91jwz) ([raw file](https://github.com/TraceMachina/nativelink/blob/01188aea8ca9a854c41f0fbe338ab044c73f02d3/nativelink-util/src/health_utils.rs#L94)):*
> ```XML
>         let component_name: Cow<'static, str> = Cow::Owned(format!("{parent_component}/{component}"));
>         for indicator in indicators {
>             let result = indicator.clone().check_health().await;
> ```

Concerned that the deep copy here could be a performance bottleneck.
___
*[`nativelink-util/src/health_utils.rs` line 112 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpWuDtI7dxVMkau2ZmP:-NpWuDtI7dxVMkau2ZmQ:b-89a4l7) ([raw file](https://github.com/TraceMachina/nativelink/blob/01188aea8ca9a854c41f0fbe338ab044c73f02d3/nativelink-util/src/health_utils.rs#L112)):*
> ```XML
>         for registry in registries {
>             let _ = self
>                 .clone()
> ```

Ditto


<!-- Sent from Reviewable.io -->

2024-01-31 23:54 UTC, blakehatch reviewed
Yes 👍

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636#-:-NpWwIztCE9GtNEOGJji:b-wzncpe)* status: 0 of 1 LGTMs obtained (waiting on @blakehatch)



<!-- Sent from Reviewable.io -->

2024-02-01 00:30 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 0 of 1 LGTMs obtained (waiting on @blakehatch)

___
*[`nativelink-util/src/health_utils.rs` line 89 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpWqe5MCYZNPeEkiv17:-NpX3YG640XhmPFRK_63:bq0yryl) ([raw file](https://github.com/TraceMachina/nativelink/blob/01188aea8ca9a854c41f0fbe338ab044c73f02d3/nativelink-util/src/health_utils.rs#L89)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

If indicator and registry are turned into slices of `Arc<dyn HealthStatusIndicator>` you should be able to avoid a deep copy. Allowing you to just pass around references to flatten and check health directly while iterating over them.

However, if this is not a large performance bottleneck at the scale this will run I would not recommend refactoring and having to fight the restructured lifetimes.
</blockquote></details>

Are you suggesting that `indicators: &Vec<Arc<dyn HealthStatusIndicator>>` -> `indicators: &Vec<Arc<&dyn HealthStatusIndicator>>`?
___
*[`nativelink-util/src/health_utils.rs` line 94 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpWuA2sE1H2wZvDcXZY:-NpX3EHj5mVuhtwkdFLH:b-5h6uny) ([raw file](https://github.com/TraceMachina/nativelink/blob/01188aea8ca9a854c41f0fbe338ab044c73f02d3/nativelink-util/src/health_utils.rs#L94)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Concerned that the deep copy here could be a performance bottleneck.
</blockquote></details>

@blakehatch Do you mean deep copy by calling `clone()` here? 


<!-- Sent from Reviewable.io -->

2024-02-01 00:42 UTC, blakehatch commented
> > _[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)_ status: 0 of 1 LGTMs obtained (waiting on @blakehatch)
> 
> _[`nativelink-util/src/health_utils.rs` line 89 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpWqe5MCYZNPeEkiv17:-NpX3YG640XhmPFRK_63:bq0yryl) ([raw file](https://github.com/TraceMachina/nativelink/blob/01188aea8ca9a854c41f0fbe338ab044c73f02d3/nativelink-util/src/health_utils.rs#L89)):_
> 
> Previously, blakehatch (Blake Hatch) wrote…
> Are you suggesting that `indicators: &Vec<Arc<dyn HealthStatusIndicator>>` -> `indicators: &Vec<Arc<&dyn HealthStatusIndicator>>`?
> 
> _[`nativelink-util/src/health_utils.rs` line 94 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpWuA2sE1H2wZvDcXZY:-NpX3EHj5mVuhtwkdFLH:b-5h6uny) ([raw file](https://github.com/TraceMachina/nativelink/blob/01188aea8ca9a854c41f0fbe338ab044c73f02d3/nativelink-util/src/health_utils.rs#L94)):_
> 
> Previously, blakehatch (Blake Hatch) wrote…
> @blakehatch Do you mean deep copy by calling `clone()` here?

`indicators: &Vec<Arc<dyn HealthStatusIndicator>> ` -> `indicators: &[Arc<dyn HealthStatusIndicator>] `.

Also yes I’m referring to making a deep copy by calling clone(). From my understanding cloning a `Vec` in Rust creates a deep copy because it duplicates the Vec's elements and underlying memory of said elements.

2024-02-01 22:02 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @blakehatch)

___
*[`nativelink-util/src/health_utils.rs` line 94 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpWuA2sE1H2wZvDcXZY:-NpagJTB-1YXdBXaDqvy:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/01188aea8ca9a854c41f0fbe338ab044c73f02d3/nativelink-util/src/health_utils.rs#L94)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

`indicators: &Vec<Arc<dyn HealthStatusIndicator>> ` -> `indicators: &[Arc<dyn HealthStatusIndicator>] `.

Also yes I’m referring to making a deep copy by calling clone(). From my understanding cloning a `Vec` in Rust creates a deep copy because it duplicates the Vec's elements and underlying memory of said elements.

</blockquote></details>

Done.
___
*[`nativelink-util/src/health_utils.rs` line 112 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpWuDtI7dxVMkau2ZmP:-NpagL292R1hFpCY8of6:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/01188aea8ca9a854c41f0fbe338ab044c73f02d3/nativelink-util/src/health_utils.rs#L112)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-01 22:03 UTC, blakehatch approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636#-:-NpagfRh1zgMLaUstNEh:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04



<!-- Sent from Reviewable.io -->

2024-02-02 01:54 UTC, allada requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-02-02 18:03 UTC, allada requested changes
> Reviewed 3 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained

___
*[`nativelink-store/src/filesystem_store.rs` line 765 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpezDwP9nyLWY4iSiMR:-NpezDwP9nyLWY4iSiMS:bbxwgg7) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-store/src/filesystem_store.rs#L765)):*
> ```XML
> #[async_trait]
> impl<Fe: FileEntry> HealthStatusIndicator for FilesystemStore<Fe> {
>     async fn check_health(self: Arc<Self>) -> Result<HealthStatus, Error> {
> ```

Hmmm, does it make much sense to use `Result<HealthStatus, Error>`? I mean, if it's an `Error`, shouldn't the `HealthStatus` be able to display it?
___
*[`nativelink-util/src/health_utils.rs` line 1 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpeuHf_4xTRKgOsOvCt:-NpeuHfa2RMYH-X7l5bl:bok2db8) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-util/src/health_utils.rs#L1)):*
> ```XML
> use std::borrow::Cow;
> ```

nit: Needs copyright.
___
*[`nativelink-util/src/health_utils.rs` line 3 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpeuOvs7E7bB6j8Tukx:-NpeuOvs7E7bB6j8Tuky:b-gk7nxf) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-util/src/health_utils.rs#L3)):*
> ```XML
> use std::borrow::Cow;
> use std::fmt::Debug;
> use std::marker::Send;
> ```

nit: I don't think you need this, I think `Send` is brought in by default.
___
*[`nativelink-util/src/health_utils.rs` line 11 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpeupZmE5BBHp7Pj22q:-NpeupZmE5BBHp7Pj22r:b-bpxljb) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-util/src/health_utils.rs#L11)):*
> ```XML
> 
> type HealthComponent = Cow<'static, str>;
> type TypeName = Cow<'static, str>;
> ```

maybe: `MessageLabel`? `TypeName` is confusing to me.

This probably should also be `&'static str`, as I don't think we should allow users to create this willy-nilly.

Actually, can you elaborate on that `TypeName` is? After reading the code, I'm not sure I understand what would normally go here.
___
*[`nativelink-util/src/health_utils.rs` line 74 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpewJIiAA8xJ1_Ot4cF:-NpewJIiAA8xJ1_Ot4cG:bbvxazk) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-util/src/health_utils.rs#L74)):*
> ```XML
>     }
> 
>     pub fn add_dependency(&mut self, component: HealthComponent) -> &mut Self {
> ```

I feel like this is backwards...

Shouldn't it instead be more like?:
```rs
pub fn child_registry(&mut self, registry_name: &str) -> &mut Self {
  let registry = HealthRegistry::new();
  self.registries.push(registry);
  self.registries
            .last_mut()
            .expect("dependencies should not to be empty.")
}
```

And remove the need for a component to be in the registry to start.
___
*[`nativelink-util/src/health_utils.rs` line 123 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npex7NeCUzOOcan4qwn:-Npex7NeCUzOOcan4qwo:bdtorz9) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-util/src/health_utils.rs#L123)):*
> ```XML
>     }
> 
>     pub async fn flatten_indicators(&mut self) -> Vec<HealthStatusDescription> {
> ```

nit: Can we make a better name for this? Maybe: `get_health_status_report` or something?
___
*[`nativelink-util/src/health_utils.rs` line 123 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpexPjC1zVahvOCukYO:-NpexPjC1zVahvOCukYP:b-i5uchh) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-util/src/health_utils.rs#L123)):*
> ```XML
>     }
> 
>     pub async fn flatten_indicators(&mut self) -> Vec<HealthStatusDescription> {
> ```

nit: If you want to be fancy, this could probably be a Stream, this would give slightly more flexibility to the caller and it could respond to each health status as it's received. Example: On first error, it can stop the stream right then and not need to do any more work.

Very minor, but just an fyi.


<!-- Sent from Reviewable.io -->

2024-02-02 18:44 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained

___
*[`nativelink-store/src/filesystem_store.rs` line 765 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpezDwP9nyLWY4iSiMR:-Npf52NwBIx-Nn4Jf2HL:bvc8slj) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-store/src/filesystem_store.rs#L765)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Hmmm, does it make much sense to use `Result<HealthStatus, Error>`? I mean, if it's an `Error`, shouldn't the `HealthStatus` be able to display it?
</blockquote></details>

I think I have shunted a possible `Error` in this implementation, tho I thought `Future`/`async` type signatures required a `Result<R, E>`, I'll try and remove that bit. If so we are saying any future failure of any sort won't be bubbled out with an `Error`, but instead be encoded within `HealthStatus`, which I'm fine with and see the redundancy in expectations
___
*[`nativelink-util/src/health_utils.rs` line 74 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpewJIiAA8xJ1_Ot4cF:-Npf6UkDDdhrkqqrW2VT:b-j4thzl) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-util/src/health_utils.rs#L74)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I feel like this is backwards...

Shouldn't it instead be more like?:
```rs
pub fn child_registry(&mut self, registry_name: &str) -> &mut Self {
  let registry = HealthRegistry::new();
  self.registries.push(registry);
  self.registries
            .last_mut()
            .expect("dependencies should not to be empty.")
}
```

And remove the need for a component to be in the registry to start.
</blockquote></details>

In the case stated, what would be the reasoning for passing `registry_name` if not used for anything? In the implementation provided is a glorified `registry_name` for the dependency added and returned for future mutation. Calling it `child_registry` seems fine to me, beyond that I'm not sure I understand the difference stated.
___
*[`nativelink-util/src/health_utils.rs` line 123 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpexPjC1zVahvOCukYO:-Npf7XsP7Syj91RtWy_U:brmfvx6) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-util/src/health_utils.rs#L123)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: If you want to be fancy, this could probably be a Stream, this would give slightly more flexibility to the caller and it could respond to each health status as it's received. Example: On first error, it can stop the stream right then and not need to do any more work.

Very minor, but just an fyi.
</blockquote></details>

Sounds doable and I'd rather work with streams, tho not sure how much it will require to rework the code flow to adopt it, will look into it


<!-- Sent from Reviewable.io -->

2024-02-02 22:01 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained

___
*[`nativelink-util/src/health_utils.rs` line 1 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpeuHf_4xTRKgOsOvCt:-NpfZ1e7BISYLfoMF63t:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-util/src/health_utils.rs#L1)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Needs copyright.
</blockquote></details>

Done.
___
*[`nativelink-util/src/health_utils.rs` line 3 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpeuOvs7E7bB6j8Tukx:-NpfZATWBuqy2HImVSu9:b7ewn2o) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-util/src/health_utils.rs#L3)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: I don't think you need this, I think `Send` is brought in by default.
</blockquote></details>

```
   Compiling nativelink-util v0.2.0 (/Users/adam/workspace/nativelink-2/nativelink-util)
error[E0277]: `dyn HealthStatusIndicator` cannot be sent between threads safely
   --> nativelink-util/src/health_utils.rs:106:44
    |
106 |             let result = indicator.clone().check_health().await;
    |                                            ^^^^^^^^^^^^ `dyn HealthStatusIndicator` cannot be sent between threads safely
```
___
*[`nativelink-util/src/health_utils.rs` line 11 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpeupZmE5BBHp7Pj22q:-NpfZX-I4RfRNmp4iESu:b2d3e8t) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-util/src/health_utils.rs#L11)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

maybe: `MessageLabel`? `TypeName` is confusing to me.

This probably should also be `&'static str`, as I don't think we should allow users to create this willy-nilly.

Actually, can you elaborate on that `TypeName` is? After reading the code, I'm not sure I understand what would normally go here.
</blockquote></details>

Its the underlying fully qualified type name of the instance registered, for example

```
HealthStatusDescription { component: "/nativelink/stores/AC_MAIN_STORE", status: Ok("nativelink_store::filesystem_store::FilesystemStore", "Successfully filesystem store health check") }
```

It is the `nativelink_store::filesystem_store::FilesystemStore` string that is captured by 

```
    fn type_name(&self) -> TypeName {
        Cow::Borrowed(std::any::type_name::<Self>())
    }
```
___
*[`nativelink-util/src/health_utils.rs` line 123 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npex7NeCUzOOcan4qwn:-Npf_DmvE5v4rRqM-eK8:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-util/src/health_utils.rs#L123)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Can we make a better name for this? Maybe: `get_health_status_report` or something?
</blockquote></details>

Done.
___
*[`nativelink-util/src/health_utils.rs` line 123 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpexPjC1zVahvOCukYO:-Npfp-2Z3OJFK1LO6YHH:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-util/src/health_utils.rs#L123)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Sounds doable and I'd rather work with streams, tho not sure how much it will require to rework the code flow to adopt it, will look into it
</blockquote></details>

Done.
___
*[`nativelink-util/src/store_trait.rs` line 185 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Np83YPu6E_J86hYqi6I:-NpfpeaQAGYh8xz3WEYL:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/01188aea8ca9a854c41f0fbe338ab044c73f02d3/nativelink-util/src/store_trait.rs#L185)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: This is a public/stable api, so it needs comments.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-02 22:06 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`nativelink-util/src/health_utils.rs` line 3 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpeuOvs7E7bB6j8Tukx:-NpfqvC5075BykivDcz1:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-util/src/health_utils.rs#L3)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

```
   Compiling nativelink-util v0.2.0 (/Users/adam/workspace/nativelink-2/nativelink-util)
error[E0277]: `dyn HealthStatusIndicator` cannot be sent between threads safely
   --> nativelink-util/src/health_utils.rs:106:44
    |
106 |             let result = indicator.clone().check_health().await;
    |                                            ^^^^^^^^^^^^ `dyn HealthStatusIndicator` cannot be sent between threads safely
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-02 23:02 UTC, allada reviewed
> Reviewed 5 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-02-04 05:27 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`nativelink-store/src/filesystem_store.rs` line 765 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpezDwP9nyLWY4iSiMR:-NpgHwTGBZNcg56QhiF5:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-store/src/filesystem_store.rs#L765)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

I think I have shunted a possible `Error` in this implementation, tho I thought `Future`/`async` type signatures required a `Result<R, E>`, I'll try and remove that bit. If so we are saying any future failure of any sort won't be bubbled out with an `Error`, but instead be encoded within `HealthStatus`, which I'm fine with and see the redundancy in expectations
</blockquote></details>

Done.
___
*[`nativelink-util/src/health_utils.rs` line 11 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpeupZmE5BBHp7Pj22q:-NpgIwmm9IGBgocq7Cpi:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-util/src/health_utils.rs#L11)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Its the underlying fully qualified type name of the instance registered, for example

```
HealthStatusDescription { component: "/nativelink/stores/AC_MAIN_STORE", status: Ok("nativelink_store::filesystem_store::FilesystemStore", "Successfully filesystem store health check") }
```

It is the `nativelink_store::filesystem_store::FilesystemStore` string that is captured by 

```
    fn type_name(&self) -> TypeName {
        Cow::Borrowed(std::any::type_name::<Self>())
    }
```
</blockquote></details>

Done.
___
*[`nativelink-util/src/health_utils.rs` line 74 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NpewJIiAA8xJ1_Ot4cF:-NpgKJ1U1y1DzldEQ6gw:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/64bef392ef12fe56df7ae988ae9834299efc77b0/nativelink-util/src/health_utils.rs#L74)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

In the case stated, what would be the reasoning for passing `registry_name` if not used for anything? In the implementation provided is a glorified `registry_name` for the dependency added and returned for future mutation. Calling it `child_registry` seems fine to me, beyond that I'm not sure I understand the difference stated.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-04 18:04 UTC, allada requested changes
> Reviewed 5 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NppHWjF5zjA8M2XP6P-:-NppHWjF5zjA8M2XP6P0:b-kyzv94) (no related file):*
Finished my ultra-fine grained review.

A lot of these are more suggestions. The reason I'm being a bit more careful here is because I think we may want to publish this API to a rust crate, so we should get the API solid before doing so.

___
___
*[`nativelink-store/src/filesystem_store.rs` line 418 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NppFUaxCbsUXfN0JlV4:-NppFUaxCbsUXfN0JlV5:bdl4wua) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-store/src/filesystem_store.rs#L418)):*
> ```XML
>         if let Err(err) = result {
>             warn!(
>                 "Could not add file to eviction cache, so deleting: {} - {:?}",
> ```

Maybe not show warning if it's one of our dot-status health files?
___
*[`nativelink-store/src/filesystem_store.rs` line 759 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NppGkKE-fvAbvZnzC6m:-NppGkKE-fvAbvZnzC6n:b734bbu) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-store/src/filesystem_store.rs#L759)):*
> ```XML
> 
>     fn register_health(self: Arc<Self>, registry: &mut HealthRegistry) {
>         registry.register_indicator(self);
> ```

I think we should make a `health_check: GenericHealthCheck` config on this store (and any other stores that will implement it) and make it tuneable for things like: how big of a blob to upload, timeout, exc...
___
*[`nativelink-store/src/filesystem_store.rs` line 770 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NppFx3D1w5D62hsWHxu:-NppFx3D1w5D62hsWHxv:b-vi188g) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-store/src/filesystem_store.rs#L770)):*
> ```XML
> #[async_trait]
> impl<Fe: FileEntry> HealthStatusIndicator for FilesystemStore<Fe> {
>     async fn check_health(self: Arc<Self>) -> HealthStatus {
> ```

Hmmm... Instead, would it make more sense to make a generic health checker that will do the following:
```
1. Call self.update().
2. Call self.get_part() on blob it just uploaded.
3. Call self.has() on blob it just uploaded.
4. Ensure all actions succeed.
```

This generic health checker would likely be usable in all places and only a few stores need to implement a more specialized version.
___
*[`nativelink-util/src/health_utils.rs` line 30 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npp69lvEy8ESumaiC2Y:-Npp69lvEy8ESumaiC2Z:bx5gjd7) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L30)):*
> ```XML
> type StructName = &'static str;
> /// Readable message status of the health indicator.
> pub type Message = Cow<'static, str>;
> ```

What do you think about making these all the primitives, like `pub type Message = str;`

Then below use `message: Cow<'static, Message>`?

The idea is to make the usage site more verbose.

Just curious in your thoughts.
___
*[`nativelink-util/src/health_utils.rs` line 34 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npp5mij15UgUBiAMWRc:-Npp5mij15UgUBiAMWRd:b-a3300v) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L34)):*
> ```XML
> ///
> /// Status state of a health indicator.
> ///
> ```

nit: This is very minor, but this style does not conform to the rest of the code base.
___
*[`nativelink-util/src/health_utils.rs` line 69 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npp75WF2nzSDxoAH6Xa:-Npp75WF2nzSDxoAH6Xb:bh6eji2) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L69)):*
> ```XML
>     /// implemented by the component to check the health status of the component.
>     ///
>     async fn check_health(self: Arc<Self>) -> HealthStatus {
> ```

nit: Should this be `self: &Arc<Self>`? This allows the caller to decide if they want to clone it or not.
___
*[`nativelink-util/src/health_utils.rs` line 74 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npp7VN5BgkBWI4B1fTH:-Npp7VN5BgkBWI4B1fTI:b-24aw20) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L74)):*
> ```XML
> 
>     /// Make a healthy status.
>     fn make_ok(&self, message: Message) -> HealthStatus {
> ```

nit: Can we move all these onto `HealthStatus` instead?

ie:
```rs
impl HealthStatus {
  pub fn new_ok(component: &impl HealthStatusIndicator, message: Message) -> Self {
    Self::Ok(component.struct_name(), message)
  }
}
```

I feel it'll be more clean. Having these helpers on the component fields weird.
___
*[`nativelink-util/src/health_utils.rs` line 112 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npp8Pfq95JnKsfTqZuB:-Npp8Pfq95JnKsfTqZuC:bdwc6ot) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L112)):*
> ```XML
> impl HealthRegistry {
>     /// Create a new health registry with the given component name.
>     pub fn new(component_name: HealthComponentName) -> Self {
> ```

nit: does `prefix` sound like a more appropriate than `component_name`?
___
*[`nativelink-util/src/health_utils.rs` line 139 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npp9c6T8VGN5T4MyPlr:-Npp9c6T8VGN5T4MyPls:b-8f40zn) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L139)):*
> ```XML
>     /// The stream is a lazy stream and the health status is checked only when the stream is polled.
>     ///
>     pub fn get_health_status_report(&mut self) -> impl Stream<Item = HealthStatusDescription> {
> ```

Don't hate me for this, but I have an idea.

What if we rewrite all this with this contract:
```rs
pub fn flatten(&self) -> impl Iterator<Item = (HealthComponentName, Arc<dyn HealthStatusIndicator>)> {
  // ...
}

trait HealthStatusReporter<S: Stream<Type = HealthStatusDescription>> {
  fn health_status_report(&self) -> S;
}

impl <T, S> HealthStatusReporter<S> for T
where
    T: Iterator<Item = (HealthComponentName, Arc<dyn HealthStatusIndicator>)>,
    S: Stream<Type = HealthStatusDescription>
{
  fn health_status_report(&self) -> S {
    // ...
  }
}

```

The idea here is that you can `flatten()` this into a collection, then with just the collection generate the report, without having to build the collection every time (if you are not going to add more items to the registry any more, which we don't).

I know this is more similar to what you had before.

Thoughts?
___
*[`nativelink-util/src/health_utils.rs` line 139 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NppByUf1oib-8R9EuEi:-NppByUf1oib-8R9EuEj:b4fs3q2) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L139)):*
> ```XML
>     /// The stream is a lazy stream and the health status is checked only when the stream is polled.
>     ///
>     pub fn get_health_status_report(&mut self) -> impl Stream<Item = HealthStatusDescription> {
> ```

nit: `mut` doesn't appear to be needed.
___
*[`nativelink-util/tests/health_utils_test.rs` line 25 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NppCmHV-1BT2OPI_0ep:-NppCmHV-1BT2OPI_0eq:brsa0c9) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/tests/health_utils_test.rs#L25) [...]

2024-02-07 17:36 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Local / ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04

___
*[`nativelink-store/src/filesystem_store.rs` line 418 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NppFUaxCbsUXfN0JlV4:-Nq02dVb2sI4mJcZkOKm:b5fwwbh) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-store/src/filesystem_store.rs#L418)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Maybe not show warning if it's one of our dot-status health files?
</blockquote></details>

Change to `error!` or just remove file name altogether? 
___
*[`nativelink-util/src/health_utils.rs` line 30 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npp69lvEy8ESumaiC2Y:-Nq04pZUAXMh46Oos-9x:b86bh49) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L30)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

What do you think about making these all the primitives, like `pub type Message = str;`

Then below use `message: Cow<'static, Message>`?

The idea is to make the usage site more verbose.

Just curious in your thoughts.
</blockquote></details>

Is the idea to make it clear why clients must call `.into()` at the call sites? I don't have much opinion here, at one side seeing the container types is nice, probably make it clear why `.into()` is being called. The other side a type alias makes the code less noisy with seeing type verbosity. 
___
*[`nativelink-util/src/health_utils.rs` line 34 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npp5mij15UgUBiAMWRc:-Nq05gez5aEmu-v2BVi9:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L34)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: This is very minor, but this style does not conform to the rest of the code base.
</blockquote></details>

Done.
___
*[`nativelink-util/src/health_utils.rs` line 74 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npp7VN5BgkBWI4B1fTH:-Nq0810z111KI_thhpPh:b8yht89) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L74)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Can we move all these onto `HealthStatus` instead?

ie:
```rs
impl HealthStatus {
  pub fn new_ok(component: &impl HealthStatusIndicator, message: Message) -> Self {
    Self::Ok(component.struct_name(), message)
  }
}
```

I feel it'll be more clean. Having these helpers on the component fields weird.
</blockquote></details>

ah nice, didn't realize an impl can be applied to an `enum` 
___
*[`nativelink-util/tests/health_utils_test.rs` line 25 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NppCmHV-1BT2OPI_0ep:-Nq3aSry1vHvwrdvPiLt:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/tests/health_utils_test.rs#L25)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: promote this above.
</blockquote></details>

Done.
___
*[`src/bin/nativelink.rs` line 91 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NppDMJZC-buBIyF-2zG:-Nq3cQUl1cLLFwzKj_bw:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/src/bin/nativelink.rs#L91)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Don't use a Mutex, just have it fully owned (mutable) here, then later turn it into an `Arc`, since once it's created you don't need to mutate it any more.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-07 19:04 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`src/bin/nativelink.rs` line 382 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NppEAukEQOSSnwgHk8R:-Nq3wYnL8eM_Brx_4_sV:b8yd2ym) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/src/bin/nativelink.rs#L382)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I think you want to implement `Fmt` for `HealthStatusDescription` instead of using `Debug`, or manually turn it into a string here. (manually doing it seems more appropriate imo.
</blockquote></details>

Migrated to use json formatting instead, this does mean the `HealthStatusDescription` now support some form of serialization. Having a enum with tuple fields presents a different challenge as it serializes to a list by default, ex:

```
curl -sS 0.0.0.0:50051/status|jq .
[
  {
    "component_name": "/nativelink/stores/AC_MAIN_STORE",
    "status": {
      "Ok": [
        "nativelink_store::filesystem_store::FilesystemStore",
        "Successfully filesystem store health check"
      ]
    }
  }
]
```
 
Done.


<!-- Sent from Reviewable.io -->

2024-02-07 19:07 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`nativelink-util/src/health_utils.rs` line 112 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npp8Pfq95JnKsfTqZuB:-Nq3xb312c9kHRTn0gs6:b-xq5u3l) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L112)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: does `prefix` sound like a more appropriate than `component_name`?
</blockquote></details>

`component_name: HealthComponentName` -> `prefix_name: HealthPrefixName` or `prefix_name: PrefixName`, either works for me, wdyt?


<!-- Sent from Reviewable.io -->

2024-02-07 20:06 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained

___
*[`nativelink-util/src/health_utils.rs` line 69 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npp75WF2nzSDxoAH6Xa:-Nq464uD82dM-9OQ-AVF:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L69)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Should this be `self: &Arc<Self>`? This allows the caller to decide if they want to clone it or not.
</blockquote></details>

Done.
___
*[`nativelink-util/src/health_utils.rs` line 74 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npp7VN5BgkBWI4B1fTH:-Nq4ANg8853Tqot4G0v_:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L74)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

ah nice, didn't realize an impl can be applied to an `enum`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-07 21:37 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained

___
*[`nativelink-store/src/filesystem_store.rs` line 770 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NppFx3D1w5D62hsWHxu:-Nq4O9MXAX4ZLhEU2AaD:b-9n3itm) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-store/src/filesystem_store.rs#L770)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Hmmm... Instead, would it make more sense to make a generic health checker that will do the following:
```
1. Call self.update().
2. Call self.get_part() on blob it just uploaded.
3. Call self.has() on blob it just uploaded.
4. Ensure all actions succeed.
```

This generic health checker would likely be usable in all places and only a few stores need to implement a more specialized version.
</blockquote></details>

Verify store cannot implement this, so don't opt it in. 
___
*[`nativelink-util/src/health_utils.rs` line 112 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npp8Pfq95JnKsfTqZuB:-Nq4JOAF7ll1T4v4McHS:b4n4q8p) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L112)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

`component_name: HealthComponentName` -> `prefix_name: HealthPrefixName` or `prefix_name: PrefixName`, either works for me, wdyt?
</blockquote></details>

Will rename to `namespace`
___
*[`nativelink-util/src/health_utils.rs` line 93 at r9](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Nq4J86P-PYKQyi-V0zy:-Nq4J86P-PYKQyi-V0zz:b4h0iln) ([raw file](https://github.com/TraceMachina/nativelink/blob/71fd990995666c4a880020965b8325664aebb4fe/nativelink-util/src/health_utils.rs#L93)):*
> ```XML
> #[derive(Default, Clone)]
> pub struct HealthRegistry {
>     component_name: HealthComponentName,
> ```

Rename references to `component_name` -> `namespace`. 


<!-- Sent from Reviewable.io -->

2024-02-08 20:28 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained, and pending CI: Local / ubuntu-22.04, Vercel, asan / ubuntu-22.04, integration-tests (20.04), pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04

___
*[`nativelink-store/src/filesystem_store.rs` line 759 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NppGkKE-fvAbvZnzC6m:-Nq9OOAcEjeXAvN1DmJg:b-xjkvjr) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-store/src/filesystem_store.rs#L759)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I think we should make a `health_check: GenericHealthCheck` config on this store (and any other stores that will implement it) and make it tuneable for things like: how big of a blob to upload, timeout, exc...
</blockquote></details>

This was done by having `HealthStatusIndicator` within the trait bounds of `Store`. Open to other suggestions on how to bound traits together without having `impl` blocks colocated, given depends on methods provided by `Store` I wasn't able to see other solutions to that.

Done.
___
*[`nativelink-store/src/filesystem_store.rs` line 770 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NppFx3D1w5D62hsWHxu:-Nq9OzqX3WESm4L4DIo6:b1kfew2) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-store/src/filesystem_store.rs#L770)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Verify store cannot implement this, so don't opt it in.
</blockquote></details>

See above on this

Done.
___
*[`nativelink-util/src/health_utils.rs` line 30 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npp69lvEy8ESumaiC2Y:-Nq4f_mv7RtcfB1b-ZeH:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L30)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Is the idea to make it clear why clients must call `.into()` at the call sites? I don't have much opinion here, at one side seeing the container types is nice, probably make it clear why `.into()` is being called. The other side a type alias makes the code less noisy with seeing type verbosity.
</blockquote></details>

Done.
___
*[`nativelink-util/src/health_utils.rs` line 112 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npp8Pfq95JnKsfTqZuB:-Nq4cGi53gCoqPz1Nk5V:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L112)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Will rename to `namespace`
</blockquote></details>

Done.
___
*[`nativelink-util/src/health_utils.rs` line 93 at r9](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Nq4J86P-PYKQyi-V0zy:-Nq4cFhJC4omGSCoux0M:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/71fd990995666c4a880020965b8325664aebb4fe/nativelink-util/src/health_utils.rs#L93)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Rename references to `component_name` -> `namespace`.
</blockquote></details>

Done.
___
*[`src/bin/nativelink.rs` line 382 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NppEAukEQOSSnwgHk8R:-Nq9P5ZN7IcfLJOu9-pJ:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/src/bin/nativelink.rs#L382)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Migrated to use json formatting instead, this does mean the `HealthStatusDescription` now support some form of serialization. Having a enum with tuple fields presents a different challenge as it serializes to a list by default, ex:

```
curl -sS 0.0.0.0:50051/status|jq .
[
  {
    "component_name": "/nativelink/stores/AC_MAIN_STORE",
    "status": {
      "Ok": [
        "nativelink_store::filesystem_store::FilesystemStore",
        "Successfully filesystem store health check"
      ]
    }
  }
]
```
 
Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-12 08:04 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`nativelink-util/src/health_utils.rs` line 139 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Npp9c6T8VGN5T4MyPlr:-NqRLAnrAITUfMtL0PI5:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L139)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Don't hate me for this, but I have an idea.

What if we rewrite all this with this contract:
```rs
pub fn flatten(&self) -> impl Iterator<Item = (HealthComponentName, Arc<dyn HealthStatusIndicator>)> {
  // ...
}

trait HealthStatusReporter<S: Stream<Type = HealthStatusDescription>> {
  fn health_status_report(&self) -> S;
}

impl <T, S> HealthStatusReporter<S> for T
where
    T: Iterator<Item = (HealthComponentName, Arc<dyn HealthStatusIndicator>)>,
    S: Stream<Type = HealthStatusDescription>
{
  fn health_status_report(&self) -> S {
    // ...
  }
}

```

The idea here is that you can `flatten()` this into a collection, then with just the collection generate the report, without having to build the collection every time (if you are not going to add more items to the registry any more, which we don't).

I know this is more similar to what you had before.

Thoughts?
</blockquote></details>

Done.
___
*[`nativelink-util/src/health_utils.rs` line 139 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NppByUf1oib-8R9EuEi:-NqRLBjr6AQQzGB6UoQI:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/aff5d086085394a211e335a93f7384d9f53bb07d/nativelink-util/src/health_utils.rs#L139)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: `mut` doesn't appear to be needed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-12 18:32 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Vercel, asan / ubuntu-22.04, pre-commit-checks, publish-image, ubuntu-20.04 / stable

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NppHWjF5zjA8M2XP6P-:-NqT_ir7B6yT2zUFJoLU:bbmu74a) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Finished my ultra-fine grained review.

A lot of these are more suggestions. The reason I'm being a bit more careful here is because I think we may want to publish this API to a rust crate, so we should get the API solid before doing so.
</blockquote></details>

@allada ptal. 

I also forgot, which stores we don't want to provide generic health check verifications for? 

___


<!-- Sent from Reviewable.io -->

2024-02-13 05:07 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r7, 23 of 25 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636#-:-NqVr2OB8nZqbKJbXPtc:bnfp4nl)* status: 1 of 1 LGTMs obtained

___
*[`-- commits` line 2 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVr4gTDB6ZIpum_45A):*
nit: This is `[Breaking]`, since it changes the behavior of `/status` and some users may rely on `/status` hard codded to return `Ok` in a happy path. I also suggest mentioning `/status` in the title.
___
*[`nativelink-util/src/health_utils.rs` line 40 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVkNhR5Wq4aSwEIiCV:-NqVkNhS9QJGjGUzRo5o:b-4p04hq) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/health_utils.rs#L40)):*
> ```XML
>         message: Cow<'static, Message>,
>     },
>     /// Initializing status, used to signal or indicate component is initializing.
> ```

nit: all these comments seems silly and just describing the definition of the word. I'd suggest removing them, as I don't see these comments adding any value except maybe the `non-fatal` part.
___
*[`nativelink-util/src/health_utils.rs` line 64 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVkprH62LOWLlbp5Aj:-NqVkprH62LOWLlbp5Ak:b-pc3j6k) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/health_utils.rs#L64)):*
> ```XML
> impl HealthStatus {
>     /// Make a healthy status.
>     pub fn new_ok(component: &(impl HealthStatusIndicator + ?Sized), message: Cow<'static, str>) -> Self {
> ```

nit: Does this need `impl` and `Sized`? Can't it just be `&HealthStatusIndicator` ? (same with below). I'd prefer not to let this pattern be copy-pasta'ed if possible.
___
*[`nativelink-util/src/health_utils.rs` line 115 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVlJRCCJSYF319PoIC:-NqVlJRCCJSYF319PoID:bi6326k) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/health_utils.rs#L115)):*
> ```XML
> 
>     /// Returns the name of the struct implementing the trait.
>     fn struct_name(&self) -> &'static str {
> ```

nit: `const fn`? Not sure if this is possible in `trait` but worth a try.
___
*[`nativelink-util/src/health_utils.rs` line 196 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVn8J8EoFKjP6LXKT5:-NqVn8J8EoFKjP6LXKT6:b6vciek) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/health_utils.rs#L196)):*
> ```XML
> /// Generally used for components that don't need custom implementations
> /// of the `check_health` function.
> #[macro_export]
> ```

nit: Lets try not exporting with this macro and then import with `nativelink_util::health_utils::default_health_status_indicator`.
___
*[`nativelink-util/src/store_trait.rs` line 176 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVnVlZ1p_wyN_Ks4cc:-NqVnVlZ1p_wyN_Ks4cd:bniae2d) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/store_trait.rs#L176)):*
> ```XML
>     // in situations where the default implementation is not sufficient.
>     async fn check_health(self: Pin<&Self>, _namespace: Cow<'static, str>) -> HealthStatus {
>         let bytes = _namespace.as_bytes();
> ```

nit: Don't prefix with `_` if it's being used.
___
*[`nativelink-util/src/store_trait.rs` line 177 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVnq43Da_qyURWaJpV:-NqVnq43Da_qyURWaJpW:bjchhf9) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/store_trait.rs#L177)):*
> ```XML
>     async fn check_health(self: Pin<&Self>, _namespace: Cow<'static, str>) -> HealthStatus {
>         let bytes = _namespace.as_bytes();
>         let hash = blake3::hash(bytes).into();
> ```

nit: does `namespace` have the component name itself too or just the path up to the component? We should probably pipe in the store's name if it's not part of the namespace.
___
*[`nativelink-util/src/store_trait.rs` line 180 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVo9y46T2P6AoQSeMm:-NqVo9y46T2P6AoQSeMn:b-dk16kt) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/store_trait.rs#L180)):*
> ```XML
>         let len = bytes.len();
>         let digest_info = DigestInfo::new(hash, len as i64);
>         let bytes_copy = bytes::Bytes::copy_from_slice(bytes);
> ```

nit: Lets make this a global config that contains the size of the digest to upload, filled with statically random generated (ie: use a constant random seed) with some of the bytes substituted with the namespace.

I'm worried that memory & filesystem store checks will have these default payloads far too small and never trigger the real problems.
___
*[`nativelink-util/src/store_trait.rs` line 182 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVp5uyAs7w_qsuhcs8:-NqVp5uyAs7w_qsuhcs9:buke8jx) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/store_trait.rs#L182)):*
> ```XML
>         let bytes_copy = bytes::Bytes::copy_from_slice(bytes);
> 
>         match self.update_oneshot(digest_info, bytes_copy.clone()).await {
> ```

nit, might be cleaner using

```rs
if let Err(e) = self.update_oneshot(digest_info, bytes_copy.clone()).await {
  return HealthStatus::new_failed(
    self.get_ref(),
    format!("Store.update_oneshot() failed: {}", e).into(),
  );
}
```
___
*[`nativelink-util/src/store_trait.rs` line 206 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVpY6U8ZMsaL6KTaYx:-NqVpY6U8ZMsaL6KTaYy:behv51z) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/store_trait.rs#L206)):*
> ```XML
>         }
> 
>         match self.has(digest_info).await {
> ```

super nit: I suggest doing this before `get_part` as knowing it didn't exist is going to be more useful than `.get_part_unchunked failed()` error.
___
*[`nativelink-util/tests/health_utils_test.rs` line 22 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVpmUz9j4qrn0Gx-Gt:-NqVpmUz9j4qrn0Gx-Gu:bfik01h) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/tests/health_utils_test.rs#L22)):*
> ```XML
> use futures::StreamExt;
> use nativelink_error::Error;
> use nativelink_util::health_utils::*;
> ```

nit: Can we spell out what we use? I really don't like using `*` as it makes code search less useful, since it hides away where the stuff is really coming from.
___
*[`src/bin/nativelink.rs` line 387 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVqfSh7aHTfv1E0SDZ:-NqVqfSh7aHTfv1E0SD_:b-54pqym) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/src/bin/nativelink.rs#L387)):*
> ```XML
>                             match serde_json5::to_string(&health_status_descriptions) {
>                                 Ok(health_status_descriptions) => Response::builder()
>                                     .status(StatusCode::OK)
> ```

Hmmm, I think we want a `503` in the case where any of the reports came back error (and maybe warning?). Failing to do this would make using this in a cloud health checker unusable.


<!-- Sent from Reviewable.io -->

2024-02-14 01:39 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained

___
*[`-- commits` line 2 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVr4gTDB6ZIpum_45A):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: This is `[Breaking]`, since it changes the behavior of `/status` and some users may rely on `/status` hard codded to return `Ok` in a happy path. I also suggest mentioning `/status` in the title.
</blockquote></details>

Done.
___
*[`nativelink-util/src/health_utils.rs` line 40 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVkNhR5Wq4aSwEIiCV:-Nq_AYixEWJXeEb9ht1u:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/health_utils.rs#L40)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: all these comments seems silly and just describing the definition of the word. I'd suggest removing them, as I don't see these comments adding any value except maybe the `non-fatal` part.
</blockquote></details>

Done.
___
*[`nativelink-util/src/health_utils.rs` line 64 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVkprH62LOWLlbp5Aj:-NqZZEP61GvFXimjOVJW:bqisjtu) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/health_utils.rs#L64)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Does this need `impl` and `Sized`? Can't it just be `&HealthStatusIndicator` ? (same with below). I'd prefer not to let this pattern be copy-pasta'ed if possible.
</blockquote></details>

https://gist.github.com/adam-singer/49faf251ca251ff7fe40f832105cd34b#file-gistfile0-txt-L2 if we remove `?Sized`, if we try `&HealthStatusIndicator` https://gist.github.com/adam-singer/c75e1d177dd105307b68230bd2bafc30 and then adding `dyn` just leads back to https://gist.github.com/adam-singer/ff64c6acd44234e001a77a1685a8c4a6.

I like that the helper methods depend on `HealthStatusIndicator` generally speaking, but using `?Sized` is bit overly flexible, so I'd rather just remove the helper methods then trying to fighting this.
___
*[`nativelink-util/src/health_utils.rs` line 115 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVlJRCCJSYF319PoIC:-NqZaD3s0IwwNSXw--pb:b5hrcoj) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/health_utils.rs#L115)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: `const fn`? Not sure if this is possible in `trait` but worth a try.
</blockquote></details>

not allowed https://gist.github.com/adam-singer/219603d86abba8f66cbf10f6e9b6e97a 

Done.
___
*[`nativelink-util/src/health_utils.rs` line 196 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVn8J8EoFKjP6LXKT5:-Nq_4ClO78-TcRg-CS65:b-wbphkv) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/health_utils.rs#L196)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Lets try not exporting with this macro and then import with `nativelink_util::health_utils::default_health_status_indicator`.
</blockquote></details>

Done. 

Tried reading up on different ways to cross the crate boundaries with macros, it doesn't seem you can do so without `macro_export`. You can "re-scope" by doing `pub use create::<macro_name>` within a `mod`, that will make the macro "scoped" in some use for `use` statements. 

https://users.rust-lang.org/t/re-exporting-macro-export-ed-macros-by-module-where-they-are-defined/84130
https://veykril.github.io/tlborm/decl-macros/minutiae/scoping.html
https://veykril.github.io/tlborm/decl-macros/minutiae/scoping.html#path-based-scope
https://doc.rust-lang.org/reference/macros-by-example.html

At least I didn't find another pattern that makes that possible from the above. 
___
*[`nativelink-util/src/store_trait.rs` line 176 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVnVlZ1p_wyN_Ks4cc:-NqZa_Nz-rEEbXP3A7WG:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/store_trait.rs#L176)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Don't prefix with `_` if it's being used.
</blockquote></details>

Done.
___
*[`nativelink-util/src/store_trait.rs` line 177 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVnq43Da_qyURWaJpV:-NqZatm86-YB1GDaz0Nl:b3q21o9) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/store_trait.rs#L177)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: does `namespace` have the component name itself too or just the path up to the component? We should probably pipe in the store's name if it's not part of the namespace.
</blockquote></details>

it does not, but we should have a reference to the store name, `self.get_name()`
___
*[`nativelink-util/src/store_trait.rs` line 182 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVp5uyAs7w_qsuhcs8:-Nq_9b7C8jZnxrvhAWlF:bn5l2dp) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/store_trait.rs#L182)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit, might be cleaner using

```rs
if let Err(e) = self.update_oneshot(digest_info, bytes_copy.clone()).await {
  return HealthStatus::new_failed(
    self.get_ref(),
    format!("Store.update_oneshot() failed: {}", e).into(),
  );
}
```
</blockquote></details>

Nice!

Done.
___
*[`nativelink-util/tests/health_utils_test.rs` line 22 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVpmUz9j4qrn0Gx-Gt:-Nq_BXwa8rxrFaczU8oo:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/tests/health_utils_test.rs#L22)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Can we spell out what we use? I really don't like using `*` as it makes code search less useful, since it hides away where the stuff is really coming from.
</blockquote></details>

Done.
___
*[`src/bin/nativelink.rs` line 387 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVqfSh7aHTfv1E0SDZ:-Nq_Bb1l03ch6JcHr0Pm:b-vci8fr) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/src/bin/nativelink.rs#L387)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Hmmm, I think we want a `503` in the case where any of the reports came back error (and maybe warning?). Failing to do this would make using this in a cloud health checker unusable.
</blockquote></details>

sgtm, the k8s stuff is very status code dependent and probably won't inspect body much. 

Done. 


<!-- Sent from Reviewable.io -->

2024-02-14 01:53 UTC, allada reviewed
> Reviewed 16 of 17 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained, and pending CI: asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13

___
*[`nativelink-util/src/store_trait.rs` line 177 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVnq43Da_qyURWaJpV:-Nq_JGqP6SEMbYPu43S1:b-wd9nih) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/store_trait.rs#L177)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

it does not, but we should have a reference to the store name, `self.get_name()`
</blockquote></details>

In that case we probably want to add `self.get_name()` salt to the hash or else we might get collisions.


<!-- Sent from Reviewable.io -->

2024-02-14 09:22 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained, and pending CI: Vercel, pre-commit-checks

___
*[`nativelink-util/src/store_trait.rs` line 177 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVnq43Da_qyURWaJpV:-Nqav7Q814m7_6cher4I:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/store_trait.rs#L177)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

In that case we probably want to add `self.get_name()` salt to the hash or else we might get collisions.
</blockquote></details>

Done.
___
*[`nativelink-util/src/store_trait.rs` line 180 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVo9y46T2P6AoQSeMm:-Nqav9Bu9JH0YAA63uPi:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/store_trait.rs#L180)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Lets make this a global config that contains the size of the digest to upload, filled with statically random generated (ie: use a constant random seed) with some of the bytes substituted with the namespace.

I'm worried that memory & filesystem store checks will have these default payloads far too small and never trigger the real problems.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-14 09:25 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained, and pending CI: Vercel, pre-commit-checks

___
*[`nativelink-util/src/store_trait.rs` line 206 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqVpY6U8ZMsaL6KTaYx:-NqavshvAVFJsVD5vfcR:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/24a98c216ecd3d9d0f4dbd357c9b8873f45fec76/nativelink-util/src/store_trait.rs#L206)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

super nit: I suggest doing this before `get_part` as knowing it didn't exist is going to be more useful than `.get_part_unchunked failed()` error.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-14 23:25 UTC, allada approved these changes
> Reviewed 7 of 8 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained

___
*[`nativelink-config/src/cas_server.rs` line 634 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqdtpkO-qHB5JhI2RXz:-NqdtpkPCUjtsKDi-dGn:b-w696af) ([raw file](https://github.com/TraceMachina/nativelink/blob/f243c53a41691b958cb9374a4302c6ed84f89012/nativelink-config/src/cas_server.rs#L634)):*
> ```XML
> 
>     /// Default digest size to use for health check when running
>     /// diagnostics checks.
> ```

super nit: Lets be a bit more descriptive on what this is doing.
___
*[`nativelink-util/src/health_utils.rs` line 189 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Nqdu66k94k3Cqwy-BoV:-Nqdu66k94k3Cqwy-BoW:b-tyf8tp) ([raw file](https://github.com/TraceMachina/nativelink/blob/f243c53a41691b958cb9374a4302c6ed84f89012/nativelink-util/src/health_utils.rs#L189)):*
> ```XML
>                 &self,
>                 namespace: std::borrow::Cow<'static, str>,
>             ) -> nativelink_util::health_utils::HealthStatus {
> ```

nit: Just import the name.
___
*[`nativelink-util/src/store_trait.rs` line 39 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqduKIWE6alXMyFVl7B:-NqduKIWE6alXMyFVl7C:biy2mbi) ([raw file](https://github.com/TraceMachina/nativelink/blob/f243c53a41691b958cb9374a4302c6ed84f89012/nativelink-util/src/store_trait.rs#L39)):*
> ```XML
> 
> pub fn default_digest_size_health_check() -> usize {
>     *DEFAULT_DIGEST_SIZE_HEALTH_CHECK.get_or_init(|| 1024 * 1024)
> ```

nit: Make this number a const and make sure it's documented that if it changes it must be updated in the config file.
___
*[`nativelink-util/src/store_trait.rs` line 204 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Nqdusb4BHdsJjrsEVju:-Nqdusb4BHdsJjrsEVjv:b84v6b9) ([raw file](https://github.com/TraceMachina/nativelink/blob/f243c53a41691b958cb9374a4302c6ed84f89012/nativelink-util/src/store_trait.rs#L204)):*
> ```XML
> 
>         // Fill data with all random bytes.
>         HEALTH_CHECK_RNG.lock().fill_bytes(&mut digest_data);
> ```

nit: We want this number to be the same on every call, but different for every component.

The way I'd do this is use the namespace and component name to generate a random int32, then feed that number into the random number generator seed, then fill this.

This ensures we get the same data every call, but different for every component. (otherwise we pollute our store with a lot of useless data.

There's other ways to do this too, but the way I outlined above seems simplest albeit slower.
___
*[`nativelink-util/src/store_trait.rs` line 222 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Nqdv_pOBFXjZv7ARoJJ:-Nqdv_pOBFXjZv7ARoJK:bagj5qy) ([raw file](https://github.com/TraceMachina/nativelink/blob/f243c53a41691b958cb9374a4302c6ed84f89012/nativelink-util/src/store_trait.rs#L222)):*
> ```XML
>         }
> 
>         let digest_data_hash = blake3::hash(&digest_data).into();
> ```

nit: Don't use blake directly, use `DigestHasher::from(default_digest_hasher_func()).update(...);`


<!-- Sent from Reviewable.io -->

2024-02-15 01:14 UTC, adam-singer reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

___
*[`nativelink-config/src/cas_server.rs` line 634 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqdtpkO-qHB5JhI2RXz:-NqeJtAT-q9SHvT4HvvB:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f243c53a41691b958cb9374a4302c6ed84f89012/nativelink-config/src/cas_server.rs#L634)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

super nit: Lets be a bit more descriptive on what this is doing.
</blockquote></details>

Done.
___
*[`nativelink-util/src/health_utils.rs` line 189 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Nqdu66k94k3Cqwy-BoV:-NqeAL6B1iZWGRG9UoOv:b59wr0a) ([raw file](https://github.com/TraceMachina/nativelink/blob/f243c53a41691b958cb9374a4302c6ed84f89012/nativelink-util/src/health_utils.rs#L189)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Just import the name.
</blockquote></details>


Done.

When macros are expanded some imports will conflict, in this case `std::borrow::Cow` and `nativelink\_util::health\_utils::HealthStatus` could already be imported in some scopes and not others. Tried suggested of just importing in this scope and in the macro scope, became a ping/pong of who imported what. 
___
*[`nativelink-util/src/store_trait.rs` line 39 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/636#-NqduKIWE6alXMyFVl7B:-NqeJoj95LMSoPmKKeVO:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f243c53a41691b958cb9374a4302c6ed84f89012/nativelink-util/src/store_trait.rs#L39)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Make this number a const and make sure it's documented that if it changes it must be updated in the config file.
</blockquote></details>

Done.
___
*[`nativelink-util/src/store_trait.rs` line 204 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Nqdusb4BHdsJjrsEVju:-NqeJngi5tFRmn5_r46b:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f243c53a41691b958cb9374a4302c6ed84f89012/nativelink-util/src/store_trait.rs#L204)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: We want this number to be the same on every call, but different for every component.

The way I'd do this is use the namespace and component name to generate a random int32, then feed that number into the random number generator seed, then fill this.

This ensures we get the same data every call, but different for every component. (otherwise we pollute our store with a lot of useless data.

There's other ways to do this too, but the way I outlined above seems simplest albeit slower.
</blockquote></details>

Done.
___
*[`nativelink-util/src/store_trait.rs` line 222 at r15](https://reviewable.io/reviews/TraceMachina/nativelink/636#-Nqdv_pOBFXjZv7ARoJJ:-NqeJme81dif_O31z-6t:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f243c53a41691b958cb9374a4302c6ed84f89012/nativelink-util/src/store_trait.rs#L222)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Don't use blake directly, use `DigestHasher::from(default_digest_hasher_func()).update(...);`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-15 01:20 UTC, allada approved these changes
> Reviewed 6 of 6 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04



<!-- Sent from Reviewable.io -->

2024-02-15 01:55 UTC, allada approved these changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-02-15 01:55 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636#-:-NqeTWvrBA3FkSIuYtmf:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-02-15 01:56 UTC, adam-singer reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/636#-:-NqeTdFEA51QI2FAa6Er:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-02-15 01:56 UTC, merged