Max concurrent GrpcStore streams
TraceMachina/nativelink pull request #656
Opened 2024-02-03 11:37 UTC by chrisstaite-menlo

# Description

Add a configuration option to limit the number of concurrent streams that are active with the upstream GrpcStore.

With this, we also introduce reconnection on error since Tonic doesn't do that.

Fixes #602

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-02-04 04:27 UTC, allada requested changes
> Reviewed 6 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/656)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/656#-NpmMK_57PR40cMn7zB2:-NpmMK_57PR40cMn7zB3:b-33vb7t) (no related file):*
nit: It doesn't fix the issue, it is `towards` that issue.

___
___
*[`nativelink-config/src/schedulers.rs` line 139 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/656#-NpmKcKa25nIp80m5ZcY:-NpmKcKa25nIp80m5ZcZ:b-cs1p9m) ([raw file](https://github.com/TraceMachina/nativelink/blob/02dd17b9f8eca16a65e5628de4e0a6cc2e020110/nativelink-config/src/schedulers.rs#L139)):*
> ```XML
> 
>     /// Limit the number of simultaneous upstream requests to this many.  A
>     /// value of zero is treated as unlimited.
> ```

nit: It might be good to document what happens if we exceed the limit (ie: do we backpressure/queue or drop).
___
*[`nativelink-config/src/stores.rs` line 551 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/656#-NpmKk2z5fqxIDJw4QoG:-NpmKk2z5fqxIDJw4QoH:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/02dd17b9f8eca16a65e5628de4e0a6cc2e020110/nativelink-config/src/stores.rs#L551)):*
> ```XML
> 
>     /// Limit the number of simultaneous upstream requests to this many.  A
>     /// value of zero is treated as unlimited.
> ```

ditto.
___
*[`nativelink-scheduler/src/grpc_scheduler.rs` line 76 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/656#-NpmLJ9m82TvX-2WqMxc:-NpmLJ9m82TvX-2WqMxd:b-khsjik) ([raw file](https://github.com/TraceMachina/nativelink/blob/02dd17b9f8eca16a65e5628de4e0a6cc2e020110/nativelink-scheduler/src/grpc_scheduler.rs#L76)):*
> ```XML
> 
>     fn on_error(&self, err: &Error) {
>         if err.code != Code::Internal {
> ```

nit: Maybe `warn!()` the error?
___
*[`nativelink-scheduler/src/grpc_scheduler.rs` line 76 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/656#-NpmLQAxAe-MirGfw2CA:-NpmLQAxAe-MirGfw2CB:b-fbscn7) ([raw file](https://github.com/TraceMachina/nativelink/blob/02dd17b9f8eca16a65e5628de4e0a6cc2e020110/nativelink-scheduler/src/grpc_scheduler.rs#L76)):*
> ```XML
> 
>     fn on_error(&self, err: &Error) {
>         if err.code != Code::Internal {
> ```

Should we use some kind of map of codes to know if we should reconnect?
___
*[`nativelink-store/src/grpc_store.rs` line 223 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/656#-NpmM_F6AE6AI4RIp6tY:-NpmM_F6AE6AI4RIp6tZ:b-6lvrgu) ([raw file](https://github.com/TraceMachina/nativelink/blob/02dd17b9f8eca16a65e5628de4e0a6cc2e020110/nativelink-store/src/grpc_store.rs#L223)):*
> ```XML
> /// This handles the permit for limiting concurrency, and also re-connecting the
> /// underlying channel on error.  It depends on users reporting all errors.
> struct Connection<'a> {
> ```

nit: This looks nearly identical to the one above in `grpc_scheduler`. Can we combine them w/ templates and put them into `grpc_utils` or something?


<!-- Sent from Reviewable.io -->

2024-02-05 14:45 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/656)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-config/src/stores.rs` line 551 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/656#-NpmKk2z5fqxIDJw4QoG:-Npt_lZJE7HNOmrE7oYi:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/02dd17b9f8eca16a65e5628de4e0a6cc2e020110/nativelink-config/src/stores.rs#L551)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/grpc_scheduler.rs` line 76 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/656#-NpmLJ9m82TvX-2WqMxc:-Npt_nQp1xPPxfZLcue8:b-9y49j7) ([raw file](https://github.com/TraceMachina/nativelink/blob/02dd17b9f8eca16a65e5628de4e0a6cc2e020110/nativelink-scheduler/src/grpc_scheduler.rs#L76)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Maybe `warn!()` the error?
</blockquote></details>

That's the purpose of the upstream really.
___
*[`nativelink-scheduler/src/grpc_scheduler.rs` line 76 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/656#-NpmLQAxAe-MirGfw2CA:-Npt_ri140jp0OEfFzWH:b-njaurq) ([raw file](https://github.com/TraceMachina/nativelink/blob/02dd17b9f8eca16a65e5628de4e0a6cc2e020110/nativelink-scheduler/src/grpc_scheduler.rs#L76)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Should we use some kind of map of codes to know if we should reconnect?
</blockquote></details>

I don't think we need to, all of the transport errors are mapped to `Internal` within Tonic: https://github.com/hyperium/tonic/blob/master/tonic/src/status.rs#L376

Notably, it states that these indicate an issue with the library: https://github.com/hyperium/tonic/blob/master/tonic/src/status.rs#L282


<!-- Sent from Reviewable.io -->

2024-02-05 15:53 UTC, allada requested changes
> Reviewed 4 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/656)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-util/src/grpc_utils.rs` line 91 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/656#-NptwbJaBPsgb4EA24oM:-NptwbJaBPsgb4EA24oN:b-jl2kyr) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef4ba39fcacdaf675acb3f753e4d646069ea1adf/nativelink-util/src/grpc_utils.rs#L91)):*
> ```XML
>         // new connection now.
>         let mut channel_lock = self.parent.channel.lock();
>         // Channel already changed, don't do it again.
> ```

nit: Can we elaborate this a bit... it took me a while to understand this...
```
// This ensures only the first error reconnects and the other reconnect
// attempts use the Channel that the first one recreated.
```
___
*[`nativelink-util/src/grpc_utils.rs` line 92 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/656#-Npty7rH5ZUJ8Ux6LEpY:-Npty7rH5ZUJ8Ux6LEpZ:bsvx0eg) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef4ba39fcacdaf675acb3f753e4d646069ea1adf/nativelink-util/src/grpc_utils.rs#L92)):*
> ```XML
>         let mut channel_lock = self.parent.channel.lock();
>         // Channel already changed, don't do it again.
>         if channel_lock.0 != self.channel_id {
> ```

I'm pretty sure you need to do this on all channels after they are updated:
```rs
self.channel_id = channel_lock.0
```

(sadly you'll need another mutex :-( )

Failing to do so will cause the second-reconnect attempt to result in `get_channel` always resulting in a bad channel.


<!-- Sent from Reviewable.io -->

2024-02-05 15:59 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/656)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-util/src/grpc_utils.rs` line 92 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/656#-Npty7rH5ZUJ8Ux6LEpY:-Nptz443AypWrJChEMSF:b-z3i1u) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef4ba39fcacdaf675acb3f753e4d646069ea1adf/nativelink-util/src/grpc_utils.rs#L92)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I'm pretty sure you need to do this on all channels after they are updated:
```rs
self.channel_id = channel_lock.0
```

(sadly you'll need another mutex :-( )

Failing to do so will cause the second-reconnect attempt to result in `get_channel` always resulting in a bad channel.
</blockquote></details>

No, a `Connection` should only be used once.  I really wanted to make this easier by `impl tower::Service<http::HttpBody> for Connection` but that would involve adding a dependency to `tower`.

Essentially, we create a new `Channel` in the parent `ConnectionManager` on failure, but any existing `Connection` that's being used can complete (and perhaps error) by itself.  This is done because in the case of `GoAway` the other established streams on the `Channel` are able to complete, but we need to terminate after that graceful disconnect has finished.


<!-- Sent from Reviewable.io -->

2024-02-05 17:13 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/656)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-util/src/grpc_utils.rs` line 92 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/656#-Npty7rH5ZUJ8Ux6LEpY:-NpuFRnwAkvWWzdvCQu8:bcitycy) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef4ba39fcacdaf675acb3f753e4d646069ea1adf/nativelink-util/src/grpc_utils.rs#L92)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

No, a `Connection` should only be used once.  I really wanted to make this easier by `impl tower::Service<http::HttpBody> for Connection` but that would involve adding a dependency to `tower`.

Essentially, we create a new `Channel` in the parent `ConnectionManager` on failure, but any existing `Connection` that's being used can complete (and perhaps error) by itself.  This is done because in the case of `GoAway` the other established streams on the `Channel` are able to complete, but we need to terminate after that graceful disconnect has finished.
</blockquote></details>

Can we add some of this to a comment? This seems like something that we will foot-gun ourselves on in the future if we don't document it.


<!-- Sent from Reviewable.io -->

2024-02-05 17:23 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/656)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04

___
*[`nativelink-util/src/grpc_utils.rs` line 92 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/656#-Npty7rH5ZUJ8Ux6LEpY:-NpuI10N2oCE1iDEHWtI:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef4ba39fcacdaf675acb3f753e4d646069ea1adf/nativelink-util/src/grpc_utils.rs#L92)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Can we add some of this to a comment? This seems like something that we will foot-gun ourselves on in the future if we don't document it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-05 18:11 UTC, merged

2024-02-06 16:45 UTC, adam-singer reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/656)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->