Adjust all instances of 'Native Link' in comments and metadata to 'NativeLink'
TraceMachina/nativelink pull request #658
Opened 2024-02-07 21:59 UTC by blakehatch

# Description
Adjusted naming and assured that all instances are just in documentation and metadata so as to not introduce any breakage when adjusting. Was done carefully per-file and not just a global find & replace.

2024-02-07 23:21 UTC, MarcusSorealheis approved these changes
> Reviewed 178 of 178 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/658)* status: 0 of 1 LGTMs obtained, and pending CI: macos-13



<!-- Sent from Reviewable.io -->

2024-02-08 06:23 UTC, tyr-one commented on nativelink-docs/docs/About.mdx
capital L

2024-02-08 06:25 UTC, tyr-one requested changes
One lowercase L made it through, otherwise looks all good!

2024-02-08 15:50 UTC, blakehatch reviewed
Thank you good catch!

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/658#-:-Nq8PUI64dI4822OhcOk:bz933kd)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Local / ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04

___
*[`nativelink-docs/docs/About.mdx` line 0 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/658#gh-1482461018:-Nq8PTI34PdQSh_HwDAK:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/19182468c4f834ad917cef304399b5a6a2782bf0/nativelink-docs/docs/About.mdx#L0)):*
<details><summary><i>Previously, tyr-one wrote…</i></summary><blockquote>

capital L
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-08 16:57 UTC, tyr-one approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/658)* status: 0 of 1 LGTMs obtained, and pending CI: macos-13



<!-- Sent from Reviewable.io -->

2024-02-09 01:32 UTC, MarcusSorealheis approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/658)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-02-09 01:42 UTC, blakehatch reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/658#-:-NqAWsl07lt7JRt3ikfp:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-02-09 01:43 UTC, merged