Increase runner size for Cargo Dev and Sanitizer workflows
TraceMachina/nativelink pull request #685
Opened 2024-03-01 23:10 UTC by aaronmondal

This should fix recent CI breakages on main.

2024-03-01 23:11 UTC, aaronmondal reviewed
+@allada +@MarcusSorealheis 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/685#-:-NrwHICM9ipHTtD4pdXD:b-waaaf6)* status: 0 of 2 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / large-ubuntu-22.04, Cargo Dev / macos-13, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, Vercel, asan / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @allada and @MarcusSorealheis)



<!-- Sent from Reviewable.io -->

2024-03-01 23:15 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/685)* status: 0 of 2 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Bazel Dev / ubuntu-22.04, Local / ubuntu-22.04, Vercel, asan / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, vale (waiting on @MarcusSorealheis)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/685#-NrwHxdc1SrODkQwWZ8z:-NrwHxdc1SrODkQwWZ9-:brwip5j) (no related file):*
I'm not sold we should do this. We are not doing complex stuff in these runners, why is it using so much disk size?

Last time we increased runner sizes it cost a ton of money too.

___


<!-- Sent from Reviewable.io -->

2024-03-01 23:22 UTC, aaronmondal reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/685)* status: 0 of 2 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Remote / large-ubuntu-22.04, asan / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, windows-2022 / stable (waiting on @allada and @MarcusSorealheis)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/685#-NrwHxdc1SrODkQwWZ8z:-NrwJ9fb3IUNodOhrxcT:b-nd0bop) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I'm not sold we should do this. We are not doing complex stuff in these runners, why is it using so much disk size?

Last time we increased runner sizes it cost a ton of money too.
</blockquote></details>

The sanitizer run produces much larger artifacts since it builds instrumented code. That run was somewhat expected to run into issues at some point.

The cargo-dev run runs into issues because the default size for the linux runners is a bit smaller than Mac and Windows, so this is also not too surprising.

I agree that we don't really need more cores though. Maybe we could add a new runner type in github that just increases the local storage size but doesn't add additional cores?

___


<!-- Sent from Reviewable.io -->

2024-03-02 02:56 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/685)* status: 0 of 2 LGTMs obtained (waiting on @MarcusSorealheis)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/685#-NrwHxdc1SrODkQwWZ8z:-Nrx4hfF1kY7afiaQjFA:b-yeolp6) (no related file):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

The sanitizer run produces much larger artifacts since it builds instrumented code. That run was somewhat expected to run into issues at some point.

The cargo-dev run runs into issues because the default size for the linux runners is a bit smaller than Mac and Windows, so this is also not too surprising.

I agree that we don't really need more cores though. Maybe we could add a new runner type in github that just increases the local storage size but doesn't add additional cores?
</blockquote></details>

It looks like these runners have `14 GB` according to documentation.

I'm thinking maybe sanitizers should use a non-debug build? I believe cargo by default uses debug builds.

Could we also somehow tell nix to use less disk space?

___


<!-- Sent from Reviewable.io -->

2024-03-02 04:15 UTC, aaronmondal reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/685)* status: 0 of 2 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @allada and @MarcusSorealheis)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/685#-NrwHxdc1SrODkQwWZ8z:-NrxH1_ACCi7CTWkxexL:b-yxb3if) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

It looks like these runners have `14 GB` according to documentation.

I'm thinking maybe sanitizers should use a non-debug build? I believe cargo by default uses debug builds.

Could we also somehow tell nix to use less disk space?
</blockquote></details>

Removing debug symbols seems to help xD

___


<!-- Sent from Reviewable.io -->

2024-03-02 05:21 UTC, allada requested changes
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/685)* status: 0 of 2 LGTMs obtained (waiting on @MarcusSorealheis)

___
*[`.github/workflows/nix.yaml` line 84 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/685#-Nrxarxk7O-qMW6oXDLU:-Nrxarxk7O-qMW6oXDLV:b-xs93ii) ([raw file](https://github.com/TraceMachina/nativelink/blob/21252c66506c85443c3b7d25d004791c2fff77cb/.github/workflows/nix.yaml#L84)):*
> ```YAML
>         run: >
>           nix develop --impure --command
>           bash -c "cargo test --all --release"
> ```

I suggest adding this to `Cargo.toml`:
```
[profile.tiny]
inherits = "release"
opt-level = "z"
strip = true
lto = "thin"
```

Then use `--profile=tiny` instead. I think this will dramatically improve compile time too.


<!-- Sent from Reviewable.io -->

2024-03-02 21:10 UTC, allada approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/685)* status: 0 of 2 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @MarcusSorealheis)

___
*[`Cargo.toml` line 15 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/685#-Ns0-C6Z9OQ8HEmo3xlk:-Ns0-C6Z9OQ8HEmo3xll:b-lfkp3s) ([raw file](https://github.com/TraceMachina/nativelink/blob/66a9002b8fb5bb5cba69a28ff4011818f62befdb/Cargo.toml#L15)):*
> ```TOML
> # Prefer this profile in CI, for instance via `cargo test --all --profile=smol`.
> # It reduces the size of the `target` directory from ~12GB to ~1GB.
> [profile.smol]
> ```

nit: what does `smol` mean?


<!-- Sent from Reviewable.io -->

2024-03-02 21:10 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/685#-:-Ns0-Irz8AdvIqXI6QcO:bnfp4nl)* status: 1 of 2 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @MarcusSorealheis)



<!-- Sent from Reviewable.io -->

2024-03-02 21:57 UTC, aaronmondal reviewed
-@MarcusSorealheis 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/685#-:-Ns09CBV8eDNcD-jnyon:b-pel5r0)* status: 1 of 1 LGTMs obtained

___
*[`Cargo.toml` line 15 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/685#-Ns0-C6Z9OQ8HEmo3xlk:-Ns09EAr2bCHo5KRpvwi:b-vq1d3m) ([raw file](https://github.com/TraceMachina/nativelink/blob/66a9002b8fb5bb5cba69a28ff4011818f62befdb/Cargo.toml#L15)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: what does `smol` mean?
</blockquote></details>

:cat2: https://knowyourmeme.com/memes/smol

See also:
- https://imgflip.com/memetemplate/73762232/Smol-Doge
- https://github.com/smol-rs/smol


<!-- Sent from Reviewable.io -->

2024-03-02 21:58 UTC, MarcusSorealheis approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/685)* status: 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-03-02 21:59 UTC, merged