Start automated aggregation and surfacing of internal documentation with Rustdoc
TraceMachina/nativelink pull request #688
Opened 2024-03-02 01:53 UTC by blakehatch

First PR for leveraging rustdoc to surface existing documentation in the code. This reduces the need for redundant documentation on complex and quickly-evolving systems such as configuration files and stores.

This PR focuses on requested improvements and aggregation of information on configuring Nativelink, as well as establishing rustdoc patterns to use on the rest of the monorepo as it is continuously documented.

The change surfaces the below information from the existing `nativelink-config` documentation for the rust doc:

- Example READMEs (For examples from [In-flight PR from @MarcusSorealheis](https://github.com/TraceMachina/nativelink/pull/680) & Kubernetes deployment examples)
  - In order to thoroughly document the requested `cas.json` , `scheduler.json`, `cas.yaml`,  and `scheduler.yaml` examples they require updating in one place
  
After running `cargo doc` in the repository, this page can be reviewed in the browser at:
`file:///Path/to/repo/nativelink/target/doc/nativelink_config/index.html`

This change also surfaces existing documentation and mildly enhances with examples for:

- `nativelink-config/stores.rs` -> `enum StoreConfig`

After running `cargo doc` in the repository, this page can be reviewed in the browser at:
`file:///Users/blakehatch/Projects/nativelink/target/doc/nativelink_config/stores/enum.StoreConfig.html`

Upcoming PRs will focus on improving the existing now surfaced and aggregated documentation as well as the formatting of the generated Markdown in `nativelink-config/src/lib.rs`

#681 

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

2024-03-02 02:51 UTC, aaronmondal requested changes
I like that we're starting to move towards more generated documentation and the added config examples are nice.

The way this is currently set up will break our bazel tests though. Note that we doc targets for the individual crates with `bazel build nativelink-config:docs` and so on. There are also generated doc tests that run as part of the testsuite, e.g. `bazel test nativelink-config:doc_test`.

I think it would be good to have the option to generate the docs with either Bazel or Cargo, but if we have to choose one we'll have to use Bazel since we don't have the same reliability for clippy's doc checking in our Cargo build.

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/688#-:-Nrx1xSBEiRasyNVdRPs:b-ve2b19)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-22.04, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @blakehatch)

___
*[`nativelink-config/Cargo.toml` line 11 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx--Pg1GcjQSswGQV5:-Nrx--Pg1GcjQSswGQV6:by6fkfu) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/Cargo.toml#L11)):*
> ```TOML
> 
> [package.metadata.docs.rs]
> readme = "./README.md"
> ```

nit: newline
___
*[`nativelink-config/examples/README.md` line 0 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-36i6Li6VvBPmkRu:-Nrx-36i6Li6VvBPmkRv:bw9u1e0) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/examples/README.md#L0)):*
nit: Intentionally empty?
___
*[`nativelink-config/src/lib.rs` line 15 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx37uY6CteWnzXDzwn:-Nrx37uY6CteWnzXDzwo:b-un4yic) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/lib.rs#L15)):*
> ```XML
> // limitations under the License.
> 
> #![doc = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/README.md"))]
> ```

Viewing this in the docpage seems a bit overwhelming. Could we move the specific config examples to the respective stores?
___
*[`nativelink-config/src/stores.rs` line 42 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-IyS6qcOpleQXont:-Nrx-IyS6qcOpleQXonu:bicw1f4) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/stores.rs#L42)):*
> ```XML
>     /// Memory store will store all data in a hashmap in memory.
>     ///
>     /// **Example JSON Config:**
> ```

I believe there needs to be an empty line around the code snippet to make sure that it's formatted correctly.
___
*[`nativelink-config/src/stores.rs` line 63 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-eEq4LKpdfBZBU8O:-Nrx-eEq4LKpdfBZBU8P:b-iipjm8) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/stores.rs#L63)):*
> ```XML
>     ///
>     /// **Example JSON Config:**
>     /// ```json
> ```

nit: ditto
___
*[`nativelink-config/src/stores.rs` line 89 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-gNR5sY5zXzYFt-Q:-Nrx-gNR5sY5zXzYFt-R:b-iipjm8) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/stores.rs#L89)):*
> ```XML
>     ///
>     /// **Example JSON Config:**
>     /// ```json
> ```

nit: ditto
___
*[`nativelink-config/src/stores.rs` line 169 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-i3XDZxLuUZaqWvL:-Nrx-i3XDZxLuUZaqWvM:b-iipjm8) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/stores.rs#L169)):*
> ```XML
>     ///
>     /// **Example JSON Config:**
>     /// ```json
> ```

nit: ditto
___
*[`nativelink-config/src/stores.rs` line 198 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-jbIEEJksqGo0lu_:-Nrx-jbIEEJksqGo0lua:bytafr8) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/stores.rs#L198)):*
> ```XML
>     /// store before those stores.
>     ///
>     /// **Example JSON Config:**
> ```

nit:ditto
___
*[`nativelink-config/src/stores.rs` line 245 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-kzNCLMsxEBWc7O0:-Nrx-kzNCLMsxEBWc7O1:b-iipjm8) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/stores.rs#L245)):*
> ```XML
>     ///
>     /// **Example JSON Config:**
>     /// ```json
> ```

nit: ditto
___
*[`nativelink-config/src/stores.rs` line 320 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-mMZ6WkfZ5hmN4Bb:-Nrx-mMZ6WkfZ5hmN4Bc:b-iipjm8) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/stores.rs#L320)):*
> ```XML
>     ///
>     /// **Example JSON Config:**
>     /// ```json
> ```

nit: ditto
___
*[`nativelink-config/src/stores.rs` line 358 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-npY4qxo9zpDNbyM:-Nrx-npY4qxo9zpDNbyN:b-iipjm8) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/stores.rs#L358)):*
> ```XML
>     ///
>     /// ***Example JSON Config:***
>     /// ```json
> ```

nit: ditto
___
*[`nativelink-config/src/stores.rs` line 393 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-osr4mqLUds_3x30:-Nrx-osr4mqLUds_3x31:b-iipjm8) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/stores.rs#L393)):*
> ```XML
>     ///
>     /// **Example JSON Config:**
>     /// ```json
> ```

nit: ditto
___
*[`nativelink-config/src/stores.rs` line 401 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-prtAM4OamoJABaN:-Nrx-prtAM4OamoJABaO:b2fu1oy) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/stores.rs#L401)):*
> ```XML
>     ///               // 10mb.
>     ///               "max_bytes": 10000000,
>     ///             
> ```

nit: intentional dots?
___
*[`nativelink-config/src/stores.rs` line 425 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-s4E7GveOYCmRGTf:-Nrx-s4E7GveOYCmRGTg:b-iipjm8) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/stores.rs#L425)):*
> ```XML
>     ///
>     /// **Example JSON Config:**
>     // ```json
> ```

nit: ditto
___
*[`nativelink-config/src/stores.rs` line 444 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-tTl77ThumpevW2U:-Nrx-tTl77ThumpevW2V:b-iipjm8) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/stores.rs#L444)):*
> ```XML
>     ///
>     /// **Example JSON Config:**
>     /// ```json
> ```

nit: ditto
___
*[`nativelink-config/src/stores.rs` line 461 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-uUn6qn-Cf1l-cN-:-Nrx-uUn6qn-Cf1l-cN0:b-iipjm8) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/stores.rs#L461)):*
> ```XML
>     ///
>     /// **Example JSON Config:**
>     /// ```json
> ```

nit: ditto
___
*[`nativelink-config/src/stores.rs` line 490 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-v_J8Rf [...]

2024-03-02 02:52 UTC, aaronmondal reviewed
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/688)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-22.04, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @blakehatch)



<!-- Sent from Reviewable.io -->

2024-03-02 17:56 UTC, blakehatch commented
Yup there goes CI blowing up lol, let me fix I thought rust format would save me 😄

2024-03-05 17:15 UTC, blakehatch reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/688)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), pre-commit-checks, publish-image (waiting on @blakehatch)

___
*[`nativelink-config/examples/README.md` line  at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-36i6Li6VvBPmkRu:-NsE__6j3_wzWtczuT1r:b-yitsjw) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/examples/README.md#L)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Intentionally empty?
</blockquote></details>

Yes this is the file Marcus is working on for https://github.com/TraceMachina/nativelink/pull/680

I'm gonna rebase and land this after that's in, this is just there in the interim so there's something to point to.
___
*[`nativelink-config/src/lib.rs` line 15 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx37uY6CteWnzXDzwn:-NsE_lVR6MsQ6T1gVHqS:bonznz7) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/lib.rs#L15)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Viewing this in the docpage seems a bit overwhelming. Could we move the specific config examples to the respective stores?
</blockquote></details>

Yeah I want to restructure this page, just wanted to get everything in one place to start. Will try to find a good place to put everything and maybe take chunks of each README for the docs.
___
*[`nativelink-config/src/stores.rs` line 42 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-IyS6qcOpleQXont:-NsEaSn66Pb4mD0GTZq3:b-mslcxc) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/stores.rs#L42)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

I believe there needs to be an empty line around the code snippet to make sure that it's formatted correctly.
</blockquote></details>

There doesn't as we saw yesterday, rustdoc just only supports `rust` and `text` code snippets lol.
___
*[`nativelink-config/src/stores.rs` line 401 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nrx-prtAM4OamoJABaN:-NsEb9bc2ph7HNOz2Qn3:bk5zfe6) ([raw file](https://github.com/TraceMachina/nativelink/blob/1bc38d38b7543c1a6cf60428dd876cebcb795bb3/nativelink-config/src/stores.rs#L401)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: intentional dots?
</blockquote></details>

Fixed, was whitespace. Not sure why it's shown like that by reviewable.


<!-- Sent from Reviewable.io -->

2024-03-05 17:39 UTC, MarcusSorealheis requested changes
I don't think you should change the config example just yet. I think the more immediate need is for a sections in the docs that enumerates the config options and what all the values mean.

2024-03-05 19:14 UTC, allada submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/688)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), pre-commit-checks, publish-image (waiting on @blakehatch)

___
*[`nativelink-config/src/stores.rs` line 65 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/688#-NsF0i8A8E5Z6gWsF5Ef:-NsF0i8A8E5Z6gWsF5Eg:b-83k9aq) ([raw file](https://github.com/TraceMachina/nativelink/blob/a7410b0182b58cf1473c69dff596cdd7616b1629/nativelink-config/src/stores.rs#L65)):*
> ```XML
>     /// ```json
>     /// "experimental_s3_store": {
>     ///      "region": "eu-north-1",
> ```

nit: spacing here vs other examples are inconsistent.
___
*[`nativelink-config/src/stores.rs` line 73 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/688#-NsF0mHm76wzk3VWXNdB:-NsF0mHm76wzk3VWXNdC:b-v9r3rt) ([raw file](https://github.com/TraceMachina/nativelink/blob/a7410b0182b58cf1473c69dff596cdd7616b1629/nativelink-config/src/stores.rs#L73)):*
> ```XML
>     ///          "jitter": 0.5,
>     ///      },
>     ///  "additional_max_concurrent_requests": 10
> ```

nit: I think we got rid of this field.
___
*[`nativelink-config/src/stores.rs` line 90 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/688#-NsF0b6zC-UEWh1lXTF0:-NsF0b6zC-UEWh1lXTF1:bwpwc54) ([raw file](https://github.com/TraceMachina/nativelink/blob/a7410b0182b58cf1473c69dff596cdd7616b1629/nativelink-config/src/stores.rs#L90)):*
> ```XML
>     /// **Example JSON Config:**
>     /// ```json
>     /// "verify": {
> ```

This example is far to complex, can we do this with just a memory or filesystem store?
___
*[`nativelink-config/src/stores.rs` line 260 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/688#-NsF11a33xEWUposRnhC:-NsF11a33xEWUposRnhD:b-l7767k) ([raw file](https://github.com/TraceMachina/nativelink/blob/a7410b0182b58cf1473c69dff596cdd7616b1629/nativelink-config/src/stores.rs#L260)):*
> ```XML
>     ///         },
>     ///         "slow": {
>     ///           "experimental_s3_store": {
> ```

nit: Lets not use s3, just stick to memory and/or filesystem in examples.
___
*[`nativelink-config/src/stores.rs` line 371 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/688#-NsF13qg4x5rBVbvUNdt:-NsF13qg4x5rBVbvUNdu:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/a7410b0182b58cf1473c69dff596cdd7616b1629/nativelink-config/src/stores.rs#L371)):*
> ```XML
>     ///     },
>     ///     "slow": {
>     ///       "experimental_s3_store": {
> ```

ditto.
___
*[`nativelink-config/src/stores.rs` line 397 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/688#-NsF1B1N8IpUhJl7ui_j:-NsF1B1N8IpUhJl7ui_k:b-xk2bvb) ([raw file](https://github.com/TraceMachina/nativelink/blob/a7410b0182b58cf1473c69dff596cdd7616b1629/nativelink-config/src/stores.rs#L397)):*
> ```XML
>     /// "shard": {
>     ///     "stores": [
>     ///         "store": {
> ```

This is not right, it's an array with a key-value.
___
*[`nativelink-config/src/stores.rs` line 406 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/688#-NsF1ENe7P76nMh50Sn7:-NsF1ENe7P76nMh50Sn8:boaffpk) ([raw file](https://github.com/TraceMachina/nativelink/blob/a7410b0182b58cf1473c69dff596cdd7616b1629/nativelink-config/src/stores.rs#L406)):*
> ```XML
>     ///         },
>     ///        },
>     ///        "store": {
> ```

duplicate.
___
*[`nativelink-config/src/stores.rs` line 473 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/688#-NsF1IvjAAcN_0VJCWaX:-NsF1IvjAAcN_0VJCWaY:b-h9y9xs) ([raw file](https://github.com/TraceMachina/nativelink/blob/a7410b0182b58cf1473c69dff596cdd7616b1629/nativelink-config/src/stores.rs#L473)):*
> ```XML
>     ///     },
>     ///     "upper_store": {
>     ///       "noop": {}
> ```

nit: Add comment here saying this store discards data larger than 128mib.


<!-- Sent from Reviewable.io -->

2024-03-05 19:15 UTC, MarcusSorealheis commented
Nit: ```json5

2024-03-08 00:41 UTC, blakehatch commented
It seems like the lines in lib.rs pulling in the READMEs with relative paths
`#![doc = include_str!("../examples/README.md")]`
are causing issues with CI and creating the OCI image.

Any idea on a workaround @aaronmondal?

2024-04-04 19:56 UTC, blakehatch reviewed
Yeah putting up a PR for that rn, hopefully they can land relatively close to each other they supplement each other nicely.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/688#-:-NsF89N9CXviIxsnrORu:b7gj4wh)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), publish-image, and 9 discussions need to be resolved

___
*[`nativelink-config/src/stores.rs` line 65 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/688#-NsF0i8A8E5Z6gWsF5Ef:-NsQBglp6ZufDyBJ8JF0:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/a7410b0182b58cf1473c69dff596cdd7616b1629/nativelink-config/src/stores.rs#L65)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: spacing here vs other examples are inconsistent.
</blockquote></details>

Done.
___
*[`nativelink-config/src/stores.rs` line 73 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/688#-NsF0mHm76wzk3VWXNdB:-NsQAww95sAAYcnJGr2O:bskhznh) ([raw file](https://github.com/TraceMachina/nativelink/blob/a7410b0182b58cf1473c69dff596cdd7616b1629/nativelink-config/src/stores.rs#L73)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: I think we got rid of this field.
</blockquote></details>

It's still in all of the examples but looks like the option now is: "multipart_max_concurrent_uploads"
___
*[`nativelink-config/src/stores.rs` line 90 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/688#-NsF0b6zC-UEWh1lXTF0:-NsF8JmRE7ig5dITXJ1T:b-7de6ac) ([raw file](https://github.com/TraceMachina/nativelink/blob/a7410b0182b58cf1473c69dff596cdd7616b1629/nativelink-config/src/stores.rs#L90)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This example is far to complex, can we do this with just a memory or filesystem store?
</blockquote></details>

Yeah I can simplify, was trying to rip examples actually used in our configs when available.
___
*[`nativelink-config/src/stores.rs` line 260 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/688#-NsF11a33xEWUposRnhC:-NsQF1Jm2egog2GFSJsR:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/a7410b0182b58cf1473c69dff596cdd7616b1629/nativelink-config/src/stores.rs#L260)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Lets not use s3, just stick to memory and/or filesystem in examples.
</blockquote></details>

Done.
___
*[`nativelink-config/src/stores.rs` line 371 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/688#-NsF13qg4x5rBVbvUNdt:-NsQEAK51eAo4N8ViZcX:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/a7410b0182b58cf1473c69dff596cdd7616b1629/nativelink-config/src/stores.rs#L371)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`nativelink-config/src/stores.rs` line 397 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/688#-NsF1B1N8IpUhJl7ui_j:-NsQF0De7xFT2HYXkoK4:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/a7410b0182b58cf1473c69dff596cdd7616b1629/nativelink-config/src/stores.rs#L397)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This is not right, it's an array with a key-value.
</blockquote></details>

Done.
___
*[`nativelink-config/src/stores.rs` line 406 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/688#-NsF1ENe7P76nMh50Sn7:-NsQBwNx3m1s1eDXP0PZ:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/a7410b0182b58cf1473c69dff596cdd7616b1629/nativelink-config/src/stores.rs#L406)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

duplicate.
</blockquote></details>

Done.
___
*[`nativelink-config/src/stores.rs` line 473 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/688#-NsF1IvjAAcN_0VJCWaX:-NsQCJQM54ipx-mFApyu:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/a7410b0182b58cf1473c69dff596cdd7616b1629/nativelink-config/src/stores.rs#L473)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Add comment here saying this store discards data larger than 128mib.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-04 21:59 UTC, aaronmondal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/688#-:-Nuf6oT05Wj1t2gWfvxL:bnfp4nl)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), publish-image, and 7 discussions need to be resolved (waiting on @blakehatch)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nuf6Cc92YLZtigHetR2):*
nit: Shorten title, put detail in message body.
___
*[`deployment-examples/kubernetes/BUILD.bazel` line 8 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nuf6JsvA_rPtARCa7Uv:-Nuf6JsvA_rPtARCa7Uw:bhm09qw) ([raw file](https://github.com/TraceMachina/nativelink/blob/d4637e92eefadb6cad10af27d2f8640d6c567c4a/deployment-examples/kubernetes/BUILD.bazel#L8)):*
> ```Starlark
>         "cas.yaml",
>         "scheduler.json",
>         "scheduler.yaml",
> ```

nit: Is this missing the worker? Maybe a glob pattern would make sense here.


<!-- Sent from Reviewable.io -->

2024-04-05 01:15 UTC, blakehatch reviewed
> Dismissed @allada from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/688)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 4 discussions need to be resolved

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nuf6Cc92YLZtigHetR2):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Shorten title, put detail in message body.
</blockquote></details>

Done.
___
*[`deployment-examples/kubernetes/BUILD.bazel` line 8 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/688#-Nuf6JsvA_rPtARCa7Uv:-NufokDM7CkYXNAh35ug:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/d4637e92eefadb6cad10af27d2f8640d6c567c4a/deployment-examples/kubernetes/BUILD.bazel#L8)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Is this missing the worker? Maybe a glob pattern would make sense here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-05 16:38 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r3, 3 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/688#-:-Nuj6wfX7MF6KbeQSKO0:bnfp4nl)* status: 0 of 1 LGTMs obtained, and pending CI: Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), and 4 discussions need to be resolved (waiting on @blakehatch)



<!-- Sent from Reviewable.io -->

2024-05-15 21:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TraceMachina/nativelink?pullRequest=688) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TraceMachina/nativelink?pullRequest=688) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TraceMachina/nativelink?pullRequest=688) it.</sub>

2024-12-14 23:51 UTC, aaronmondal commented
Outdated.

2024-12-14 23:51 UTC, closed without merging