check owner and group executable bits
TraceMachina/nativelink pull request #727
Opened 2024-03-06 03:27 UTC by zbirenbaum

# Description
Change `is_executable` to check for owner and group permissions instead of just all users

Fixes #675

- [ x ] Bug fix (non-breaking change which fixes an issue)

2024-03-06 05:38 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/727)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/727#-NsHG8OF5CKaP3ekv03G:-NsHG8OF5CKaP3ekv03H:b-6qma3n) (no related file):*
nit: Please correct the paragraph part in the pull request to be grammatically correct.

___
*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/727#-NsHGFuk5KnRT5fjxrLv:-NsHGFuk5KnRT5fjxrLw:b-dm6lxm) (no related file):*
Need a test

___


<!-- Sent from Reviewable.io -->

2024-03-06 07:41 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/727)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/727#-NsHG8OF5CKaP3ekv03G:-NsHdPgE3Cz2ix_TPC7y:bnqmpgr) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Please correct the paragraph part in the pull request to be grammatically correct.
</blockquote></details>

Haha nice catch! Just fixed it

___
*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/727#-NsHGFuk5KnRT5fjxrLv:-NsHeXfv78uwAk6_v2_B:b4djkz4) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Need a test
</blockquote></details>

Got it, I'll work on that next

___


<!-- Sent from Reviewable.io -->

2024-03-06 17:06 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/727)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/727#-NsHG8OF5CKaP3ekv03G:-NsJioz89OAZSuJNLvFE:b2e7t6g) (no related file):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Haha nice catch! Just fixed it
</blockquote></details>

Nice, but please remove the question now. This will become your commit message.

___


<!-- Sent from Reviewable.io -->

2024-03-07 07:42 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/727)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/727#-NsHGFuk5KnRT5fjxrLv:-NsMrD4q55tvzWD_UgJC:b-lcblvg) (no related file):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Got it, I'll work on that next
</blockquote></details>

Test has been added and I confirmed that it fails without the change

___


<!-- Sent from Reviewable.io -->

2024-03-08 20:56 UTC, adam-singer requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/727)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/727#-NsUqFFKDfXBXftmyYfn):*
commits should be squashed 


<!-- Sent from Reviewable.io -->

2024-03-10 03:17 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/727#-:-NsaMLGs4oeMJeX3ARIT:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: pre-commit-checks

___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/727#-NsaK87M28Ms2tIrYHx4):*
nit: should be in form:
```
Short tile without trailing period

Short paragraph of what changed.

[fixes|closes|towards] #ticket_number
```
___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 145 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/727#-NsaKQl16T29kZ0BzpFt:-NsaKQl16T29kZ0BzpFu:b-pc5r9u) ([raw file](https://github.com/TraceMachina/nativelink/blob/f98eaf3e2ac2a38ea6d48632728b6f2406c94d55/nativelink-worker/tests/running_actions_manager_test.rs#L145)):*
> ```XML
> #[cfg(test)]
> mod running_actions_manager_tests {
>     use nativelink_proto::build::bazel::remote::execution::v2::command::EnvironmentVariable;
> ```

nit: Put this at top of file with other imports.
___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2586 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/727#-NsaKplQ0nvEiKYQRTaF:-NsaKplQ0nvEiKYQRTaG:b-mtpuuq) ([raw file](https://github.com/TraceMachina/nativelink/blob/f98eaf3e2ac2a38ea6d48632728b6f2406c94d55/nativelink-worker/tests/running_actions_manager_test.rs#L2586)):*
> ```XML
>         fs::create_dir_all(&root_work_directory).await?;
> 
>         let running_actions_manager = Arc::new(RunningActionsManagerImpl::new_with_callbacks(
> ```

nit: I believe in this test we can use `RunningActionsManagerImpl::new` unless you need those callbacks.
___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2618 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/727#-NsaLo0I9CF2i7YFfWki:-NsaLo0I9CF2i7YFfWkj:b-uhbgt7) ([raw file](https://github.com/TraceMachina/nativelink/blob/f98eaf3e2ac2a38ea6d48632728b6f2406c94d55/nativelink-worker/tests/running_actions_manager_test.rs#L2618)):*
> ```XML
>                     "sh".to_string(),
>                     "-c".to_string(),
>                     "echo whoami > ${OUTS} && chmod 740 ${OUTS}".to_string(),
> ```

nit:
```rs
"touch {FILE_1_NAME} && chmod 700 {FILE_1_NAME}".to_string()
```

And remove the environ.
___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2650 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/727#-NsaLJFrEgRqWl4SRqPU:-NsaLJFrEgRqWl4SRqPV:bjpj0pg) ([raw file](https://github.com/TraceMachina/nativelink/blob/f98eaf3e2ac2a38ea6d48632728b6f2406c94d55/nativelink-worker/tests/running_actions_manager_test.rs#L2650)):*
> ```XML
>                             ..Default::default()
>                         }),
>                         salt: SALT,
> ```

nit: Inline these. Or better yet use `..Default::default()` and remove them.
___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2659 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/727#-NsaME0N3-p2JRe7j-iD:-NsaME0N3-p2JRe7j-iE:bb6v01b) ([raw file](https://github.com/TraceMachina/nativelink/blob/f98eaf3e2ac2a38ea6d48632728b6f2406c94d55/nativelink-worker/tests/running_actions_manager_test.rs#L2659)):*
> ```XML
>         };
>         // Ensure the file copied from worker to CAS is executable.
>         assert!(action_result.output_files[0].is_executable);
> ```

nit: Add description of error as second argument.


<!-- Sent from Reviewable.io -->

2024-03-10 23:28 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/727)* status: 1 of 1 LGTMs obtained, and pending CI: pre-commit-checks

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/727#-NsUqFFKDfXBXftmyYfn):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

commits should be squashed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-11 05:01 UTC, allada reviewed
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/727)* status: 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-03-11 05:02 UTC, allada reviewed
> Dismissed @adam-singer from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/727)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-03-11 16:12 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/727#-:-NsiHLpt3fTAo7yegAiE:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-03-11 16:57 UTC, zbirenbaum reviewed
> Reviewed 1 of 1 files at r1, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/727)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-03-11 16:57 UTC, merged