Use jemalloc on non-windows to reduce memory fragmentation
TraceMachina/nativelink pull request #738
Opened 2024-03-08 19:55 UTC by allada

To help reduce/remove memory fragmentation caused by memory store we are switching our allocator to jemalloc. This should make our memory compaction significantly more efficient.

closes #621

2024-03-08 19:56 UTC, allada reviewed
+@aaronmondal 

fyi: @chrisstaite-menlo 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/738#-:-NsUckNX6M5tTJLRsIXG:b9jwnn1)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @aaronmondal)



<!-- Sent from Reviewable.io -->

2024-03-08 20:14 UTC, MarcusSorealheis reviewed
It's great that we have solved this here and I think it's a fantastic ongoing experiment for us. The `memory_store`will continue to surface bleeding edge issues. 

Now, more than ever I think we need to land the redis_store (not actually vendor specific) functionality. cc @blakehatch and @zbirenbaum 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/738#-:-NsUfsnP5Na5AlDsrV17:b-c9rz5j)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @aaronmondal)



<!-- Sent from Reviewable.io -->

2024-03-08 20:24 UTC, blakehatch commented
> It's great that we have solved this here and I think it's a fantastic ongoing experiment for us. The `memory_store`will continue to surface bleeding edge issues.
> 
> Now, more than ever I think we need to land the redis_store (not actually vendor specific) functionality. cc @blakehatch and @zbirenbaum
> 
> > _[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/738#-:-NsUfsnP5Na5AlDsrV17:b-c9rz5j)_ status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @aaronmondal)

Agreed I'll be dusting off the old redis store PR soon with a fresh rebase and clean up how the mocking is done. Will need to set up some integration tests with @aaronmondal and would love @zbirenbaum's help as well!

2024-03-08 20:50 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

We should try and collect some previous metrics on memory consumption and deploy this collecting same metrics to see a difference. jemalloc does allow for easier profiling and is a battle harden allocator, ymmv depending on what this is to solve. Longer term we should probably have some like https://www.polarsignals.com/blog/posts/2023/12/20/rust-memory-profiling integrated to pull a profile while system is running. 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/738#-:-NsUncMK1uYEjMbm49RU:bwgo5y4)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), publish-image (waiting on @aaronmondal)



<!-- Sent from Reviewable.io -->

2024-03-09 00:09 UTC, aaronmondal requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/738)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), publish-image (waiting on @aaronmondal)

___
*[`Cargo.toml` line 57 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/738#-NsVXbtu-IoH2zqCIoYa:-NsVXbtu-IoH2zqCIoYb:b5eczdy) ([raw file](https://github.com/TraceMachina/nativelink/blob/82b5ad37db455daace7f717e8d5c5dc78ec2c5c0/Cargo.toml#L57)):*
> ```TOML
> 
> [target.'cfg(not(target_env = "msvc"))'.dependencies]
> tikv-jemallocator = "0.5.4"
> ```

It looks like we'd have to patch (or rewrite) the buildscript for the crate. The previous attempt to use MiMalloc #736 passed tests etc but didn't solve the defragmentation issue.

If I understand https://github.com/microsoft/mimalloc/issues/632 correctly it seems like it's possible to pull the defragmentation functionality from jemalloc into mimalloc with a patch like this: https://github.com/romange/helio/tree/master/patches

Maybe it's worth a shot to attempt using such a patched version of `mimalloc` rather than trying to fix the buildscript for `tikv-jemallocator`?


<!-- Sent from Reviewable.io -->

2024-03-09 00:31 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/738)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), publish-image (waiting on @aaronmondal)

___
*[`Cargo.toml` line 57 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/738#-NsVXbtu-IoH2zqCIoYa:-NsVblLv-rnjjB0c-ujB:b-h42s6l) ([raw file](https://github.com/TraceMachina/nativelink/blob/82b5ad37db455daace7f717e8d5c5dc78ec2c5c0/Cargo.toml#L57)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

It looks like we'd have to patch (or rewrite) the buildscript for the crate. The previous attempt to use MiMalloc #736 passed tests etc but didn't solve the defragmentation issue.

If I understand https://github.com/microsoft/mimalloc/issues/632 correctly it seems like it's possible to pull the defragmentation functionality from jemalloc into mimalloc with a patch like this: https://github.com/romange/helio/tree/master/patches

Maybe it's worth a shot to attempt using such a patched version of `mimalloc` rather than trying to fix the buildscript for `tikv-jemallocator`?
</blockquote></details>

Hmmm, maybe we should just make the copy in a different allocator then :-( . 


<!-- Sent from Reviewable.io -->

2024-03-11 05:06 UTC, closed without merging