Add safe request timeout for running actions manager
TraceMachina/nativelink pull request #743
Opened 2024-03-10 01:03 UTC by zbirenbaum

# Description
Backport of running actions manager timeout changes which checks the timeout for an action and defaults to a maximum if not set.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-03-10 02:57 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NsaHjc04NsD9eJzysrt:-NsaHjc04NsD9eJzysru:b-nwzgsn) (no related file):*
lgtm, but we need a test.

___


<!-- Sent from Reviewable.io -->

2024-03-11 16:22 UTC, adam-singer approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-03-11 20:17 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NsaHjc04NsD9eJzysrt:-Nsj9T-C2u4IlGq2PfWy:b-mz8885) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

lgtm, but we need a test.
</blockquote></details>

Test has been added

___


<!-- Sent from Reviewable.io -->

2024-03-11 20:27 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743#-:-NsjBn5V73pX8XIJEDlR:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: pre-commit-checks



<!-- Sent from Reviewable.io -->

2024-03-11 23:44 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743#-:-Nsjtly5CL1xq_us8KeG:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: windows-2022 / stable



<!-- Sent from Reviewable.io -->

2024-03-17 08:44 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 1 of 1 LGTMs obtained, and pending CI: windows-2022 / stable

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2660 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NtAZYQ5E_HXGLWTaFKj:-NtAZYQ5E_HXGLWTaFKk:bdng0xf) ([raw file](https://github.com/TraceMachina/nativelink/blob/54afc90b8616a5fa5ff800095a6f172a4f819376/nativelink-worker/tests/running_actions_manager_test.rs#L2660)):*
> ```XML
>     #[tokio::test]
>     async fn running_actions_manager_respects_action_timeout() -> Result<(), Box<dyn std::error::Error>> {
>         #[cfg(target_family = "unix")]
> ```

nit: This should probably be removed.
___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2698 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NtA_9bY42U1Ht-YH1BM:-NtA_9bY42U1Ht-YH1BN:b-836v9w) ([raw file](https://github.com/TraceMachina/nativelink/blob/54afc90b8616a5fa5ff800095a6f172a4f819376/nativelink-worker/tests/running_actions_manager_test.rs#L2698)):*
> ```XML
>         )
>         .await?;
>         const TASK_TIMEOUT: Duration = Duration::from_secs(1);
> ```

Tests should not use wall-time. In this case, you probably want to use `RunningActionsManagerImpl::new_with_timeout` or something to give test control of the timeout function, then use some signaling to facilitate this test.


<!-- Sent from Reviewable.io -->

2024-03-25 20:30 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, vale, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2698 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NtA_9bY42U1Ht-YH1BM:-NtrH03o2o7OwvNTa9fl:bzcnam9) ([raw file](https://github.com/TraceMachina/nativelink/blob/54afc90b8616a5fa5ff800095a6f172a4f819376/nativelink-worker/tests/running_actions_manager_test.rs#L2698)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Tests should not use wall-time. In this case, you probably want to use `RunningActionsManagerImpl::new_with_timeout` or something to give test control of the timeout function, then use some signaling to facilitate this test.
</blockquote></details>

I think the easiest way to do this without actually waiting is to set both the timeout and max_timeout to 0, at which point the checks for time elapsed will just always return true. 


<!-- Sent from Reviewable.io -->

2024-03-26 16:25 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743#-:-Ntv_EK997OKCDi4WNdy:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: windows-2022 / stable



<!-- Sent from Reviewable.io -->

2024-03-27 16:24 UTC, allada requested changes
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 1 of 1 LGTMs obtained, and pending CI: windows-2022 / stable, and 3 discussions need to be resolved

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2698 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NtA_9bY42U1Ht-YH1BM:-Nu-i9L_7kgqd91IqLDL:b-hso3lj) ([raw file](https://github.com/TraceMachina/nativelink/blob/54afc90b8616a5fa5ff800095a6f172a4f819376/nativelink-worker/tests/running_actions_manager_test.rs#L2698)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

I think the easiest way to do this without actually waiting is to set both the timeout and max_timeout to 0, at which point the checks for time elapsed will just always return true.
</blockquote></details>

I'm not a huge fan of doing this, it makes future bugs even more difficult to write tests for and people will end up copy-pasta the pattern around.

It should be fairly trivial to hand in a custom `sleep` function and allow the test to override it here, we do this in quite a few places.


<!-- Sent from Reviewable.io -->

2024-04-01 06:59 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Bazel Dev / ubuntu-22.04, Publish image, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, and 2 discussions need to be resolved

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2660 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NtAZYQ5E_HXGLWTaFKj:-NuNRoHc1hQhpLNgOfVT:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/54afc90b8616a5fa5ff800095a6f172a4f819376/nativelink-worker/tests/running_actions_manager_test.rs#L2660)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: This should probably be removed.
</blockquote></details>

Done.
___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2698 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NtA_9bY42U1Ht-YH1BM:-NuNRpyCEODHVeo39TaL:b-vimjbu) ([raw file](https://github.com/TraceMachina/nativelink/blob/54afc90b8616a5fa5ff800095a6f172a4f819376/nativelink-worker/tests/running_actions_manager_test.rs#L2698)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I'm not a huge fan of doing this, it makes future bugs even more difficult to write tests for and people will end up copy-pasta the pattern around.

It should be fairly trivial to hand in a custom `sleep` function and allow the test to override it here, we do this in quite a few places.
</blockquote></details>

I've updated it to take a custom sleep function which will immediately return if the correct timeout is passed and stall indefinitely causing the action to complete and the test to fail otherwise.


<!-- Sent from Reviewable.io -->

2024-04-01 15:25 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743#-:-NuPG-sUB8ye3m0IEZiu:bnfp4nl)* status: 2 of 1 LGTMs obtained, and pending CI: windows-2022 / stable, and 2 discussions need to be resolved

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2944 at r8](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NuPEbBy6_tieLXAZdnl:-NuPEbBy6_tieLXAZdnm:b-2wak3l) ([raw file](https://github.com/TraceMachina/nativelink/blob/00a1250beea8f8501375ab5899424de3c20d0cd7/nativelink-worker/tests/running_actions_manager_test.rs#L2944)):*
> ```XML
>         fs::create_dir_all(&root_work_directory).await?;
> 
>         // ignore the sleep and immediately timeout
> ```

nit: Caps and period.
___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2973 at r8](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NuPFmz597rLQR2CycKD:-NuPFmz597rLQR2CycKE:bayjl6h) ([raw file](https://github.com/TraceMachina/nativelink/blob/00a1250beea8f8501375ab5899424de3c20d0cd7/nativelink-worker/tests/running_actions_manager_test.rs#L2973)):*
> ```XML
>                 // otherwise return pending and fail the test.
>                 sleep_fn: |duration| {
>                     if duration.as_secs() == ACTION_TIMEOUT as u64 {
> ```

nit: For readability, assert that duration is `ACTION_TIMEOUT` and then return ready.


<!-- Sent from Reviewable.io -->

2024-04-01 17:42 UTC, adam-singer approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 2 of 1 LGTMs obtained, and pending CI: windows-2022 / stable, and 2 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-04-02 22:20 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 2 of 1 LGTMs obtained, and pending CI: Vercel, pre-commit-checks

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2944 at r8](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NuPEbBy6_tieLXAZdnl:-NuVt_7216-75IxEFoOp:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/00a1250beea8f8501375ab5899424de3c20d0cd7/nativelink-worker/tests/running_actions_manager_test.rs#L2944)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Caps and period.
</blockquote></details>

Done.
___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2973 at r8](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NuPFmz597rLQR2CycKD:-NuVtU9m8NobJqTEBTIF:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/00a1250beea8f8501375ab5899424de3c20d0cd7/nativelink-worker/tests/running_actions_manager_test.rs#L2973)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: For readability, assert that duration is `ACTION_TIMEOUT` and then return ready.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-03 15:29 UTC, allada approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 2 of 1 LGTMs obtained, and pending CI: integration-tests (20.04), integration-tests (22.04), windows-2022 / stable



<!-- Sent from Reviewable.io -->

2024-04-03 23:29 UTC, zbirenbaum reviewed
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 2 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04



<!-- Sent from Reviewable.io -->

2024-04-04 18:44 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 2 of 1 LGTMs obtained, and pending CI: integration-tests (20.04), integration-tests (22.04), windows-2022 / stable, and 1 discussions need to be resolved

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 3259 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NueQ-ov7aF6QcEKvOzA:-NueQ-ov7aF6QcEKvOzB:b-7dxp1o) ([raw file](https://github.com/TraceMachina/nativelink/blob/9a81488259f002d777e08155b4f1f3e689db144a/nativelink-worker/tests/running_actions_manager_test.rs#L3259)):*
> ```XML
>         let arguments = vec!["sh".to_string(), "-c".to_string(), "sleep 2".to_string()];
>         #[cfg(target_family = "windows")]
>         let arguments = vec![
> ```

This is what is causing the test to fail. It is returning error code 1 which is `incorrect function`. I have been reading up on it but can't figure it out so I'm just going to remove to remove this test for windows if that's alright @allada 


<!-- Sent from Reviewable.io -->

2024-04-04 23:22 UTC, adam-singer approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 2 of 1 LGTMs obtained, and pending CI: integration-tests (20.04), integration-tests (22.04), windows-2022 / stable, and 1 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-04-05 16:46 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 2 of 1 LGTMs obtained, and pending CI: integration-tests (20.04), integration-tests (22.04), windows-2022 / stable, and 1 discussions need to be resolved

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 3259 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NueQ-ov7aF6QcEKvOzA:-Nuj8tioDMDQmx49qYPW:b-lrwbey) ([raw file](https://github.com/TraceMachina/nativelink/blob/9a81488259f002d777e08155b4f1f3e689db144a/nativelink-worker/tests/running_actions_manager_test.rs#L3259)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

This is what is causing the test to fail. It is returning error code 1 which is `incorrect function`. I have been reading up on it but can't figure it out so I'm just going to remove to remove this test for windows if that's alright @allada
</blockquote></details>

Why not down below set the error code on windows to expect exit code `1`?


<!-- Sent from Reviewable.io -->

2024-04-05 19:02 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 2 of 1 LGTMs obtained, and pending CI: integration-tests (20.04), integration-tests (22.04), windows-2022 / stable, and 1 discussions need to be resolved

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 3259 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NueQ-ov7aF6QcEKvOzA:-NujcdlV0k6HRT-tcSSc:b2cxym3) ([raw file](https://github.com/TraceMachina/nativelink/blob/9a81488259f002d777e08155b4f1f3e689db144a/nativelink-worker/tests/running_actions_manager_test.rs#L3259)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Why not down below set the error code on windows to expect exit code `1`?
</blockquote></details>

Judging by the docs it seems like exit code 1 corresponds to something else that wouldn't actually be showing the proper behavior here. It's difficult to tell so I guess its possible that's the expected error code but I'm not certain. If not being sure is preferable to removing the test we can do that


<!-- Sent from Reviewable.io -->

2024-04-05 22:30 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 2 of 1 LGTMs obtained, and pending CI: integration-tests (20.04), integration-tests (22.04), windows-2022 / stable, and 1 discussions need to be resolved

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 3259 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NueQ-ov7aF6QcEKvOzA:-NukNRYvEe0QUsDX3rke:b-y59bol) ([raw file](https://github.com/TraceMachina/nativelink/blob/9a81488259f002d777e08155b4f1f3e689db144a/nativelink-worker/tests/running_actions_manager_test.rs#L3259)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Judging by the docs it seems like exit code 1 corresponds to something else that wouldn't actually be showing the proper behavior here. It's difficult to tell so I guess its possible that's the expected error code but I'm not certain. If not being sure is preferable to removing the test we can do that
</blockquote></details>

This test is not actually testing the error code, it's checking that the timeout triggers. The error code is a side-effect. In this case, I would just make a TODO and keep the test for windows.


<!-- Sent from Reviewable.io -->

2024-04-08 20:54 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/743)* status: 2 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-22.04

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 3259 at r12](https://reviewable.io/reviews/TraceMachina/nativelink/743#-NueQ-ov7aF6QcEKvOzA:-NuzTIW67dwd_iqeaIMM:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/9a81488259f002d777e08155b4f1f3e689db144a/nativelink-worker/tests/running_actions_manager_test.rs#L3259)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This test is not actually testing the error code, it's checking that the timeout triggers. The error code is a side-effect. In this case, I would just make a TODO and keep the test for windows.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-08 21:10 UTC, merged