Create directory for action
TraceMachina/nativelink pull request #752
Opened 2024-03-11 23:25 UTC by zbirenbaum

# Description

Modifies running actions manager and workers to create an action directory with a dedicated work directory inside instead of just creating a work directory for the task. Other directories can be mounted to this space and will be automatically cleaned on completion.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Added a test to ensure that any temporary resources in the directory are cleaned on action completion

## Checklist

- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-03-11 23:30 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/752)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`nativelink-config/src/cas_server.rs` line 429 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/752#-NsjpaOA-Y7xKmQRBF9L:-NsjpaOB5MIu4eDIcKKY:bulbj5x) ([raw file](https://github.com/TraceMachina/nativelink/blob/2910f8a1aa2ac03e6ccafeb37ef0b9d9832112e3/nativelink-config/src/cas_server.rs#L429)):*
> ```XML
>     /// completed. This directory will be purged after the action has
>     /// completed.
>     action_directory,
> ```

Since this is in nativelink-config and the idea of this change is to have a space where users can put temporary resources, I thought there should be a documentation update, but there isn't any reference to these fields in the example. Should I include the v0.1 changes to deployment examples in this PR since there is one that makes use of it?


<!-- Sent from Reviewable.io -->

2024-03-17 08:37 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/752#-:-NtAYn0p5CRLboigW2W6:bnfp4nl)* status: 1 of 1 LGTMs obtained

___
*[`nativelink-config/src/cas_server.rs` line 429 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/752#-NsjpaOA-Y7xKmQRBF9L:-NtAX31L1R8or0Ynj-hl:bui1dhc) ([raw file](https://github.com/TraceMachina/nativelink/blob/2910f8a1aa2ac03e6ccafeb37ef0b9d9832112e3/nativelink-config/src/cas_server.rs#L429)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Since this is in nativelink-config and the idea of this change is to have a space where users can put temporary resources, I thought there should be a documentation update, but there isn't any reference to these fields in the example. Should I include the v0.1 changes to deployment examples in this PR since there is one that makes use of it?
</blockquote></details>

Yeah, I think adding a sample on how to use it would be useful, but maybe this would be better to document as more of an advanced config, so users rely on it only for these special cases, like using it with docker.

or maybe in one of the examples that uses `entrypoint.sh` we can show it overriding `TMPDIR` with a path this folder?
___
*[`nativelink-store/Cargo.toml` line 34 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/752#-NtAXyav9vdz16iULsSV:-NtAXyav9vdz16iULsSW:bgpu4m) ([raw file](https://github.com/TraceMachina/nativelink/blob/99701e0b7feacdba7e26540164ca238a01c1efcc/nativelink-store/Cargo.toml#L34)):*
> ```TOML
> shellexpand = "3.1.0"
> tempfile = "3.10.1"
> tokio = { version = "1.36.0", features = ["rt-multi-thread"] }
> ```

I don't think this is required for this change.


<!-- Sent from Reviewable.io -->

2024-03-25 20:06 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/752)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`nativelink-config/src/cas_server.rs` line 429 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/752#-NsjpaOA-Y7xKmQRBF9L:-NtrCUjK9UWBuY3C2KjI:b-5z33p1) ([raw file](https://github.com/TraceMachina/nativelink/blob/2910f8a1aa2ac03e6ccafeb37ef0b9d9832112e3/nativelink-config/src/cas_server.rs#L429)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Yeah, I think adding a sample on how to use it would be useful, but maybe this would be better to document as more of an advanced config, so users rely on it only for these special cases, like using it with docker.

or maybe in one of the examples that uses `entrypoint.sh` we can show it overriding `TMPDIR` with a path this folder?
</blockquote></details>

I can't find any examples referencing entrypoint.sh except one in terraform's GCP directory and I'm not sure exactly what to add there for this. I rebased the commit to see if any more were added and resolve the conflicts but that still seems to be the only example


<!-- Sent from Reviewable.io -->

2024-03-25 21:06 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/752)* status: 1 of 1 LGTMs obtained

___
*[`nativelink-config/src/cas_server.rs` line 429 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/752#-NsjpaOA-Y7xKmQRBF9L:-NtrPh6KCUyezqm3TJCB:b-hq3x8b) ([raw file](https://github.com/TraceMachina/nativelink/blob/2910f8a1aa2ac03e6ccafeb37ef0b9d9832112e3/nativelink-config/src/cas_server.rs#L429)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

I can't find any examples referencing entrypoint.sh except one in terraform's GCP directory and I'm not sure exactly what to add there for this. I rebased the commit to see if any more were added and resolve the conflicts but that still seems to be the only example
</blockquote></details>

@adam-singer and I looked for a good place to include the usage or document this feature but couldn't find any. There aren't very many examples where it would make sense to set the action directory, and modifying them would likely result in users just copying it in when they go to set up their own config. Since there is not any existing documentation for the other fields in EnvironmentSource maybe we could document this feature during a full pass at those and then have a minimal example or description showing it's usage there?


<!-- Sent from Reviewable.io -->

2024-03-26 16:25 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/752#-:-Ntv_3Zz9Bcrf-q9hFBy:bnfp4nl)* status: 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-03-27 17:00 UTC, adam-singer reviewed
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/752)* status: 2 of 1 LGTMs obtained, and 2 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-03-27 18:27 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/752)* status: 2 of 1 LGTMs obtained, and pending CI: Publish image, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, vale, and 1 discussions need to be resolved

___
*[`nativelink-store/Cargo.toml` line 34 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/752#-NtAXyav9vdz16iULsSV:-Nu09d0BEPF8kokS16QW:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/99701e0b7feacdba7e26540164ca238a01c1efcc/nativelink-store/Cargo.toml#L34)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I don't think this is required for this change.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-28 19:37 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/752)* status: 2 of 1 LGTMs obtained, and 1 discussions need to be resolved

___
*[`nativelink-store/Cargo.toml` line 34 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/752#-NtAXyav9vdz16iULsSV:-Nu5Yy9GBucxvO0_GBfi:b-45zrka) ([raw file](https://github.com/TraceMachina/nativelink/blob/99701e0b7feacdba7e26540164ca238a01c1efcc/nativelink-store/Cargo.toml#L34)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think this is blocking the PR since it’s the only thing left in reviewable.


<!-- Sent from Reviewable.io -->

2024-03-30 14:36 UTC, allada requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/752)* status: 2 of 1 LGTMs obtained, and 1 discussions need to be resolved

___
*[`nativelink-config/src/cas_server.rs` line 459 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/752#-NuElZWUAlHrNhKq8YCx:-NuElZWUAlHrNhKq8YCy:b-5b3tr) ([raw file](https://github.com/TraceMachina/nativelink/blob/91f7297ed1228e73019321a6920946ddccc3c25c/nativelink-config/src/cas_server.rs#L459)):*
> ```XML
>     /// For example:
>     /// If an action makes use of some constant path to create and
>     /// reference files (such as /tmp), you can set this value to /tmp.
> ```

This is missleading. I suggest something like:

```
For example:
If an action writes temporary data to a path but nativelink should clean up this path after
the job has executed, you may create any directory under the path provided in this variable.
A common pattern would be to use `entrypoint` to set a shell script that reads this variable,
`mkdir $ENV_VAR_NAME/tmp` and `export TMPDIR=$ENV_VAR_NAME/tmp`. Another example
might be to bind-mount the `/tmp` path in a container to this path in `entrypoint`.
```


<!-- Sent from Reviewable.io -->

2024-04-01 07:21 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/752)* status: 2 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Bazel Dev / ubuntu-22.04, Publish image, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, vale, and 1 discussions need to be resolved

___
*[`nativelink-config/src/cas_server.rs` line 459 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/752#-NuElZWUAlHrNhKq8YCx:-NuNTWvW6SlKXVVmbH40:b-3cu5nn) ([raw file](https://github.com/TraceMachina/nativelink/blob/91f7297ed1228e73019321a6920946ddccc3c25c/nativelink-config/src/cas_server.rs#L459)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This is missleading. I suggest something like:

```
For example:
If an action writes temporary data to a path but nativelink should clean up this path after
the job has executed, you may create any directory under the path provided in this variable.
A common pattern would be to use `entrypoint` to set a shell script that reads this variable,
`mkdir $ENV_VAR_NAME/tmp` and `export TMPDIR=$ENV_VAR_NAME/tmp`. Another example
might be to bind-mount the `/tmp` path in a container to this path in `entrypoint`.
```
</blockquote></details>

Thanks for including this! I edited the comment.


<!-- Sent from Reviewable.io -->

2024-04-01 15:26 UTC, allada reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/752)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-04-01 17:40 UTC, adam-singer reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/752)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-04-01 22:31 UTC, zbirenbaum reviewed
> Reviewed 1 of 5 files at r3, 3 of 3 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/752)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-04-01 23:56 UTC, merged