Unify RunningAction and AwaitedAction
TraceMachina/nativelink pull request #782
Opened 2024-03-20 21:25 UTC by zbirenbaum

Refactor scheduler to use a single struct for state management of all incomplete actions. Removes `RunningAction` entirely and adds an optional `worker_id` field to `AwaitedAction`

closes: #781

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

All existing tests pass

## Checklist
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-03-21 13:13 UTC, adam-singer requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/782)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 477 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/782#-NtW8Aab66LLMDEi01B1:-NtW8AacEvlrCNCD9iVF:bob2ogq) ([raw file](https://github.com/TraceMachina/nativelink/blob/466fee6613f62b5d6459a83fb0989a7ad5de518f/nativelink-scheduler/src/simple_scheduler.rs#L477)):*
> ```XML
>             );
>             Arc::make_mut(&mut awaited_action.current_state).stage = ActionStage::Executing;
>             awaited_action.worker_id = Some(worker_id);
> ```

Is it possible for this to be previously set?  If so what happens if it is?


<!-- Sent from Reviewable.io -->

2024-03-22 20:12 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/782)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 477 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/782#-NtW8Aab66LLMDEi01B1:-Ntbfom5A2m3Xof9wNsL:bnhwpog) ([raw file](https://github.com/TraceMachina/nativelink/blob/466fee6613f62b5d6459a83fb0989a7ad5de518f/nativelink-scheduler/src/simple_scheduler.rs#L477)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Is it possible for this to be previously set?  If so what happens if it is?
</blockquote></details>

It might be possible for it to be previously set, but it shouldn't be an issue. If an action info in queued_actions has an assigned worker_id, that would mean it was previously running, but got dropped and added back to the queued actions list. If this occurs, then we need to assign it a new worker anyway. 


<!-- Sent from Reviewable.io -->

2024-03-22 23:17 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/782)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 477 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/782#-NtW8Aab66LLMDEi01B1:-NtbmyPq62K__dF1UI9t:b-3bl82x) ([raw file](https://github.com/TraceMachina/nativelink/blob/466fee6613f62b5d6459a83fb0989a7ad5de518f/nativelink-scheduler/src/simple_scheduler.rs#L477)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

It might be possible for it to be previously set, but it shouldn't be an issue. If an action info in queued_actions has an assigned worker_id, that would mean it was previously running, but got dropped and added back to the queued actions list. If this occurs, then we need to assign it a new worker anyway.
</blockquote></details>

It looks like there's a requested change for removing the borrow from `&mut awaited_action.current_state` but doing so causes a compiler error.


<!-- Sent from Reviewable.io -->

2024-03-25 21:23 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/782)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 595 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/782#-NtqjpY_8jJWL9vgoR55:-NtrUk7X0MkqO1wXO3N4:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/466fee6613f62b5d6459a83fb0989a7ad5de518f/nativelink-scheduler/src/simple_scheduler.rs#L595)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Unwrapping a `None` here would cause a panic, are we assuming all code paths have properly set this field to an Option?

I've seen this pattern with rust, where Options inner values are reached for but disregarding the `None` case.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-25 21:23 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/782#-:-NtrUhFkETJoMya4T8Nb:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04



<!-- Sent from Reviewable.io -->

2024-03-25 21:28 UTC, adam-singer approved these changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/782)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04



<!-- Sent from Reviewable.io -->

2024-03-25 21:31 UTC, adam-singer approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/782)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04



<!-- Sent from Reviewable.io -->

2024-03-27 02:39 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/782#-:-NtxljgCEGzugBUtsq7p:bnfp4nl)* status: 2 of 1 LGTMs obtained

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 529 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/782#-Ntxkl3Y0Imyf5HDeYRt:-Ntxkl3Y0Imyf5HDeYRu:b-arqe3t) ([raw file](https://github.com/TraceMachina/nativelink/blob/fb37dae70889b1ef8d7da37df3f8783ba086219c/nativelink-scheduler/src/simple_scheduler.rs#L529)):*
> ```XML
>                 .update_action_with_internal_error_from_wrong_worker
>                 .inc();
>             match running_action.worker_id {
> ```

nit: This ordering is a bit weird, I suggest something more like:
```rs
let Some(running_action_worker_id) = running_action.worker_id else {
  error!(
    "Got a result from a worker that should not be running the action, Removing worker. Expected action to be unassigned got worker {worker_id}"
  );
};
```
___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 597 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/782#-Ntxlcw39rtoI4taUwN_:-Ntxlcw39rtoI4taUwNa:bq6hnzx) ([raw file](https://github.com/TraceMachina/nativelink/blob/fb37dae70889b1ef8d7da37df3f8783ba086219c/nativelink-scheduler/src/simple_scheduler.rs#L597)):*
> ```XML
>                     Code::Internal,
>                     "Got a result from a worker that should not be running the action, Removing worker. Expected worker {} got worker {worker_id}",
>                     running_action_worker_id
> ```

nit: inline this variable.


<!-- Sent from Reviewable.io -->

2024-03-27 04:12 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/782)* status: 2 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 529 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/782#-Ntxkl3Y0Imyf5HDeYRt:-Nty618MCTJ3Dy4n1s6u:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/fb37dae70889b1ef8d7da37df3f8783ba086219c/nativelink-scheduler/src/simple_scheduler.rs#L529)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: This ordering is a bit weird, I suggest something more like:
```rs
let Some(running_action_worker_id) = running_action.worker_id else {
  error!(
    "Got a result from a worker that should not be running the action, Removing worker. Expected action to be unassigned got worker {worker_id}"
  );
};
```
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 597 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/782#-Ntxlcw39rtoI4taUwN_:-Nty5ym48ejdKvdhmJmT:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/fb37dae70889b1ef8d7da37df3f8783ba086219c/nativelink-scheduler/src/simple_scheduler.rs#L597)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: inline this variable.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-27 16:28 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/782)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 529 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/782#-Ntxkl3Y0Imyf5HDeYRt:-Nu-jCCE77WKyvhXzvOJ:b-jk9maj) ([raw file](https://github.com/TraceMachina/nativelink/blob/fb37dae70889b1ef8d7da37df3f8783ba086219c/nativelink-scheduler/src/simple_scheduler.rs#L529)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: Do this the other way and put it above the outer if-statement. It'll make the code much more readable and de-uglify `if running_action.worker_id == Some(*worker_id)`


<!-- Sent from Reviewable.io -->

2024-03-27 16:28 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/782)* status: 2 of 1 LGTMs obtained, and 1 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-03-27 17:03 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/782#-:-Nu-rMDKDl8dzcLPkiPP:bnfp4nl)* status: 2 of 1 LGTMs obtained, and 1 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-03-29 15:01 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/782)* status: 2 of 1 LGTMs obtained, and 1 discussions need to be resolved

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 529 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/782#-Ntxkl3Y0Imyf5HDeYRt:-Nu9iTC_C4JH2IpN3KDF:b-xqa85t) ([raw file](https://github.com/TraceMachina/nativelink/blob/fb37dae70889b1ef8d7da37df3f8783ba086219c/nativelink-scheduler/src/simple_scheduler.rs#L529)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

By other way do you mean the match statement?
</blockquote></details>

No, I just mean, move this if-statement before this one:
```rs
if running_action.worker_id == Some(*worker_id) {
```


<!-- Sent from Reviewable.io -->

2024-03-29 20:45 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/782)* status: 2 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 1 discussions need to be resolved

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 529 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/782#-Ntxkl3Y0Imyf5HDeYRt:-NuAxHP84btpRsC4QDWW:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/fb37dae70889b1ef8d7da37df3f8783ba086219c/nativelink-scheduler/src/simple_scheduler.rs#L529)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

No, I just mean, move this if-statement before this one:
```rs
if running_action.worker_id == Some(*worker_id) {
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-30 23:20 UTC, allada approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/782)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-04-01 07:23 UTC, merged