Resolve upload deadlock
TraceMachina/nativelink pull request #816
Opened 2024-03-29 20:14 UTC by chrisstaite

# Description

We get the metadata for a file after opening it, which causes two file descriptors to be used rather than one.  In order to ensure that every future requires exactly one file descriptor at a time and therefore not cause a deadlock in the OPEN FILE Semaphore, we simply get the metadata before we open the file.

Fixes # (issue)

## Type of change

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-03-30 22:45 UTC, allada requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/816)* status: 0 of 1 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), and 4 discussions need to be resolved

___
*[`nativelink-worker/src/running_actions_manager.rs` line 385 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/816#-NuGUdDQEdAW6fpPfhac:-NuGUdDQEdAW6fpPfhad:b-58ut9s) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8cc2869e0edc799cb1a6ba30a8fa9d2987e4521/nativelink-worker/src/running_actions_manager.rs#L385)):*
> ```XML
>             // futures with all the work we are wanting to do then execute it. It allows us to
>             // close the directory iterator file descriptor, then open the child files/folders.
>             while let Some(entry) = dir_stream.next().await {
> ```

nit: `entry_result`
___
*[`nativelink-worker/src/running_actions_manager.rs` line 432 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/816#-NuGUi341FEQh6xl-rUA:-NuGUi341FEQh6xl-rUB:btpfp1i) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8cc2869e0edc799cb1a6ba30a8fa9d2987e4521/nativelink-worker/src/running_actions_manager.rs#L432)):*
> ```XML
>                 } else if file_type.is_file() {
>                     file_futures.push(async move {
>                         let metadata = fs::metadata(&full_path).await?;
> ```

nit: `.err_tip()`
___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2938 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/816#-NuGVMYA1ZczxKyrk5Xc:-NuGVMYA1ZczxKyrk5Xd:bwqza4t) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8cc2869e0edc799cb1a6ba30a8fa9d2987e4521/nativelink-worker/tests/running_actions_manager_test.rs#L2938)):*
> ```XML
>     // Be default this test is ignored because it *must* be run single threaded... to run this
>     // test execute:
>     // cargo test -p nativelink-worker --test running_actions_manager_test -- --test-threads=1 --ignored
> ```

Idea, what if we use `tokio_fork` to fork the test, then have the child call process.exit directly (to prevent other tests from running), then have the parent just wait on the exit code?

This should prevent threads from stepping on each other.
___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2954 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/816#-NuGXR6j6NbAAh9vlRJn:-NuGXR6j6NbAAh9vlRJo:b-9mk39k) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8cc2869e0edc799cb1a6ba30a8fa9d2987e4521/nativelink-worker/tests/running_actions_manager_test.rs#L2954)):*
> ```XML
> 
>         // Take all but one FD permit away.
>         let _permits = futures::stream::iter(1..fs::OPEN_FILE_SEMAPHORE.available_permits())
> ```

nit: Just use `fs::set_open_file_limit(1)`.


<!-- Sent from Reviewable.io -->

2024-03-30 22:45 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/816#-:-NuGXZgC7zQkWYkLGAmo:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), and 4 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-03-31 07:32 UTC, chrisstaite reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/816)* status: 1 of 1 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), and 4 discussions need to be resolved

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2954 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/816#-NuGXR6j6NbAAh9vlRJn:-NuIQ4lP7fzYF7J3kH9R:ba5625j) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8cc2869e0edc799cb1a6ba30a8fa9d2987e4521/nativelink-worker/tests/running_actions_manager_test.rs#L2954)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Just use `fs::set_open_file_limit(1)`.
</blockquote></details>

I read the code and am pretty sure it doesn't support reducing the number


<!-- Sent from Reviewable.io -->

2024-03-31 19:44 UTC, chrisstaite reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/816)* status: 1 of 1 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), and 2 discussions need to be resolved

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2938 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/816#-NuGVMYA1ZczxKyrk5Xc:-NuL1eNZ6GWLfEtZj7Oc:b-bb7irh) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8cc2869e0edc799cb1a6ba30a8fa9d2987e4521/nativelink-worker/tests/running_actions_manager_test.rs#L2938)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Idea, what if we use `tokio_fork` to fork the test, then have the child call process.exit directly (to prevent other tests from running), then have the parent just wait on the exit code?

This should prevent threads from stepping on each other.
</blockquote></details>

I'm not sure that `tokio_fork` works after a runtime has already been set up?


<!-- Sent from Reviewable.io -->

2024-03-31 19:49 UTC, chrisstaite reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/816)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 2 discussions need to be resolved

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2954 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/816#-NuGXR6j6NbAAh9vlRJn:-NuL2Uwp4hjCDDiMaA0-:b3e3klm) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8cc2869e0edc799cb1a6ba30a8fa9d2987e4521/nativelink-worker/tests/running_actions_manager_test.rs#L2954)):*
<details><summary><i>Previously, chrisstaite (Chris) wrote…</i></summary><blockquote>

I read the code and am pretty sure it doesn't support reducing the number
</blockquote></details>

`fetch_add` with a negative value in a `usize`... does that work?  Then calling `add_permits` with a negative value... All seems like a bad idea.


<!-- Sent from Reviewable.io -->

2024-04-01 00:13 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/816)* status: 1 of 1 LGTMs obtained, and 2 discussions need to be resolved

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2938 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/816#-NuGVMYA1ZczxKyrk5Xc:-NuLzxQQ1TGK_zhX5_i2:b52131g) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8cc2869e0edc799cb1a6ba30a8fa9d2987e4521/nativelink-worker/tests/running_actions_manager_test.rs#L2938)):*
<details><summary><i>Previously, chrisstaite (Chris) wrote…</i></summary><blockquote>

I'm not sure that `tokio_fork` works after a runtime has already been set up?
</blockquote></details>

What about something like this?
https://gist.github.com/allada/23f6d9f11854c830d48828a1f00ae8a5
___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2954 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/816#-NuGXR6j6NbAAh9vlRJn:-NuLo4CX4lAnnZcBYSA4:b-v0gb95) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8cc2869e0edc799cb1a6ba30a8fa9d2987e4521/nativelink-worker/tests/running_actions_manager_test.rs#L2954)):*
<details><summary><i>Previously, chrisstaite (Chris) wrote…</i></summary><blockquote>

`fetch_add` with a negative value in a `usize`... does that work?  Then calling `add_permits` with a negative value... All seems like a bad idea.
</blockquote></details>

Yeah, we'd need to rewrite `set_open_file_limit` to call `forget_permits` and remove the check.


<!-- Sent from Reviewable.io -->

2024-04-01 18:00 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/816#-:-NuPoNQJEhvTCIK1gIRF:bnfp4nl)* status: 2 of 1 LGTMs obtained, and 2 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-04-01 18:42 UTC, chrisstaite commented
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2938 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/816#-NuGVMYA1ZczxKyrk5Xc:-NuPy5Y07Gq8LtHOqOVr:b-z5lzew) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8cc2869e0edc799cb1a6ba30a8fa9d2987e4521/nativelink-worker/tests/running_actions_manager_test.rs#L2938)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

What about something like this?
https://gist.github.com/allada/23f6d9f11854c830d48828a1f00ae8a5
</blockquote></details>

Nope I get:
```
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
```


<!-- Sent from Reviewable.io -->

2024-04-01 19:00 UTC, chrisstaite commented
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2938 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/816#-NuGVMYA1ZczxKyrk5Xc:-NuQ122D5vyiBTl5u9Da:b-fudhli) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8cc2869e0edc799cb1a6ba30a8fa9d2987e4521/nativelink-worker/tests/running_actions_manager_test.rs#L2938)):*
<details><summary><i>Previously, chrisstaite (Chris) wrote…</i></summary><blockquote>

Nope I get:
```
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
```
</blockquote></details>

Figured it out, can spawn a new thread after forking and then just block before exiting.


<!-- Sent from Reviewable.io -->

2024-04-01 19:16 UTC, chrisstaite commented
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2938 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/816#-NuGVMYA1ZczxKyrk5Xc:-NuQ4jqJCilcYEyJ3rRa:bz3qykg) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8cc2869e0edc799cb1a6ba30a8fa9d2987e4521/nativelink-worker/tests/running_actions_manager_test.rs#L2938)):*
<details><summary><i>Previously, chrisstaite (Chris) wrote…</i></summary><blockquote>

Figured it out, can spawn a new thread after forking and then just block before exiting.
</blockquote></details>

Nope, it's not at all stable... Gets very upset.


<!-- Sent from Reviewable.io -->

2024-04-01 20:55 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/816)* status: <span>:shipit:</span> complete! 3 of 1 LGTMs obtained

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 2938 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/816#-NuGVMYA1ZczxKyrk5Xc:-NuQRSnB0vBEy_i22a_n:bo1uykv) ([raw file](https://github.com/TraceMachina/nativelink/blob/b8cc2869e0edc799cb1a6ba30a8fa9d2987e4521/nativelink-worker/tests/running_actions_manager_test.rs#L2938)):*
<details><summary><i>Previously, chrisstaite (Chris) wrote…</i></summary><blockquote>

Nope, it's not at all stable... Gets very upset.
</blockquote></details>

Hmmm, ok :-(


<!-- Sent from Reviewable.io -->

2024-04-02 16:24 UTC, allada approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/816)* status: <span>:shipit:</span> complete! 3 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-04-02 23:40 UTC, adam-singer approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/816)* status: 3 of 1 LGTMs obtained, and pending CI: integration-tests (20.04), integration-tests (22.04)



<!-- Sent from Reviewable.io -->

2024-04-03 00:22 UTC, allada reviewed
@aaronmondal , was docker-compose removed from our images?
ref: https://github.com/TraceMachina/nativelink/actions/runs/8529184265/job/23364409815

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/816#-:-NuWKNNQ4-k-JN6Tusjv:b-s4kd3)* status: 3 of 1 LGTMs obtained, and pending CI: integration-tests (20.04), integration-tests (22.04)



<!-- Sent from Reviewable.io -->

2024-04-03 09:20 UTC, merged