Kill worker after action execution limit is reached
TraceMachina/nativelink pull request #825
Opened 2024-04-02 21:16 UTC by zbirenbaum

# Description

Allows users to set the maximum number of action executions a worker is allowed to complete. Upon reaching this limit, the worker will no longer accept new jobs, and will exit upon completing all assigned ones.

Fixes #815 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

A test has been added to ensure the going_away signal is properly sent and received

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-04-02 23:38 UTC, adam-singer requested changes
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/825)* status: 0 of 1 LGTMs obtained, and 5 discussions need to be resolved

___
*[`nativelink-config/src/cas_server.rs` line 611 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/825#-NuW39xt2PVf-lcthgMF:-NuW39xt2PVf-lcthgMG:bv285mn) ([raw file](https://github.com/TraceMachina/nativelink/blob/d295c8896edfcb97fdd819ea1788be68279d4f51/nativelink-config/src/cas_server.rs#L611)):*
> ```XML
>     /// If you would like for each individual action to spin up a kubernetes
>     /// pod and then exit on completion, you would set this value to 1.
>     pub execution_limit: Option<u64>,
> ```

tioli: Thoughts on other names to convey the idea of fixed number of execution before worker terminates, `workload_limit`, `action_limit_before_termination`, `job_completion_limit`, `execution_termination_limit`. No strong thoughts here, do wonder if we can somehow encode the idea of termination of worker in naming 
___
*[`nativelink-config/src/cas_server.rs` line 611 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/825#-NuW7djm9awq69tYJ4u5:-NuW7djm9awq69tYJ4u6:b-va2yjo) ([raw file](https://github.com/TraceMachina/nativelink/blob/d295c8896edfcb97fdd819ea1788be68279d4f51/nativelink-config/src/cas_server.rs#L611)):*
> ```XML
>     /// If you would like for each individual action to spin up a kubernetes
>     /// pod and then exit on completion, you would set this value to 1.
>     pub execution_limit: Option<u64>,
> ```

Where should we assert that this value is `> 1`, if someone supplies a `0` I think we should fail to launch on bad config, maybe the serialization library has some primitive value constraints? 
___
*[`nativelink-worker/src/local_worker.rs` line 82 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/825#-NuW506k-fOru-NkwK2u:-NuW506lDW7i31az2Sx0:b-mytd4d) ([raw file](https://github.com/TraceMachina/nativelink/blob/d295c8896edfcb97fdd819ea1788be68279d4f51/nativelink-worker/src/local_worker.rs#L82)):*
> ```XML
>     // on by the scheduler.
>     actions_in_transit: Arc<AtomicU64>,
>     // The number of actions a worker has completed.
> ```

This triplet makes me think of something I've used in the past of triplets for async counter/counting patterns request/success/failure or started/executing/completed. I wonder if other parts of the code could use that kind of information exposed as metrics. 

I think we should have metrics here that align with the concept of actions "started/executing/completed", current metrics afaict don't cover that, just covers `start_actions_received`
___
*[`nativelink-worker/src/local_worker.rs` line 346 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/825#-NuW7zTc3ftZnieSmokP:-NuW7zTc3ftZnieSmokQ:br8hgpj) ([raw file](https://github.com/TraceMachina/nativelink/blob/d295c8896edfcb97fdd819ea1788be68279d4f51/nativelink-worker/src/local_worker.rs#L346)):*
> ```XML
>                 // Futures will never be empty due to keep alive
>                 if futures.len() == 1 && assigned == limit && completed == assigned {
>                     std::process::exit(0);
> ```

We should `debug!` or `info!` a message about exiting due to worker reaching termination limit, probably `debug!` as lots of executions that exist could be noisy for logs. 
___
*[`nativelink-worker/tests/local_worker_test.rs` line 643 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/825#-NuW9bhXD8tkVII9yvZX:-NuW9bhXD8tkVII9yvZY:b-vof2cl) ([raw file](https://github.com/TraceMachina/nativelink/blob/d295c8896edfcb97fdd819ea1788be68279d4f51/nativelink-worker/tests/local_worker_test.rs#L643)):*
> ```XML
> 
>     #[tokio::test]
>     async fn worker_action_limit_test() -> Result<(), Box<dyn std::error::Error>> {
> ```

To be pedantic we should add tests that assert a `0`, `1`, `3` as `execution_limit` values. Also a test where multiple requests happen and a previous request takes longer to complete than the others. For example request1 takes T0:T4 time, request2 T1:T2, request3 T1:T3 or something of that nature to show exit conditions are not bound by last request received 


<!-- Sent from Reviewable.io -->

2024-04-03 21:33 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/825)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 5 discussions need to be resolved

___
*[`nativelink-config/src/cas_server.rs` line 611 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/825#-NuW39xt2PVf-lcthgMF:-Nu_pHlmEk3muxXlho-V:br5xu0n) ([raw file](https://github.com/TraceMachina/nativelink/blob/d295c8896edfcb97fdd819ea1788be68279d4f51/nativelink-config/src/cas_server.rs#L611)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

tioli: Thoughts on other names to convey the idea of fixed number of execution before worker terminates, `workload_limit`, `action_limit_before_termination`, `job_completion_limit`, `execution_termination_limit`. No strong thoughts here, do wonder if we can somehow encode the idea of termination of worker in naming
</blockquote></details>

I updated it to be `actions_before_termination` which I think is pretty clear
___
*[`nativelink-config/src/cas_server.rs` line 611 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/825#-NuW7djm9awq69tYJ4u5:-Nu_qJMX1-5-2lMizthQ:bsegx1p) ([raw file](https://github.com/TraceMachina/nativelink/blob/d295c8896edfcb97fdd819ea1788be68279d4f51/nativelink-config/src/cas_server.rs#L611)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Where should we assert that this value is `> 1`, if someone supplies a `0` I think we should fail to launch on bad config, maybe the serialization library has some primitive value constraints?
</blockquote></details>

I added a check inside `LocalWorkerImpl::new()` that throws an error stating it has to be greater than 0. This should catch during initialization like our other validation and default value checks
___
*[`nativelink-worker/src/local_worker.rs` line 82 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/825#-NuW506k-fOru-NkwK2u:-Nu_qe5U3XdEknP5Cq1P:b-1nqxyo) ([raw file](https://github.com/TraceMachina/nativelink/blob/d295c8896edfcb97fdd819ea1788be68279d4f51/nativelink-worker/src/local_worker.rs#L82)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

This triplet makes me think of something I've used in the past of triplets for async counter/counting patterns request/success/failure or started/executing/completed. I wonder if other parts of the code could use that kind of information exposed as metrics. 

I think we should have metrics here that align with the concept of actions "started/executing/completed", current metrics afaict don't cover that, just covers `start_actions_received`
</blockquote></details>

I was thinking about this too. The metrics stuff is going to undergo a full rewrite soon though, so having these vars and maybe adding a way to expose them later should be sufficient.
___
*[`nativelink-worker/src/local_worker.rs` line 346 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/825#-NuW7zTc3ftZnieSmokP:-Nu_r5GB-OTyF1FI3r0f:b-g1iah5) ([raw file](https://github.com/TraceMachina/nativelink/blob/d295c8896edfcb97fdd819ea1788be68279d4f51/nativelink-worker/src/local_worker.rs#L346)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

We should `debug!` or `info!` a message about exiting due to worker reaching termination limit, probably `debug!` as lots of executions that exist could be noisy for logs.
</blockquote></details>

Good idea, added


<!-- Sent from Reviewable.io -->

2024-04-04 23:53 UTC, adam-singer reviewed
> Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/825)* status: 0 of 1 LGTMs obtained, and 1 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-04-10 15:50 UTC, allada requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/825)* status: 0 of 1 LGTMs obtained, and 3 discussions need to be resolved

___
*[`nativelink-config/src/cas_server.rs` line 606 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/825#-Nv7g9H_5B14FNO9xQup:-Nv7g9H_5B14FNO9xQuq:b-wgtrse) ([raw file](https://github.com/TraceMachina/nativelink/blob/a2e7a40454a3b70592758ab9b9cf753a0ec0c924/nativelink-config/src/cas_server.rs#L606)):*
> ```XML
>     /// The maximum number of actions a worker can executions .
>     /// After this limit is reached, the nativelink binary will exit.
>     /// A value of None means no limit.
> ```

nit: Put this on the last line of the comment by itself and say `Default: ` (see other examples in the config)
___
*[`nativelink-worker/src/local_worker.rs` line 139 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/825#-Nv7gmnu3fpIkboNN7t5:-Nv7gmnu3fpIkboNN7t6:b-hc6dz6) ([raw file](https://github.com/TraceMachina/nativelink/blob/a2e7a40454a3b70592758ab9b9cf753a0ec0c924/nativelink-worker/src/local_worker.rs#L139)):*
> ```XML
>             grpc_client,
>             worker_id,
>             actions_completed: Arc::new(AtomicU64::new(0)),
> ```

I don't think these needs to be Atomic's or Arc's. Looking at how they are used, it looks like all the places have mutable access to `Self`.


<!-- Sent from Reviewable.io -->

2024-04-11 00:00 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/825)* status: 0 of 1 LGTMs obtained, and 2 discussions need to be resolved

___
*[`nativelink-config/src/cas_server.rs` line 606 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/825#-Nv7g9H_5B14FNO9xQup:-Nv9SAmo1eil67BoJb9Y:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/a2e7a40454a3b70592758ab9b9cf753a0ec0c924/nativelink-config/src/cas_server.rs#L606)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Put this on the last line of the comment by itself and say `Default: ` (see other examples in the config)
</blockquote></details>

Done.
___
*[`nativelink-worker/src/local_worker.rs` line 139 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/825#-Nv7gmnu3fpIkboNN7t5:-Nv9Lc4JE972Atc-P-vF:b9pz4zz) ([raw file](https://github.com/TraceMachina/nativelink/blob/a2e7a40454a3b70592758ab9b9cf753a0ec0c924/nativelink-worker/src/local_worker.rs#L139)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I don't think these needs to be Atomic's or Arc's. Looking at how they are used, it looks like all the places have mutable access to `Self`.
</blockquote></details>

I tried making them normal u64 but both run into borrow checker issues I couldn't figure out how to fix due to the spawns.


<!-- Sent from Reviewable.io -->

2024-04-14 00:46 UTC, adam-singer reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/825)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks, and 2 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-05-15 21:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TraceMachina/nativelink?pullRequest=825) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TraceMachina/nativelink?pullRequest=825) before we can accept your contribution.<br/><hr/>**Zach Birenbaum** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TraceMachina/nativelink?pullRequest=825) it.</sub>

2025-10-13 14:05 UTC, palfrey commented
Finally catching up with this one. @zbirenbaum are you able to resolve the conflicts? I think this is still of interest, but we'd need to solve those first.

2026-06-10 11:45 UTC, palfrey commented
Closing due to lack of response and non-signed CLA

2026-06-10 11:45 UTC, closed without merging