Implement worker api for killing running actions
TraceMachina/nativelink pull request #840
Opened 2024-04-05 21:16 UTC by zbirenbaum

# Description
Implements worker api for requesting a currently running action to be killed. Allows for action cancellation requests to be sent from the scheduler during scenarios such as client disconnection.

towards: #338

## Type of change

Please delete options that aren't relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Added a new test case to confirm that the request to kill an action is received and handled accordingly.

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-04-05 22:53 UTC, allada requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/840)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13, and 7 discussions need to be resolved

___
*[`nativelink-proto/com/github/trace_machina/nativelink/remote_execution/worker_api.proto` line 136 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NukQx9Z-bi0Kv5WdKvI:-NukQx9Z-bi0Kv5WdKvJ:b143lhf) ([raw file](https://github.com/TraceMachina/nativelink/blob/95edf4ba510a7637eabec451d776ea476b80b3c3/nativelink-proto/com/github/trace_machina/nativelink/remote_execution/worker_api.proto#L136)):*
> ```proto
> /// Request to kill a running action sent from the scheduler to a worker.
> message KillActionRequest {
>     /// The the hash of the unique qualifier for the action to be killed.
> ```

nit: Don't make it the hash, make it the hex.
___
*[`nativelink-proto/com/github/trace_machina/nativelink/remote_execution/worker_api.proto` line 138 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NukQoWu2Wz5hd-E0OOI:-NukQoWu2Wz5hd-E0OOJ:bdrxj5l) ([raw file](https://github.com/TraceMachina/nativelink/blob/95edf4ba510a7637eabec451d776ea476b80b3c3/nativelink-proto/com/github/trace_machina/nativelink/remote_execution/worker_api.proto#L138)):*
> ```proto
>     /// The the hash of the unique qualifier for the action to be killed.
>     string action_id = 1;
>     reserved 2;
> ```

nit: Add `// NextId.`
___
*[`nativelink-worker/src/local_worker.rs` line 215 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NukRDjTBgiikXh2HLXN:-NukRDjTBgiikXh2HLXO:b-fzeu8j) ([raw file](https://github.com/TraceMachina/nativelink/blob/95edf4ba510a7637eabec451d776ea476b80b3c3/nativelink-worker/src/local_worker.rs#L215)):*
> ```XML
>                         Update::KillActionRequest(kill_action_request) => {
>                             let kill_action_result = self.running_actions_manager
>                                 .kill_action(kill_action_request.clone())
> ```

nit: Pass just the action_id by ref. If we need more later we can change it, but keep it simple for now.
___
*[`nativelink-worker/src/local_worker.rs` line 217 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NukRVIN0GUE8xKgPCTd:-NukRVIN0GUE8xKgPCTe:b-rex07) ([raw file](https://github.com/TraceMachina/nativelink/blob/95edf4ba510a7637eabec451d776ea476b80b3c3/nativelink-worker/src/local_worker.rs#L217)):*
> ```XML
>                                 .kill_action(kill_action_request.clone())
>                                 .await;
>                             if let Err(e) = kill_action_result {
> ```

Shouldn't we propagate this error back up the grpc stream? See how `Update::ConnectionResult` does it.
___
*[`nativelink-worker/src/running_actions_manager.rs` line 1792 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NukRlbs07o1OeU5whXW:-NukRlbs07o1OeU5whXX:b-2l0xow) ([raw file](https://github.com/TraceMachina/nativelink/blob/95edf4ba510a7637eabec451d776ea476b80b3c3/nativelink-worker/src/running_actions_manager.rs#L1792)):*
> ```XML
> 
>         assert_eq!(
>             hex::decode_to_slice(kill_action_request.action_id, &mut action_id as &mut [u8]),
> ```

nit: Make the caller do this conversion and pass in an `ActionId`.
___
*[`nativelink-worker/src/running_actions_manager.rs` line 1799 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NukSA278hI-xphl4AgW:-NukSA278hI-xphl4AgX:b9ue0lm) ([raw file](https://github.com/TraceMachina/nativelink/blob/95edf4ba510a7637eabec451d776ea476b80b3c3/nativelink-worker/src/running_actions_manager.rs#L1799)):*
> ```XML
>         let running_actions = self.running_actions.lock();
>         running_actions.get(&action_id).map_or(
>             Err(make_err!(
> ```

nit: use `make_input_err!()`
___
*[`nativelink-worker/src/running_actions_manager.rs` line 1805 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NukSHgU0PolVycR5ynn:-NukSHgU0PolVycR5yno:bf9inhn) ([raw file](https://github.com/TraceMachina/nativelink/blob/95edf4ba510a7637eabec451d776ea476b80b3c3/nativelink-worker/src/running_actions_manager.rs#L1805)):*
> ```XML
>             )),
>             |action| {
>                 action.upgrade().map(Self::kill_action);
> ```

If upgrade fails, we should return an error.


<!-- Sent from Reviewable.io -->

2024-04-05 22:53 UTC, allada reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/840)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13, and 7 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-04-06 02:19 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/840)* status: 0 of 1 LGTMs obtained, and 2 discussions need to be resolved

___
*[`nativelink-proto/com/github/trace_machina/nativelink/remote_execution/worker_api.proto` line 136 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NukQx9Z-bi0Kv5WdKvI:-NulBd019LonVynOLt0L:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/95edf4ba510a7637eabec451d776ea476b80b3c3/nativelink-proto/com/github/trace_machina/nativelink/remote_execution/worker_api.proto#L136)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Don't make it the hash, make it the hex.
</blockquote></details>

Done.
___
*[`nativelink-proto/com/github/trace_machina/nativelink/remote_execution/worker_api.proto` line 138 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NukQoWu2Wz5hd-E0OOI:-NulBdqy9NwMevvSIxZs:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/95edf4ba510a7637eabec451d776ea476b80b3c3/nativelink-proto/com/github/trace_machina/nativelink/remote_execution/worker_api.proto#L138)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Add `// NextId.`
</blockquote></details>

Done.
___
*[`nativelink-worker/src/local_worker.rs` line 215 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NukRDjTBgiikXh2HLXN:-NulBevwA7I9k3bg6NBm:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/95edf4ba510a7637eabec451d776ea476b80b3c3/nativelink-worker/src/local_worker.rs#L215)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Pass just the action_id by ref. If we need more later we can change it, but keep it simple for now.
</blockquote></details>

Done.
___
*[`nativelink-worker/src/local_worker.rs` line 217 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NukRVIN0GUE8xKgPCTd:-NulBfeE1EVCS0iQa-p4:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/95edf4ba510a7637eabec451d776ea476b80b3c3/nativelink-worker/src/local_worker.rs#L217)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Shouldn't we propagate this error back up the grpc stream? See how `Update::ConnectionResult` does it.
</blockquote></details>

Done.
___
*[`nativelink-worker/src/running_actions_manager.rs` line 1792 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NukRlbs07o1OeU5whXW:-NulBgeWEiJtW3jcAj3C:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/95edf4ba510a7637eabec451d776ea476b80b3c3/nativelink-worker/src/running_actions_manager.rs#L1792)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Make the caller do this conversion and pass in an `ActionId`.
</blockquote></details>

Done.
___
*[`nativelink-worker/src/running_actions_manager.rs` line 1799 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NukSA278hI-xphl4AgW:-NulBhui-LGSJaVqeoRG:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/95edf4ba510a7637eabec451d776ea476b80b3c3/nativelink-worker/src/running_actions_manager.rs#L1799)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: use `make_input_err!()`
</blockquote></details>

Done.
___
*[`nativelink-worker/src/running_actions_manager.rs` line 1805 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NukSHgU0PolVycR5ynn:-NulBibPDPb4cItENme3:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/95edf4ba510a7637eabec451d776ea476b80b3c3/nativelink-worker/src/running_actions_manager.rs#L1805)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

If upgrade fails, we should return an error.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-06 15:30 UTC, allada approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/840)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-22.04, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 3 discussions need to be resolved

___
*[`nativelink-worker/src/local_worker.rs` line 215 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NunyHfd9lZgECtDBWZ5:-NunyHfd9lZgECtDBWZ6:b-wp1om2) ([raw file](https://github.com/TraceMachina/nativelink/blob/b9caf1ea13c9e7c0e09acc2b1dad05a85ac14a81/nativelink-worker/src/local_worker.rs#L215)):*
> ```XML
>                         Update::KillActionRequest(kill_action_request) => {
>                             let mut action_id = [0u8; 32];
>                             let decode_result = hex::decode_to_slice(kill_action_request.action_id, &mut action_id as &mut [u8]);
> ```

nit:
```rs
hex::decode_to_slice(kill_action_request.action_id, &mut action_id as &mut [u8])
    .map_err(|e| Err(make_input_err!(
      "KillActionRequest failed to decode ActionId hex with error {}",
      e
    ))?;
```
___
*[`nativelink-worker/src/local_worker.rs` line 223 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NunycuRCTyLrs-AoSHp:-NunycuRCTyLrs-AoSHq:b-dwyu20) ([raw file](https://github.com/TraceMachina/nativelink/blob/b9caf1ea13c9e7c0e09acc2b1dad05a85ac14a81/nativelink-worker/src/local_worker.rs#L223)):*
> ```XML
>                                 ));
>                             }
>                             let kill_action_result = self.running_actions_manager
> ```

nit:
```rs
self.running_actions_manager
  .kill_action(action_id)
  .await
  .err_tip(|| format!("Kill action {} failed with error - {}", hex::encode(action_id), e))

```
___
*[`nativelink-worker/src/running_actions_manager.rs` line 1790 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NunzFAO52lJ5A60dL36:-NunzFAO52lJ5A60dL37:bwu5v3x) ([raw file](https://github.com/TraceMachina/nativelink/blob/b9caf1ea13c9e7c0e09acc2b1dad05a85ac14a81/nativelink-worker/src/running_actions_manager.rs#L1790)):*
> ```XML
>     async fn kill_action(&self, action_id: ActionId) -> Result<(), Error> {
> 
>         let upgrade_or_err: Result<Arc<RunningActionImpl>, Error> = {
> ```

nit:
```rs
async fn kill_action(&self, action_id: ActionId) -> Result<(), Error> {
    let running_action = {
        let running_actions = self.running_actions.lock();
        running_actions
            .get(&action_id)
            .and_then(|action| action.upgrade())
            .ok_or_else(|| make_input_err!(
                "Failed to get running action {}",
                hex::encode(action_id)
            ))?
    };
    Self::kill_action(running_action).await;
    Ok(())
}

```


<!-- Sent from Reviewable.io -->

2024-04-06 15:30 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/840#-:-Nuo19nA1J77nIGFCt_S:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-22.04, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 3 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-04-07 19:20 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/840)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-22.04, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 2 discussions need to be resolved

___
*[`nativelink-worker/src/local_worker.rs` line 215 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NunyHfd9lZgECtDBWZ5:-NutwkyQ5P7Pu9ijI692:bthvxb6) ([raw file](https://github.com/TraceMachina/nativelink/blob/b9caf1ea13c9e7c0e09acc2b1dad05a85ac14a81/nativelink-worker/src/local_worker.rs#L215)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit:
```rs
hex::decode_to_slice(kill_action_request.action_id, &mut action_id as &mut [u8])
    .map_err(|e| Err(make_input_err!(
      "KillActionRequest failed to decode ActionId hex with error {}",
      e
    ))?;
```
</blockquote></details>

Thanks, the error handling got really messy here. The compiler didn't like the `Err` part but 
```
hex::decode_to_slice(kill_action_request.action_id, &mut action_id as &mut [u8])
    .map_err(|e| make_input_err!(
        "KillActionRequest failed to decode ActionId hex with error {}",
         e
     ))?;
```
seems to work. I'm not certain of what the `make_input_err!` macro does (assume it expands to an error with some custom code) so want to check that it's actually functionally equivalent to your previous code.
___
*[`nativelink-worker/src/local_worker.rs` line 223 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NunycuRCTyLrs-AoSHp:-Nuty0U_7LQROG6snsZ-:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/b9caf1ea13c9e7c0e09acc2b1dad05a85ac14a81/nativelink-worker/src/local_worker.rs#L223)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit:
```rs
self.running_actions_manager
  .kill_action(action_id)
  .await
  .err_tip(|| format!("Kill action {} failed with error - {}", hex::encode(action_id), e))

```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-07 19:25 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/840)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-22.04, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 1 discussions need to be resolved

___
*[`nativelink-worker/src/running_actions_manager.rs` line 1790 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NunzFAO52lJ5A60dL36:-Nuu0JGz3zCUHtoLok48:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/b9caf1ea13c9e7c0e09acc2b1dad05a85ac14a81/nativelink-worker/src/running_actions_manager.rs#L1790)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit:
```rs
async fn kill_action(&self, action_id: ActionId) -> Result<(), Error> {
    let running_action = {
        let running_actions = self.running_actions.lock();
        running_actions
            .get(&action_id)
            .and_then(|action| action.upgrade())
            .ok_or_else(|| make_input_err!(
                "Failed to get running action {}",
                hex::encode(action_id)
            ))?
    };
    Self::kill_action(running_action).await;
    Ok(())
}

```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-08 01:46 UTC, allada approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/840)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-22.04, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`nativelink-worker/src/local_worker.rs` line 215 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/840#-NunyHfd9lZgECtDBWZ5:-NuvMdOf0LnrdQFRXskp:b-xokal8) ([raw file](https://github.com/TraceMachina/nativelink/blob/b9caf1ea13c9e7c0e09acc2b1dad05a85ac14a81/nativelink-worker/src/local_worker.rs#L215)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Thanks, the error handling got really messy here. The compiler didn't like the `Err` part but 
```
hex::decode_to_slice(kill_action_request.action_id, &mut action_id as &mut [u8])
    .map_err(|e| make_input_err!(
        "KillActionRequest failed to decode ActionId hex with error {}",
         e
     ))?;
```
seems to work. I'm not certain of what the `make_input_err!` macro does (assume it expands to an error with some custom code) so want to check that it's actually functionally equivalent to your previous code.
</blockquote></details>

Yeah it's the same thing.

`make_input_err!` is just short for:
```rs
Error::new(
  Code::InvalidArgument,
  format!("{}", format_args!($($arg)+)),
)
```


<!-- Sent from Reviewable.io -->

2024-04-08 07:27 UTC, merged