Updated Kubernetes Readme for more information about using docker images
TraceMachina/nativelink pull request #846
Opened 2024-04-10 20:25 UTC by nfarah86

# Description

Updated deployment-examples/kubernetes/README.md for more context around tagging, building, and running images.

Fixes # (issue)
The original question for this improvement popped up here: https://nativelink.slack.com/archives/C066XC8JT0X/p1711386866760809

## Type of change

Please delete options that aren't relevant.
- [x] This change requires a documentation update

## Checklist

- [x] Updated documentation if needed
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-04-10 22:26 UTC, MarcusSorealheis submitted a review, later dismissed
This looks pretty good. Can you link from the top level README to this deployent example if there is a good place to suggest that people look at Kubernetes deployment examples? I'm not sure if there is a good place as this has been around for a while.

2024-04-11 07:24 UTC, aaronmondal requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/846)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks, and 12 discussions need to be resolved

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvAjhCdCdF9GtHLM9dO):*
Updated -> Update
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvB1X6XEdkphpYEYzwu):*
nit: Try to shorten the title
___
*[`.github/styles/config/vocabularies/TraceMachina/accept.txt` line 29 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvAjnIuCLoCrl4pbcpx:-NvAjnIuCLoCrl4pbcpy:b-6b4vkq) ([raw file](https://github.com/TraceMachina/nativelink/blob/8d3a1a9b19d9f8b0dfade7e15a2fa21cfc58fe9e/.github/styles/config/vocabularies/TraceMachina/accept.txt#L29)):*
> ```help
> remoteable
> Chromium
> namespace
> ```

This is breaking pre-commit hooks because the last line doesn't have a trailing newline. To fix it:

```
# The current status of your Pr
git status

# invoke the pre-commit hooks (only works in the nix flake)
pre-commit run -a

# view the changed files
git status

# in this case it should've modified the `accept.txt` file
git add .github/styles/config/vocabularies/TraceMachina/accept.txt

# Amend the commit
git commit --amend
```
___
*[`deployment-examples/kubernetes/README.md` line 78 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvAzPvn1_yBnS5wR89G:-NvAzPvn1_yBnS5wR89H:b-715wqc) ([raw file](https://github.com/TraceMachina/nativelink/blob/8d3a1a9b19d9f8b0dfade7e15a2fa21cfc58fe9e/deployment-examples/kubernetes/README.md#L78)):*
> ```Markdown
> ```
> ## Use a published image
> [Published images](https://github.com/TraceMachina/nativelink/pkgs/container/nativelink) can be found under the Container registry, which uses the namespace `https://ghcr.io`. The Container registry offers benefits such as granular permissions and storage optimizations for images.
> ```

I'm not sure whether this is correct. AFAIU the only thing the remote registry gives us is "prebuilt" images which effectively means that they're just faster to start than when you'd build the image youreself first.
___
*[`deployment-examples/kubernetes/README.md` line 81 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvAkafK2RcBgMSI-pmj:-NvAkafK2RcBgMSI-pmk:bu86df0) ([raw file](https://github.com/TraceMachina/nativelink/blob/8d3a1a9b19d9f8b0dfade7e15a2fa21cfc58fe9e/deployment-examples/kubernetes/README.md#L81)):*
> ```Markdown
> 
> To pull an existing image, you can run:
> ```sh
> ```

nit: Consider surrounding code blocks with newlines to reduce the changes which will be necessary when we add markdownlint to our pre-commit hooks: https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md031---fenced-code-blocks-should-be-surrounded-by-blank-lines
___
*[`deployment-examples/kubernetes/README.md` line 85 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvAlNc966QTgob5AB-5:-NvAlNc966QTgob5AB-6:bapb8nz) ([raw file](https://github.com/TraceMachina/nativelink/blob/8d3a1a9b19d9f8b0dfade7e15a2fa21cfc58fe9e/deployment-examples/kubernetes/README.md#L85)):*
> ```Markdown
> ```
> 
> ## Tag an OCI image
> ```

nit: Consider surrounding headings with newlines: https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md022---headers-should-be-surrounded-by-blank-lines
___
*[`deployment-examples/kubernetes/README.md` line 86 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvAlkL16vBW25kopUQ8:-NvAlkL16vBW25kopUQ9:bn72m1q) ([raw file](https://github.com/TraceMachina/nativelink/blob/8d3a1a9b19d9f8b0dfade7e15a2fa21cfc58fe9e/deployment-examples/kubernetes/README.md#L86)):*
> ```Markdown
> 
> ## Tag an OCI image
> You can tag an image by invoking `nix eval` and either specifying the commit hash you want to build or point to the current state of the upstream NativeLink main branch. For example, to tag an image with a specific commit hash, run the `nix eval` command and change `someCommit` with the commit hash you want to use:
> ```

This is not exactly correct. The `nix eval` command doesn't tag an image. Instead, it derives/computes the tag that nix would generate if you were to build the image and push it to a registry.

When you do

```
nix run github:TraceMachina/nativelink/someCommit#image.copyToDockerDaemon
```

the image you get when you run `docker image ls` would have the tag:

```
nix eval github:TraceMachina/nativelink/someCommit#image.imageTag --raw
```
___
*[`deployment-examples/kubernetes/README.md` line 93 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvAnNvz8US2zB8HbIkN:-NvAnNvz8US2zB8HbIkO:b-ph69z) ([raw file](https://github.com/TraceMachina/nativelink/blob/8d3a1a9b19d9f8b0dfade7e15a2fa21cfc58fe9e/deployment-examples/kubernetes/README.md#L93)):*
> ```Markdown
> Alternatively, the tag can be derived from the upstream sources at the current state of the upstream main branch by running this command:
> ```sh
> nix eval github:TraceMachina/nativelink --raw
> ```

This `nix eval` command doesn't give you the tag of the image. Instead would give you the evaluated output of the entire `nativelink` flake (which probably doesn't work).

The image tags for the `nativelink` container images are autogenerated from the inputs to the `image` output. Since this image output is only dependent on the `nativelink` executable, its hash is only derived from the rust sources, it's dependencies, and the container-specific config options. It's not derived from the entire nativelink repository. For instance, the tag wouldn't change if you modified some random non-rust file that doesn't influence the nativelink build.

Something to not confuse here is that `.#image` and `.#image.imageTag` are two different expressions. `nix eval .#image` would try to evaluate the`image` flake output (which probably doesn't work because you can't "print" an image). `nix eval .#image.imageTag` just evaluates the `imageTag` field in the `image` output, which is effectively just a string.
___
*[`deployment-examples/kubernetes/README.md` line 107 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvApLQx45qJX7nBn73l:-NvApLQy65ZDWOwriiqp:b-gzih7t) ([raw file](https://github.com/TraceMachina/nativelink/blob/8d3a1a9b19d9f8b0dfade7e15a2fa21cfc58fe9e/deployment-examples/kubernetes/README.md#L107)):*
> ```Markdown
> > retrieve an image:
> > ```sh
> > nix eval github:TraceMachina/nativelink.image.> imageTag --raw
> ```

Probably a typo which meant to say:

```
nix eval github:TraceMachina/nativelink.image.imageTag --raw
```
___
*[`deployment-examples/kubernetes/README.md` line 126 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvArOXV8I9aX6FUBxAD:-NvArOXV8I9aX6FUBxAE:b-gxen3n) ([raw file](https://github.com/TraceMachina/nativelink/blob/8d3a1a9b19d9f8b0dfade7e15a2fa21cfc58fe9e/deployment-examples/kubernetes/README.md#L126)):*
> ```Markdown
> 
> ```sh
>  `nix run .#image
> ```

You can't run the `.#image` output, as it's just a json file which looks like this (you can verify this by running `nix build` and printing the output of the `result` symlink that the build command creates):

```
{
	"version": 1,
	"image-config": {
		"Entrypoint": [
			"/nix/store/wswj7zid10blknd6kcg4xp8w0ri81d3x-nativelink-0.3.0/bin/nativelink"
		],
		"Labels": {
			"org.opencontainers.image.description": "An RBE compatible, high-performance cache and remote executor.",
			"org.opencontainers.image.documentation": "https://github.com/TraceMachina/nativelink",
			"org.opencontainers.image.licenses": "Apache-2.0",
			"org.opencontainers.image.revision": "aab867a79396f1aefba7030fcd1128822107a2e0-dirty",
			"org.opencontainers.image.source": "https://github.com/TraceMachina/nativelink",
			"org.opencontainers.image.title": "NativeLink",
			"org.opencontainers.image.vendor": "Trace Machina, Inc."
		}
	},
	"layers": [
		{
			"d [...]

2024-04-15 17:33 UTC, nfarah86 commented
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvB1X6XEdkphpYEYzwu):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Try to shorten the title
</blockquote></details>

Update Kubernetes Readme  is ok?


<!-- Sent from Reviewable.io -->

2024-04-15 17:36 UTC, nfarah86 commented
*[`deployment-examples/kubernetes/README.md` line 78 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvAzPvn1_yBnS5wR89G:-NvXowQk5-rax73XkocE:b-jfhovz) ([raw file](https://github.com/TraceMachina/nativelink/blob/c88afab60b5591e093ac843b9583e4aff58ccb3b/deployment-examples/kubernetes/README.md#L78)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

I'm not sure whether this is correct. AFAIU the only thing the remote registry gives us is "prebuilt" images which effectively means that they're just faster to start than when you'd build the image youreself first.
</blockquote></details>

This is from type of verbage came from github. 


<!-- Sent from Reviewable.io -->

2024-04-15 17:36 UTC, nfarah86 commented
*[`deployment-examples/kubernetes/README.md` line 78 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvAzPvn1_yBnS5wR89G:-NvXpE_u8fZtfvgmsBhn:b-102xdn) ([raw file](https://github.com/TraceMachina/nativelink/blob/c88afab60b5591e093ac843b9583e4aff58ccb3b/deployment-examples/kubernetes/README.md#L78)):*
<details><summary><i>Previously, nfarah86 (nadine farah) wrote…</i></summary><blockquote>

This is from type of verbage came from github.
</blockquote></details>

This type of verbage came from github... I can amend it to include your comment. 


<!-- Sent from Reviewable.io -->

2024-04-15 17:43 UTC, nfarah86 commented
*[`deployment-examples/kubernetes/README.md` line 81 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvAkafK2RcBgMSI-pmj:-NvXqpXFD_-hS19acZfC:b-7ql1td) ([raw file](https://github.com/TraceMachina/nativelink/blob/c88afab60b5591e093ac843b9583e4aff58ccb3b/deployment-examples/kubernetes/README.md#L81)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Consider surrounding code blocks with newlines to reduce the changes which will be necessary when we add markdownlint to our pre-commit hooks: https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md031---fenced-code-blocks-should-be-surrounded-by-blank-lines
</blockquote></details>

fixed


<!-- Sent from Reviewable.io -->

2024-04-15 17:44 UTC, nfarah86 commented
*[`deployment-examples/kubernetes/README.md` line 85 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvAlNc966QTgob5AB-5:-NvXr6sJ3fLPbIu5yoVJ:b-7ql1td) ([raw file](https://github.com/TraceMachina/nativelink/blob/c88afab60b5591e093ac843b9583e4aff58ccb3b/deployment-examples/kubernetes/README.md#L85)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Consider surrounding headings with newlines: https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md022---headers-should-be-surrounded-by-blank-lines
</blockquote></details>

fixed


<!-- Sent from Reviewable.io -->

2024-04-15 18:01 UTC, nfarah86 commented
*[`deployment-examples/kubernetes/README.md` line 86 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvAlkL16vBW25kopUQ8:-NvXuzB84G08kAyKX3Ii:bkmi42f) ([raw file](https://github.com/TraceMachina/nativelink/blob/c88afab60b5591e093ac843b9583e4aff58ccb3b/deployment-examples/kubernetes/README.md#L86)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

This is not exactly correct. The `nix eval` command doesn't tag an image. Instead, it derives/computes the tag that nix would generate if you were to build the image and push it to a registry.

When you do

```
nix run github:TraceMachina/nativelink/someCommit#image.copyToDockerDaemon
```

the image you get when you run `docker image ls` would have the tag:

```
nix eval github:TraceMachina/nativelink/someCommit#image.imageTag --raw
```
</blockquote></details>

updated to clarify this


<!-- Sent from Reviewable.io -->

2024-04-15 18:07 UTC, nfarah86 commented
*[`deployment-examples/kubernetes/README.md` line 93 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvAnNvz8US2zB8HbIkN:-NvXw6y1E2eBOzUjYKd8:b3psvdp) ([raw file](https://github.com/TraceMachina/nativelink/blob/c88afab60b5591e093ac843b9583e4aff58ccb3b/deployment-examples/kubernetes/README.md#L93)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

This `nix eval` command doesn't give you the tag of the image. Instead would give you the evaluated output of the entire `nativelink` flake (which probably doesn't work).

The image tags for the `nativelink` container images are autogenerated from the inputs to the `image` output. Since this image output is only dependent on the `nativelink` executable, its hash is only derived from the rust sources, it's dependencies, and the container-specific config options. It's not derived from the entire nativelink repository. For instance, the tag wouldn't change if you modified some random non-rust file that doesn't influence the nativelink build.

Something to not confuse here is that `.#image` and `.#image.imageTag` are two different expressions. `nix eval .#image` would try to evaluate the`image` flake output (which probably doesn't work because you can't "print" an image). `nix eval .#image.imageTag` just evaluates the `imageTag` field in the `image` output, which is effectively just a string.
</blockquote></details>

@aaronmondal I think we should not mention this if it probably doesn't work`nix eval .#image` LMKWYT. 


<!-- Sent from Reviewable.io -->

2024-04-15 19:25 UTC, nfarah86 commented
*[`deployment-examples/kubernetes/README.md` line 93 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvAnNvz8US2zB8HbIkN:-NvYD3FZ13ps50-9PqAP:bvnrpcm) ([raw file](https://github.com/TraceMachina/nativelink/blob/c88afab60b5591e093ac843b9583e4aff58ccb3b/deployment-examples/kubernetes/README.md#L93)):*
<details><summary><i>Previously, nfarah86 (nadine farah) wrote…</i></summary><blockquote>

@aaronmondal I think we should not mention this if it probably doesn't work`nix eval .#image` LMKWYT.
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2024-04-15 19:29 UTC, nfarah86 commented
*[`deployment-examples/kubernetes/README.md` line 107 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvApLQx45qJX7nBn73l:-NvYEBhd-ydZl3O4lpD9:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/c88afab60b5591e093ac843b9583e4aff58ccb3b/deployment-examples/kubernetes/README.md#L107)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Probably a typo which meant to say:

```
nix eval github:TraceMachina/nativelink.image.imageTag --raw
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-15 20:06 UTC, nfarah86 commented
*[`deployment-examples/kubernetes/README.md` line 126 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvArOXV8I9aX6FUBxAD:-NvYMWWjCIAJbthEaCBA:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/c88afab60b5591e093ac843b9583e4aff58ccb3b/deployment-examples/kubernetes/README.md#L126)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

You can't run the `.#image` output, as it's just a json file which looks like this (you can verify this by running `nix build` and printing the output of the `result` symlink that the build command creates):

```
{
	"version": 1,
	"image-config": {
		"Entrypoint": [
			"/nix/store/wswj7zid10blknd6kcg4xp8w0ri81d3x-nativelink-0.3.0/bin/nativelink"
		],
		"Labels": {
			"org.opencontainers.image.description": "An RBE compatible, high-performance cache and remote executor.",
			"org.opencontainers.image.documentation": "https://github.com/TraceMachina/nativelink",
			"org.opencontainers.image.licenses": "Apache-2.0",
			"org.opencontainers.image.revision": "aab867a79396f1aefba7030fcd1128822107a2e0-dirty",
			"org.opencontainers.image.source": "https://github.com/TraceMachina/nativelink",
			"org.opencontainers.image.title": "NativeLink",
			"org.opencontainers.image.vendor": "Trace Machina, Inc."
		}
	},
	"layers": [
		{
			"digest": "sha256:22e91acf12aba41ba8469db4a900baa550803fa3f4289f5d997683916c920353",
			"size": 29400576,
			"diff_ids": "sha256:22e91acf12aba41ba8469db4a900baa550803fa3f4289f5d997683916c920353",
			"paths": [
				{
					"path": "/nix/store/wswj7zid10blknd6kcg4xp8w0ri81d3x-nativelink-0.3.0"
				}
			],
			"mediatype": "application/vnd.oci.image.layer.v1.tar"
		}
	],
	"arch": "amd64"
}
```

The way to make this image runnable is to invoke the `copyTo` or `copyToRegistry` or `copyToDockerDaemon` attributes on the image. See this for more information:

https://github.com/nlewo/nix2container/tree/master

Something you could `nix run` is the actual nativelink executable which you can run via a raw `nix run` in the cloned repository without any additional arguments (but note that this is running the executable natively, not invoking any image).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-15 20:06 UTC, nfarah86 commented
*[`.github/styles/config/vocabularies/TraceMachina/accept.txt` line 29 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvAjnIuCLoCrl4pbcpx:-NvYM_3R1-uPgieLElAq:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/c88afab60b5591e093ac843b9583e4aff58ccb3b/.github/styles/config/vocabularies/TraceMachina/accept.txt#L29)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

This is breaking pre-commit hooks because the last line doesn't have a trailing newline. To fix it:

```
# The current status of your Pr
git status

# invoke the pre-commit hooks (only works in the nix flake)
pre-commit run -a

# view the changed files
git status

# in this case it should've modified the `accept.txt` file
git add .github/styles/config/vocabularies/TraceMachina/accept.txt

# Amend the commit
git commit --amend
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-15 20:07 UTC, nfarah86 reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/846)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 7 discussions need to be resolved

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/846#-NvAjhCdCdF9GtHLM9dO):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Updated -> Update
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-15 20:07 UTC, aaronmondal approved these changes
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/846)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04



<!-- Sent from Reviewable.io -->

2024-04-15 20:12 UTC, nfarah86 reviewed
-@MarcusSorealheis

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/846#-:-NvYNJGMAzlA4REK0ik0:b8cg3jw)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04



<!-- Sent from Reviewable.io -->

2024-04-15 20:13 UTC, aaronmondal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/846#-:-NvYO3xS7g_7eKy9l39W:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04



<!-- Sent from Reviewable.io -->

2024-04-15 20:47 UTC, merged