Refactor buf_channel
TraceMachina/nativelink pull request #849
Opened 2024-04-11 19:23 UTC by allada

Major rewrite of how DropCloserReadHalf and DropCloserWriteHalf.
* Simplified DropCloserReadHalf::consume()
* DropCloserWriteHalf will no longer wait for eof to be received
* Added utility func DropCloserWriteHalf::bind()
* DropCloserReadHalf can now be configured to hold a queue of recent data to aid with places that might need retry.
* EOF signal is now an AtomicBool instead of a tokio::once channel.
* DropCloserReadHalf::try_reset_stream added to put queue back onto head of stream if able.

# Description

Please include a summary of the changes and the related issue. Please also
include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-04-11 19:24 UTC, allada reviewed
+@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/849#-:-NvDbWtpEPPr5eDltNMS:b-bn1n1c)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @adam-singer)



<!-- Sent from Reviewable.io -->

2024-04-12 22:59 UTC, adam-singer reviewed
> Reviewed 13 of 16 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/849)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-04-12 23:31 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/849)* status: 0 of 1 LGTMs obtained (waiting on @adam-singer)

___
*[`nativelink-store/tests/filesystem_store_test.rs` line 231 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/849#-NvDcD0u2GHxy-n2ek0P:-NvDcD0u2GHxy-n2ek0Q:b-xd04qy) ([raw file](https://github.com/TraceMachina/nativelink/blob/90489eef2840e56e24ed987a22108ca3be69c84b/nativelink-store/tests/filesystem_store_test.rs#L231)):*
> ```XML
>     const HASH1: &str = "0123456789abcdef000000000000000000010000000000000123456789abcdef";
>     const HASH2: &str = "0123456789abcdef000000000000000000020000000000000123456789abcdef";
>     const VALUE1: &str = "1234";
> ```

fyi: The buffer queue got slightly increased, so I needed slightly more data.


<!-- Sent from Reviewable.io -->

2024-04-12 23:40 UTC, adam-singer requested changes
> Reviewed 1 of 16 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/849)* status: 0 of 1 LGTMs obtained, and 3 discussions need to be resolved

___
*[`nativelink-util/src/buf_channel.rs` line 67 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/849#-NvJYGUJ9vtg2skAOzSA:-NvJYGUJ9vtg2skAOzSB:bd5h5ve) ([raw file](https://github.com/TraceMachina/nativelink/blob/2a9c935d535a52e2cb468bf3b1087fa88cf83d4c/nativelink-util/src/buf_channel.rs#L67)):*
> ```XML
> impl DropCloserWriteHalf {
>     /// Sends data over the channel to the receiver.
>     pub fn send(&mut self, buf: Bytes) -> impl Future<Output = Result<(), Error>> + '_ {
> ```

Whats the reasoning or errors that made switching from `async` keyword to full type signature of `impl Future<..> + '_`?
___
*[`nativelink-util/src/buf_channel.rs` line 145 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/849#-NvJagFu5zqW9cMVNCoF:-NvJagFu5zqW9cMVNCoG:b-76pwm3) ([raw file](https://github.com/TraceMachina/nativelink/blob/2a9c935d535a52e2cb468bf3b1087fa88cf83d4c/nativelink-util/src/buf_channel.rs#L145)):*
> ```XML
> 
>         // Now close our stream.
>         self.tx = None;
> ```

Should `drop` be called on the contained type of `tx`, `self.tx.map(|tx| drop(tx));` before applying `None`? 
___
*[`nativelink-util/src/buf_channel.rs` line 223 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/849#-NvJbayn4PnB8rx-k3QZ:-NvJbayn4PnB8rx-k3Q_:b-ktd84f) ([raw file](https://github.com/TraceMachina/nativelink/blob/2a9c935d535a52e2cb468bf3b1087fa88cf83d4c/nativelink-util/src/buf_channel.rs#L223)):*
> ```XML
>                     ));
>                 }
>                 const ZERO_DATA: Bytes = Bytes::new();
> ```

Can this value be hoisted to global to this module? 


<!-- Sent from Reviewable.io -->

2024-04-14 02:29 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/849)* status: 0 of 1 LGTMs obtained, and 3 discussions need to be resolved (waiting on @adam-singer)

___
*[`nativelink-util/src/buf_channel.rs` line 67 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/849#-NvJYGUJ9vtg2skAOzSA:-NvPOnmdB5L0Bg2xgbiy:b5z9xnd) ([raw file](https://github.com/TraceMachina/nativelink/blob/2a9c935d535a52e2cb468bf3b1087fa88cf83d4c/nativelink-util/src/buf_channel.rs#L67)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Whats the reasoning or errors that made switching from `async` keyword to full type signature of `impl Future<..> + '_`?
</blockquote></details>

It's probably me over thinking things, but in theory it makes inlining easier/more-possible for the compiler.

When it's `async fn` it forces the user to `.await` another future, but if you are just forwarding on the future, you could let the compiler infer it using `impl Future<>`.

The compiler can probably inline some of it, but I've learnt with rust to not trust rust at inlining `async` functions because it needs to track stack traces on panic (or something). When we forward it, in theory there is no stack trace, so it's pure inlinable.
___
*[`nativelink-util/src/buf_channel.rs` line 145 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/849#-NvJagFu5zqW9cMVNCoF:-NvPPR72CL47_iyIqgl_:bb8aazm) ([raw file](https://github.com/TraceMachina/nativelink/blob/2a9c935d535a52e2cb468bf3b1087fa88cf83d4c/nativelink-util/src/buf_channel.rs#L145)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Should `drop` be called on the contained type of `tx`, `self.tx.map(|tx| drop(tx));` before applying `None`?
</blockquote></details>

By spec (RAII), `drop `must be called when it's overridden.
___
*[`nativelink-util/src/buf_channel.rs` line 223 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/849#-NvJbayn4PnB8rx-k3QZ:-NvPQfWb6_9x-PWKvV8k:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/2a9c935d535a52e2cb468bf3b1087fa88cf83d4c/nativelink-util/src/buf_channel.rs#L223)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Can this value be hoisted to global to this module?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-15 16:37 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/849#-:-NvXbgG83qe1el5BHLBm:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-04-15 17:50 UTC, merged