Implement get_tree() feature
TraceMachina/nativelink pull request #905
Opened 2024-05-09 08:09 UTC by aleksdmladenovic

# Description

I handled get_tree() GRPC request in the CAS Server. Used FIFO(First-In-First-Out) traversal method ( BFS Algorithm ) to loop over directories using `VecDeque` data structure. Paging is supported and `page_token` in `GetTreeRequest` is used to point the directory to start traversing with. And `next_page_token` in `GetTreeResponse` refers the `page_token` parameter which will be used in the next request.

Fixes #355 

## Type of change

Please delete options that aren't relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Still not tested yet.

## Checklist

- [x] Updated documentation if needed
- [ ] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-05-09 08:10 UTC, aleksdmladenovic commented
+@allada, @MarcusSorealheis

2024-05-09 17:51 UTC, adam-singer commented
@aleksdmladenovic can we add tests ?

2024-05-12 19:36 UTC, allada approved these changes
Looks mostly good, but needs some tests.

There's also a few performance improvements that could be made, but it's fine to omit them for now.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/905#-:-NxiIPjn4K7hX4IRW4bI:bb37ln1)* status: 0 of 1 LGTMs obtained, and 4 discussions need to be resolved

___
*[`nativelink-service/src/cas_server.rs` line 251 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxiDWJ89VfnfyP59Uk9:-NxiDWJ89VfnfyP59UkA:b-i2643j) ([raw file](https://github.com/TraceMachina/nativelink/blob/f4772cf9acdc620de10bc1874093ffd904e36571/nativelink-service/src/cas_server.rs#L251)):*
> ```XML
>         let mut deque: VecDeque<DigestInfo> = VecDeque::new();
>         let mut directories: Vec<Directory> = Vec::new();
>         let page_token = inner_request.page_token;
> ```

nit: Lets convert this to a `DigestInfo` and error otherwise. If it's an empty string consider it ok.

You should not use `hash_str()`, because it also needs to match the size to be in spec.
___
*[`nativelink-service/src/cas_server.rs` line 257 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxiDv252Ubc0JmTWosh:-NxiDv252Ubc0JmTWosi:b-d5baiu) ([raw file](https://github.com/TraceMachina/nativelink/blob/f4772cf9acdc620de10bc1874093ffd904e36571/nativelink-service/src/cas_server.rs#L257)):*
> ```XML
>         // `next_page_token` will return the `hash_str` of the next request round's first directory digest.
>         // It will be an empty string when it reached the end of the directory tree.
>         let mut next_page_token: String = String::new();
> ```

nit: Use digest and convert it last. This saves on allocations too.
___
*[`nativelink-service/src/cas_server.rs` line 261 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxiHDTl5WNuufftSD2b:-NxiHDTm1r9zE5TIrCGv:b-mnx9jx) ([raw file](https://github.com/TraceMachina/nativelink/blob/f4772cf9acdc620de10bc1874093ffd904e36571/nativelink-service/src/cas_server.rs#L261)):*
> ```XML
> 
>         while !deque.is_empty() {
>             let digest: DigestInfo = *deque.front().err_tip(|| "In VecDeque::front")?;
> ```

nit: use `.pop_front()` here.
___
*[`nativelink-service/src/cas_server.rs` line 269 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxiHhb18HJa83kHgbEx:-NxiHhb18HJa83kHgbEy:bcw3n08) ([raw file](https://github.com/TraceMachina/nativelink/blob/f4772cf9acdc620de10bc1874093ffd904e36571/nativelink-service/src/cas_server.rs#L269)):*
> ```XML
>             }
>             if page_token_matched {
>                 if directories.len() as i32 == page_size + 1 {
> ```

nit: call `directories.push(directory.clone())` first, so you don't need to add `+ 1` here.


<!-- Sent from Reviewable.io -->

2024-05-13 18:00 UTC, aleksdmladenovic reviewed
I've added tests and fixed nits you mentioned.

cc: @allada , @adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/905#-:-Nxn5iyg68Gftfu3J8io:bgu63rz)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable



<!-- Sent from Reviewable.io -->

2024-05-14 00:42 UTC, allada requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/905)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-22.04, and 7 discussions need to be resolved

___
*[`nativelink-service/src/cas_server.rs` line 252 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxoUznA4YlENZg2Xvpk:-NxoUznA4YlENZg2Xvpl:b8m54ke) ([raw file](https://github.com/TraceMachina/nativelink/blob/313b3691ef8ca4a728c954f357610f857c1b3356/nativelink-service/src/cas_server.rs#L252)):*
> ```XML
>         let mut directories: Vec<Directory> = Vec::new();
>         // `page_token` will return the `{hash_str}:{size_bytes}` of the current request's first directory digest.
>         let page_token_parts: Vec<&str> = inner_request.page_token.split(":").collect();
> ```

nit: This is really inefficient and causes allocations. Instead you should use `.split("-")` then `.next()` on the iterator to get the two parts into the variables (with `.err_tip()`).
___
*[`nativelink-service/src/cas_server.rs` line 252 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxoVcQ8BNFbMDMHLApV:-NxoVcQ8BNFbMDMHLApW:b-r5qynr) ([raw file](https://github.com/TraceMachina/nativelink/blob/313b3691ef8ca4a728c954f357610f857c1b3356/nativelink-service/src/cas_server.rs#L252)):*
> ```XML
>         let mut directories: Vec<Directory> = Vec::new();
>         // `page_token` will return the `{hash_str}:{size_bytes}` of the current request's first directory digest.
>         let page_token_parts: Vec<&str> = inner_request.page_token.split(":").collect();
> ```

nit: Don't use `:` use `-`, this is standard in the rest of the code.
___
*[`nativelink-service/src/cas_server.rs` line 292 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxoWK83ElG8q26IQ47r:-NxoWK83ElG8q26IQ47s:b-5bo36t) ([raw file](https://github.com/TraceMachina/nativelink/blob/313b3691ef8ca4a728c954f357610f857c1b3356/nativelink-service/src/cas_server.rs#L292)):*
> ```XML
>         // `next_page_token` will return the `{hash_str}:{size_bytes}` of the next request's first directory digest.
>         // It will be an empty string when it reached the end of the directory tree.
>         let next_page_token: String = if let Some(value) = deque.front() {
> ```

nit: Because we are now grabbing the front-item, we are introducing a fence-post case where `deque.front()` could be `None` because the `for directory in directory.directories {` did not run.

We should move the `for-loop` above the `if page_token_matched {` branch to protect us.
___
*[`nativelink-service/tests/cas_server_test.rs` line 346 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxoWqOO28g16XB9zpK0:-NxoWqOO28g16XB9zpK1:bjyelub) ([raw file](https://github.com/TraceMachina/nativelink/blob/313b3691ef8ca4a728c954f357610f857c1b3356/nativelink-service/tests/cas_server_test.rs#L346)):*
> ```XML
>         let store_pinned = Pin::new(store_owned.as_ref());
> 
>         // Set up 5 sub-directories
> ```

nit: Period.
___
*[`nativelink-service/tests/cas_server_test.rs` line 361 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxoWzY82vTXB3y1ecn9:-NxoWzY82vTXB3y1ecnA:bie06be) ([raw file](https://github.com/TraceMachina/nativelink/blob/313b3691ef8ca4a728c954f357610f857c1b3356/nativelink-service/tests/cas_server_test.rs#L361)):*
> ```XML
>                     mtime: Some(Timestamp {
>                         seconds: 0,
>                         nanos: i,
> ```

nit: put this in `seconds`. `nanos` might not get converted properly due to percision issues.
___
*[`nativelink-service/tests/cas_server_test.rs` line 393 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxoXR7Y7wDM6jOgvsbs:-NxoXR7Y7wDM6jOgvsbt:b-nwjp10) ([raw file](https://github.com/TraceMachina/nativelink/blob/313b3691ef8ca4a728c954f357610f857c1b3356/nativelink-service/tests/cas_server_test.rs#L393)):*
> ```XML
>         )
>         .await?;
>         let root_directory_digest: Digest = Digest::try_from(root_directory_digest_info).unwrap();
> ```

nit: use `root_directory_digest_info.into()` (ditto with others).
___
*[`nativelink-service/tests/cas_server_test.rs` line 431 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxoXgiY8fLv0cw6GziC:-NxoXgiY8fLv0cw6GziD:bq8jztl) ([raw file](https://github.com/TraceMachina/nativelink/blob/313b3691ef8ca4a728c954f357610f857c1b3356/nativelink-service/tests/cas_server_test.rs#L431)):*
> ```XML
>         );
> 
>         // Must work when paging is enabled ( `page_size` is 2 ).
> ```

This should be a different test.

I suggest making a setup function that will get our state all prepared, then we can call it from different tests.


<!-- Sent from Reviewable.io -->

2024-05-14 04:08 UTC, aleksdmladenovic reviewed
Resolved comments. cc:@allada, @adam-singer

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/905#-:-NxpH5bo2LumTvmIb95J:b-9pdbie)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 1 discussions need to be resolved

___
*[`nativelink-service/tests/cas_server_test.rs` line 431 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxoXgiY8fLv0cw6GziC:-NxpH4UtDqDHI4nRC_TM:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/313b3691ef8ca4a728c954f357610f857c1b3356/nativelink-service/tests/cas_server_test.rs#L431)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This should be a different test.

I suggest making a setup function that will get our state all prepared, then we can call it from different tests.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-14 15:23 UTC, allada requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/905)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, pre-commit-checks, ubuntu-22.04, and 6 discussions need to be resolved

___
*[`nativelink-service/src/cas_server.rs` line 260 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxrPN-Q4hGtxG8-bPWT:-NxrPN-Q4hGtxG8-bPWU:b-4bmqpu) ([raw file](https://github.com/TraceMachina/nativelink/blob/1b9bc0283384d578f1f35731df12211dfad5fa7d/nativelink-service/src/cas_server.rs#L260)):*
> ```XML
>                 .next()
>                 .err_tip(|| "Failed to parse `size_bytes` in `page_token`")?
>                 .parse::<i64>()?,
> ```

nit: Please `.err_tip()` or `.map_err()`.
___
*[`nativelink-service/src/cas_server.rs` line 261 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxrPQIU2qYv7H0iKfnO:-NxrPQIU2qYv7H0iKfnP:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/1b9bc0283384d578f1f35731df12211dfad5fa7d/nativelink-service/src/cas_server.rs#L261)):*
> ```XML
>                 .err_tip(|| "Failed to parse `size_bytes` in `page_token`")?
>                 .parse::<i64>()?,
>         )?;
> ```

ditto.
___
*[`nativelink-service/src/cas_server.rs` line 275 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxrPVif4oM6MeNxIn5S:-NxrPVif4oM6MeNxIn5T:be5e9yn) ([raw file](https://github.com/TraceMachina/nativelink/blob/1b9bc0283384d578f1f35731df12211dfad5fa7d/nativelink-service/src/cas_server.rs#L275)):*
> ```XML
>                 page_token_matched = true;
>             }
>             for directory in directory.clone().directories {
> ```

nit: Clone not needed. You probably want to clone `directory.digest()` instead.
___
*[`nativelink-service/src/cas_server.rs` line 284 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxrPcu0-9WiwR65orVh:-NxrPcu0-9WiwR65orVi:b-uu3epr) ([raw file](https://github.com/TraceMachina/nativelink/blob/1b9bc0283384d578f1f35731df12211dfad5fa7d/nativelink-service/src/cas_server.rs#L284)):*
> ```XML
>             }
>             if page_token_matched {
>                 directories.push(directory.clone());
> ```

`.clone()` not needed.
___
*[`nativelink-service/tests/cas_server_test.rs` line 343 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxraPYlBf_2tp07LCRU:-NxraPYlBf_2tp07LCRV:b9j4972) ([raw file](https://github.com/TraceMachina/nativelink/blob/1b9bc0283384d578f1f35731df12211dfad5fa7d/nativelink-service/tests/cas_server_test.rs#L343)):*
> ```XML
>     ) -> Result<
>         (
>             Digest,
> ```

nit: Make a struct that represents these to make it more readable.
___
*[`nativelink-service/tests/cas_server_test.rs` line 349 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxraTGu2315erJNWhCb:-NxraTGu2315erJNWhCc:b-q1s662) ([raw file](https://github.com/TraceMachina/nativelink/blob/1b9bc0283384d578f1f35731df12211dfad5fa7d/nativelink-service/tests/cas_server_test.rs#L349)):*
> ```XML
>             Vec<DigestInfo>,
>         ),
>         Box<dyn std::error::Error>,
> ```

nit: Use nativelink's `Error`.


<!-- Sent from Reviewable.io -->

2024-05-14 16:45 UTC, aleksdmladenovic reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/905)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 2 discussions need to be resolved

___
*[`nativelink-service/src/cas_server.rs` line 261 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxrPQIU2qYv7H0iKfnO:-Nxrzb-xAVr6bu07vTEW:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/1b9bc0283384d578f1f35731df12211dfad5fa7d/nativelink-service/src/cas_server.rs#L261)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`nativelink-service/src/cas_server.rs` line 284 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxrPcu0-9WiwR65orVh:-NxrzdYJ5CriXzpAU5YM:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/1b9bc0283384d578f1f35731df12211dfad5fa7d/nativelink-service/src/cas_server.rs#L284)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

`.clone()` not needed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-14 17:54 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/905#-:-NxsEVqb6Ia55HIvA9m_:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13, and 1 discussions need to be resolved

___
*[`nativelink-service/tests/cas_server_test.rs` line 341 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/905#-NxsEI6Q0ZawJ-0GVNw4:-NxsEI6Q0ZawJ-0GVNw5:blkbd7f) ([raw file](https://github.com/TraceMachina/nativelink/blob/4503f9144f1dd98a3640f7a73fa86fba3a41fa31/nativelink-service/tests/cas_server_test.rs#L341)):*
> ```XML
> 
>     struct SetupDirectoryResult {
>         root_directory_digest: Digest,
> ```

nit: just use `DigestInfo`, it's always safe to convert directly to `Digest`.


<!-- Sent from Reviewable.io -->

2024-05-14 18:29 UTC, aleksdmladenovic reviewed
Resolved. cc: @allada 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/905#-:-NxsMKV42ti88H2otxJu:b-sbq0y0)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable



<!-- Sent from Reviewable.io -->

2024-05-14 18:37 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/905#-:-NxsOBl-0-EhC8uKrgP_:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable



<!-- Sent from Reviewable.io -->

2024-05-15 11:36 UTC, MarcusSorealheis commented
This looks good. thank you for the PR [aleksdmladenovic](https://github.com/aleksdmladenovic)!

2024-05-15 11:53 UTC, MarcusSorealheis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/905#-:-Nxw5Q7sB_EACeFkoAvq:bnfp4nl)* status: 2 of 1 LGTMs obtained, and pending CI: pre-commit-checks



<!-- Sent from Reviewable.io -->

2024-05-15 12:00 UTC, MarcusSorealheis commented
@allada If this looks good still, please merge it.Even though we don't use it, a lot of tools do use it so maybe it will be helpful to NativeLink users.

2024-05-15 23:50 UTC, MarcusSorealheis commented
@aleksdmladenovic what was the reason for the most recent push?

2024-05-15 23:50 UTC, MarcusSorealheis commented
Looks like it may have been a rebase but correct me if I am wrong.

2024-05-15 23:57 UTC, aleksdmladenovic commented
Just rebase. cc: @MarcusSorealheis

2024-05-16 06:43 UTC, MarcusSorealheis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> again due to rebase

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/905#-:-Ny-85iT-8x90z1k1VG7:b-tukgky)* status: <span>:shipit:</span> complete! 3 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-05-16 06:43 UTC, merged