Fix nix build on MacOS
TraceMachina/nativelink pull request #919
Opened 2024-05-15 21:21 UTC by zbirenbaum

# Description

Any nix build will currently fail on MacOS due to the formatting of the linker arguments. This fixes it to re-enable nix builds.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2024-05-15 21:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TraceMachina/nativelink?pullRequest=919) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TraceMachina/nativelink?pullRequest=919) before we can accept your contribution.<br/><hr/>**Zach Birenbaum** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TraceMachina/nativelink?pullRequest=919) it.</sub>

2024-05-15 21:43 UTC, aaronmondal requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/919)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, license/cla, windows-2022 / stable, and 1 discussions need to be resolved

___
*[`tools/nixpkgs_link_libunwind_and_libcxx.diff` line 46 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/919#-NxyCUtDB2hNVHAeJhX0:-NxyCUtDB2hNVHAeJhX1:undefined) ([raw file](https://github.com/TraceMachina/nativelink/blob/8d7992bec3115ea832861a04a43380994a152a4b/tools/nixpkgs_link_libunwind_and_libcxx.diff#L46)):*
> ```Diff
> +        "-rpath ${targetLlvmLibraries.libunwind}/lib"
> +        "-L${targetLlvmLibraries.libcxx}/lib"
> +        "-rpath ${targetLlvmLibraries.libcxx}/lib"
> ```





_Suggestion:_
```Diff
+        "-L${targetLlvmLibraries.libunwind}/lib"
+        "-rpath" "${targetLlvmLibraries.libunwind}/lib"
+        "-L${targetLlvmLibraries.libcxx}/lib"
+        "-rpath" "${targetLlvmLibraries.libcxx}/lib"
```


<!-- Sent from Reviewable.io -->

2024-05-15 21:47 UTC, aaronmondal reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/919)* status: 0 of 1 LGTMs obtained, and pending CI: Local / ubuntu-22.04, Remote / large-ubuntu-22.04, license/cla, windows-2022 / stable, and 2 discussions need to be resolved

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/919#-NxyDLKj4TclmhxQZ-SY):*
nit: Add `Fixes #918` in the commit message body.


<!-- Sent from Reviewable.io -->

2024-05-15 21:51 UTC, aaronmondal reviewed
Ah actually this influences the generated bazel toolchains. You'll need to run `generate-toolchains` on a Linux x86_64 machine. That will regenerate the files in the `local-remote-execution` directory. The two failures in the LRE jobs are caused by this mismatch.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/919#-:-NxyDrDy5-KsZ8PTe4dJ:b-8t83l3)* status: 0 of 1 LGTMs obtained, and pending CI: Local / ubuntu-22.04, Remote / large-ubuntu-22.04, license/cla, and 2 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-05-15 23:46 UTC, aaronmondal commented
@zbirenbaum I added the toolchain changes in #920 and added regression tests. Added you as Co-author on that commit.

2024-05-16 04:32 UTC, adam-singer reviewed
How could I reproduce the before and after of this patch? 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/919#-:-Nxzen5W90OTnM8PdPSB:b5k66y7)* status: 0 of 1 LGTMs obtained, and pending CI: Local / ubuntu-22.04, Remote / large-ubuntu-22.04, license/cla, and 2 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-05-16 13:15 UTC, closed without merging