Include UUID in ActionState
TraceMachina/nativelink pull request #927
Opened 2024-05-22 23:31 UTC by zbirenbaum

# Description

Changes the field used for identifying which action an ActionState corresponds to include a uuid as well as the ActionInfoHashKey. All existing functionality is kept the same by making use of the nested ActionInfoHashKey contained within the Id. These changes will provide the basis for all usage of Id in followup changes to the scheduler.  This breaks compatibility for forwarding an operation from one remote execution system to another that does not use our operation name format (ie: very unlikely, but possible).

Please delete options that aren't relevant.
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)

## How Has This Been Tested?

All existing tests have been modified to remain functionally equivalent.

## Checklist

- [ x ] Updated documentation if needed
- [ x ] Tests added/amended
- [ x ] `bazel test //...`  passes locally
- [ x ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-05-22 23:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TraceMachina/nativelink?pullRequest=927) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TraceMachina/nativelink?pullRequest=927) before we can accept your contribution.<br/><hr/>**Zach Birenbaum** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TraceMachina/nativelink?pullRequest=927) it.</sub>

2024-05-24 20:55 UTC, adam-singer requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/927)* status: 0 of 1 LGTMs obtained, and pending CI: license/cla, pre-commit-checks, and 1 discussions need to be resolved

___
*[`nativelink-util/src/action_messages.rs` line 60 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/927#-NygNfPJ2lUcLfS9toOb:-NygNfPJ2lUcLfS9toOc:bgsizj3) ([raw file](https://github.com/TraceMachina/nativelink/blob/bf424be09cc7bbdf1b6cf3e35e0963eafa2e6457/nativelink-util/src/action_messages.rs#L60)):*
> ```XML
> }
> 
> impl Id {
> ```

Can we make units for `Id` that test creation, comparison, parsing? Would also be nice to get a sense of what this field looks like as a string to be parsed. 


<!-- Sent from Reviewable.io -->

2024-05-29 01:55 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/927)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), license/cla, macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 1 discussions need to be resolved

___
*[`nativelink-util/src/action_messages.rs` line 60 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/927#-NygNfPJ2lUcLfS9toOb:-Nz11h_t7TurRlJPA5jk:bwrpudf) ([raw file](https://github.com/TraceMachina/nativelink/blob/bf424be09cc7bbdf1b6cf3e35e0963eafa2e6457/nativelink-util/src/action_messages.rs#L60)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Can we make units for `Id` that test creation, comparison, parsing? Would also be nice to get a sense of what this field looks like as a string to be parsed.
</blockquote></details>

The format for the string is just {unique_qualifier}:{uuid}

@allada I believe when we just spoke you felt tests weren't required for this refactor as long as all existing tests pass correct?


<!-- Sent from Reviewable.io -->

2024-05-29 03:19 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/927#-:-Nz1M0AiByC0D0BPd2A7:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), license/cla, macos-13, ubuntu-22.04, and 4 discussions need to be resolved

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 203 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/927#-Nz1LjlW4T8C7bPD8ATm:-Nz1LjlW4T8C7bPD8ATn:b-3sbu52) ([raw file](https://github.com/TraceMachina/nativelink/blob/37d2ba3605642328a6ff35fca81410e14dbeae87/nativelink-scheduler/src/simple_scheduler.rs#L203)):*
> ```XML
>     }
> }
> impl Borrow<ActionInfoHashKey> for CompletedAction {
> ```

I think you can remove this now?
___
*[`nativelink-util/src/action_messages.rs` line 60 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/927#-NygNfPJ2lUcLfS9toOb:-Nz1JgDeEbvR180W95Ji:bvmfktg) ([raw file](https://github.com/TraceMachina/nativelink/blob/bf424be09cc7bbdf1b6cf3e35e0963eafa2e6457/nativelink-util/src/action_messages.rs#L60)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

The format for the string is just {unique_qualifier}:{uuid}

@allada I believe when we just spoke you felt tests weren't required for this refactor as long as all existing tests pass correct?
</blockquote></details>

I'd say yes, we probably don't need a test for this unless we want the external-visible format of `OperationId` to be stable across versions, but I don't think we should strive for that just yet.
___
*[`nativelink-util/src/action_messages.rs` line 103 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/927#-Nz1KGvyC4MpprmXWyjF:-Nz1KGvyC4MpprmXWyjG:b-6okqux) ([raw file](https://github.com/TraceMachina/nativelink/blob/37d2ba3605642328a6ff35fca81410e14dbeae87/nativelink-util/src/action_messages.rs#L103)):*
> ```XML
> impl std::fmt::Debug for OperationId {
>     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
>         let id_str = format!("{}:{}", self.unique_qualifier.action_name(), self.id);
> ```

nit: use `f.write_fmt()`. It will remove a needless string allocation.
___
*[`nativelink-util/src/action_messages.rs` line 112 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/927#-Nz1KXdh3GrKpK86n3J_:-Nz1KXdh3GrKpK86n3Ja:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/37d2ba3605642328a6ff35fca81410e14dbeae87/nativelink-util/src/action_messages.rs#L112)):*
> ```XML
> pub struct WorkerId(pub Uuid);
> 
> impl std::fmt::Display for WorkerId {
> ```

ditto.


<!-- Sent from Reviewable.io -->

2024-05-29 04:23 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/927)* status: 1 of 1 LGTMs obtained, and pending CI: Vercel, pre-commit-checks, and 3 discussions need to be resolved

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 203 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/927#-Nz1LjlW4T8C7bPD8ATm:-Nz1YBO55zlmH6SLrypK:b-d3rh6h) ([raw file](https://github.com/TraceMachina/nativelink/blob/37d2ba3605642328a6ff35fca81410e14dbeae87/nativelink-scheduler/src/simple_scheduler.rs#L203)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I think you can remove this now?
</blockquote></details>

Unfortunately not. Until everything is migrated to use an OperationId map, `find_recently_completed_action` and probably other places will error out if you remove this code.
___
*[`nativelink-util/src/action_messages.rs` line 103 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/927#-Nz1KGvyC4MpprmXWyjF:-Nz1_dZwDJd12QFo-IKJ:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/37d2ba3605642328a6ff35fca81410e14dbeae87/nativelink-util/src/action_messages.rs#L103)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: use `f.write_fmt()`. It will remove a needless string allocation.
</blockquote></details>

Done.
___
*[`nativelink-util/src/action_messages.rs` line 112 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/927#-Nz1KXdh3GrKpK86n3J_:-Nz1_fg5AqHX7zKtcAta:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/37d2ba3605642328a6ff35fca81410e14dbeae87/nativelink-util/src/action_messages.rs#L112)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-29 19:01 UTC, zbirenbaum reviewed
> Dismissed @adam-singer from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/927)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable, and 2 discussions need to be resolved

___
*[`nativelink-util/src/action_messages.rs` line 60 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/927#-NygNfPJ2lUcLfS9toOb:-Nz1_moPDr2to2sdITlr:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/bf424be09cc7bbdf1b6cf3e35e0963eafa2e6457/nativelink-util/src/action_messages.rs#L60)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I'd say yes, we probably don't need a test for this unless we want the external-visible format of `OperationId` to be stable across versions, but I don't think we should strive for that just yet.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-29 19:57 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 8 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/927#-:-Nz4vUMb0nSaVt-CfgC8:bnfp4nl)* status: 2 of 1 LGTMs obtained, and 2 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-05-29 22:03 UTC, allada approved these changes
> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/927)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-05-29 22:03 UTC, allada approved these changes
> Reviewed 1 of 9 files at r1, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/927)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-05-29 22:15 UTC, merged