Add kind-loadbalancer
TraceMachina/nativelink pull request #929
Opened 2024-05-24 01:22 UTC by SchahinRohani

# Description

Provide an envoy loadbalancer container to access the local kind cluster. The loadbalancer adds the ability to reach the local kind cluster trough localhost, so that it is possible to work with a mac on the nativelink cluster.

Docker on Mac uses a aarch64 linux vm unter the hood, so the builds in the cluster can now be tested on that architecture.

Users can now query the loadbalancer instead of the gateway.

The loadbalancer has the following endpoints:

localhost:8080                  -> hubble-ui
localhost:8081                  -> tekton-dashboard
localhost:8082/eventlistener    -> nativelink-eventlistener
localhost:8082/cache            -> nativelink-cache
localhost:8082/scheduler        -> nativelink-scheduler

## Type of change

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

aarch64-darwin

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-05-24 01:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TraceMachina/nativelink?pullRequest=929) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TraceMachina/nativelink?pullRequest=929) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TraceMachina/nativelink?pullRequest=929) it.</sub>

2024-05-24 01:58 UTC, SchahinRohani commented
@aaronmondal Can you check this on linux?





<!-- Sent from Reviewable.io -->

2024-05-24 02:42 UTC, aaronmondal requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/929)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, and 1 discussions need to be resolved

___
*[`native-cli/components/loadbalancer.go` line 240 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NycT5-s8_VBIl02ICi-:-NycT5-s8_VBIl02ICi0:b-5wdhcr) ([raw file](https://github.com/TraceMachina/nativelink/blob/31b658de347af00f5f1822b91efb20b40c3e3843/native-cli/components/loadbalancer.go#L240)):*
> ```Go
> 				&docker.ContainerMountArgs{
> 					Source: pulumi.String(absolutePath),
> 					Target: pulumi.String("/etc/envoy/envoy.yaml"),
> ```

I'm getting this:

```
[2024-05-24 02:39:47.817][1][critical][main] [source/server/server.cc:112] error initializing configuration '/etc/envoy/envoy.yaml': unable to read file: /etc/envoy/envoy.yaml
[2024-05-24 02:39:47.817][1][info][main] [source/server/server.cc:855] exiting unable to read file: /etc/envoy/envoy.yaml
```

It looks like the `envoy.yaml` doesn't make it into the `kind-loadbalancer` container.


<!-- Sent from Reviewable.io -->

2024-05-25 02:52 UTC, SchahinRohani commented
*[`native-cli/components/loadbalancer.go` line 240 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NycT5-s8_VBIl02ICi-:-Nyhe5Cp3t5br5z2dM-c:b-vr4xx2) ([raw file](https://github.com/TraceMachina/nativelink/blob/31b658de347af00f5f1822b91efb20b40c3e3843/native-cli/components/loadbalancer.go#L240)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

I'm getting this:

```
[2024-05-24 02:39:47.817][1][critical][main] [source/server/server.cc:112] error initializing configuration '/etc/envoy/envoy.yaml': unable to read file: /etc/envoy/envoy.yaml
[2024-05-24 02:39:47.817][1][info][main] [source/server/server.cc:855] exiting unable to read file: /etc/envoy/envoy.yaml
```

It looks like the `envoy.yaml` doesn't make it into the `kind-loadbalancer` container.
</blockquote></details>

Fixed. The file permissions of the created envoy config werent allowing to read the file in the container.


<!-- Sent from Reviewable.io -->

2024-05-25 23:32 UTC, aaronmondal requested changes
> Reviewed 10 of 14 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/929)* status: 0 of 1 LGTMs obtained, and 22 discussions need to be resolved

___
*[`native-cli/clusters/config.yaml` line 5 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NylsE4e3Y6wWzfa1jiY:-NylsE4e3Y6wWzfa1jiZ:b2ni8l0) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/clusters/config.yaml#L5)):*
> ```YAML
> apiVersion: kind.x-k8s.io/v1alpha4
> networking:
>   # the default CNI will not be installed
> ```

nit



_Suggestion:_
```YAML
# Don't install the default CNI.
```
___
*[`native-cli/clusters/localcluster.go` line 87 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NyluVH4BM4-Anmn5Qot:-NyluVH4BM4-Anmn5Qou:b-6ld836) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/clusters/localcluster.go#L87)):*
> ```Go
> 	Nodes                   []Node     `yaml:"nodes"`
> 	ContainerdConfigPatches []string   `yaml:"containerdConfigPatches"`
> }
> ```

Can we make this work in the same way that the envoy templating works? I.e. have the kind `config.yaml` a `kind-config.template.yaml` and use a simila approach as for `envoy.template.yaml`.
___
*[`native-cli/clusters/localcluster.go` line 101 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NyltY5b7tSKYruapoIc:-NyltY5b7tSKYruapoId:b-qpl7lm) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/clusters/localcluster.go#L101)):*
> ```Go
> 	var config ClusterConfig
> 
> 	config.get()
> ```

Does `config := ClusterConfig.get()` work?



_Code quote:_
```Go
	var config ClusterConfig

	config.get()
```
___
*[`native-cli/clusters/localcluster.go` line 103 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NyltFkr8GGdj7PyHmz2:-NyltFkr8GGdj7PyHmz3:bmalzof) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/clusters/localcluster.go#L103)):*
> ```Go
> 	config.get()
> 
> 	gitRoot := gitSrcRoot()
> ```

You can inline this.
___
*[`native-cli/clusters/localcluster.go` line 114 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nylu08j91Kn9dqpfkun:-Nylu08j91Kn9dqpfkuo:bx9wq4t) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/clusters/localcluster.go#L114)):*
> ```Go
> 				},
> 			)
> 			if runtime.GOOS == "linux" {
> ```

Let's add a `"TODO(username): Implement nix caching for MacOS."` to make it clear that this doesn't work yet.
___
*[`native-cli/components/loadbalancer.go` line 89 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym-Sth2CbUi7Fl1FQp:-Nym-Sth2CbUi7Fl1FQq:b-islhsk) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L89)):*
> ```Go
> 		waitGroup.Add(1)
> 		// Assign the function to a variable and then invoke it in the go statement
> 		checkAndAddGateway := func(name string) {
> ```

nit: You can remove this variable and instead do:

```
go func(name string) {
...
}(name)
```



_Code quote:_
```Go
checkAndAddGateway :=
```
___
*[`native-cli/components/loadbalancer.go` line 121 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym1tjz6UhE9CCj5qPV:-Nym1tjz6UhE9CCj5qPW:bcnghd0) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L121)):*
> ```Go
> }
> 
> func addGatewayIfNeeded(
> ```

Missing docstring.
___
*[`native-cli/components/loadbalancer.go` line 166 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym1Y0sD1HdhmG_UY3D:-Nym1Y0sD1HdhmG_UY3E:b-tv1wrh) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L166)):*
> ```Go
> 
> 	return true
> }
> ```

Since this is only used once, inline the function.



_Code quote:_
```Go
func allGatewaysFound(requiredGateways map[string]bool) bool {
	for _, found := range requiredGateways {
		if !found {
			return false
		}
	}

	return true
}
```
___
*[`native-cli/components/loadbalancer.go` line 168 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym2WIp0gzBde1zTKV1:-Nym2WIp0gzBde1zTKV2:b-2h6rw5) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L168)):*
> ```Go
> }
> 
> func getHomeDir() (string, error) {
> ```

This function is unnecessary because the way to call it would look like this:

```go
home, err := getHomeDir()
if err != nil {
  return "", fmt.Errorf("xxxxxx"),
}
```

That's equivalent to how this function looks like, so we might as well just write this code out directly.
___
*[`native-cli/components/loadbalancer.go` line 177 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym2wbj73lxJZDERs5Y:-Nym2wbj73lxJZDERs5Z:b2nreh6) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L177)):*
> ```Go
> }
> 
> func buildKubeConfig(kubeconfig *string) (*rest.Config, error) {
> ```

Same as above.
___
*[`native-cli/components/loadbalancer.go` line 186 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym37Vb26OaXT4WHBtw:-Nym37Vb26OaXT4WHBtx:b2nreh6) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L186)):*
> ```Go
> }
> 
> func createGatewayClientset(
> ```

Same as above.
___
*[`native-cli/components/loadbalancer.go` line 313 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym4JE5EHtx1o_HBGX_:-Nym4JE5EHtx1o_HBGXa:bwfuwe9) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L313)):*
> ```Go
> 	}
> 
> 	requiredGateways := map[string]bool{
> ```

You can inline this variable.
___
*[`native-cli/components/loadbalancer.go` line 315 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym3u5yCrqiiGxtvzfW:-Nym3u5yCrqiiGxtvzfX:bft6c9h) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L315)):*
> ```Go
> 	requiredGateways := map[string]bool{
> 		"scheduler-gateway": false,
> 		"cache-gateway":     false,
> ```

At the moment the loadbalancer doesn't yet require (or expose) the scheduler and cache gateways. Let's comment these two out and put a TODO that we want them enabled.



_Code quote:_
```Go
		"scheduler-gateway": false,
		"cache-gateway":     false,
```
___
*[`native-cli/components/loadbalancer.go` line 337 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym4ZBE6RIupvcp7jsc:-Nym4ZBE6RIupvcp7jsd:b-rij1z9) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L337)):*
> ```Go
> 	}
> 
> 	ports := prepareDockerContainerPorts(component.Ports)
> ```

Inline this variable and call the function `dockerContainerPorts`.
___
*[`native-cli/components/nativelink-routes.go` line 22 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NylvPjh86wbODPkFTHd:-NylvPjh86wbODPkFTHe:bkynjgw) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/nativelink-routes.go#L22)):*
> ```Go
> var nativeLinkRoutesYaml string
> 
> // Install sets up the Gateways for the NativeLink deployment.
> ```

The comments in this file need to be updated.
___
*[`native-cli/components/embedded/envoy_template.yaml` line 16 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NylvjsJ1UvrMf [...]

2024-05-27 05:05 UTC, SchahinRohani reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/929)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 19 discussions need to be resolved

___
*[`native-cli/clusters/localcluster.go` line 87 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NyluVH4BM4-Anmn5Qot:-NysPt1X128JzxejujOt:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/clusters/localcluster.go#L87)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Can we make this work in the same way that the envoy templating works? I.e. have the kind `config.yaml` a `kind-config.template.yaml` and use a simila approach as for `envoy.template.yaml`.
</blockquote></details>

Done.
___
*[`native-cli/clusters/localcluster.go` line 101 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NyltY5b7tSKYruapoIc:-NysPurNBJui7EsBDDWb:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/clusters/localcluster.go#L101)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Does `config := ClusterConfig.get()` work?
</blockquote></details>

Done.
___
*[`native-cli/clusters/localcluster.go` line 103 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NyltFkr8GGdj7PyHmz2:-NysPvlM8xkS8E_kOu1q:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/clusters/localcluster.go#L103)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

You can inline this.
</blockquote></details>

Done.
___
*[`native-cli/clusters/localcluster.go` line 114 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nylu08j91Kn9dqpfkun:-NysQ5zB5b1-6ZYbTd_z:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/clusters/localcluster.go#L114)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Let's add a `"TODO(username): Implement nix caching for MacOS."` to make it clear that this doesn't work yet.
</blockquote></details>

Done.
___
*[`native-cli/components/loadbalancer.go` line 121 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym1tjz6UhE9CCj5qPV:-NysQC3t38YbWXtAzkam:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L121)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Missing docstring.
</blockquote></details>

Done.
___
*[`native-cli/components/loadbalancer.go` line 166 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym1Y0sD1HdhmG_UY3D:-NysQDsG-00JX-1BFmgF:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L166)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Since this is only used once, inline the function.
</blockquote></details>

Done.
___
*[`native-cli/components/loadbalancer.go` line 168 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym2WIp0gzBde1zTKV1:-NysQJlTDFO2OIrH7oiX:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L168)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

This function is unnecessary because the way to call it would look like this:

```go
home, err := getHomeDir()
if err != nil {
  return "", fmt.Errorf("xxxxxx"),
}
```

That's equivalent to how this function looks like, so we might as well just write this code out directly.
</blockquote></details>

Done.
___
*[`native-cli/components/loadbalancer.go` line 177 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym2wbj73lxJZDERs5Y:-NysQMtR6NIrW1EZ02Eu:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L177)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`native-cli/components/loadbalancer.go` line 186 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym37Vb26OaXT4WHBtw:-NysQLmK0jN1Wvvv1PiB:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L186)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`native-cli/components/loadbalancer.go` line 313 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym4JE5EHtx1o_HBGX_:-NysQO7N04pV1LI8nXHt:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L313)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

You can inline this variable.
</blockquote></details>

Done.
___
*[`native-cli/components/loadbalancer.go` line 315 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym3u5yCrqiiGxtvzfW:-NysQQB4EQX_UQF87d8R:b-61utc3) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L315)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

At the moment the loadbalancer doesn't yet require (or expose) the scheduler and cache gateways. Let's comment these two out and put a TODO that we want them enabled.
</blockquote></details>

Lets keep them to ensure that we have all gateway ips in place.
___
*[`native-cli/components/loadbalancer.go` line 337 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-Nym4ZBE6RIupvcp7jsc:-NysQrs43xHWmuqGeqd2:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/loadbalancer.go#L337)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Inline this variable and call the function `dockerContainerPorts`.
</blockquote></details>

Done.
___
*[`native-cli/components/nativelink-routes.go` line 22 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NylvPjh86wbODPkFTHd:-NysQuYF4KE5cqxhYajk:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6e53717c6/native-cli/components/nativelink-routes.go#L22)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

The comments in this file need to be updated.
</blockquote></details>

Done.
___
*[`native-cli/components/embedded/nativelink-gateways.yaml` line 16 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NylxADt4VvxZgTEtk0N:-NysR1fk8mYrMvrnS_fp:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f64b2187a0d9560065276c25b11b56e6 [...]

2024-05-27 16:43 UTC, aaronmondal approved these changes
One minor nit to merge `Route` into `RouteConfig`, otherwise looks good! Great work!

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/929#-:-NyuvXRZ3upLlOTk-nlH:b-vfh1fd)* status: 1 of 1 LGTMs obtained, and 4 discussions need to be resolved

___
*[`native-cli/components/loadbalancer.go` line 39 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NyutcdDCiIrMHuyJ-t3:-NyutcdDCiIrMHuyJ-t4:bnk8e3u) ([raw file](https://github.com/TraceMachina/nativelink/blob/633b4967c0d4a61e29241b7ea92f6c42aef32526/native-cli/components/loadbalancer.go#L39)):*
> ```Go
> 	Cluster       string
> 	PrefixRewrite string
> }
> ```

nit: It looks like we can move the `Cluster` and `PrefixRewrite` fields directly into the `RouteConfig`.



_Code quote:_
```Go
type Route struct {
	Cluster       string
	PrefixRewrite string
}
```
___
*[`native-cli/components/embedded/nativelink-gateways.yaml` line 50 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NyusoqXDnGZ-T1xqX3K:-NyusoqXDnGZ-T1xqX3L:bun5sqf) ([raw file](https://github.com/TraceMachina/nativelink/blob/633b4967c0d4a61e29241b7ea92f6c42aef32526/native-cli/components/embedded/nativelink-gateways.yaml#L50)):*
> ```YAML
>       allowedRoutes:
>         namespaces:
>           from: Same
> ```

nit: This can be removed since `Same` is the default.
___
*[`native-cli/components/embedded/nativelink-gateways.yaml` line 65 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NyusujYDsytHWggHWiy:-NyusujZCtcyqPxSHuGZ:b-iipjm8) ([raw file](https://github.com/TraceMachina/nativelink/blob/633b4967c0d4a61e29241b7ea92f6c42aef32526/native-cli/components/embedded/nativelink-gateways.yaml#L65)):*
> ```YAML
>       allowedRoutes:
>         namespaces:
>           from: Same
> ```

nit: ditto
___
*[`native-cli/programs/local.go` line 133 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NyuuGTU8IRDgnTfmBRO:-NyuuGTU8IRDgnTfmBRP:bw2gaku) ([raw file](https://github.com/TraceMachina/nativelink/blob/633b4967c0d4a61e29241b7ea92f6c42aef32526/native-cli/programs/local.go#L133)):*
> ```Go
> 					Cluster: "hubble-gateway",
> 				},
> 			},
> ```

When the `Route` is changed as above these become:



_Suggestion:_
```Go
			{
				Prefix: "/",
                Cluster: "hubble-gateway",
			},
```


<!-- Sent from Reviewable.io -->

2024-05-31 11:48 UTC, SchahinRohani reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/929)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, and 1 discussions need to be resolved

___
*[`native-cli/programs/local.go` line 133 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/929#-NyuuGTU8IRDgnTfmBRO:-NzDTawg0tLFNQMvRL7m:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/633b4967c0d4a61e29241b7ea92f6c42aef32526/native-cli/programs/local.go#L133)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

When the `Route` is changed as above these become:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-31 12:23 UTC, aaronmondal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/929#-:-NzDahR77XNlnD4HeFch:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13



<!-- Sent from Reviewable.io -->

2024-05-31 12:25 UTC, merged