Refactor Store Api into client side and driver side
TraceMachina/nativelink pull request #935
Opened 2024-05-27 23:38 UTC by allada

Refactors the Store api into the driver (backend) implementation and a client Store/StoreLike api. Store & StoreLike have their sizes known at compile-time. This enables us to add templates to the client-side to make it easier to work with, for example, we no longer need to Pin the store and we'll be able to add things like `digest: impl Into<DigestInfo>` to make the callers life much easier.

towards: #934

2024-05-27 23:40 UTC, allada reviewed
+@adam-singer

fyi: @zbirenbaum 

Note: This is for an early review. I still need to figure out a better way to do `inner_store`, as it turns out this method is not a good way.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/935#-:-NywQBsOCUe88ndWUryh:be353j6)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, and 1 discussions need to be resolved (waiting on @adam-singer)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/935#-NywPwYR6SKNa5i2w19z:-NywPwYR6SKNa5i2w1A-:bk05d2w) (no related file):*
note: This PR is waiting for this patch to land:
https://github.com/TraceMachina/nativelink/pull/932

___


<!-- Sent from Reviewable.io -->

2024-05-28 00:02 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/935)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, vale (waiting on @adam-singer)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/935#-NywPwYR6SKNa5i2w19z:-NywVD_J7ZlqoUUlTL_H:b-896fix) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

note: This PR is waiting for this patch to land:
https://github.com/TraceMachina/nativelink/pull/932
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2024-05-28 18:58 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/935)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 1 discussions need to be resolved (waiting on @adam-singer)

___
*[`deployment-examples/docker-compose/Dockerfile` line 32 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/935#-Nz-ZABc-OuRoIPGI6K1:-Nz-ZABc-OuRoIPGI6K2:bwgygri) ([raw file](https://github.com/TraceMachina/nativelink/blob/26ed4fd214e0ec9c939248605ea24bf975f3b245/deployment-examples/docker-compose/Dockerfile#L32)):*
> ```Dockerfile
>         apt-get install --no-install-recommends -y \
>             npm=8.5.1~ds-1 \
>             git=1:2.34.1-1ubuntu1.11 \
> ```

there was a security vulnerability in previous git versions, so ubuntu dropped the old versions.


<!-- Sent from Reviewable.io -->

2024-05-28 23:42 UTC, adam-singer requested changes
Look great, I really like this approach

> Reviewed 19 of 47 files at r2, 1 of 21 files at r3, 7 of 25 files at r4, 21 of 21 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/935#-:-Nz0_1li2Iqxf44ZMCZ_:b-cssdwm)* status: 0 of 1 LGTMs obtained, and 6 discussions need to be resolved

___
*[`nativelink-store/src/ac_utils.rs` line 40 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/935#-Nz0RMT540p3_UyVuBNo:-Nz0RMT540p3_UyVuBNp:b-5egvbm) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d6630e87f708abe1910fa2b31ec6cb8bc9592eb/nativelink-store/src/ac_utils.rs#L40)):*
> ```XML
> 
> /// Attempts to fetch the digest contents from a store into the associated proto.
> pub async fn get_and_decode_digest<'a, T: Message + Default>(
> ```

Why is a declaration needed here of an implementation reference vs dynamic trait dispatch? Would it be possible to remove and hope the "monomorphization" of rust compiler to figure it out?
___
*[`nativelink-store/src/default_store_factory.rs` line 52 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/935#-Nz0SkO-Exbpq3Rf1qsc:-Nz0SkO-Exbpq3Rf1qsd:bd1vlto) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d6630e87f708abe1910fa2b31ec6cb8bc9592eb/nativelink-store/src/default_store_factory.rs#L52)):*
> ```XML
> ) -> Pin<FutureMaybeStore<'a>> {
>     Box::pin(async move {
>         let store: Arc<dyn StoreDriver> = match backend {
> ```

Wondering out loud here.. what other "tricks" could be done to reduce this to a `impl` vs `dyn` for instance creation? I assume the `StoreDriver` traits would need to change. From a code/understanding pov, going towards templating the code looks much better vs having to pin/dyn everything. Wondering if some mix of using macros to define the factory methods and as templates for defining the `StoreDriver`. 
___
*[`nativelink-store/tests/completeness_checking_store_test.rs` line 81 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/935#-Nz0VOgBD9457PDGx0GC:-Nz0VOgBD9457PDGx0GD:bb6xuho) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d6630e87f708abe1910fa2b31ec6cb8bc9592eb/nativelink-store/tests/completeness_checking_store_test.rs#L81)):*
> ```XML
>         let tree_digest = serialize_and_upload_message(
>             &tree,
>             cas_store.as_pin(),
> ```

Does `as_pin()` need to be called on each pass? Guessing that is to please the borrowing of a new Pin vs reusing an existing assignment? 
___
*[`nativelink-worker/src/running_actions_manager.rs` line 367 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/935#-Nz0ZcJ503Mi13neyiT3:-Nz0ZcJ503Mi13neyiT4:bhvivnm) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d6630e87f708abe1910fa2b31ec6cb8bc9592eb/nativelink-worker/src/running_actions_manager.rs#L367)):*
> ```XML
> 
> fn upload_directory<'a, P: AsRef<Path> + Debug + Send + Sync + Clone + 'a>(
>     cas_store: Pin<&'a impl StoreLike>,
> ```

Is lifetime still needed here?
___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 217 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/935#-Nz0YYLd28NrndjsEgod:-Nz0YYLd28NrndjsEgoe:b-ixf2c0) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d6630e87f708abe1910fa2b31ec6cb8bc9592eb/nativelink-worker/tests/running_actions_manager_test.rs#L217)):*
> ```XML
>             download_to_directory(
>                 cas_store.as_ref(),
>                 Pin::new(fast_store.as_ref()),
> ```

don't the `as_pin` class of functions hang off of this? Same for other `download_to_directory` calls below


<!-- Sent from Reviewable.io -->

2024-06-04 03:56 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/935)* status: 0 of 1 LGTMs obtained, and 4 discussions need to be resolved (waiting on @adam-singer)

___
*[`nativelink-store/src/ac_utils.rs` line 40 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/935#-Nz0RMT540p3_UyVuBNo:-NzWM_Ah5bs8HXmsqG6d:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d6630e87f708abe1910fa2b31ec6cb8bc9592eb/nativelink-store/src/ac_utils.rs#L40)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Why is a declaration needed here of an implementation reference vs dynamic trait dispatch? Would it be possible to remove and hope the "monomorphization" of rust compiler to figure it out?
</blockquote></details>

Done.
___
*[`nativelink-store/src/default_store_factory.rs` line 52 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/935#-Nz0SkO-Exbpq3Rf1qsc:-NzWMfwnA1pn1ZxviGmg:b-d0bgl5) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d6630e87f708abe1910fa2b31ec6cb8bc9592eb/nativelink-store/src/default_store_factory.rs#L52)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Wondering out loud here.. what other "tricks" could be done to reduce this to a `impl` vs `dyn` for instance creation? I assume the `StoreDriver` traits would need to change. From a code/understanding pov, going towards templating the code looks much better vs having to pin/dyn everything. Wondering if some mix of using macros to define the factory methods and as templates for defining the `StoreDriver`.
</blockquote></details>

Yeah, in the future I'm sure someone will look at this API and figure out a better way to do it, but for now it's not worth the brain power.
___
*[`nativelink-store/tests/completeness_checking_store_test.rs` line 81 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/935#-Nz0VOgBD9457PDGx0GC:-NzWNBJd5LFQ80-lpM--:b24rgwc) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d6630e87f708abe1910fa2b31ec6cb8bc9592eb/nativelink-store/tests/completeness_checking_store_test.rs#L81)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Does `as_pin()` need to be called on each pass? Guessing that is to please the borrowing of a new Pin vs reusing an existing assignment?
</blockquote></details>

To be honest, I'm not sure. Removing the `Pin` requirement is not as easy as it sounds, because if the caller already has it pinned, they need to unpin it, which is worse IMO `Pin::get_ref(store_pin)`. Forcing the user to just be a pin seems easier to use than if it's already a pin :shrug: 
___
*[`nativelink-worker/src/running_actions_manager.rs` line 367 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/935#-Nz0ZcJ503Mi13neyiT3:-NzWNiv44ZfXFRSipXYD:b9gt2u2) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d6630e87f708abe1910fa2b31ec6cb8bc9592eb/nativelink-worker/src/running_actions_manager.rs#L367)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Is lifetime still needed here?
</blockquote></details>

Yes because it's returning a `BoxFuture`.
___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 217 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/935#-Nz0YYLd28NrndjsEgod:-NzWNzqB7Rw0guNp7v1y:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/6d6630e87f708abe1910fa2b31ec6cb8bc9592eb/nativelink-worker/tests/running_actions_manager_test.rs#L217)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

don't the `as_pin` class of functions hang off of this? Same for other `download_to_directory` calls below
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-04 04:48 UTC, adam-singer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 21 files at r3, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/935#-:-NzWZoxV1JWBRWyjmPYa:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Cargo Dev / ubuntu-22.04, pre-commit-checks, and 1 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-06-04 16:37 UTC, merged