Redis Operation Filter
TraceMachina/nativelink pull request #962
Opened 2024-06-04 00:28 UTC by zbirenbaum

- **Convert RedisError into nativelink Error**
- **Minor update to OperationStateManager API**
- **Add serialize and deserialize to structs**
- **Add filtering implementation for redis**

# Description
Implements an extremely basic version of fetching operations based on provided filters. Additionally, adds Serialize and Deserialize to all structs required for storing in redis.

One of the following must be merged for this to work:
1. Serialize and Deserialize added to structs (done in a commit on this PR)
2. #941 must be merged and types here can be changed. #941 would enable storage of non-json values in Redis

## Type of change

Please delete options that aren't relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
TDB

## Checklist

- [ ] Tests added/amended
- [x] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-06-04 04:25 UTC, allada requested changes
> Reviewed 1 of 1 files at r1, 3 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/962)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-22.04, and 14 discussions need to be resolved

___
*[`-- commits` line 1 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWQiciC_NjbZ1CYP8e):*
nit: Please condense this.
___
*[`nativelink-scheduler/Cargo.toml` line 34 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWQaeTDnPVkR10g4l0:-NzWQaeTDnPVkR10g4l1:b-wl5wx) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/Cargo.toml#L34)):*
> ```TOML
> redis = { version = "0.25.2", features = ["aio", "tokio", "json"] }
> serde = "1.0.203"
> serde_json = "1.0.117"
> ```

nit: unused?
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 1 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWQzUD-IfEDM75MHhC:-NzWQzUD-IfEDM75MHhD:bc4aqi5) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L1)):*
> ```XML
> use std::sync::Arc;
> ```

nit: Please add copyright header.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 14 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWRS4pBoFXiNH_PVcG:-NzWRS4q7uEqHnWa8F0Z:b-jeuri7) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L14)):*
> ```XML
> 
> pub struct RedisStateManager  {
>     client: Client,
> ```

Instead, lets bring this in as a `RedisStore`. Add some custom functions to get the underlying redis-store client so it's accessible here.

In the constructor have it take in a `Store`. It may also be good to rebase on top of:
https://reviewable.io/reviews/TraceMachina/nativelink/964

This should allow you to do everything but pub/sub, but you can use the redis-store-client-getter for that.

This will dramatically reduce the amount of changes needed and will allow us to eventually have this take any store.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 80 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWSI-45SHa6fg9M97w:-NzWSI-45SHa6fg9M97x:bsbwky1) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L80)):*
> ```XML
> impl RedisOperation {
>     pub fn action_stage(&self) -> Result<ActionStage, Error> {
>         match self.stage {
> ```

Why not just store the stage as an `ActionStage`? This would also remove the need for `self.result`.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 97 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWSV7PBDUd5zpmgK4L:-NzWSV7Q2X4mpYMeBd6e:b-iw77tk) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L97)):*
> ```XML
>         }
>     }
>     pub fn unique_qualifier(&self) -> &ActionInfoHashKey {
> ```

nit: no need to be public.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 121 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWULmX1xzT1baC6iHM:-NzWULmY4-spxNYohUoI:b-pmrntd) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L121)):*
> ```XML
> #[async_trait]
> impl MatchingEngineStateManager for RedisStateManager {
>     /// Returns a stream of operations that match the filter.
> ```

nit: No need to comment here. This is documented in the api.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 126 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWTcK0B0MxoNilqofP:-NzWTcK0B0MxoNilqofQ:bbyl0ko) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L126)):*
> ```XML
>         filter: OperationFilter,
>     ) -> Result<ActionStateResultStream, Error> {
>         let mut con = self.get_multiplex_connection().await.unwrap();
> ```

nit: don't use `unwrap()` use `.err_tip()`.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 127 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWUPHs4DvANkfON620:-NzWUPHs4DvANkfON621:b-o5t8wg) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L127)):*
> ```XML
>     ) -> Result<ActionStateResultStream, Error> {
>         let mut con = self.get_multiplex_connection().await.unwrap();
>         let operations = {
> ```

nit: Just hoist the data directly, there doesn't appear to be any reason to add an additional 3 lines that don't make it more readable and don't have functionality.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 128 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWTVL-EQ4uQge1eECx:-NzWTVL0D3P2w_j_Cv02:bb1h1nj) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L128)):*
> ```XML
>         let mut con = self.get_multiplex_connection().await.unwrap();
>         let operations = {
>             // returns list of all operations
> ```

nit: caps and period.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 129 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWTaMK4tvuZbk-dsG_:-NzWTaMK4tvuZbk-dsGa:b-nbsblo) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L129)):*
> ```XML
>         let operations = {
>             // returns list of all operations
>             let Json(operations): Json<Vec<RedisOperation>> = con.json_get("operations:", "$").await?;
> ```

nit: Needs `.err_tip`.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 132 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWTkcX6X2h7aQfUDTn:-NzWTkcX6X2h7aQfUDTo:bf2f5sn) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L132)):*
> ```XML
>             operations
>         };
>         let mut v: Vec<Arc<dyn ActionStateResult>> = Vec::new();
> ```

nit: Lets use the raw stream api. use `operations.into_iter()` as the state in `unfold()`.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 147 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWUBBf6I9cWlrVTF4Y:-NzWUBBf6I9cWlrVTF4Z:bi9ggi3) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L147)):*
> ```XML
>         _action_stage: Result<ActionStage, Error>,
>     ) -> Result<(), Error> {
>         let mut con = self.get_multiplex_connection().await.unwrap();
> ```

nit: Just use `todo!()` don't add any of the other code.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 153 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWUG1qEJfqFjUsBbI8:-NzWUG1qEJfqFjUsBbI9:b-pmrntd) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L153)):*
> ```XML
>     }
> 
>     /// Remove an operation from the state manager.
> ```

nit: No need to comment here. This is documented in the api.


<!-- Sent from Reviewable.io -->

2024-06-04 04:44 UTC, adam-singer reviewed
> Reviewed 1 of 1 files at r1, 1 of 4 files at r2, 4 of 4 files at r3, 3 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/962)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-22.04, and 14 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-06-04 05:01 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/962)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Installation / ubuntu-22.04, Local / ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, ubuntu-20.04 / stable, vale, and 7 discussions need to be resolved

___
*[`-- commits` line 1 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWQiciC_NjbZ1CYP8e):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Please condense this.
</blockquote></details>

This relies on #960 #959 and Either #962 or the `Add serialize and deserialize to structs` commit as a seperate PR. Those will go away once the other PR's are merged.
___
*[`nativelink-scheduler/Cargo.toml` line 34 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWQaeTDnPVkR10g4l0:-NzWaJFC6TQ93h2mqxN2:bl0dw9g) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/Cargo.toml#L34)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: unused?
</blockquote></details>

It was used at one point and will be in the future but removed for now.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 80 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWSI-45SHa6fg9M97w:-NzWakER-Ksl2n8oYAss:bsjb9nu) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L80)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Why not just store the stage as an `ActionStage`? This would also remove the need for `self.result`.
</blockquote></details>

`ActionStage::CompletedFromCache(Proto)` isn't serializable/deserializable and can't be made so.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 97 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWSV7PBDUd5zpmgK4L:-NzWbo-dCrzufJILWitH:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L97)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: no need to be public.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 121 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWULmX1xzT1baC6iHM:-NzWbEbiEf2UqS3ZxwQY:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L121)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: No need to comment here. This is documented in the api.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 126 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWTcK0B0MxoNilqofP:-NzWbFSO0qT6_qwwdmoc:bi5merb) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L126)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: don't use `unwrap()` use `.err_tip()`.
</blockquote></details>

Done. I can just use `?` here since they both return Results.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 127 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWUPHs4DvANkfON620:-NzWbbHQA8wa3_ivLYgl:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L127)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Just hoist the data directly, there doesn't appear to be any reason to add an additional 3 lines that don't make it more readable and don't have functionality.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 128 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWTVL-EQ4uQge1eECx:-NzWbcD07GYJfDIMzKoi:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L128)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: caps and period.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 147 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWUBBf6I9cWlrVTF4Y:-NzWbjqV8Xig6TpIA5AK:bhupzs3) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L147)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Just use `todo!()` don't add any of the other code.
</blockquote></details>

Done. This is implemented now.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 153 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWUG1qEJfqFjUsBbI8:-NzWbm36D2Itw6Z_86JM:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L153)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: No need to comment here. This is documented in the api.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-04 05:03 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/962)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Installation / ubuntu-22.04, Local / ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, vale, and 7 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 129 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/962#-NzWTaMK4tvuZbk-dsG_:-NzWbvwOEoWqP7t__76f:bq0i2iq) ([raw file](https://github.com/TraceMachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L129)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Needs `.err_tip`.
</blockquote></details>

I'm a bit confused on this one. Should we use `.err_tip` everywhere `?` is used? Pretty much every function in `redis-rs` returns a result so that might get a bit unwieldy.


<!-- Sent from Reviewable.io -->

2024-06-11 22:57 UTC, adam-singer reviewed
> Reviewed 1 of 4 files at r9, 9 of 12 files at r10.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/962)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 8 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 1 at r10](https://reviewable.io/reviews/TraceMachina/nativelink/962#-O-8Tp-vC5BthIzNQMgU:-O-8Tp-vC5BthIzNQMgV:b-4tu1mb) ([raw file](https://github.com/TraceMachina/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L1)):*
> ```XML
> // Copyright 2024 The NativeLink Authors. All rights reserved.
> ```

Could we put this into its own folder and separate out some of this into different files?
___
*[`nativelink-scheduler/tests/redis_state_manager_test.rs` line 130 at r10](https://reviewable.io/reviews/TraceMachina/nativelink/962#-O-8VwFMBOjARel5HUeD:-O-8VwFMBOjARel5HUeE:b222sml) ([raw file](https://github.com/TraceMachina/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/tests/redis_state_manager_test.rs#L130)):*
> ```XML
>     async fn basic_update_operation_test() -> Result<(), Error> {
>         let worker_id = WorkerId(uuid::Uuid::new_v4());
>         let state_manager = RedisStateManager::new("redis://localhost/".to_string());
> ```

Does this mean we assume that redis is running when executing unit tests? Unsure if we have that wired up in our test harness cc: @blakehatch ? 


<!-- Sent from Reviewable.io -->

2024-06-13 03:33 UTC, allada requested changes
> Reviewed 9 of 12 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nativelink/nativelink/962)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 10 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 30 at r10](https://reviewable.io/reviews/nativelink/nativelink/962#-O-Eb8HB542vtBre0V_n:-O-Eb8HB542vtBre0V_o:b41z7e5) ([raw file](https://github.com/nativelink/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L30)):*
> ```XML
> 
> pub struct RedisOperationState {
>     client: Client,
> ```

nit: Have this instead take a `Store` and make a helper function:
```rs
fn get_redis_client(&self) -> Result<Client, Error>
```

And downcast it to the redis store.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 43 at r10](https://reviewable.io/reviews/nativelink/nativelink/962#-O-EbwD6CoXfZSIMY0fl:-O-EbwD6CoXfZSIMY0fm:b2njocx) ([raw file](https://github.com/nativelink/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L43)):*
> ```XML
> }
> 
> impl TryFrom<RedisOperationImpl> for ActionState {
> ```

nit: Move this below to the rest of `RedisOperation` stuff.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 60 at r10](https://reviewable.io/reviews/nativelink/nativelink/962#-O-EcnPI4-OHong8mf8W:-O-EcnPI4-OHong8mf8X:b-7kooul) ([raw file](https://github.com/nativelink/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L60)):*
> ```XML
>         let mut sub = client.get_async_pubsub().await?;
>         let sub_channel = format!("{}:*", &self.inner.operation_id.unique_qualifier.action_name());
>         // Subscribe to action name: any completed operation can return status
> ```

nit: period.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 61 at r10](https://reviewable.io/reviews/nativelink/nativelink/962#-O-EdDSz5Rc_JJvIqNqj:-O-EdDSz5Rc_JJvIqNqk:b-y09pvr) ([raw file](https://github.com/nativelink/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L61)):*
> ```XML
>         let sub_channel = format!("{}:*", &self.inner.operation_id.unique_qualifier.action_name());
>         // Subscribe to action name: any completed operation can return status
>         sub.subscribe(sub_channel).await.unwrap();
> ```

This could easily cause memory leaks. It looks like we need to do something similar to what was done with the `StoreSubscription` and make this return a Box<dyn ActionStateSubscription>` instead. Because we need to call `unsubscribe()` if no-one is subscribed any more.

This is also were we'll have the spawn's handle live.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 64 at r10](https://reviewable.io/reviews/nativelink/nativelink/962#-O-Echtl3-AqX_sItCIj:-O-Echtl3-AqX_sItCIk:b-erbbng) ([raw file](https://github.com/nativelink/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L64)):*
> ```XML
>         let mut stream = sub.into_on_message();
>         let action_state: ActionState = self.inner.clone().try_into()?;
>         // let arc_action_state: Arc<ActionState> = Arc::new();
> ```

nit: Cleanup.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 65 at r10](https://reviewable.io/reviews/nativelink/nativelink/962#-O-Ecjcj7UMAbITDY5jh:-O-Ecjcj7UMAbITDY5ji:b-ftsvd7) ([raw file](https://github.com/nativelink/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L65)):*
> ```XML
>         let action_state: ActionState = self.inner.clone().try_into()?;
>         // let arc_action_state: Arc<ActionState> = Arc::new();
>         // This hangs forever atm
> ```

nit: cleanup?
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 67 at r10](https://reviewable.io/reviews/nativelink/nativelink/962#-O-EdqhW9TtDdmOxhSYp:-O-EdqhW9TtDdmOxhSYq:b-7kooul) ([raw file](https://github.com/nativelink/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L67)):*
> ```XML
>         // This hangs forever atm
>         let (tx, rx) = tokio::sync::watch::channel(Arc::new(action_state));
>         // Hand tuple of rx and future to pump the rx
> ```

nit: period.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 69 at r10](https://reviewable.io/reviews/nativelink/nativelink/962#-O-Edt2s6aMBOV4zLKAL:-O-Edt2s6aMBOV4zLKAM:blpgvrk) ([raw file](https://github.com/nativelink/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L69)):*
> ```XML
>         // Hand tuple of rx and future to pump the rx
>         // Note: nativelink spawn macro name field doesn't accept variables so for now we have to use this to avoid conflicts.
>         #[allow(clippy::disallowed_methods)]
> ```

nit: remove.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 270 at r10](https://reviewable.io/reviews/nativelink/nativelink/962#-O-Ebp5hA3htLhmgUZBZ:-O-Ebp5hA3htLhmgUZB_:besa763) ([raw file](https://github.com/nativelink/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L270)):*
> ```XML
> 
> #[derive(Serialize, Deserialize, Clone, ToRedisArgs, FromRedisValue)]
> pub struct RedisOperationImpl {
> ```

nit: This is not an impl, it's just `RedisOperation`


<!-- Sent from Reviewable.io -->

2024-06-13 05:53 UTC, adam-singer reviewed
> Reviewed 1 of 12 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nativelink/nativelink/962)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 10 discussions need to be resolved



<!-- Sent from Reviewable.io -->

2024-06-17 20:23 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/962)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Local / ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, vale, and 4 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 14 at r4](https://reviewable.io/reviews/tracemachina/nativelink/962#-NzWRS4pBoFXiNH_PVcG:-O-brQMl2sULWWZPp8zB:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L14)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Instead, lets bring this in as a `RedisStore`. Add some custom functions to get the underlying redis-store client so it's accessible here.

In the constructor have it take in a `Store`. It may also be good to rebase on top of:
https://reviewable.io/reviews/TraceMachina/nativelink/964

This should allow you to do everything but pub/sub, but you can use the redis-store-client-getter for that.

This will dramatically reduce the amount of changes needed and will allow us to eventually have this take any store.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 132 at r4](https://reviewable.io/reviews/tracemachina/nativelink/962#-NzWTkcX6X2h7aQfUDTn:-O-brSTG8RMcKYbmO2sr:bseceb9) ([raw file](https://github.com/tracemachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L132)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Lets use the raw stream api. use `operations.into_iter()` as the state in `unfold()`.
</blockquote></details>

Done. I don't think this applies anymore.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 60 at r10](https://reviewable.io/reviews/tracemachina/nativelink/962#-O-EcnPI4-OHong8mf8W:-O-bqUtF6BziKrldftZM:b75p2pj) ([raw file](https://github.com/tracemachina/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L60)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: period.
</blockquote></details>

Done. This function no longer exists as it uses store now.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 61 at r10](https://reviewable.io/reviews/tracemachina/nativelink/962#-O-EdDSz5Rc_JJvIqNqj:-O-bq_OcCTCYpacCw34k:b75p2pj) ([raw file](https://github.com/tracemachina/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L61)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This could easily cause memory leaks. It looks like we need to do something similar to what was done with the `StoreSubscription` and make this return a Box<dyn ActionStateSubscription>` instead. Because we need to call `unsubscribe()` if no-one is subscribed any more.

This is also were we'll have the spawn's handle live.
</blockquote></details>

Done. This function no longer exists as it uses store now.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 64 at r10](https://reviewable.io/reviews/tracemachina/nativelink/962#-O-Echtl3-AqX_sItCIj:-O-bqj3m03uRJJoqcZOc:b75p2pj) ([raw file](https://github.com/tracemachina/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L64)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Cleanup.
</blockquote></details>

Done. This function no longer exists as it uses store now.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 65 at r10](https://reviewable.io/reviews/tracemachina/nativelink/962#-O-Ecjcj7UMAbITDY5jh:-O-bqjkz4tGcFboFirH7:b75p2pj) ([raw file](https://github.com/tracemachina/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L65)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: cleanup?
</blockquote></details>

Done. This function no longer exists as it uses store now.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 67 at r10](https://reviewable.io/reviews/tracemachina/nativelink/962#-O-EdqhW9TtDdmOxhSYp:-O-bqkMXBs72zjRVBd7w:b75p2pj) ([raw file](https://github.com/tracemachina/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L67)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: period.
</blockquote></details>

Done. This function no longer exists as it uses store now.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 69 at r10](https://reviewable.io/reviews/tracemachina/nativelink/962#-O-Edt2s6aMBOV4zLKAL:-O-bqlSG2w_0BJ1vnXeo:b75p2pj) ([raw file](https://github.com/tracemachina/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L69)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: remove.
</blockquote></details>

Done. This function no longer exists as it uses store now.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 270 at r10](https://reviewable.io/reviews/tracemachina/nativelink/962#-O-Ebp5hA3htLhmgUZBZ:-O-brKd23Kq-lIN8sJS7:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/deca9e681088f6a625eb68de47ad95c218dce39c/nativelink-scheduler/src/redis_operation_state.rs#L270)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: This is not an impl, it's just `RedisOperation`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-17 20:23 UTC, zbirenbaum reviewed
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/962)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Local / ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, vale, and 4 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 1 at r4](https://reviewable.io/reviews/tracemachina/nativelink/962#-NzWQzUD-IfEDM75MHhC:-O-brfPT--fCDG7guTak:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/debe9fc2b502b685b378a7b30e9560606b77a04e/nativelink-scheduler/src/redis_operation_state.rs#L1)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Please add copyright header.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-19 17:54 UTC, zbirenbaum commented
No longer working on this here, split into:
#1020 
#1021 
#1022 
#1023

2024-06-19 17:54 UTC, closed without merging