Fix Cargo mismatch on MacOS bukd
TraceMachina/nativelink pull request #974
Opened 2024-06-06 14:00 UTC by SchahinRohani

# Description

The flake.nix uses the default crane toolchain on darwin. Override the default crane toolchain and specify 
the target to use the correct rust toolchain fixes the cargo mismatch on the MacOS build.

Fixes #948

## Type of change

Please delete options that aren't relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Invoke nix build on MacOS

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

2024-06-06 15:00 UTC, allada reviewed
+@aaronmondal 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/974#-:-Nzi368B9GoNGtOkAKG_:b-p12xwa)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks (waiting on @aaronmondal)



<!-- Sent from Reviewable.io -->

2024-06-06 15:05 UTC, aaronmondal requested changes
Oh this exposed a bunch of issues. Thanks a lot for looking into this.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/974#-:-Nzi3wlS3hF-owczYouO:bhyxihf)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks, and 4 discussions need to be resolved (waiting on @aaronmondal)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/974#-Nzi2i-KBJq7lJbaPfXt):*




_Suggestion:_
```
to use the correct rust toolchain.

Fixes #948
```
___
*[`Cargo.toml` line 8 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/974#-Nzi3BcC0eoOPhTnmnS7:-Nzi3BcD3_EBDhC72yR8:bmnvwon) ([raw file](https://github.com/TraceMachina/nativelink/blob/3dbbbad9baf5dfad0eccb178bd7da8dadce92567/Cargo.toml#L8)):*
> ```TOML
> version = "0.4.0"
> edition = "2021"
> rust-version = "1.78.0"
> ```

Let's defer this to another PR. It's correct that we want this to match, but the flake change impacts darwin alone and this change impacts the build for all architectures.

Once we have the current PR landed we can bump this and then start always keeping it in sync with the version in `flake.nix`.
___
*[`flake.nix` line 40 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/974#-Nzi-Q886zyLjR9ZouAv:-Nzi-Q886zyLjR9ZouAw:b9sdinb) ([raw file](https://github.com/TraceMachina/nativelink/blob/3dbbbad9baf5dfad0eccb178bd7da8dadce92567/flake.nix#L40)):*
> ```Nix
>         "x86_64-linux"
>         "x86_64-darwin"
>         "aarch64-linux"
> ```

Let's remove this as it's not part of the change.
___
*[`flake.nix` line 93 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/974#-Nzi-UT78lZow8fRFg3X:-Nzi-UT78lZow8fRFg3Y:bhpdag6) ([raw file](https://github.com/TraceMachina/nativelink/blob/3dbbbad9baf5dfad0eccb178bd7da8dadce92567/flake.nix#L93)):*
> ```Nix
>           then
>             (crane.mkLib pkgs).overrideToolchain (stable-rust.default.override {
>               targets = ["aarch64-apple-darwin"];
> ```

I was wondering why your PR succeeded even on the `macos-13` runners which are `x86_64-apple-darwin`, and I think it's because the GHA workflows there are not correct. We only invoke `nix build` in:

https://github.com/TraceMachina/nativelink/blob/c0c09ed3de52573385d783868156824bafcce09d/.github/workflows/nix.yaml#L84

This means that with your current change things pass CI but won't work as intended because you'll be cross-compiling for `aarch64-darwin` on any Mac, even on an `x86_64-darwin` system.

The way to double check against this is to instead use `nix run` in the installation workflow above and make the github action query whether the output of `nix run` is:

```
error: the following required arguments were not provided:
  <CONFIG_FILE>

Usage: nativelink <CONFIG_FILE>

For more information, try '--help'.
```

The above is what you'd get if the `nativelink` executable worked. If it has been compiled for a different architecture this should create a segfault or raise an error like `file not found` because of a mismatching dynamic loader.


<!-- Sent from Reviewable.io -->

2024-06-08 20:13 UTC, SchahinRohani reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/974)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 4 discussions need to be resolved (waiting on @aaronmondal)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/974#-Nzi2i-KBJq7lJbaPfXt):*
Done.
___
*[`flake.nix` line 40 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/974#-Nzi-Q886zyLjR9ZouAv:-Nzn728-1ztlWn1PDQzT:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/3dbbbad9baf5dfad0eccb178bd7da8dadce92567/flake.nix#L40)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Let's remove this as it's not part of the change.
</blockquote></details>

Done.
___
*[`flake.nix` line 93 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/974#-Nzi-UT78lZow8fRFg3X:-NztTpAa297fPy8JRGnZ:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/3dbbbad9baf5dfad0eccb178bd7da8dadce92567/flake.nix#L93)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

I was wondering why your PR succeeded even on the `macos-13` runners which are `x86_64-apple-darwin`, and I think it's because the GHA workflows there are not correct. We only invoke `nix build` in:

https://github.com/TraceMachina/nativelink/blob/c0c09ed3de52573385d783868156824bafcce09d/.github/workflows/nix.yaml#L84

This means that with your current change things pass CI but won't work as intended because you'll be cross-compiling for `aarch64-darwin` on any Mac, even on an `x86_64-darwin` system.

The way to double check against this is to instead use `nix run` in the installation workflow above and make the github action query whether the output of `nix run` is:

```
error: the following required arguments were not provided:
  <CONFIG_FILE>

Usage: nativelink <CONFIG_FILE>

For more information, try '--help'.
```

The above is what you'd get if the `nativelink` executable worked. If it has been compiled for a different architecture this should create a segfault or raise an error like `file not found` because of a mismatching dynamic loader.
</blockquote></details>

Done.
___
*[`Cargo.toml` line 8 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/974#-Nzi3BcC0eoOPhTnmnS7:-Nzn78DRC5RzHMySDP9_:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/3dbbbad9baf5dfad0eccb178bd7da8dadce92567/Cargo.toml#L8)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Let's defer this to another PR. It's correct that we want this to match, but the flake change impacts darwin alone and this change impacts the build for all architectures.

Once we have the current PR landed we can bump this and then start always keeping it in sync with the version in `flake.nix`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-08 21:51 UTC, aaronmondal approved these changes
I believe you need to rebase. There was a CI issue with the pre-commit hooks.

Thanks a lot!

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/974#-:-NztopX28sjBu01-th9v:b-ag8t87)* status: 1 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, pre-commit-checks



<!-- Sent from Reviewable.io -->

2024-06-15 20:07 UTC, merged